### ISSUE TITLE
use setlocale(LC_NUMERIC,"C")

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1044]
Factor requires LC_NUMERIC to have the "C" local to correctly print numbers. See:
- https://www.mail-archive.com/factor-talk@lists.sourceforge.net/msg04748.html
- https://www.mail-archive.com/factor-talk@lists.sourceforge.net/msg05815.html

Summary:
- All backends should call setlocale(LC_NUMERIC, "C")
- The values in factor x11/xlib.factor are the wrong ones: they are for the function _Xsetlocale which we don't use.

Setting it from factor like in the patch http://paste.factorcode.org/paste?id=2595 is problematic because LC_NUMERIC has different values.
- libc values on my machine (ubuntu12.04): LC_NUMERIC=1. Isn't part of the main header, instead is in "bits/locale.h" meaning the value could change...
- @mrjbq7  mentions on OSX LC_NUMERIC=4

So we can put the LC_NUMERIC value in a factor CONSTANT: but need to maintain several systems. Can we instead use the vm compilation to get the correct LC_NUMERIC value ?

**Comment by bjourne** [comment]
Can we close this one now? I think float-printing has been fixed, hasn't it?

**Comment by mrjbq7** [comment]
Fixed because we pass in the ``"C"`` locale to ``format-float``.
