### ISSUE TITLE
Usage of PATH_MAX constant is incorrect.

### ISSUE THREAD

**Issue by sstewartgallus** [factor/factor#1074]
Instead of using a `PATH_MAX` constant one should use the POSIX `fpathconf(fd, _PC_PATH_MAX)` (which avoids the time of check time of use bugs associated with `pathconf`) or retry upon error with a larger buffer.

This issue affects the following functionality:
`read-symbolic-link ( path -- path )` in ./basis/unix/unix.factor
`const char* default_image_path()` in /vm/os-genunix.cpp
`const char* vm_executable_path()` in ./vm/os-linux.cpp

**Comment by bjourne** [comment]
Indeed, Factor crashes when you try to run it from a to long path which is what I think this bug report is about.

**Comment by bjourne** [comment]
On a second thought, I'm not sure there is a bug here at all. I checked the sbcl code and they use PATH_MAX in the exact same way we do. Python does something similar but defaults to 1024 if PATH_MAX is not defined. And this page also shows our method in the "compliant solution" box: https://www.securecoding.cert.org/confluence/display/c/POS30-C.+Use+the+readlink%28%29+function+properly

**Comment by bjourne** [comment]
Should be fixed now.
