### ISSUE TITLE
Use of fatal_error inside signal handlers is not signal safe.

### ISSUE THREAD

**Issue by sstewartgallus** [factor/factor#1077]
`fatal_error` is used inside of signal handlers but uses the C++ runtime.
It is not at all signal safe.

Luckily, `fatal_error` is super simple and so can be rewritten to be signal safe.

**Comment by bjourne** [comment]
I really don't think signal safety matters here. You must trigger a long sequence of extremely unlikely events for the signal unsafety of `std::cout` to cause something undefined. That the vm is calling `fatal_error` means that it is screwed and can't continue anyway. IMHO, there is nothing to fix here.

**Comment by bjourne** [comment]
So if you don't mind, I'm going to go ahead and close this bug. If a crash can be produced because of signal unsafety issues, then we can reopen it.
