### ISSUE TITLE
make python binding compatible with python3

### ISSUE THREAD

**Issue by erg** [factor/factor#1087]
On Arch linux, the library is called `libpython3.so` instead of `libpython3.0.so`. This will be patched shortly using `find-library*`

However, there is another problem -- in Python 3, all of the `PyString_*` etc are renamed to `PyBytes_`, `PyInt_` was renamed to `PyLong_`. So, if we want to support Python 2 and Python 3, we should break out the functions into two vocabularies and have `extra/python2` and `extra/python3` imo.

http://stackoverflow.com/questions/8229597/embedding-python

**Comment by mrjbq7** [comment]
Updated the Python bindings to Python 3.
