### ISSUE TITLE
if script has USE: errors, wrong error is reported

### ISSUE THREAD

**Issue by erg** [factor/factor#1152]
``` factor
! env.factor
USE: system
USE: prettyprint
! USE: prettyprint.config ! if this line is commented out, then script fails with wrong error message
USE: environment
os-envs [ . ] without-limits
```

``` factor
resource:basis/io/launcher/windows/windows-tests.factor: 177

Unit Test: {
    [ "B" ]
    [
        launcher-test-path [
            <process> console-vm "-script" "env.factor" 3array
            >>command { { "A" "B" } } >>environment
            utf8 <process-reader> stream-contents
        ] with-directory ( -- alist ) eval "A" of
    ]
}

1: env.factor
             ^
No word named “env.factor” found in current vocabulary search path
```

**Comment by dimmie** [comment]
After a long due git pull, newly updated factor now fails to deloy unmodified source code. The stack walk-down identifies the problem as peg.factor using a 5drop word which cannot be found in the kernel vocabulary. I am not a factor wizard, and my patch is just that : a mean to have things working.
----------------------------------------------------------------------------------------
cat basis-peg-factor.patch
diff -urN factor-unpatched/basis/peg/peg.factor factor-patched/basis/peg/peg.factor
--- factor-unpatched/basis/peg/peg.factor	2019-04-13 00:21:54.388380178 +0200
+++ factor-patched/basis/peg/peg.factor	2019-04-13 00:00:02.848358966 +0200
@@ -18,6 +18,9 @@
 
 SYMBOL: error-stack
 
+! somehow 5drop isn't found in the current kernel
+: 5drop ( v w x y z -- ) 4drop drop ; ! inline
+
 : merge-overlapping-errors ( a b -- c )
     dupd [ messages>> ] bi@ union [ [ position>> ] [ got>> ] bi ] dip
     <parse-error> ;
----------------------------------------------------------------------------------------
That allows the deploy-tool to perform its job correctly.
As to why 5drop should be missing in the kernel vocabulary at that instant in the execution, that's way over my abilities to figure out.

**Comment by dimmie** [comment]
Oooh shucks ! This damn' thing does markdown. It was not my intent, sorry.

**Comment by mrjbq7** [comment]
run:

delete-staging-images

Try again?

we need to version the images at some point so they can be detected as stale and regenerated automatically.
