### ISSUE TITLE
The factor/factor repo, or "is factor dead?"

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1160]
Im talking about this one: https://github.com/factor/factor It says it's the github mirror. I've seen people on irc and hacker news think factor is a dead project because nothing happens in factor/factor, all the action is in slavapestov/factor. And it's bad if people have that perception. Can something be done about it? Like redirect from factor/factor to slavapestov/factor or rename the repo slavapestov/factor to factor/factor?

**Comment by mrjbq7** [comment]
I'd love to switch to factor/factor. Would doing this before 0.98 be a good idea so it can be announced at the same time?

**Comment by bpollack** [comment]
This has been done, y'all! Let's close this.

**Comment by mrjbq7** [comment]
Done!!

**Comment by bjourne** [comment]
Great work! :+1:
