### ISSUE TITLE
Factor needs xmpp/pubsub/comet/bayeux/websockets protocol(s)

### ISSUE THREAD

**Issue by erg** [factor/factor#1200]
I'm writing a demo from a webapp and it's hard to get the data out. I wanted to use raw TCP sockets but the browser support is lacking and you have to do timeouts/reconnects, which we don't do well either. pubsub would be easy but we don't support it.

Checked items are implemented, crossed-out items are scrapped.

- [ ] HTTP/2 - important
- [ ] gRPC
- [ ] QUIC - maybe
- [ ] websockets - http://en.wikipedia.org/wiki/WebSocket
- [ ] capnproto - https://capnproto.org/
- [ ] protobuf - https://github.com/google/protobuf
- [ ] xmpp - http://en.wikipedia.org/wiki/XMPP
- [ ] xmpp pubsub - http://www.xmpp.org/extensions/xep-0060.html
- [ ] nodejs client and serverside pubsub - http://faye.jcoglan.com/
- [ ] bayeux protocol - http://svn.cometd.org/trunk/bayeux/bayeux.html
- [ ] pubnub - http://www.pubnub.com/
- [ ] graphql - http://graphql.org/
- [ ] apache arrow - https://github.com/apache/arrow
- [ ] apache parquet - https://parquet.apache.org/
- [ ] iap/ion - no idea
- [ ] AMQP
- [ ] MQTT
- [x] msgpack - http://msgpack.org/  (Edit: in `extra/msgpack`)
- [ ] ~~SPDY - maybe~~
- [ ] ~~libwebsockets - https://libwebsockets.org/trac/libwebsockets~~
- [ ] ~~pubsubhubbub spec - https://pubsubhubbub.googlecode.com/git/pubsubhubbub-core-0.4.html~~

**Comment by bpollack** [comment]
Don't we speak msgpack, or am I missing something? And the big thing we're missing from that list we badly want is HTTP2.

**Comment by erg** [comment]
``extra/msgpack`` - I never noticed!

HTTP2 -- What's the best strategy? Implement it in Factor or use a library?

**Comment by bpollack** [comment]
You want natively, and there are nice test suites we can use (e.g. https://github.com/http2/http2-test/) to make doing that easier. However, HTTP/2 requires our SSL library be fully up-to-snuff, and now you know part of my motivation for trying to clean up that mess. :)

**Comment by mrjbq7** [comment]
Since 2013! 

http://re-factor.blogspot.com/2013/11/messagepack.html

**Comment by bpollack** [comment]
I swear, whenever I want a library, I usually just look at your blog first and see if you already did it @mrjbq7. I enjoyed using the Gopher client on Metafilter's relaunched server, too. :)

**Comment by mrjbq7** [comment]
:-)

I need to code some more.  Real life got in the way with twins (now 6 months old!) that needed some of my time.

**Comment by bpollack** [comment]
Hah, that makes sense. I'm in the middle of buying a house; hacking on Factor in my spare time is the only thing keeping me sane right now.

**Comment by bpollack** [comment]
@erg SPDY is deprecated and getting removed from all major browsers since HTTP/2 is now "done"; we don't need that. You may want to add [QUIC](https://en.wikipedia.org/wiki/QUIC) in its place if you want one of the experimental-but-likely-to-land things; up to you. WebSockets, I don't think we'd want to use `libwebsockets`, but that's up to whoever gets there. I believe that pubsubhubnub is effectively dead at this point, so I'm not sure that's worth implementing.

**Comment by erg** [comment]
https://github.com/factor/factor/issues/2039 supersedes this issue. We really only need one of these checklists.
