### ISSUE TITLE
SBUF" " doesn't show high code points in describe

### ISSUE THREAD

**Issue by erg** [factor/factor#1237]
```factor
IN: scratchpad SBUF" " clone 65279 over push describe
sbuf with 1 elements
underlying "\0\0"
length     1
```

**Comment by bjourne** [comment]
I think it is right how it is. "aux" shouldn't be shown anywhere because it is a private detail like "count" and "deleted" slots of `hashtable`.

**Comment by erg** [comment]
I want to see all the information in the sbuf somehow. Maybe juts like strings?

Showing an empty underlying array is misleading because it's not the full story.

**Comment by bjourne** [comment]
You can always use: `SBUF" " clone 65279 over push underlying>> describe` to see the string. 

But maybe describe on all sequences should show the contained elements? It's logical if `BV{ 3 4 } describe` works analogous to `SBUF" 34" describe`.

**Comment by erg** [comment]
```factor
IN: scratchpad SBUF" " clone 65279 over push describe
sbuf with 1 elements
underlying "﻿\0"
length     1
```

Who would call ``underlying>>`` when it says it's zero?

I use ``describe`` to try to get at all of the information about an object, especially things that the prettyprinter hides like if tuple literals have the default slot values then they aren't shown, or words like ``+`` that are obviously hiding something. If ``describe`` doesn't show you all the implementation information and hidden data, then what will?
