### ISSUE TITLE
strings don't show low code point characters in describe

### ISSUE THREAD

**Issue by erg** [factor/factor#1238]
Strings have the opposite problem of ``SBUF"``--they show the ``aux`` but not the ``underlying``.

```factor
IN: scratchpad "abc" describe
string with 3 elements
length 3
aux    f
```

See #1237.

**Comment by bjourne** [comment]
I fixed it so they would work like arrays:
```factor
"случайный" describe
string with 9 characters
0 1089
1 1083
2 1091
3 1095
4 1072
5 1081
6 1085
7 1099
8 1081
```
It has the side effect of letting you edit the slots in the inspector.

**Comment by erg** [comment]
Cool!

**Comment by mrjbq7** [comment]
Maybe instead of the number it should show the 1string of the code point?

**Comment by erg** [comment]
Or an assoc with both? I like to see the code points.

**Comment by mrjbq7** [comment]
an alist with key of 1string and value of code point?

**Comment by mrjbq7** [comment]
(An alist so it is ordered properly)

**Comment by erg** [comment]
It needs indices too i think.

On Fri, Mar 25, 2016 at 2:05 PM, John Benediktsson <notifications@github.com

**Comment by mrjbq7** [comment]
Right so leave it as is?  Or print the string in the first line before the characters? Or make the value:

[ 1string ] [ number>string ] bi " " glue

Or something

**Comment by erg** [comment]
How about tabular output with index, code point, and ``1string``?

**Comment by bjourne** [comment]
The textual output of `describe` probably wouldn't be so hard to fix. But how do we make it look good in the Inspector? Like in the UI you can click on a string and then edit it.

**Comment by mrjbq7** [comment]
I can work on this later today if you want.

The inspector uses the mirrors vocab and a table renderer in ui.tools.inspector. 

It assumes 2 columns: key/value

I think would be harder to make work like @erg said without a bunch of special cases.
