### ISSUE TITLE
reading from files using stream-length is broken, e.g. /proc/cpuinfo

### ISSUE THREAD

**Issue by erg** [factor/factor#1259]
```factor
USE: tools.hexdump
"/proc/cpuinfo" hexdump-file
! Length: 0, 0h

"/proc/cpuinfo" binary file-contents .
B{ }

"/proc/cpuinfo" utf8 file-contents .
! works...
```

**Comment by bjourne** [comment]
Is it still broken? `"/proc/cpuinfo" hexdump-file` works for me.

**Comment by mrjbq7** [comment]
Yeah, I think I fixed it in 924fc60e30516b8dc2e4665c1cf4abdde929da45.

We still have a race condition on ``/proc`` files where the ``length`` changes between when you ``stat`` and when you ``read``, but thats a separate bug.

**Comment by erg** [comment]
Is this a speed regression on files with known length? Might want to make a separate issue for that slowdown if so.

**Comment by mrjbq7** [comment]
It was, but I think fixed now.

**Comment by mrjbq7** [comment]
I guess the original race condition bug is still a bug.

**Comment by bjourne** [comment]
Cross referencing the ml thread: http://article.gmane.org/gmane.comp.lang.factor.general/7692
