### ISSUE TITLE
Cookie parse errors?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1331]
Noticed this patch on Python.

https://hg.python.org/cpython/rev/9e765e65e5cb

They return an empty parse, we throw errors, but different ones:

``` factor
IN: scratchpad { "]foo=x" "[foo=x" "blah]foo=x" "blah[foo=x" }
               [ [ parse-cookie . ] [ . ] recover ] each

T{ bounds-error { index 0 } { seq V{ } } }
T{ bounds-error { index 0 } { seq V{ } } }
T{ parse-error
    { position 4 }
    { got "blah]foo=x" }
    { messages V{ "'='" } }
}
T{ parse-error
    { position 4 }
    { got "blah[foo=x" }
    { messages V{ "'='" } }
}
```

Might want to normalize the errors, or possibly return empty cookies like Python?

**Comment by bpollack** [comment]
I can make the errors consistent (it's pretty easy to convert the `bounds-error` to a `parse-error`, or to jacket both in a `cookie-error`, if you'd prefer); that we should introduce a new word, `parse-cookies`, which silently drops cookies that error; and then that `http.server.requests:extract-cookies` should be switched to the new word. I'm going to start a PR that does this, but yell if this plan sounds bad.

**Comment by mrjbq7** [comment]
Sure, that cleanup sounds good.  As for normalizing the errors, that's up to you.

**Comment by bpollack** [comment]
*A brief day of delay ensues while I learn PEGs.*

**Comment by mrjbq7** [comment]
http://re-factor.blogspot.com/2009/08/calculating-with-ebnf.html

http://re-factor.blogspot.com/2010/07/rolling-dice.html

http://re-factor.blogspot.com/2011/08/printf.html

**Comment by erg** [comment]
```factor
{ "]foo=x" "[foo=x" "blah]foo=x" "blah[foo=x" }
               [ [ parse-cookie . ] [ . ] recover ] each
{ T{ cookie { name "]foo" } { value "x" } } }
{ T{ cookie { name "[foo" } { value "x" } } }
{ T{ cookie { name "blah]foo" } { value "x" } } }
{ T{ cookie { name "blah[foo" } { value "x" } } }
```

**Comment by erg** [comment]
This works now, closing!

**Comment by erg** [comment]
![signal-2022-01-06-205247_001](https://user-images.githubusercontent.com/27430/148483927-0027c795-6611-4d13-92eb-8ebe77cd54a6.png)
