### ISSUE TITLE
extra/variants leaks disposables

### ISSUE THREAD

**Issue by erg** [factor/factor#1346]
``help-lint-all`` reported this somehow.

```
resource:extra/variants/variants-docs.factor: 39

Asset: T{ link f match }

41 disposable(s) leaked in example
```

**Comment by mrjbq7** [comment]
I get those sometimes when running ``help-lint``, but its not consistent.

Run ``"variants" help-lint`` a couple times and the error goes away... not sure whats going on.

**Comment by mrjbq7** [comment]
So I looked at the leaks and they are:

```
HS{ ~line~ ~single-texture~ ~single-texture~ ~single-texture~...
```

So basically, UI stuff that is being cached... so we should either close this bug report, or maybe ignore them in the help-lint?

**Comment by mrjbq7** [comment]
Could do something like this:

```diff
diff --git a/basis/help/lint/checks/checks.factor b/basis/help/lint/checks/checks.factor
index 0133e3b..2bd523f 100644
--- a/basis/help/lint/checks/checks.factor
+++ b/basis/help/lint/checks/checks.factor
@@ -29,7 +29,11 @@ SYMBOL: vocab-articles
             ] keep
             last assert=
         ] vocabs-quot get call( quot -- )
-    ] leaks members length [
+    ] leaks members
+    [
+        class-of vocabulary>>
+        { "core-text" "opengl" "ui" } [ head? ] with any?
+    ] reject length [
         "%d disposable(s) leaked in example" sprintf simple-lint-error
     ] unless-zero ;
 
```

**Comment by bpollack** [comment]
Do we wanna do something like this? I can figure out what exact classes to filter out, and probably make an auxiliary word that doesn't do the filtering as well for GUI tests.

**Comment by erg** [comment]
@bpollack go for it!

**Comment by mrjbq7** [comment]
I filtered out specific classes on mac, linux, and windows (by "name" so it's not perfect), but better than filtering by vocabulary.  However, there are probably tests where we wouldn't want to filter them out, but....

**Comment by mrjbq7** [comment]
Should be "fixed".
