### ISSUE TITLE
Compressed images?

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1377]
That thought occurred to me while looking at some tests that fail because the images has gotten to big. You get a fairly nice compression ratio:

```
$ ls -hl factor.image
-rw-r--r-- 1 bjourne bjourne 73M jun 27 22:12 factor.image
$ gzip -c factor.image > factor.image.zip && ls -lh factor.image.zip
-rw-rw-r-- 1 bjourne bjourne 18M jun 29 21:08 factor.image.zip
```

It would probably require adding zlib as a dependency because a decompressor written in factor probably wouldn't be fast enough. What do you think?

**Comment by nomennescio** [comment]
See #2577 for a more optimal solution using Zstd compression
