### ISSUE TITLE
Unicode listener text input bugs

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1382]
I got inspired to make an emoji vocabulary and noticed some bugs with unicode input on Mac.

If you define this:

``` factor
CONSTANT: 🔟 10 inline
```

And then try to "paste" 🔟into the listener, then try and type a space and then text like `sqrt`, or even paste one then space paste another, then `+`, you can see that the cursor is having trouble being at the correct location.

**Comment by mrjbq7** [comment]
If you're curious here are other emoji:

https://github.com/mrjbq7/re-factor/blob/master/emoji/emoji.factor

**Comment by pirj** [comment]
🔟 is not properly aligned in Chrome, iTerm2 (width detected as single instead of double). However, it is properly aligned in Safari (same sites), Spotlight, Contacts, Notes.

**Comment by erg** [comment]
This particular issue is resolved.
