### ISSUE TITLE
Bug when drawing text on a gradient

### ISSUE THREAD

**Issue by nicolas-p** [factor/factor#1397]
I think I found a bug that occurs when drawing text on a gradient background, and that occurs on Windows but not on OS X.

```factor
"hello" >label
[ t >>bold? ] change-font
{ 10 10 } <border>
{ COLOR: white COLOR: grey85 } <gradient> >>interior gadget.
```

On Windows, the text appears on a black background, which is itself inside the gradient. On OS X, the text appears normally inside the gradient.

The problem doesn't occur when the gradient is replaced by a solid background.

On both systems I used recent 64-bit development versions of Factor.

**Comment by jonenst** [comment]
Also, the text appears when it is selected.

Jon

**Comment by erg** [comment]
This may be related:
https://github.com/slavapestov/factor/issues/152

I think the slides use gradients?

**Comment by mrjbq7** [comment]
Good find! Lets fix this for next release.

**Comment by mrjbq7** [comment]
When this is fixed, need to remove the workarounds in https://github.com/slavapestov/factor/blob/master/basis/ui/gadgets/labeled/labeled.factor#L16 and https://github.com/slavapestov/factor/blob/master/extra/slides/slides.factor#L57.

**Comment by bjourne** [comment]
Let's close this since it is the same bug as #152.
