### ISSUE TITLE
Factor Windows binaries should be signed with an Extended Validation (EV) Cert (Windows SmartScreen)

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1403]
I was trying Factor on a Windows computer (not something I personally do a lot of) and noticed that Windows SmartScreen prevents it from starting because it is an unrecognized publisher.  Can we sign the Windows apps like we do the Mac ones?

**Comment by erg** [comment]
http://stackoverflow.com/questions/84847/how-do-i-create-a-self-signed-certificate-for-code-signing-on-windows

**Comment by mrjbq7** [comment]
Be nice to fix this for 0.98

**Comment by mrjbq7** [comment]
@erg ping :-)

**Comment by erg** [comment]
We are now self-signing, but we need a .net account to sign through microsoft.

**Comment by AlexIljin** [comment]
How about an authoritative signature? Free certs for open-source code signing here:
https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

**Comment by erg** [comment]
https://www.digicert.com/order/order-1.php EV cert $200/yr hmm

**Comment by erg** [comment]
/@AlexIljin I'll try your link soon. I wonder if they offer EV certs?

**Comment by AlexIljin** [comment]
@erg, they only offer DV certs, but in a completely automated fashion, so that you never have to worry about it again.

**Comment by AlexIljin** [comment]
They do offer EV, but that's a separate offer, not the same as the free certs for open-source software.
The free ones are same as the Standard Code Signing offer.

**Comment by mrjbq7** [comment]
I couldn't get an EV code signing certificate as an individual, but the binaries are now signed by my normal code signing certificate.
