### ISSUE TITLE
change-at, change-nth, change-global defined when they shouldn't be

### ISSUE THREAD

**Issue by erg** [factor/factor#1437]
In `core/slots/slots.factor` we define these headache words. Maybe we can handle removing them now?

``` factor
! Predefine some slots, because there are change-* words in other vocabs
! that nondeterministically cause ambiguities when USEd alongside
! accessors

SLOT: at
SLOT: nth
SLOT: global
```

**Comment by erg** [comment]
We use ``at`` as a slot accessor in ``extra/zoneinfo``

**Comment by mrjbq7** [comment]
I'm not sure... If at some point someone ever defines those slots then refresh / reload on already working code will break with disambiguation. It sucks that code working depends on other vocabs not in your use hierarchy, no?

**Comment by erg** [comment]
Yep. The ``change-foo`` words are the real culprit here, because nobody has good reason to redefine ``>>a`` and ``a>>`` and ``a<<`` really, but names like ``change-global`` and ``change-at`` and ``change-nth`` are all three desirable names for dealing with variables and hashtables.

Maybe we can just stop generating ``change-foo`` and replace it with something?

**Comment by erg** [comment]
923df44ec31d4e1b660284b2d11123a4aa9b8fbf lol.

**Comment by erg** [comment]
I think the solution is to use ``change: slotname`` everywhere and remove the ``change-slotname`` accessors. That way nobody can break your vocabulary simply by defining a tuple class that has a slot name that conflicts with an existing word, e.g.

```factor
: change-nth ( ..a i seq quot: ( ..a elt -- ..b newelt ) -- ..b )
    [ [ nth ] dip call ] 3keep drop set-nth-unsafe ; inline

TUPLE: nth-holder nth ;

T{ nth-holder f 0 } [ 1 + ] change: nth
```

If you use the ``change:`` your vocabulary is robust against slot name conflicts. ``change-foo`` can't be used in core/ yet because it's a macro, so we can't get rid of generated ``change-foo`` words yet.

**Comment by mrjbq7** [comment]
Maybe... but it is weird syntax, I perhaps there's a way to name a changer that looks more like our slot accessors.

**Comment by mrjbq7** [comment]
Alternatively, we should use ``get:  foo`` and ``set: foo`` for symmetry with ``change: foo``.

**Comment by bjourne** [comment]
I think it is harder to see what goes on if extra syntax is added. You can type `\ change-foo see` and see what the generated word is doing. Can't we just change the name of `change-foo` to something more special like um.. `[foo]>>`?

**Comment by bpollack** [comment]
Kind of with @bjourne on this one. I'm not keen on adding yet another thing the debugger can't actually display sanely, and I don't think it'd be intuitive to most people that `get: foo` is a single word. But having something less likely to cause collisions might be really handy.

**Comment by erg** [comment]
This has been fixed by having vocab:foo everywhere imo.
