### ISSUE TITLE
fresh bootstrap has :error?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1444]
Fresh bootstrap on Mac OS X, and I saw a tip-of-the-day about ``:error`` and hmm, why is there an ``error get``?  

```factor
IN: scratchpad :error
uninferable

IN: scratchpad error get .
T{ uninferable }
```

Looks like ``uninferable`` is throw from ``compiler.tree.propagation.call-effect``, and maybe we aren't clearing the ``error`` variable when we should?

**Comment by bjourne** [comment]
Weird. Looks like the compiler is setting the `error` variable in some strange way:

```factor
IN: scratchpad f error set-global
IN: scratchpad USE: fuel
...
IN: scratchpad error get-global

--- Data stack:
T{ uninferable }
```

**Comment by erg** [comment]
Having errors after a fresh bootstrap is bad. Let's fix this for .98.

**Comment by bjourne** [comment]
It's weird that sometimes `error get` is used and other times `error get-global` to get the error. Also the variable is set even if the error is handled/ignored like in `[ 0 0 / ] ignore-errors`. Looks like the `error-continuation` global is also set by default.

**Comment by mrjbq7** [comment]
This might be part of the problem:

```
IN: scratchpad [ "asdf" throw ] [ drop ] recover
IN: scratchpad error get-global .
"asdf"
```

Maybe ``recover`` and ``cleanup`` shouldn't leave the ``error`` and ``error-continuation`` (and ``original-error``) set?

**Comment by bjourne** [comment]
I think so too. Like if you write `[ 1 0 / ] [ ] recover`, then the error is on the stack and you shouldn't need to look in the `error` global to find the error. But a problem is that the callstack is not on the stack so you need to look at `error-continuation` to find it. I think it would be better if the error object itself included the continuation containing the callstack.

Like, writing `"asdf" throw` would create a thrown error tuple: `T{ thrown-error { object "asdf" } { continuation ... } { restarts ... } }` wrapping what is thrown. 

Btw the commit in fc9eb0d5acba9bb8c0063e82ce17b6cadfc61b39 should make it so a fresh bootstrap never has those variables set.
