### ISSUE TITLE
DLL errors

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1464]
I'm going through the windows dlls (http://downloads.factorcode.org/dlls/) and checking which are having load problems.

### 32 bit
* `libudis86.dll` - links to ´msvcr120d.dll` which is a debug dll and can't be distributed outside of vs
* `libpq.dll` - links to ´libintl.dll` which we dont have in 32bit
* `libintl-8.dll`, `libintl.dll` -  both are 64bit

 Edit: I deleted all of these. -erg

**Comment by bjourne** [comment]
## 64 bit
`bzip2.dll` - is a 32bit dll
`freetype6.dll` - also 32bit
`glut32.dll` - also 32bit
`intl.dll` - also 32bit
`jpeg62.dll` - also 32bit
`libasprintf-0.dll` - looks for a `libgcc_s_sjlj-1.dll`

**Comment by bjourne** [comment]
## 64 bit
* `libatk-1.0-0.dll` 32bit
* `libglib-2.0-0.dll` 32bit
* `libgmodule-2.0-0.dll` 32bit

**Comment by erg** [comment]
http://opendll.com/index.php?file-download=libpq.dll&arch=32bit&version=7.0.2.0&dsc=PostgreSQL-Access-Library#

Cool site, might use some of these, but I have to reboot into Windows later to try.

**Comment by erg** [comment]
Updated dlls to libressl-2.3.2 for win32/win64 on factorcode.

**Comment by erg** [comment]
I'll update all of the 32/64 dlls that the build machine is using and start mirroring those onto factorcode.org.

**Comment by bpollack** [comment]
@erg I don't have permissions to do this, but can you edit the description and throw in a checklist of what is and isn't broken? I have build scripts for some of these libs from ~2011; I don't mind updating them to a recent VS, and there's some comfort in being able to build our support libs.

**Comment by erg** [comment]
I'm bundling sqlite and libressl on Windows. I deleted all the problem libraries mentioned here so the dlls/ directories on downloads.factorcode.org should have dlls that load and might do what you expect.

I think we can make people find their own dlls
