### ISSUE TITLE
Register spilling happens too early

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1471]
Consider this cfg:

```factor
=== Basic block #12

##spill RBX tagged-rep T{ spill-slot }
##check-nursery-branch 32 cc<= RAX RCX

Successors: 14, 13

=== Basic block #13

##save-context RAX RCX
##call-gc T{ gc-map
    { scrub-d { } }
    { scrub-r { } }
    { gc-roots { T{ spill-slot } } }
    { derived-roots V{ } }
}
##branch

Successors: 14

=== Basic block #14

##load-reference RBX {
    self
    1
    2
    tuple
    236985587512
    struct
    286361846888410896
    self
    432054795567209679
}
##allot RAX 24 tuple RCX
##set-slot-imm RBX RAX 1 7
##reload RBX tagged-rep T{ spill-slot }
##set-slot-imm RBX RAX 2 7
##replace RAX D: 0
##compare-imm-branch RAX f cc/=
```
Generated using `[ self <struct> dup doget [ 2 slot 0 alien-cell dup [ self memory>struct ] when dup ] loop ] regs.`. The `##spill` and `##reload` should be moved inside the `##call-gc` block:

```factor
=== Basic block #13

##spill RBX tagged-rep T{ spill-slot }
##save-context RAX RCX
##call-gc T{ gc-map
    { scrub-d { } }
    { scrub-r { } }
    { gc-roots { T{ spill-slot } } }
    { derived-roots V{ } }
}
##reload RBX tagged-rep T{ spill-slot }
##branch
```
That way 99% of all spill/reloads wouldn't be executed and Factor would be a little faster.

**Comment by mrjbq7** [comment]
I don't know if you have time to fix this but it could be a really awesome improvement!

**Comment by mrjbq7** [comment]
@bjourne is this something you were working on for 0.98 release?  Would be cool!

**Comment by bjourne** [comment]
Yep I'm working on it. But mostly because it is interesting. It probably won't make the generated code noticably faster.

**Comment by mrjbq7** [comment]
Interesting is good!!

**Comment by bjourne** [comment]
Thinking loud.. Looks like the intervals are split on each sync point. Which is why spills and reloads are interspersed in normal code. 

Would probably be better to not split them and then for each sync point look what vregs are live and spill those. For each live vreg that is in tagged-rep, add that to the set of roots to be traced. ##call-gc should look like:
```
##call-gc T{ gc-map
    { scrub-d { 0 0 0 0 } }
    { scrub-r { 0 0 0 0 0 } }
    { spills { { RBX T{ spill-slot } t } { RAX T{ spill-slot { n 8 } } f } } }    
    { derived-roots V{ } }
}
```
`{ RBX T{ spill-slot } t }` would mean spill from RBX to the first spill slot AND trace it. `{ RAX T{ spill-slot { n 8 } } f } }` spill to offset 8 and NOT trace it.

**Comment by bjourne** [comment]
Almost there.. Not splitting them did kind of work. Except for ##alien-invoke, there you gain a lot by "amortizing" the spill/reloading:

```factor
##mul-float XMM1 XMM1 XMM2
##add-float XMM0 XMM0 XMM1
##spill XMM0 double-rep T{ spill-slot { n 184 } }
##alien-invoke V{ { T{ spill-slot { n 184 } } double-rep XMM0 } } V{ } { { T{ spill-slot { n 192 } } double-rep XMM0 } } { } 0 0 cos
 f T{ gc-map
    { scrub-d { } }
    { scrub-r { } }
    { gc-roots { T{ spill-slot { n 144 } } T{ spill-slot } } }
    { derived-roots V{ } }
}
##alien-invoke V{ { T{ spill-slot { n 184 } } double-rep XMM0 } } V{ } { { T{ spill-slot { n 200 } } double-rep XMM0 } } { } 0 0 sin
 f T{ gc-map
    { scrub-d { } }
    { scrub-r { } }
    { gc-roots { T{ spill-slot { n 144 } } T{ spill-slot } } }
    { derived-roots V{ } }
}
```

**Comment by bjourne** [comment]
I made it work. So the block containing the `##call-gc` would also contain the `##spill` and `##reload` instructions:

    ##spill RBX tagged-rep T{ spill-slot }    
    ##call-gc T{ gc-map
        { scrub-d { } }
        { scrub-r { } }
        { gc-roots { T{ spill-slot } } }
        { derived-roots V{ } }
    }
    ##reload RBX tagged-rep T{ spill-slot }
    ##branch

The crayze thing is that that executes *slower* than how it was before. Very odd.

**Comment by bjourne** [comment]
It was my shoddy benchmarking practices! On contrived benchmarks, where you write the code so that many redundant spills happen, it is like 8-11% faster. It has no negative impact on any benchmark which is to be expected.

**Comment by mrjbq7** [comment]
Cool!

**Comment by mrjbq7** [comment]
So this is fixed?

**Comment by bjourne** [comment]
I hope so.
