### ISSUE TITLE
Rename unordered-set back to set for 0.98 release

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1473]

**Comment by erg** [comment]
:-1:  C++ has unordered-set and that's what the data structure is in Factor. 

http://www.cplusplus.com/reference/unordered_set/unordered_set/

**Comment by mrjbq7** [comment]
It's not, though.

It was ``set`` which could stand for either ordered or unordered, it was not guaranteed.

If we have a ``ordered_set``, then both unordered and ordered should derive from ``set`` which should have most of the generic methods defined on it.

**Comment by mrjbq7** [comment]
Python:

    set
    https://docs.python.org/2/library/stdtypes.html#set

Ruby:

    Set
    http://ruby-doc.org/stdlib-1.9.3/libdoc/set/rdoc/Set.html

Javascript:

    Set
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

Perl:

    Set::Object
    http://search.cpan.org/~rurban/Set-Object-1.35/lib/Set/Object.pm

    Set::Scalar
    http://search.cpan.org/~davido/Set-Scalar-1.29/lib/Set/Scalar.pm

C++:

    Set (also unordered_set)
    http://www.cplusplus.com/reference/set/set/

Scala:

    Set
    http://docs.scala-lang.org/overviews/collections/sets.html

Java:

    Set
    https://docs.oracle.com/javase/7/docs/api/java/util/Set.html

C#:

    Set
    https://msdn.microsoft.com/en-us/library/ms228368.aspx

OCaml:

    Set
    http://caml.inria.fr/pub/docs/manual-ocaml/libref/Set.html

Erlang:

    Set
    http://www.erlang.org/doc/man/sets.html


Racket:

    Set
    http://docs.racket-lang.org/reference/sets.html

**Comment by bjourne** [comment]
+1 on set. I think it's implied that a set is unordered unless otherwise specified.

**Comment by mrjbq7** [comment]
Part of the rename is to not conflict with namespaces:set which is used a lot. Working on uniform variable syntax or using get: and set: and change: syntax instead maybe.

**Comment by mrjbq7** [comment]
But I agree, I'm +1 on `set`.

**Comment by mrjbq7** [comment]
Another argument:

If we have ``unordered-set``, presumably we also have ``ordered-set``... what do those have in common?  Well, ``set`` of course!

**Comment by mrjbq7** [comment]
Even Swift has a ``Set``:

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html

Also, closing this bug, fixed!

(Or mostly fixed, a few ``namespaces:set`` still to add to get all vocabs to load).
