### ISSUE TITLE
Add back triple quote strings for 0.98 release

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1474]

**Comment by bjourne** [comment]
What was the deal with those? Do we need triple quotes when strings can span multiple lines?

**Comment by mrjbq7** [comment]
No mostly triple quotes make it easy to have strings with quotes in them. And I got to like them in Python. @erg wants Lua style strings in 0.98 with the new parser, which are more flexible but also less visually "string-like".

**Comment by mrjbq7** [comment]
I'm not sure I'm in favor of adding them back but we have no "string with quotations in them" solution without escaping right now.

**Comment by bjourne** [comment]
I see. Also in Python, both `'` and `"` can be used for strings so if you have lots of double quotes embedded you use single quote strings and vice versa: `'python "string"'` `"python 'string'"`

**Comment by mrjbq7** [comment]
Right.  That's handy and fits the "looks like a string" rule. I'm not totally convinced `[[text]]` or `[=[text]=]` looks enough like a string to give up the idea of triple quotes or single quote strings.

**Comment by bjourne** [comment]
I don't like `[[` as string delimiter either. So should we aim to add `'` strings instead or are you adamant on getting `"""` back? Maybe the latter since """ already existed in 0.97?

**Comment by erg** [comment]
I added ``[[`` and ``![[`` to ``multiline`` as lua-string/magic-string delimiters in 75d6395849a999bd6eef9aadd95d5f027bcbcf8f. It's not perfect because you need a space after the opening delimiter (but not before the closing delimiter) and they don't extend to arbitrary size yet.

The triple-quote or single-quote strings dont solve a problem because they can't contain arbitrary string payloads without escaping the delimiters.

**Comment by erg** [comment]
Imo this is fixed. 👍

**Comment by mrjbq7** [comment]
I like triple-quotes because it looks like a string.  IMHO, Lua strings are awesome as a feature, but they look weird to 99% of programmers.

**Comment by bpollack** [comment]
Since Factor *itself* "looks weird" to most programmers, that's the least persuasive argument I could come up with. Every other concern you've raised seems fair.

**Comment by AlexIljin** [comment]
I agree with @mrjbq7.

I also like the triple quotes, and I strongly dislike the idea of the mandatory space after the `[[`, or whatever prefixes there are. It's inconsistent with the simple double-quoted strings, which include the leading space in the string contents; and the square brackets are strongly associated with quotations, breaking that association with a special case for strings also violates the consistency. Just my opinion, of course.

I like the conciseness and expressiveness of Factor, and a lot of it stems from meaningful use of characters. Repurposing the brackets in such way would be weird, and not in a good way. We already have quotes for strings.

**Comment by mrjbq7** [comment]
The mandatory space goes away in 0.99's development cycle with the new parser. Which to me is compelling reason to add triple quotes back. The reason not to is the new parser doesn't currently support them (but could and maybe should).

**Comment by erg** [comment]
We have [[ ]] now, it should be integrated into the parser without leading whitespace soon, and it should subsume any use case you'd ever want for ``"""``. :)
