### ISSUE TITLE
Possible memory leak using io.directories.search

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1483]
From the mailing list:

> Well, I just checked the running factor session that failed the 
> task overnight that I mentioned in below email.
> 
> From the linux system command 'top',  
> I see that this particular factor is using 
> VIRT   4.0g
> RES   2.0g
> %MEM 26%
> 
> I clicked on the restart listener button and the numbers remain the same.
> should I have done more to clean up the memory usage ?
> ---
> 
> For comparison, I killed the factor session and restart it from the shell.
> The numbers are
> VIRT  940M
> RES  182M
> %MEM 2.2%
> 
> ==> Had the factor continued to run last night,
>        it would have probably exhausted the memory on the machine.
>        I guess there might be some memory (leak) issue somewhere ???
> 
> --HP
> 
> ---------- Forwarded message ----------
> From: HP wei hpwei01@gmail.com
> Date: Thu, Oct 1, 2015 at 9:36 AM
> Subject: how to error trapping 'link-info'
> To: factor-talk@lists.sourceforge.net
> 
> As suggested by John, I test out the following action to 
> get the total file sizes of a disk volume.
> 
> 0 "a_path_to_big_folder" [ link-info dup symbolic-link? [ drop ] [ size>> + ] if  ] each-file
> 
> Our big-folder is on a netapp server shared by tens of people. Many small files get updated
> every minutes if not seconds. The update may involve removing the file first.
> It has many many subfolders which in turn have more subfolders.
> Each subfolder may have hundreds of files (occasionally in the thousands).
> 
> After a few day's discussion with factor guru's, I understand that
> each-file traverses the directory structure by first putting 
> entries of a folder in a sequence. And it processes each entry one by one.
> Although this may not cause using big chunk of memory at a time,
> it does have the following issue..
> ---
> 
> Last night, I left the command running and came back this morning to find
> that it failed with the message.
> lstat:  "a path to a file" does not exist !!!
> 
> This is because after 'each-file' puts the file into the sequence and then when 
> it is its turn to be processed, it is not there at the time!!
> Without error trapping, the above "0 ... each-file"  could not work in our case.
> 
> So, I guess I would need to do error-trapping on the word link-info.
> I do not know how to do it.  Any hint ?
> 
> Thanks
> HP

**Comment by mrjbq7** [comment]
Follow up:

> Summary of further investigation.
> 
> The code
> 0 "a_path_to_big_folder" x [ link-info dup symbolic-link? [ drop ] [ size>> + ] if  ] each-file
> 
> (1) when x = t  (breadth-first  BFS)
>      the memory usage reported by linux's  'top' shows steady increase 
>      from around 190M to as high as 2GB before either I killed it or it hit tge
>      missing file issue.
> 
> (2) when x = f  (Depth-first DFS)
>      Watching RES from 'top', I noticed that
>      the memory usage even drops from 190M to around 94M before I went home
>      and let the code run in the office.
>      The next morning, I found that it finished OK with a total-file-size on the data stack
>   
>       But the total-file-size of about 280GB is incorrect.  It should be around 74GB.
> 
> -------------------------------------------------
> 
> Just a reminder, our disk has the following properties.
> 
>    it is a disk with a tree of directories.
>    directory count ~ 6000
>    total number of files as of now ~ 1.1 million
>    total number of softlinks ~ 570000
>    total file size ~ 70GB
> 
>    number of files in each sub-directory (not including the files in sub-directory inside it)
>    range from a few hundreds to as high as of the order of <~10K.
> 
>    (NOTE-A) Some of the folders are in fact softlinks that links to "OTHER disk locations".
> 
> --------------------------------------------------------
> 
> For the above disk,  DFS appears to consume much less memory !
> But the resulting file size is incorrect (280GB instead of 70GB).
> This is presumably due to (NOTE-A) and the code must have scanned through those
> OTHER disks.  But then the extra scanning appears to be incomplete!
> Becasue 280GB is too small.  A complete traversing the above disk plus all those
> OTEHR disks will amount to a few Terabytes.
> 
> So, somewhere the traversing was screwed up. This may be another investigation for another day.

**Comment by erg** [comment]
A naive summation of ``file-info`` will count symlinks as the size of the file that is pointed to. Using ``link-info`` yields the exact sizes for me. If that's not the issue it could be C struct/ffi/api bugs.

Also, directory traversal could be much more efficient if you were to keep a list of directory iterators instead of making a queue/stack of the directory paths when doing a BFS or DFS search.

```factor
USE: io.directories.search
"resource:core" t recursive-directory-files [ dup file-info size>> ] { } map>assoc
values sum .
557641748

USE: io.directories.search
"resource:core" t recursive-directory-files [ dup link-info size>> ] { } map>assoc
values sum .
556300378

! The only symlink on my mac directory
ergmac:factor erg$ [master*] ls -al Factor.app/Contents/MacOS/factor
-rwxr-xr-x  1 erg  staff  497048 Mar 25 12:11 Factor.app/Contents/MacOS/factor

497048 + 556300378 = 557641748
```

This find command doesn't include directory sizes and I'm not sure if it includes hidden files:
```bash
# in factor/
find . -type f -print0 | xargs -0 stat -f%z | awk '{b+=$1} END {print b}'
556300378
```

I'm not certain there is a memory leak. The size of virtual memory can grow very large but Factor's not necessarily using that much, and it also doesn't free it back to the OS.

**Comment by AlexIljin** [comment]
Should we close this issue, if there is no memory leak?
