### ISSUE TITLE
Resizing ui in gtk takes a very long time

### ISSUE THREAD

**Issue by erg** [factor/factor#1487]
When resized, the original window size is still drawn and Factor seems to redraw the window for each tick of the resize, taking several seconds. In the space that the resize is attempting to grow to is just black pixels.

**Comment by erg** [comment]
An even better demonstration is to grab a corner and resize several times before releasing the mouse. The window will then replay your mouse movements, drawing the zoom in and out.

It takes as long to draw the new size as you spent dragging the window.

**Comment by jonenst** [comment]
I'm pretty sure that's a new behavior.. Tested with the 0.97 release, it's
doing it also and I don't think it was doing it before. Are you using fglrx
? I recently updated fglrx on this machine.

Jon

**Comment by erg** [comment]
Nvidia GTX970 and AMD both show the behavior.

**Comment by mrjbq7** [comment]
Would be great to fix this for 0.98... complicated?

**Comment by mrjbq7** [comment]
Could be related to the GTK theme being used, perhaps try a different theme?

Alternatively, maybe because we are calling ``relayout`` on every ``expose-event`` here:

https://github.com/slavapestov/factor/blob/master/basis/ui/backend/gtk/gtk.factor#L260

**Comment by erg** [comment]
Doesn't fix it, but example of how to manually use main loop.
```
M: gtk-ui-backend (with-ui)
    [
        0 gint <ref> f void* <ref> gtk_init
        0 gint <ref> f void* <ref> gtk_gl_init
        load-icon
        init-clipboard
        start-ui
        [
            [
                [
                    ! gtk_main
                    [ gtk_main_iteration gtk_events_pending [ yield ] unless t ] loop
                ] with-timer
            ] with-event-loop
        ] with-destructors
    ] ui-running ;
```

**Comment by mrjbq7** [comment]
Refactored to ``yield`` in the idle callback in 2929cc21f5d1b17e71014f0c32f3fb2f33f744b6.

Maybe fixed by using ``with-event-loop`` without the ``with-timer`` in 7d5df2c8a28b37cb5a4f8dfbbb40698ed6507793.

**Comment by mrjbq7** [comment]
Another option is to delay the resize event:

```diff
diff --git a/basis/ui/backend/gtk/gtk.factor b/basis/ui/backend/gtk/gtk.factor
index 67b60f4..13a9e23 100644
--- a/basis/ui/backend/gtk/gtk.factor
+++ b/basis/ui/backend/gtk/gtk.factor
@@ -255,6 +255,24 @@ CONSTANT: action-key-codes
 : on-expose ( win event user-data -- ? )
     2drop window relayout t ;
 
+! TODO: think about a delayed resize event
+
+CONSTANT: resize-gadgets HS{ }
+
+: resize-callback ( -- alien )
+    [
+        drop resize-gadgets
+        [ members [ relayout-1 ] each ] [ clear-set ] bi
+        f
+    ] GSourceFunc ;
+
+: resize-later ( gadget -- )
+    resize-gadgets ?adjoin [
+        resize-gadgets cardinality 1 = [
+            10 resize-callback f g_timeout_add drop
+        ] when
+    ] when ;
+
 : on-configure ( win event user-data -- ? )
     drop swap window dup active?>> [
         swap GdkEventConfigure memory>struct
```

**Comment by jonenst** [comment]
> An even better demonstration is to grab a corner and resize several times before releasing the mouse. The window will then replay your mouse movements, drawing the zoom in and out.

I just retested with current factor on ubuntu studio 14.04 (it uses *xfce*, so I guess the same would happen on xubuntu), it does *not* trigger the bug. (with *unity* on ubuntu, it *does* triggers the bug).
Did someone figure this one out ?
