### ISSUE TITLE
Crash running "1000000 iota [ . ] each" on 32-bit Windows

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1488]
Reported on the mailing list.

``` factor
IN: scratchpad 1,000,000 iota [ . ] each
```

**Comment by mrjbq7** [comment]
Looks like an out-of-memory error on Windows.

Works on Mac OS X.

**Comment by mrjbq7** [comment]
Shows up in the console but not when running just the GUI.

**Comment by bjourne** [comment]
Don't you mean the opposite? It only happens in the GUI. I don't think it is a memory leak but a space leak because a lot of markup is created by the `.`  word. Each line consumes 1k of memory so you easily get into the gigabytes of memory usage range.

**Comment by mrjbq7** [comment]
Hah, I mean the error shows up when the UI is run with the console open (one of the factor.com maybe does this?). Most of the time Windows users don't have the console open (factor.exe?) so they would never see the out of memory error.

**Comment by bjourne** [comment]
Ok. I think to solve this problem completely you need to scroll the output of the listener and truncate it after 100k lines or so. It is probably a hard feature to implement.

**Comment by mrjbq7** [comment]
Mac OSX implements an LRU cache for the underlying CTLine objects. Maybe Windows doesn't have a similar feature for reducing memory usage?

**Comment by bjourne** [comment]
I think it's just the gui system that creates a lot of objects. It's close to oom on my Linux computer too. So if you run with 5,000,000 iota or some even higher constant it should crash for you too.

**Comment by bjourne** [comment]
The last commit adds simple scrolling. So now memory usage stays constant (700mb for me) no matter how much output there is. The downside is of course that the oldest lines just disappear from the gadgets scroll buffer.

**Comment by mrjbq7** [comment]
That's a different kind of memory leak, though - children are ‘`add-gadget`` which does bookkeeping that maybe we should do the reverse of and also maybe this silently doesn't dispose properly for any disposable gadgets?

**Comment by jonenst** [comment]
Also, it's probably better to make it configurable with a dynamic variable ?

Jon

On Fri, Oct 16, 2015 at 1:01 PM, John Benediktsson <notifications@github.com

**Comment by mrjbq7** [comment]
@bjourne also some test failures under ``ui``, probably just the change from dlist to vector (which since it pushed and popped from the back of the deque, seems a lot better as a vector!).

**Comment by bjourne** [comment]
I'm unsure about the disposing. I don't think gadgets in general needs to be disposed because they don't have any resources on them so I think just changing the children sequence should be fine. The reverse of `add-gadget` would be `unparent` but there will be 100k gadgets to remove, so unparenting them one at a time is much to slow.

**Comment by mrjbq7** [comment]
Well I don't maybe mean unparent exactly, but just removing them from children seems a little.... Fragile? What about layout considerations? Or any model/listeners that might be gadgets in the children? At least need to be ungrafted?

**Comment by jonenst** [comment]
They must be ungrafted.. Think of

10 [ "resource:extra/graphviz/gallery/" dup directory-files [ append-path
load-image image. yield ] with each ] times

Jon

On Sat, Oct 17, 2015 at 4:54 AM, John Benediktsson <notifications@github.com

**Comment by bjourne** [comment]
Yes, true. Most of the times the gadgets added to the incremental pane doesn't have an ungraft* handler so it doesn't matter. The fix in 8bb96cbfd136fa46bd9d4bc8c6f3f2d55c29f168 should ensure ungraft is called on them though. It has to be done in a very specific way to ensure that the ui isn't repainted to often and that the gadget queues does not fill up.

**Comment by mrjbq7** [comment]
Should we look into what ``unparent`` does? It looks like it calls ``remove-gadget`` which is implemented by a couple classes with some custom logic, then ``ungraft`` (via ``(unparent)`` which also calls ``forget-pref-dim``), ``unfocus-gadget`` and ``relayout``...?

**Comment by bjourne** [comment]
Yes calling `unparent`  is more correct than calling `ungraft` on the gadgets. I tried it and it works, but it is sloooow. unparent triggers some kind of relayouting of all gadgets in the container. So it takes forever.

**Comment by mrjbq7** [comment]
Maybe we can inline the logic without the relayout until at the end?  Since I think relayout is just being called on parent can be called once.

**Comment by bpollack** [comment]
Is this actually a blocker for 0.98?

**Comment by mrjbq7** [comment]
Not a blocker, let's re-assign to 0.99.

**Comment by kusumotonorio** [comment]
The following did not crash:

```Factor
Press F1 at any time for help.
Factor 0.99 x86.32 (1978, heads/master-ba81ca3fa6, Feb 14 2020 01:24:42)
[Microsoft Visual C++ 190023506] on windows

IN: scratchpad 1,000,000 <iota> [ . ] each
```
However, only prints  800005 through  999999 remain in the listener window as the result.

If this result is due to some improvement, it may be by https://github.com/factor/factor/commit/94cbe2b4796fd97d99e8ab32244f1fd3f7362721 .

**Comment by kusumotonorio** [comment]
`5,000,000 <iota> [ . ] each` was OK, too.

**Comment by mrjbq7** [comment]
I believe this does not crash any longer.

**Comment by mrjbq7** [comment]
Finished the code to ``unfocus`` and ``(unparent)``...

43477d5295b68d2f9e11b2eed5a8203f5f658e29
