### ISSUE TITLE
Load urls.secure when needed

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1493]
It's kind of annoying to have to ``"urls.secure" require`` when you have a vocab that depends on an ``https`` URL.  Better would be for the URLs vocabulary to load ``urls.secure`` if someone creates a URL that requires SSL.

**Comment by rationalrevolt** [comment]
I'd like to work on this if someone hasn't already started. I was thinking to modify the `url-addr` word in the `urls` vocabulary to ensure that `urls.secure` has been loaded after the `secure-protocol?` check. Does this sound reasonable?

**Comment by mrjbq7** [comment]
So, adding `"urls.secure" require` there? Give it a try and see if it works!

**Comment by bjourne** [comment]
Looks like this change causes the deploy images to grow in size? The `bunny` test uses the `bunny.model` vocab which uses `http.client`. I think the `require` word causes the compiler to be included in the image.

**Comment by mrjbq7** [comment]
Hmmm... I wonder how else we could do this then.

**Comment by mrjbq7** [comment]
Maybe always load the secure stuff but error on first use not when loaded if OpenSSL missing?

**Comment by bjourne** [comment]
Yeah, that's probably good.

**Comment by mrjbq7** [comment]
Okay, I reverted the patch for now.  Will have to find a better way to do it so not to grow the deploy sizes.

**Comment by erg** [comment]
I moved urls.secure into urls, which allows ``USE: io.sockets.secure`` since we are now bundling libressl on Windows.

**Comment by erg** [comment]
Fixed by fe3031bc96a83ecf742f6d537d30f362f5414c39. I hope.
