### ISSUE TITLE
FUNCTION: word has incorrect documentation

### ISSUE THREAD

**Issue by rationalrevolt** [factor/factor#1495]
The documentation for the `FUNCTION:` parsing word in the `alien.syntax` vocabulary suggests that the following usages are valid:

1. The first one below indicates that the `;` character is required to terminate the function definition. But the implementation produces an error `Expected end of input but got ;`

    FUNCTION: void glHint ( GLenum target, GLenum mode ) ;

2. The second one noted below indicates that the parenthesis and commas are optional syntax sugar, but the implementation produces an error `Expected token but got end of input` if the parenthesis are missing:

    FUNCTION: void glHint GLenum target GLenum mode ;

It seems that the only valid definition is what is noted below:

    FUNCTION: void glHint ( GLenum target, GLenum mode )

**Comment by mrjbq7** [comment]
@erg removed the semi-colon at the end since it was redundant to the end parentheses (which as you point out are (became?) required.

We are considering adding back the semi-colon for symmetry with other word definitions. 

Thoughts about that and whether parentheses should be optional?

**Comment by mrjbq7** [comment]
And optional commas apparently...?

**Comment by bjourne** [comment]
Isn't it more symmetrical without the semi-colon ending? `GENERIC:` which also only declares the word doesn't have a semi-colon at the end.

**Comment by mrjbq7** [comment]
If we don't have semi-colon, we need parens to be required.

If we bring back semi-colon, we can have the old optional/flexible behavior.

@erg do you have an opinion?

I can update docs/code either way we go.

**Comment by bpollack** [comment]
@mrjbq7 @erg I actually fixed this in 7d8d60ede313d0e1a00d69befeb208c9d9406308 without realizing it was a bug. We can close this.
