### ISSUE TITLE
Allow new roots to be specified on the command-line

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1498]
We have the ``.factor-roots`` file and the ``FACTOR_ROOTS`` environment variable, but there is a use-case that would be nice to have roots specified on the command-line, something like:

```
factor -roots="~/foo:~/baz" blah.factor
```

See, for example the discussion here:

https://github.com/kanaka/mal/pull/98#issuecomment-152253257

**Comment by mrjbq7** [comment]
There was also a question about whether we should have ``.`` (the current directory) always be a vocab-root, although I think maybe that would cause some confusion in the majority of long-term image-based use-cases.

**Comment by mrjbq7** [comment]
Maybe ``.`` can be added as a vocab-root when factor is run with a script file as an argument?  That could prevent the confusion.  I also note that lots of languages have ``.`` in the path, like python, for example.

**Comment by bjourne** [comment]
Great idea I think. The roots are set in the hook in `vocabs.loader` and that hook is stripped out when you deploy images. So adding `.` would only matter when you are using Factor in development mode.
