### ISSUE TITLE
Error running on Linux server without X11

### ISSUE THREAD

**Issue by smartmic** [factor/factor#1520]
I want to run Factor 0.97 on my server in the command line only (without GUI listener). However, it refuses to start without Gtk/X11 installed:

```
$ ./factor -run=listener
./factor: error while loading shared libraries: libgtkglext-x11-1.0.so.0: cannot open shared object file: No such file or directory
```

The host:

```
$ uname -a
Linux 2.6.32-042stab092.3 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64 GNU/Linux
```

**Comment by mrjbq7** [comment]
I reproduced this on both the 0.97 release and the nightly build.

Seems we static link to the libraries instead of loading them dynamically?

**Comment by jonenst** [comment]
It is dynamically linked, that's why it's loaded at startup and it fails.

There are some worarounds:
- You can compile factor yourself with NO_UI=1.
- you can put a dummy .so file with the correct name (you can use
LD_LIBRARY_PATH to load it from a non system path)

Also, if I remember correctly (see my comment at
https://github.com/slavapestov/factor/issues/982), the symbols of the
linked library are not even used (we dlopen the library) and we could
remove the linking (and the NO_UI option) entirely.
Le 31 déc. 2015 12:55 AM, "John Benediktsson" <notifications@github.com> a
écrit :

**Comment by mrjbq7** [comment]
Sounds like good options. It sucks to have binaries that don't work on headless servers.

**Comment by catb0t** [comment]
Why not just install `libgtkglx`? Surely the package can be installed without X?

**Comment by bjourne** [comment]
I went ahead and made the change. Please revert if you dont like. Before

    $ ldd factor                                                                                                                                                                               
    ...
    libgtkglext-x11-1.0.so.0 => /usr/lib/libgtkglext-x11-1.0.so.0 (0x00007fe1647d3000)
    libgdkglext-x11-1.0.so.0 => /usr/lib/libgdkglext-x11-1.0.so.0 (0x00007fe16456f000)
    libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007fe164300000)
    libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fe164068000)
    libXmu.so.6 => /usr/lib/x86_64-linux-gnu/libXmu.so.6 (0x00007fe163e4f000)

After: 

    $ ldd factor
    linux-vdso.so.1 =>  (0x00007ffd51cef000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f364b549000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f364b341000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f364b122000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f364ada0000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f364aa98000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f364a880000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f364a4b6000)
    /lib64/ld-linux-x86-64.so.2 (0x000055c6c2f1c000)

There was no reason to link with the gtk libs, it was completely redundant. Now the only thing NO_UI does is check if the libraries are installed, but it doesn't actually link to them.

**Comment by mrjbq7** [comment]
That sounds great!

**Comment by mrjbq7** [comment]
Is this fixed?

**Comment by bjourne** [comment]
Yep!
