### ISSUE TITLE
Factor https client does not include SNI

### ISSUE THREAD

**Issue by samueltardieu** [factor/factor#1527]
Factor does not implement SNI (server name indication), which is a mechanism to support multiple virtual hosts over SSL, each one being able to get its own certificate.

While browsers support it, Factor does not:

```
IN: scratchpad USING: http.client io.sockets.secure urls ;

IN: scratchpad URL" https://smsapi.free-mobile.fr/" http-get
Subject name verification failed
expected "smsapi.free-mobile.fr"
got      { "*.free.fr" "free.fr" "*.free.fr" }
```

(the expected answer is a 404, since the server answers but this particular URL is invalid)

**Comment by erg** [comment]
http://stackoverflow.com/questions/5113333/how-to-implement-server-name-indication-sni

**Comment by bpollack** [comment]
I've now got a patch for this that seems to work acceptably.
