### ISSUE TITLE
mac osx help crashes

### ISSUE THREAD

**Issue by matchg** [factor/factor#1533]
I have just downloaded and install the x86-64 version of Factor. When accessing the help I get the following error.

![factor-help-error](https://cloud.githubusercontent.com/assets/6779335/13310256/a9d34ca0-db41-11e5-9c93-562799a56956.png)

**Comment by mrjbq7** [comment]
Mac OS X "El Capitan" has an issue that Factor 0.97 hits.  The latest development release fixes that.

**Comment by matchg** [comment]
Thanks for the info.
