### ISSUE TITLE
string-lines and stream-lines have different behaviors

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1546]
```factor
IN: scratchpad "Hello" [ lines . ] with-string-reader ! { "Hello" }
IN: scratchpad "Hello\n" [ lines . ] with-string-reader ! { "Hello" }
IN: scratchpad "Hello" string-lines . ! { "Hello" }
IN: scratchpad "Hello\n" string-lines . ! { "Hello" "" }
```
I think both behaviors are useful:
  * stream-lines is better most of the time because that's how text files work, and it's forgiving on bad files missing the last line ending. But this means it loses information.
  * string-lines doesn't lose information but doesn't abstract the last missing line ending.

Also, it makes sense that the current "string-lines" from the "splitting" vocabulary would work like this.

But having the same naming convention is confusing.

What about renaming the current "string-lines" to "split-lines" or "split-newlines", and add "string-lines" word (maybe in io.streams.string) that works like file-lines ( ```: string-lines ( string -- seq )
    <string-reader> stream-lines ;``` ) ?

**Comment by mrjbq7** [comment]
I've thought ``split-lines`` is a better name for it than ``string-lines``.

But maybe we should "fix" ``string-lines`` to not have that last empty line? @erg?

**Comment by mrjbq7** [comment]
Python:

```python
>>> "Hello\n".splitlines()
['Hello']
```

**Comment by jonenst** [comment]
So if I push it we merge it ? :)

**Comment by erg** [comment]
Split implies that it's removing the separators, which is consistent with python's way. String-lines means that it's returning each line as a string, so it should retain the newlines.

So this would mean ``string-lines`` should keep newlines as empty strings, ``split-lines`` could remove them, and ``stream-lines`` should be like ``string-lines`` and not lose data.

**Comment by erg** [comment]
What's the patch do?

**Comment by jonenst** [comment]
There's no patch yet, I was referring to
 > What about renaming the current "string-lines" to "split-lines" or "split-newlines", and add "string-lines" word (maybe in io.streams.string) that works like file-lines ( : string-lines ( string -- seq ) <string-reader> stream-lines ; ) ?

So we change file-lines, lines, each-line, and all the things to keep the newline sequences "\r" "\n" or "\r\n" at the end of every string ?
And add all the split-line variants for these that remove the newline sequence?

I think most code that does line oriented work doesn't care about the the newline sequence and that it should be removed by default, even if that means it loses information ?

**Comment by erg** [comment]
Looks like ``lines`` just has a bug? It shouldn't be eating the last newline so that it's consistent with ``file-lines`` and ``string-lines``.

```
"Hello\n\n\n" [ lines . ] with-string-reader
{ "Hello" "" "" }```

**Comment by mrjbq7** [comment]
Maybe that's the only change we need to make?

**Comment by jonenst** [comment]
> Looks like lines just has a bug? It shouldn't be eating the last newline so that it's consistent with file-lines and string-lines.
"Hello\n\n\n" [ lines . ] with-string-reader
{ "Hello" "" "" }

No:
* it is consistent with file-lines (both use ```stream-lines```); string-lines is the one who is inconsistent with everything else.
* it should have 3 lines (1 with hello and 2 empty):
```
$ echo -e -n "hello\n\n\n" > /tmp/foo.txt
$ xxd /tmp/foo.txt 
0000000: 6865 6c6c 6f0a 0a0a                      hello...
$ wc -l /tmp/foo.txt 
3 /tmp/foo.txt

$ # also, wc is not forgiving, but factor should be (python is)
$ echo -e -n "hello\n\n\nthis line is missing it's lineending sequence" > /tmp/foo.txt
$ wc -l /tmp/foo.txt 
3 /tmp/foo.txt
```

**Comment by jonenst** [comment]
I thought you wanted to change it to the following ?
```factor
! each line with it's linebreak sequence at the end
"Hello\n\n\n" [ lines . ] with-string-reader
{ "Hello\n" "\n" "\n" }

! Or with other linebreak sequences
"Hello\r\n\r\n\r\n" [ lines . ] with-string-reader
{ "Hello\r\n" "\r\n" "\r\n" }

! mixing them
"Hello\r\r\n\n" [ lines . ] with-string-reader
{ "Hello\r" "\r\n" "\n" }

! missing last
"Hello\n\n\nWorld" [ lines . ] with-string-reader
{ "Hello\n" "\n" "\n" "World" }
```

**Comment by bjourne** [comment]
Many editors insists on adding a line break to the end of text files so it is a good thing that `stream-lines` omits the "empty" last line. It it didn't, line counting wouldn't work. So imho, `"Hello\n" string-lines .` yielding `{ "Hello" "" }` is the bug. 

You can always use `split` in rare cases when the last empty line is useful: `"hello\n" "\n" split` -> `{ "hello" "" }`.

**Comment by jonenst** [comment]
> Many editors insists on adding a line break to the end of text files

It's the only sane thing to do. It's the definition of POSIX text files. To quote a random person from the internet "Newlines are not Line Separators. They are Line Terminators." (an angry SublimeText user for not adding the last newline by default)

>  So imho, "Hello\n" string-lines . yielding { "Hello" "" } is the bug. 

I agree.

> You can always use split in rare cases when the last empty line is useful: "hello\n" "\n" split -> { "hello" "" }.

I think that it's not enough, it would be a word that correctly splits newline sequences ( ie doesn't split between "\r\n" )

**Comment by mrjbq7** [comment]
Fixed in ef2ae9c360721eab10bad9c7bee9161ed8b5255e.

**Comment by mrjbq7** [comment]
@erg I'd like to rename ``string-lines`` to ``split-lines``.  Thoughts?

**Comment by erg** [comment]
I always thought of ``lines`` itself as implying a ``split``.  ``lines,``, ``file-lines``, and ``string-lines`` are symmetric. If you just renamed ``string-lines`` that would break the symmetry.

I would expect ``lines`` -> ``split-lines``, ``string-lines`` -> ``split-string-lines``, and ``file-lines`` -> ``split-file-lines`` if you want to go with split in the name, but I don't think it's necessary.

**Comment by mrjbq7** [comment]
That's way confusing.

**Comment by erg** [comment]
So you'd have ``split-lines`` which works on strings and ``file-lines`` which works on files? And ``lines`` wouldn't even have the word ``split`` in it?

**Comment by mrjbq7** [comment]
``lines`` is shortcut for ``stream-lines``.

``file-lines`` is just ``[ lines ] with-file-reader``.

``string-lines`` is currently a faster (and duplicative) version of ``[ lines ] with-string-reader``, and restricted to ``string`` and ``sbuf`` and is in the ``splitting`` vocabulary...

I don't feel super strongly, but I like verbs and ``string-`` isn't a verb.

Note: I would not support ``split-file-lines`` or ``split-string-lines``.

**Comment by mrjbq7** [comment]
I'd be fine with not changing it right now, although ``split-lines`` seems like a nice english-y phrase.

**Comment by erg** [comment]
I think it's fine the way it is, or do the ``split-`` prefix for all to ensure there is a verb if that's the requirement. ``file-lines`` isn't a verb, ``lines`` isn't a verb, but they do imply that something is being split up.

**Comment by mrjbq7** [comment]
Okay, I guess I'll leave it now.

But I think we may want to consider renaming ``string-lines`` to ``split-lines`` later.  And leave all the others alone.

**Comment by mrjbq7** [comment]
``file-lines`` and ``set-file-lines`` are nicely symmetric....

**Comment by mrjbq7** [comment]
``file-lines`` isn't "splitting", it's retrieving a file as an array of lines....

**Comment by erg** [comment]
So it's more like this?

```factor
file-lines     ! get-file-lines vs set-file-lines
lines           ! read-lines vs write-lines, stream-read-lines stream-write-lines
string-lines ! split-lines vs join-lines
```

**Comment by jonenst** [comment]
> string-lines is currently a faster (and duplicative) version of [ lines ] with-string-reader, and restricted to string and sbuf and is in the splitting vocabulary.

The simple following benchmark seems to show that the performance is roughly the same ? if so, maybe it's better to just define string-lines as ```: string-lines ( string -- seq ) <string-reader> stream-lines ;``` ?

```factor
! the new implementation of string-lines 
GENERIC: gen-string-lines ( str -- lines )
M: string gen-string-lines
      [ V{ } clone 0 ] dip [ 2dup bounds-check? ] [
        2dup [ "\r\n" member? ] find-from swapd [
            over [ [ nip length ] keep ] unless
            [ subseq suffix! ] 2keep [ 1 + ] dip
        ] dip CHAR: \r eq? [
            2dup ?nth CHAR: \n eq? [ [ 1 + ] dip ] when
        ] when
    ] while 2drop { } like ;

! Using io.streams.string
: other-string-lines ( str -- lines ) <string-reader> stream-lines ;

1000 CHAR: A CHAR: Z [a,b] CHAR: a CHAR: z [a,b] append CHAR: \n suffix
'[ 10000 [ _ random ] "" replicate-as ] replicate
gc dup
[ [ [ gen-string-lines drop ] each ] time ]
[ [ [ other-string-lines drop ] each ] time ] bi

Running time: 0.227807665 seconds
Running time: 0.249099092 seconds
```

It's seems normal since M\ string-reader stream-readln uses the algorithm:
```factor
M: string-reader stream-readln
    dup >sequence-stream< bounds-check? [
        "\r\n" over sequence-read-until 13 eq? [
            over >sequence-stream< dupd ?nth 10 eq?
            [ 1 + pick i<< ] [ drop ] if
        ] when nip "" or
    ] [ drop f ] if ;
```factor

**Comment by jonenst** [comment]
```
! each line with it's linebreak sequence at the end
"Hello\rThe\r\nWorld\n" -> { "Hello\r" "The\r\n" "World\n" }

! missing last
"Hello\nWorld" -> { "Hello\n" "World" }
```
Is this useful enough to have words for it ?

**Comment by jonenst** [comment]
A word from the splitting vocab should split (remove separators and don't eat the last separator): "Hello\n" -> { "Hello" "" } . I think good names would be ```split-newlines``` or ```split-linebreaks```. It looks useful enough (especially when you are not dealing with text *files* where newlines are not separators (they are terminators)) to be defined in the splitting vocabulary.

**Comment by mrjbq7** [comment]
Do we have any use cases for that?

I would assume since you are working with lines that callers would want the new and current behavior more often?

**Comment by mrjbq7** [comment]
Also, I like the idea of making ``string-lines`` use ``<string-reader> stream-lines``, but then it can't be in ``splitting``, which is part of the boot image because it's in ``core``...

**Comment by erg** [comment]
I like the idea of a word that splits but keeps the separators. It could possibly even return pairs, where ``first`` is the line and ``second`` is the separators.
