### ISSUE TITLE
cum-map vs accumulate

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1547]
```factor
IN: scratchpad { 2 2 2 2 2 } 0 [ + ] accumulate . .
{ 0 2 4 6 8 }
10
IN: scratchpad { 2 2 2 2 2 } 0 [ + ] cum-map .
{ 2 4 6 8 10 }
```

I think they should be together, in the sequences vocab, with related-words docs, and maybe cum-map can be renamed to accumulate* ?

Also, we should add cum-map-as.

Also, cum-sum0 doesn't have docs (unrelated but shows that the accumulate behavior is less useful?)

I would even argue that a version that just prefixes the identity (which is often a literal) to the result is less useful than a version where the final result is at the end of the result, so accumulate should be cum-map and the current accumulate could become accumulate* ?

I can do the patch, if it's going to be merged, for some/all of these items. What do you think?

**Comment by mrjbq7** [comment]
Are you planning on moving the other ``cum-`` words?

**Comment by jonenst** [comment]
I would say no, It feels like the other ```cum-``` words belong more to math.statitics .

**Comment by mrjbq7** [comment]
So your suggestion is ``cum-map`` becomes ``accumulate*`` in the ``sequences`` vocabulary?

And leave the other words in ``math.statistics``?

Sorry, just trying to understand.

That seems okay to me.

**Comment by mrjbq7** [comment]
The other change to swap ``accumulate`` and ``accumulate*`` might be okay too, although I think we use ``accumulate`` more than ``cum-map`` right now in the source tree.

**Comment by jonenst** [comment]
yes.

Also, most other languages (scala, haskell, RXjava) call it scan:
https://en.wikipedia.org/wiki/Prefix_sum

I wanted to change the name, but Python calls it accumulate.. So I guess it's ok.

**Comment by jonenst** [comment]
I didn't swap accumulate to accumulate*, you're right about the usage.
