### ISSUE TITLE
cleanup duplicated string-lines in documents vocabulary

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1558]
As part of fixing #1546, the documents vocabulary depended on the old behavior so I made `doc-lines` a copy of the old `string-lines`.  It would be nice to clean that up, but I didn't have time to work it out.

**Comment by mrjbq7** [comment]
Cleaned up in 337d554c0950b9b6005b0d09bcb976276560d8ef.  I didn't change the documents algorithm, but now we use ``string-lines`` in it.

**Comment by bjourne** [comment]
Cool!
