### ISSUE TITLE
Rename io.files.unique:current-temporary-directory

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1564]
The ``current-temporary-directory`` is confusing, because it is used by ``unique-directory`` and really just means ``unique-directory-root``, so perhaps we can rename it to something else.

**Comment by mrjbq7** [comment]
Alternatively, we could make ``io.files.unique`` use ``io.files.temp`` and use ``with-temp-directory``.  This would probably be a lot better...

**Comment by mrjbq7** [comment]
@erg any reason why I shouldn't make it use ``io.files.temp`` instead of it's own "temp" directory?

Right now ``io.files.unique`` defaults to ``/tmp`` on mac and linux and ``"TEMP" os-env`` on windows... which is a little different than our ``io.files.temp``.

**Comment by mrjbq7** [comment]
Hmm, ``io.files.temp`` doesn't seem to allow changing the ``temp-directory``, so perhaps we should rename to a ``unique-directory-root`` symbol after all.

**Comment by mrjbq7** [comment]
(If that's a useful feature).

**Comment by erg** [comment]
``with-temp-directory`` and ``temp-file`` are no good. If you use them then your unit tests collide with each other. That's why I made the unique vocab.

- ``with-temp-directory`` (4 usages) should go away
- ``temp-file`` (225 usages) should go away
- ``io.directories`` should just provide two hooks for ``temp-directory`` and ``cache-directory`` and ``with-cache-directory`` maybe
- ``current-temporary-directory`` is what you should use instead of ``temp-directory``
- whatever other words we need to replace temp-file can be written

What if we merge ``io.files.unique`` into ``io.directories``?

**Comment by mrjbq7** [comment]
Hmm... lemme think about  that.  I'm in the middle of some cleanup to both vocabs.

**Comment by mrjbq7** [comment]
I think sometimes you want to use a temp-directory that is a constant between runs, and sometimes you want a unique-temp-directory...

**Comment by mrjbq7** [comment]
Lemme have a go at it using your feedback and see what you think when I'm done?

**Comment by mrjbq7** [comment]
Okay, so I have a patch that I'm almost ready to push for ``io.files.unique`` cleanup.

First, it removes the ``default-temporary-directory`` stuff because ``io.files.temp`` does that better.

Next, it splits the current "unique temporary file creation" into two concepts:

1. ``unique-file`` and ``unique-directory`` (in the current directory)
2. ``unique-temp-file`` and ``unique-temp-directory`` (in the temp directory)

The ``with-unique-directory`` combinator actually changes directory into the unique directory instead of setting some silly symbol and doing nothing else.

The ``cleanup-unique-directory`` combinator actually cleans up in the case of an error by using ``cleanup`` (to match it's documentation) instead of littering a unfindable directory behind.

Every use case we have actually just uses ``with-unique-temp-directory`` and ``cleanup-unique-temp-directory`` because thats what we want in the tests.

@erg thoughts?

**Comment by mrjbq7** [comment]
Alternatively, we could just keep a ``unique-root`` variable (that defaults to the temporary directory) and do it similar to the old way but with some of the other cleanups that I mentioned.

I like the way I suggest above, but I could be convinced that it's simpler this other way. @erg

**Comment by mrjbq7** [comment]
Especially since everyone uses ``unique-temp-`` right now instead of just ``unique-``, kind of implies we should always default to temp directory.

**Comment by mrjbq7** [comment]
Although my version is a bit more generalized (with the current directory feature).

**Comment by mrjbq7** [comment]
Okay, I split the difference and pushed a patch where the ``io.files.unique`` always operate on the ``current-directory``.  That makes it a lot simpler and easier to understand then having a ``unique-root`` or ``current-unique-directory`` symbol to keep track of.
