### ISSUE TITLE
Split inputs and outputs in word help

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1572]
This is a good suggestion by @nicolas-p:

https://github.com/nicolas-p/skov/issues/1#issuecomment-198567107

**Comment by mrjbq7** [comment]
It probably requires different help syntax, or possibly can get it by setting the ``current-topic`` when you call ``print-topic`` and then using the stack effect of the current topic (if it's a word) to split the ``$values`` into separate groups for inputs and outputs.

**Comment by nicolas-p** [comment]
I will post the images here as well.

The current display:

![capture d ecran 2016-03-18 a 23 19 12](https://cloud.githubusercontent.com/assets/11431580/13900354/b56fffec-ee04-11e5-99e1-94543c05b783.png)

My proposition:

![inputs-outputs](https://cloud.githubusercontent.com/assets/11431580/13900351/9998727c-ee04-11e5-9aaf-6bddbd25c82c.png)

**Comment by mrjbq7** [comment]
This is one way to do it, by mutating the help content when it is set on a word:

```diff
diff --git a/basis/help/help.factor b/basis/help/help.factor
index 2139890..453457f 100644
--- a/basis/help/help.factor
+++ b/basis/help/help.factor
@@ -179,7 +179,21 @@ help-hook [ [ print-topic ] ] initialize
 : remove-word-help ( word -- )
     f "help" set-word-prop ;
 
+: inputs-and-outputs ( content word -- content word )
+    over [ ?first \ $values = ] find drop [
+        [ cut unclip rest ] curry dip
+        [
+            stack-effect [ in>> ] [ out>> ] bi
+            [ [ dup pair? [ first ] when effect>string ] map ] bi@
+            [ [ [ ?first ] dip member? ] curry filter ] bi-curry@
+            \ $inputs \ $outputs
+            [ [ prefix ] curry compose ] bi-curry@ bi* bi
+            2array glue
+        ] keep
+    ] when* ;
+
 : set-word-help ( content word -- )
+    inputs-and-outputs
     [ remove-word-help ] keep
     [ swap "help" set-word-prop ] keep
     xref-article ;

diff --git a/basis/help/markup/markup.factor b/basis/help/markup/markup.factor
index 1b3324b..27add1c 100644
--- a/basis/help/markup/markup.factor
+++ b/basis/help/markup/markup.factor
@@ -396,6 +396,12 @@ M: f ($instance) ($link) ;
     unclip \ $snippet swap present 2array
     swap dup first word? [ \ $instance prefix ] when 2array ;
 
+: $inputs ( element -- )
+    "Inputs" $heading [ values-row ] map $table ;
+
+: $outputs ( element -- )
+    "Outputs" $heading [ values-row ] map $table ;
+
 : $values ( element -- )
     "Inputs and outputs" $heading
     [ values-row ] map $table ;
```

**Comment by mrjbq7** [comment]
Note: if we do it this way, we need to update ``help.lint.checks`` to have an inputs and outputs check (right now it just checks values).

**Comment by mrjbq7** [comment]
Also @nicolas-p the tables won't line up because they aren't the same table they don't get the same column width calculations... that's maybe a little visually annoying.

**Comment by nicolas-p** [comment]
Actually it may be better if they don't line up. The above mock-up looks strange to me now.

Please don't post your `inputs-and-outputs` function to the _"Show me some code!"_ section on the Factor website. Nobody would download Factor ever again.

**Comment by mrjbq7** [comment]
Haha! Yes, I just wrote it in the listener step by step without regard for code quality, hah. 

Could use some cleanup for sure.  :-)

**Comment by mrjbq7** [comment]
Also, it still prints an ``Outputs`` heading when there are no outputs... another case where I'm not sure that's good or not visually.

**Comment by nicolas-p** [comment]
We could do this:

![none](https://cloud.githubusercontent.com/assets/11431580/13905988/55d1eb48-eece-11e5-8bcd-e922330d2ccb.png)

**Comment by mrjbq7** [comment]
Sure, something like:

```factor
: $inputs ( element -- )
    "Inputs" $heading [ values-row ] map 
    [ [ "none" print ] ($block) ] [ $table ] if-empty ;

: $outputs ( element -- )
    "Outputs" $heading [ values-row ] map
    [ [ "none" print ] ($block) ] [ $table ] if-empty ;
```

**Comment by bjourne** [comment]
What about the case when you have the same values as inputs and outputs? See f.e the `bounds-check` word in sequences. Like, the custom that if you have a word `: foo ( a b -- a b )`, then a and b are passed through unchanged. But if you write `: foo ( a b -- a' b' )` then a' and b' are new objects.

**Comment by mrjbq7** [comment]
Yep, in that case they'd be duplicated in both tables.

**Comment by nicolas-p** [comment]
I did it in a slightly different way.

I keep your two new words in _help.markup_:
```factor
: $inputs ( element -- )
    "Inputs" $heading
    [ [ "none" print ] ($block) ]
    [ [ values-row ] map $table ] if-empty ;

: $outputs ( element -- )
    "Outputs" $heading
    [ [ "none" print ] ($block) ]
    [ [ values-row ] map $table ] if-empty ;
```

But in _help_ I just change this word:
```factor
M: word word-help*
    stack-effect [ in>> ] [ out>> ] bi [
        [
            dup pair? [
                first2 dup effect? [ \ $quotation swap 2array ] when
            ] [
                object
            ] if [ effect>string ] dip
        ] { } map>assoc
    ] bi@ [ \ $inputs prefix ] dip \ $outputs prefix 2array ;
```

It works fine for new words created after this change, but the help page of all the other words in the system isn't updated. What is the best way to update the "help" property of every word without losing the word description?

I did this:
```factor
[ [ [ "help" word-prop [ \ $description swap member? ] filter ]
    [ word-help* swap append ]
    [ swap "help" set-word-prop ] tri
  ] try
] each
```
but is there a better way?

**Comment by mrjbq7** [comment]
Well, the problem is that most ``-docs.factor`` files use ``$values{ }`` to describe their inputs and outputs.  The ``M\ word word-help*`` is used to describe words that don't have help docs for them.

My hacky hack was trying to allow people to keep using ``$values`` but "fix it up" in the code by introspection and removing the ``$values`` and replacing with ``$inputs`` and ``$outputs``.  One of the reasons ``$values`` has been convenient is that the person writing the docs doesn't have to duplicate description of objects that are both an input and an output.

**Comment by mrjbq7** [comment]
Maybe you could do something like this at runtime to "update" words, but then it would revert next time you bootstrapped or refreshed the ``-docs.factor`` files with any changes:

```factor
all-words [
    dup "help" word-prop [
        dup [ first \ $values = ] find drop [
            cut rest pick word-help* glue "help" set-word-prop
        ] [ nip ] if*
    ] [ drop ] if*
] each
```

**Comment by AlexIljin** [comment]
I like the idea of separating inputs from outputs in the help. Although, it is one of those thing that get increasingly difficult to retrofix as codebase grows.

If you want to convert the help files from $values to { $inputs $outputs }, I could volunteer some gruntwork (much like I did with switching VM to `//`-style comments).

**Comment by catb0t** [comment]
any new ideas about this? there are good suggestions in this thread but it was forgotten.

**Comment by mrjbq7** [comment]
I pushed this change in eded28cc74cae9ff956523e697dfb6c1f0c56106, I'm not sure why I didn't push through the last time.

Anyway, for now let's keep writing docs the way we have been with ``$values``.

This will let us get a feel for the new separate inputs and outputs docs.
