### ISSUE TITLE
Get rid of definition-icons

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1577]
Because of a change to `string-lines`, it caused the definition icons not to be displayed until I made a fix in c04ce00b45c134f2deefd10fd439b566a532fffb.  Turns out it looks a lot nicer without all the icons.  I think it's a combination of not having proper retina icons and that the icons look really busy on screen. 

So suggestions:
1. Get rid of definition icons
2. Change definition icons to be less colorful
3. Make definition icons retina

I'm leaning towards the first one... thoughts?

**Comment by bpollack** [comment]
I was planning to make them retina, but don't have an ETA; I went from having too much time for Factor to not enough in the last week. (I want to fix up the scroll bars at the same time, too.)

**Comment by nicolas-p** [comment]
I have disabled the icons with:
```factor
IN: help.markup
: $image ( element -- ) drop ;
```

It took me some time to decide if I liked it better with or without the icons. In the end I think we should keep them, but they can certainly be improved. There must be free icon packages that we can use.

**Comment by mrjbq7** [comment]
Upgraded definitions icons to "retina" (which just means 32x32 instead of 16x16).
