### ISSUE TITLE
Better help file-names

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1578]
We escape the HTML file names that are generated here:

https://github.com/factor/factor/blob/master/basis/help/html/html.factor#L15

It makes for some wonky looking files:

http://docs.factorcode.org/content/word-__hash____hash__compare-float-unordered%2Ccompiler.cfg.instructions.html

Maybe we should just `url-encode` them...?

**Comment by mrjbq7** [comment]
Note: you can't just ``url-encode``, because you also have to at least have to escape ``/`` and ``\``...

**Comment by mrjbq7** [comment]
This should help cut down on size of files like #1428.

**Comment by bjourne** [comment]
Sounds good. It looks like the `url-encode-full` word can be used to encode all special characters including `/`.

**Comment by mrjbq7** [comment]
I guess one drawback is search engine indexing if we change the file names...

**Comment by mrjbq7** [comment]
With gzip encoding turned on, on the server, the actual transfer is much smaller than the file size for most users.

I'd rather not change file sizes, since search engines indexed current ones.
