### ISSUE TITLE
db.errors sub-vocabs?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1581]
I noticed we have ``db.errors.postgresql`` and ``db.errors.sqlite``.  I think it would be cleaner to keep those under ``db.postgresql`` and ``db.sqlite``.  I was going to change it then remembered @erg has done some work on ``db`` cleanup so didn't want to trample that.

**Comment by erg** [comment]
You can change it. I ported those vocabs to different names and api in a branch, so changes wont matter.

**Comment by mrjbq7** [comment]
Fixed in 6ec952c4367b41eed8dcfbbd16ccddaa0b1bff29.
