### ISSUE TITLE
Rename sequences:start

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1591]
@erg and I were chatting about the (poorly named?) `start` and `start*` word.

Suggestion is `subseq-index` and `subseq-index-from`.

Is that good?  Any better names?

**Comment by mrjbq7** [comment]
How about ``subseq-start``?

**Comment by nicolas-p** [comment]
`subseq-index` and `subseq-start` are both good. I also like `-from` instead of `*`.

**Comment by erg** [comment]
Going with ``subseq-start`` and ``subseq-start-from``. Seems good enough for starters!

**Comment by mrjbq7** [comment]
Alias the old word names for 0.98?

**Comment by erg** [comment]
Why? Rather not have any backward compatibility code until the new parser...?

**Comment by mrjbq7** [comment]
Because a fair amount of people use 0.97 according to questions on the mailing list and issue reports and seems like we should minimize breaking when possible. 

I mean I also like moving forward but... that's why I also want triple quote strings back for 0.98.

**Comment by erg** [comment]
Ok. I can add an alias for ``start`` and ``start*``. I hate triple-quote strings...but add them back if you want! 👎 

The new parser will have a compatibility option that can port your old code to more recent Factor versions through word renames, vocab renames, etc.

**Comment by erg** [comment]
I also renamed the ``start`` and ``finish`` words in the compiler vocab because they are way too vague (even in the same file) and so people don't keep using the wrong ``start`` somehow.

**Comment by erg** [comment]
Fixed in c5b563ed093840e4d18880e3ce5764334732fc51 and 88bff3a034b259e24ee1105c90dc7c78fda010bf.

**Comment by erg** [comment]
(Oops I forgot to include the github issue in the patch...)

**Comment by mrjbq7** [comment]
Well if we don't care as much about backwards compatibility or migration maybe we revert the second patch... thoughts?

**Comment by jonenst** [comment]
See https://github.com/factor/factor/issues/358#issuecomment-305749955
maybe I should have gone with goberserk :goberserk: !

Anyway my opinion is good changes should go in :trophy: :+1: :sparkler:
