### ISSUE TITLE
Setting end-op/beginning-op for the symbol `symbol` breaks other modes  

### ISSUE THREAD

**Issue by iqbalansari** [factor/factor#1592]
Hi,

`factor-mode.el` [sets](https://github.com/factor/factor/blob/120c9d646ee095c0b06b0cd2d2d8f791ad4c24f4/misc/fuel/factor-mode.el#L175-L176) the `end-op` and `beginning-op` for the symbol property, this breaks `thing-at-point` function for other modes.

To reproduce -

1) Open a buffer in Emacs Lisp mode
2) Type `(test)`
3) With point at `test`, do <kbd>M</kbd><kbd>:</kbd>`(thing-at-point 'symbol)`<kbd>RET</kbd>, the result should be `test`
4) Now load `factor-mode` and repeat steps 1, 2 and 3. The result is `(test)` which is incorrect.

This breaks atleast one package that I use [elisp-slime-nav](https://github.com/purcell/elisp-slime-nav) but I am sure a lot of other packages might break because of this.

Thanks

**Comment by bjourne** [comment]
Hmm I see your point. Guess I thought end-op and beginning-op would be local to the mode.

**Comment by iqbalansari** [comment]
I thought the same when I came across that code, however it seems there is not way to set the property locally for a buffer. The previous approach of using a custom symbol (`factor-symbol`) seemed fine any particular reason that was changed?
