### ISSUE TITLE
More meaningful / helpful tracebacks / errors?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1594]
It would be really nice if, when code being run in the Listener throws an exception of some sort, the line number or code snippet / context (or both) could be included somewhere -- it would be really helpful to debugging.

For instance, if I ask Python to raise an exception, I get:

```python
Traceback (most recent call last):
  File "./SimpleForth.py", line 103, in <module>
    main()
  File "./SimpleForth.py", line 19, in main
    interpret(argv)
  File "./SimpleForth.py", line 44, in interpret
    f = pmlr.readkey()
  File "/home/cat/projects/git/simpleforth/pmlr/pmlr/__init__.py", line 46, in isdefined
    return func(*args, **kwargs)
  File "/home/cat/projects/git/simpleforth/pmlr/pmlr/__init__.py", line 286, in readkey
    if ch == CHAR.INT: raise KeyboardInterrupt
KeyboardInterrupt
```

Line numbers, file names, function/method names, and code context (well, some). I know Python is a *scripting* language and Factor is "compiled", but Python is also compiled to bytecode.

In Factor, if I invoke (the equivalent of) a TypeError by calling a method on a type it doesn't define a word for, after clicking a few things I can get:

![screenshot from 2016-03-27 13-00-30](https://cloud.githubusercontent.com/assets/3238748/14066591/edb4e18e-f41b-11e5-93f1-22b977da0c9f.png)

Which is useful if I'm a Factor developer and there's a bug with Factor itself that's exposed by my code. However, it's not very meaningful to me as a user of the platform.

Which line, of which file? What does the line that threw the error look like? Which word or vocabulary, even?

I understand it may be hard to provide this information for fully compiled / deployed apps because of Factor's execution model, but the Listener can fully inspect everything that goes on, and its introspection seems almost magical at some times. 

Would it be possible to make the Listener know about debugging information?

As an additional request, could there be a `deploy-tool` option to compile with debugging symbols / information (i.e include the source in the compiled output so tracebacks can be debugged in full)?

**Comment by catb0t** [comment]
Oh, I haven't used the deploy tool in a while.

![asd](https://raw.githubusercontent.com/mrjbq7/re-factor/master/docs/cat.png)

It *does* have options to include lots of debugging info (!) but again, the listener doesn't seem to be equipped to expose it.

**Comment by mrjbq7** [comment]
What do you mean "[not] equipped to expose it"?

**Comment by catb0t** [comment]
@mrjbq7 Line numbers and code context, which word / vocab threw, etc -- proper, helpful tracebacks that are relevant to me, and that don't just show the underlying code that's meaningless to me (especially when it's just anonymous, like the "Call Stack" section in the screenshot in the original post).

If the information is there for the Listener to find (in source form or in a deployed binary), then it just doesn't display it anywhere.

The "Data Stack" viewer is useful, but not as meaningful as seeing exactly what code caused the error.

**Comment by bjourne** [comment]
Maybe we should start a FAQ since this is asked about quite often? I think it was discussed o the mailing list a while ago. @catb0t, the info about file names and line numbers aren't exposed because the data isn't there in the first place. Due to how Factor compiles and executes code it would be very hard to decorate stack traces with it. Not impossible mind you, just lots of work!

**Comment by erg** [comment]
I would like to fix this in the new parser. It doesn't warrant a separate issue though since it's one of the main goals.
