### ISSUE TITLE
world active? could be t/f

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1599]
It looks like the ``active?`` slot on ``world`` is only ever ``0`` or ``100``, it might have been other things in the past, but maybe we should change to a boolean?

@bjourne

**Comment by bjourne** [comment]
Yeah. I changed it to make UI starts faster but it didn't work out well so it should be changed back.

**Comment by mrjbq7** [comment]
No worries!  Fixed in 1b71efb74802562dc6a226417b2761bd191d7a11.
