### ISSUE TITLE
Restarting the Listener UI doesn't stop currently running code

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1600]
To print the date & time each second forever:
```
[ t ] [ 1 seconds sleep now "%c" strftime print ] while
```

Running this in the Listener UI, it will run forever until the UI process is forcibly killed. The UI doesn't stop responding, though, so "Restart Listener" can still be clicked... and when it is, the loop is still running, printing the time every second, in a "fresh" session. 

I was under the impression the purpose of the "Restart Listener" button was just to kill running code / reset the state of the world, which is apparently not what happens.

1. Is the Restart Listener button supposed to kill the currently running code? 
2. If not, can there be a "Break" button in the top bar which sends SIGINT or something to the currently running code? This won't be of much use when the UI is completely frozen as in https://github.com/factor/factor/issues/1573, but it's a start.

**Comment by catb0t** [comment]
Some screenshots of what I mean.

Running the code:

![screenshot from 2016-03-30 10-35-55](https://cloud.githubusercontent.com/assets/3238748/14145855/66c340e0-f663-11e5-8bd3-a7279d660a42.png)

After clicking "Restart Listener":

![screenshot from 2016-03-30 10-36-00](https://cloud.githubusercontent.com/assets/3238748/14145866/7517e484-f663-11e5-8052-ceef38643085.png)

**Comment by erg** [comment]
If you want to stop the output, then open another listener and close the original listener window. shift-alt-L

Of course, closing the listener window doesn't make the thread stop running. Don't write infinite loops? :)

**Comment by erg** [comment]
Closing for now. If we get interruptible threads then this will get fixed with that.
