### ISSUE TITLE
UI error infinite loop

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1601]
When starting the UI listener, my desktop environment would slow down, a window would show and disappear instantly  in an infinite loop.

reverting 7d0c596c923e8b6e9baa1db77000ee8e87deada1 fixed it. A single error window was opened and gave the error message.

(In my case, the underlying error gave a working workaround:
```
Required OpenGL version 1.0 not supported ((null) available)
If you have several libGL.so installed, Factor tried the first one in: ldconfig -p | grep libGL.so$
You can change the library used like so: LD_LIBRARY_PATH=/usr/lib/fglrx/ ./factor
```
)

**Comment by jonenst** [comment]
Running vanilla ubuntu 14.04

**Comment by mrjbq7** [comment]
Hmmm I wonder which part broke it.

Previously we would ``die`` which has stack effect ``( -- )`` so the various ``error-hook`` when you ``c`` to continue would throw a quotation effect error because ``( error -- )`` is not the same as ``( error -- * )`` which they expect.

But maybe throwing the original error is problematic somewhere?

**Comment by jonenst** [comment]
can you reproduce or do you want me to give more info ?

**Comment by mrjbq7** [comment]
How do I reproduce? Vanilla install without ``libGL.so``?

**Comment by jonenst** [comment]
Anything that throws an error in the UI thread I guess. Like make a gadget
that throws in it's graft*. Haven't tested though, i will confirm in 30
minutes
Le 30 mars 2016 18:15, "John Benediktsson" <notifications@github.com> a
écrit :

**Comment by mrjbq7** [comment]
Ok thanks, sorry for breaking it.

**Comment by erg** [comment]
I saw this last night, but then I bootstrapped again and it worked. Not sure what to make of it. Bug or not?

**Comment by erg** [comment]
I think this is fixed, but if there's still an issue please reopen! :dango: :dango: :dango:
