### ISSUE TITLE
Errors description "a XXX tuple"

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1602]
ERROR: invalid-proxy proxy ;
f invalid-proxy ! shows a message "a invalid-proxy tuple"

It was better before, when it said only "invalid-proxy"

Also, now that it's english, it's upsetting that it doesn't get the right a/an : "an invalid-proxy tuple"

**Comment by mrjbq7** [comment]
Well I fixed the English in e881f3d5a62ae7ed4aea627b22d3e01932bbab49.

Regarding ``"a foo tuple"``, I don't have a strong opinion, although I lean towards your suggestion.

**Comment by mrjbq7** [comment]
Decided that you're right (sorry @bjourne!) because ``hashtable with 1 entries`` isn't ``a hashtable with ` entries``.  One of them had to change and the error summary was a good argument.

cf0f748991319a9896336cc2dec24431bddac118
