### ISSUE TITLE
UI: Don't use 100% of a core

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1604]
I opened the Factor UI Listener yesterday after `./build.sh update`-ing to find the UI (but not the shell invoked with `-run=listener`) was using `102%` of CPU, so I completely removed all traces of Factor from my system and started over. 

The problem persists after a fresh bootstrap from scratch: Opening the UI uses up a core for no apparent reason (it's not frozen), but running `./factor -run=listener` does not. `top` showing this:

![factor](https://cloud.githubusercontent.com/assets/3238748/14188254/3cac83f0-f755-11e5-9d21-4eea88494790.png)

It will stay like that that until my laptop overheats and switches itself off (which it just did an hour ago).

However, if I hit CTRL-C then CTRL-D in the shell, I get this printed:
```
$ ./factor -run=listener
Factor 0.98 x86.64 (1760, heads/master-96ad040ed7, Thu Mar 31 12:54:53 2016)
[Clang (GCC 4.2.1 Compatible Ubuntu Clang 3.6.2 (tags/RELEASE_362/final))] on linux
IN: scratchpad ^CInterrupted
Starting low level debugger...
Basic commands:
  q ^D             -- quit Factor
  c                -- continue executing Factor - NOT SAFE
  t                -- throw exception in Factor - NOT SAFE
  .s .r .c         -- print data, retain, call stacks
  help             -- full help, including advanced commands

> ==== DATA STACK:
T{ io.backend.unix.multiplexers.epoll:epoll-mx f f 11 T{ hashtables:hashtable 6 0 { 16 T{ vectors:vector { T{ threads:thread "Linux monitor thread" T{ kernel:curry T{ io.ports:input-port f f T{ io.backend.unix:fd f f 16 } f T{ io.buffers:buffer 65536 #<alien 0x1bcacb0> 0 0 f } } [ io.monitors.linux:inotify-read-thread ] } [ ] 29 T{ boxes:box #<alien 0x1bee9c0> syntax:t } "I/O" syntax:t f T{ hashtables:hashtable 0 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } f } } 1 } 17 T{ vectors:vector { T{ threads:thread "Linux monitor thread" T{ kernel:curry T{ io.ports:input-port f f T{ io.backend.unix:fd f f 17 } f T{ io.buffers:buffer 65536 #<alien 0x1bdadc0> 0 0 f } } [ io.monitors.linux:inotify-read-thread ] } [ ] 31 T{ boxes:box #<alien 0x1beebc0> syntax:t } "I/O" syntax:t f T{ hashtables:hashtable 0 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } f } } 1 } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } 3 T{ vectors:vector { T{ threads:thread "Signals" T{ kernel:curry T{ io.ports:input-port f f T{ io.backend.unix:fd f f 3 } f T{ io.buffers:buffer 65536 #<alien 0x1b757d0> 0 0 f } } [ io.backend.unix:signal-pipe-loop ] } [ ] 19 T{ boxes:box #<alien 0x1ba9f80> syntax:t } "I/O" syntax:t f T{ hashtables:hashtable 0 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } f } } 1 } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f }... } } T{ hashtables:hashtable 0 0 { T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } T{ hashtables.private:tombstone f } } } T{ specialized-arrays.instances.unix.linux.epoll.epoll-event:epoll-event-array B{ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0... } 256 } }
-1
==== RETAIN STACK:
T{ kernel:compose [ threads:sleep-time io.backend:io-multiplex threads:yield ] [ io.thread:io-thread-running? namespaces:get-global ] }
[ io.thread:io-thread-running? namespaces:get-global ]
==== CALL STACK:

frame: 0x7ffb113abe38 size 192
executing: kernel.private:signal-handler
scan: 1
word/quot addr: 7ffb1f749b4c
word/quot xt: 7ffb1b667d80
return address: 7ffb1b667dbb

frame: 0x7ffb113abef8 size 48
executing: io.backend.unix.multiplexers.epoll:wait-event
scan: -1
word/quot addr: 7ffb2160d33c
word/quot xt: 7ffb1b49d9f0
return address: 7ffb1b49db51

frame: 0x7ffb113abf28 size 16
executing: epoll-mx=>wait-for-events
scan: -1
word/quot addr: 7ffb20eed49c
word/quot xt: 7ffb1b639210
return address: 7ffb1b639279

frame: 0x7ffb113abf38 size 32
executing: [ threads:sleep-time io.backend:io-multiplex threads:yield ]
scan: 1
word/quot addr: 7ffb21d0f564
word/quot xt: 7ffb1b9b7a90
return address: 7ffb1b9b7aa4

frame: 0x7ffb113abf58 size 32
executing: compose=>call
scan: 2
word/quot addr: 7ffb1f8c6f6c
word/quot xt: 7ffb1b1f3ea0
return address: 7ffb1b1f3ec2

frame: 0x7ffb113abf78 size 32
executing: kernel:keep
scan: 2
word/quot addr: 7ffb1f8d18ec
word/quot xt: 7ffb1b219360
return address: 7ffb1b219388

frame: 0x7ffb113abf98 size 32
executing: kernel:loop
scan: 1
word/quot addr: 7ffb1f8c886c
word/quot xt: 7ffb1b1e86b0
return address: 7ffb1b1e86d0

frame: 0x7ffb113abfb8 size 32
executing: [ namespaces:set-namestack continuations.private:init-catchstack threads:self accessors:quot>> kernel:call threads:stop ]
scan: 4
word/quot addr: 7ffb204d4484
word/quot xt: 7ffb1b9b7740
return address: 7ffb1b9b7763
```

Other programs don't do this, and Factor's never done this before yesterday.

**Comment by mrjbq7** [comment]
Can you update to latest master and try again?

This on Linux with GTK backend?

**Comment by mrjbq7** [comment]
If it is still busted, could you try reverting either (or both) of these commits:

https://github.com/factor/factor/commit/2929cc21f5d1b17e71014f0c32f3fb2f33f744b6

https://github.com/factor/factor/commit/7d5df2c8a28b37cb5a4f8dfbbb40698ed6507793

We did not notice this locally on our Ubuntu 15.10 or 16.04, and I am hoping this will be resolved by clean ``buikd.sh update``, but if not let's see if reverting will help.

**Comment by catb0t** [comment]
This is Ubuntu 15.10 with GTK, yes. Updating to latest didn't solve it.

I'll be back with the results of reverting those in a few, but here's what happens after CTRL-C + CTRL-D'ing the UI, if it matters:

```
$ ./factor
^CInterrupted
Starting low level debugger...
Basic commands:
  q ^D             -- quit Factor
  c                -- continue executing Factor - NOT SAFE
  t                -- throw exception in Factor - NOT SAFE
  .s .r .c         -- print data, retain, call stacks
  help             -- full help, including advanced commands

> ==== DATA STACK:
==== RETAIN STACK:
==== CALL STACK:

frame: 0x7f49d1249f08 size 192
executing: kernel.private:leaf-signal-handler
scan: 1
word/quot addr: 7f49df44661c
word/quot xt: 7f49db3905d0
return address: 7f49db39060b

frame: 0x7f49d1249fc8 size 16
executing: ( callback )
scan: -1
word/quot addr: 7f49e2277d3c
word/quot xt: 7f49dbe00250
return address: 7f49dbe00250
```

**Comment by mrjbq7** [comment]
@erg do you see the same thing?

I will try and look at it in a few hours. 

Thanks for the bug report.

**Comment by mrjbq7** [comment]
I think the problem is my yield callback in ``g_idle_add``... but you can't just revert that one patch because then the UI doesn't load properly.  I'll try and fix tonight.  Sorry about that.

**Comment by mrjbq7** [comment]
I reverted both patches so it works (as well as before), although #1487 is unfixed. :-)

**Comment by catb0t** [comment]
Well, that's fixed it, it's normal again. I'll `git checkout` and `make` both of the above commits and try to discern which broke it.

**Comment by catb0t** [comment]
I can't reproduce this anymore by `git checkout <hash>; make clean; make` -- I'm not very skilled at git, what'm I supposed to be doing?

**Comment by mrjbq7** [comment]
Don't worry about reproducing which commit, I think my yield callback in "idle" was being run continuously.  I may have misunderstood the GTK main loop documentation. Will probably switch to a g_main_iteration followed by a single yield simple loop. Haven't gotten that done yet but soon.

**Comment by catb0t** [comment]
So, this is fixed but #1487 was unfixed... although, I've never been able to #1487, for whatever reason.

**Comment by mrjbq7** [comment]
To reproduce #1487, just grab the corner and resize a bunch of times and then stop and watch the delayed repainting. It's not because Factor is slow, it's because we aren't quite properly integrated with the GTK main loop and since most people don't resize often it's not noticed.

**Comment by mrjbq7** [comment]
Also, on fast computers the "delay" is like 500ms and not as visible as like in a VM or on certain configurations where it can be seconds.
