### ISSUE TITLE
Make all quotations support fry?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1606]
Instead of having `USE: fry`, maybe we should modify the quotation parser to be able to fry if you use `_` and/or `@` in them?

Downside is that you might not be able to tell that something was "fried" because the syntax looks the same as a normal quotation.  Upside is less syntax (freeing up `'` for character literals)?

``` factor
'[ swap _ push-at ] each
```

vs.

``` factor
[ swap _ push-at ] each
```

**Comment by erg** [comment]
Code inspection and walker would look like a mess with all the fry/locals expansions.

**Comment by bpollack** [comment]
Can we not, actually? Factor syntax is already so dense; I actually value seeing `'[` and knowing I'm about to see a fried quotation, because I mentally immediately fold the last stack element into the quotation. If you remove that, I won't realize until partway through the quote that the last element was curried.

**Comment by mrjbq7** [comment]
@bpollack I don't disagree, but I hate when they don't line up, so maybe if we swap ``'[`` and ``['`` I'd be more likely to not care :-)

```
'[ do-something _ etc ]
[ do-another-thing ] bi
```

vs

```
[' do-something _ etc ]
[ do-another-thing ] bi
```

(or similar right side vs left side syntax)

**Comment by bpollack** [comment]
@mrjbq7 Okay, that looks awesome. I hear you on the alignment thing, but I am a lot happier keeping the tick mark.

**Comment by jonenst** [comment]
"['" would also "free" ' for character literals. I agree with bpollack here.

Also, I like the "everything is a parsing word" approach, I would proceed
with caution on this kind of change. For exemple the move of comments to
the parser has the universal comments benefits, but i wonder if it could
have been done differently (nested parsing words ?).
Le 1 avr. 2016 8:00 PM, "John Benediktsson" <notifications@github.com> a
écrit :

**Comment by mrjbq7** [comment]
If it's possible to do it all with nested parsing words, I'm all for it.

The new lexer design is even more in the direction of "smart lexing" with certain implied name restrictions (not being able to have a word called ``foo{`` because thats a typed container "lexing word").  We haven't quite settled on where that goes because we want 0.98 to be a great current release before we experiment with simplifying and changing the lexing/parsing rules.

Neither @erg or I want to lose the simplicity of how parsing words work, the new lexer ideas started from being able to "lex" or "parse" a define statement like ``: foo ( a b -- c ) + ;`` without having side effects (like ``create-word-in`` and ``define-declared``).  That led to a discussion around some kind of AST-like thing.  Which lead to ideas around simplifying all places where we parse containers by making a kind of "lexing syntax" word of some kind.  All ideas at this stage and input is very welcome as we get to a point where we can ``USE: new-lexer`` and see a few examples of how it might work and look like.

**Comment by erg** [comment]
Having fry on all quotations doesn't work because of nested fry:

``[ _ _ [ _ ] ]``

``'[ _ _ [ _ ] ] vs '[ _ _ '[ _ ] ]``

**Comment by erg** [comment]
This would break nested fry, so closing it!

**Comment by AlexIljin** [comment]
But what about the `[' ... ]` idea? I kinda liked it...
It's in line with the `( n -- n' )` notation, where the apostrophe designates a modified version of something, and the apostrophe must be placed after the thing (`n'`, not `'n`).

**Comment by erg** [comment]
It could work.

```
SYNTAX: ':
    (:) [ fry [ call ] compose ] [ apply-inlined-effects ] bi*
    define-declared ;

': foo ( a b -- c ) _ _ + ;

10 20 foo .
30
```

This could easily be ``:'`` instead.

What if we had smart-combinator syntax, where would the ``'`` go?

```factor
[ 1 2 3 ] sum-outputs .
6

+[ 1 2 3 ] .
6

+[ 1 2 3 +] .
6

1 2 3 '+[ _ _ _ ]
1 2 3 +'[ _ _ _ ]
1 2 3 +[' _ _ _ ]
```

**Comment by AlexIljin** [comment]
For the smart-combinators I would vote for the third option: `1 2 3 +[' _ _ _ ]`

Maybe even `[' _ _ _ ']` for symmetry, (`1 2 3 +[' _ _ _ ']`), but that's perhaps a bit too far.

**Comment by erg** [comment]
Here's some more speculative syntax. I think the single quote looks good in front. (Assume that you read as many objects as you have colons, and that fry works in arrays)

```factor
1 2 3 4 tag:: '{ _ _ } '{ _ _ }
tag{ { 3 4 } { 1 2 } }

1 2 3 4 'tag:: { _ _ } { _ _ }
tag{ { 1 2 } { 3 4 } }


1 2 3 4 tag:: {' _ _ } {' _ _ }
tag{ { 3 4 } { 1 2 } }

1 2 3 4 tag::' { _ _ } { _ _ }
tag{ { 1 2 } { 3 4 } }
```

**Comment by catb0t** [comment]
what is `+[`? does it apply `+` across the elements of the quotation or something? it seems un-needed when you can just write `sum`

**Comment by erg** [comment]
@catb0t You're right, it's completely unnecessary but it might be cool to define some kind of transform for ``tag[ ]`` forms since they make sense as a notation and don't currently do anything. Like if they reduce ``( a b -- c )`` then you can make a smart combinator out of it.

The difference between a smart combinator and sum is that the smart combinator knows at compile-time how many additions to make, while sum accumulates the array sum at runtime. Smart combinators are like varargs that are known at compile-time.
