### ISSUE TITLE
UI Listener should raise its expectations for syntax errors concerning double quotes

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1608]
```factor
IN: scratchpad "some string
```

->

![doublequoteerr](https://cloud.githubusercontent.com/assets/3238748/14227618/be169aa4-f8cf-11e5-91f3-378668ce4294.png)

`Expected`? Expected what? Likely, it should say `Expected "`, which means the `"` isn't being escaped properly, which is a Bad Thing, no?

**Comment by mrjbq7** [comment]
I think it's a missing quote after vim instead of a double quote? That's a bad error message though. Let's fix it!

**Comment by catb0t** [comment]
@mrjbq7 the initial screenshot apparently wasn't very demonstrative, so I changed it. Yeah, my point is that for whatever reason double quotes thrown from syntax errors don't actually show up in the error.

On the other hand:
```factor
"\"" "Expected %s" sprintf throw 
```
->
![doublequoteerr](https://cloud.githubusercontent.com/assets/3238748/14227671/f6207202-f8d0-11e5-8da6-463dfb801c23.png)

So it's not so trivial as formatting.

**Comment by mrjbq7** [comment]
@catb0t this is fixed in master.  We were advancing the lexer and then when we throw the error, it was throwing at the end of the lexer input, not the beginning.  That is fixed and it says ``Unterminated string`` now.
