### ISSUE TITLE
Glob and directories

### ISSUE THREAD

**Issue by nicolas-p** [factor/factor#1610]
@mrjbq7, the `glob-directory` word that you implemented recently doesn't find directories, only files. I have just checked that Python's `glob` can. Is this normal? Are you planning to add a `glob` word that would work exactly like Python's?

**Comment by mrjbq7** [comment]
So, it's a work in progress but... I think it does?

```factor
"**/" glob-directory natural-sort
```

What did you expect to work and what didn't work?

**Comment by nicolas-p** [comment]
On my Desktop, I have created two folders: _folderA_ and _folderB_.

Factor:
```factor
"~/Desktop/fol*" glob-directory .
{ }
```

Python:
```python
>>> glob.glob("./Desktop/fol*")
['./Desktop/folderA', './Desktop/folderB']
```

**Comment by mrjbq7** [comment]
Hmmmm, I see.  Thats a bug.  I'll try to fix it as part of the glob cleanup I have in progress.

**Comment by mrjbq7** [comment]
Fixed in f80057d4b036163c3f7585ca2a2e9b6b9afb6d0f.

Want to try it?

**Comment by nicolas-p** [comment]
OK, it works.

Are you sure `glob-directory` is a better name than just `glob`? The input isn't a directory, and the output isn't either.

**Comment by mrjbq7** [comment]
Haha yes I think glob is better, then I need to rename <glob> and glob-matches? 

I'll queue that up too

**Comment by mrjbq7** [comment]
Renamed in 1234eb72e2da2501524e6616c641e41ca31da43d.
