### ISSUE TITLE
I have found a bug in locals?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1612]
I was rewriting the `send-mail` example on RosettaCode:

```
USING: accessors io.sockets locals namespaces smtp ;
:: send-mail ( f t c s b -- )
    default-smtp-config "smtp.gmail.com" 587 <inet> >>server
    t >>tls?
    "my.gmail.address@gmail.com" "qwertyuiasdfghjk" <plain-auth> >>auth \ smtp-config set-global 
    <email> 
       f >>from 
       t >>to
       c >>cc 
       s >>subject
       b >>body 
    send-email ;
```

When I pressed Enter in the listener, I got:

![bugin](https://cloud.githubusercontent.com/assets/3238748/14406136/70d55eb8-fe6c-11e5-9b05-30856779aa34.png)

So here I am, reporting it.

**Comment by mrjbq7** [comment]
That's weird, I pasted this into my listener and didn't get that.  Are you using the latest git master?  Can you think of something else you might have done?

**Comment by mrjbq7** [comment]
Also it's odd the ``obj`` is ``from``, that means it's trying to use a local called "from"?

**Comment by erg** [comment]
Which platform? And can you find an easy way to repro it?

Doesn't break with just pasting your code as first step.

**Comment by catb0t** [comment]
I updated / recompiled Factor and I can't do anything to repro this, so I don't know what happened, but this is closed.
