### ISSUE TITLE
Anonymous MAIN:

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1613]
@erg and I were talking about making `MAIN:` a defining word, rather than a tagging word.  It would names the main word `( main )` and require the stack effect of `( -- )`:

``` factor
SYNTAX: MAIN2:
    "( main )" create-word-in [
        [ parse-definition ] with-definition
        ( -- ) define-declared
    ] [
        [ current-vocab main<< ]
        [ current-source-file get [ main<< ] [ drop ] if* ] bi
    ] bi ;
```

And then this would work:

``` factor
IN: scratchpad MAIN2: "hello" print ;

IN: scratchpad "scratchpad" run
hello

IN: scratchpad "( main )" "scratchpad" lookup-word execute( -- )
hello
```

**Comment by bjourne** [comment]
I think it is a little to magic if you don't specify the name. In the other syntax words that wors like `MAIN:`, `MAIN-WINDOW:` and `GAME:`, you have to give the name of the main word.

**Comment by mrjbq7** [comment]
Experiment added in d2114e913c5735f52f438ca2ba001f92aa359e23.

**Comment by mrjbq7** [comment]
Allows this now:

```factor
MAIN: [
    command-line get [ print ] each
]
```

You can get the main word by:

```factor
"foo" lookup-vocab main>>
```
