### ISSUE TITLE
dark-theme is too hard to read

### ISSUE THREAD

**Issue by erg** [factor/factor#1626]
![Dark ui](https://i.imgur.com/7iLv2rg.png)

Maybe lighten up the background color? Or is this a dup of that bug where the color profiles are ignored so the colors are wrong?

**Comment by erg** [comment]
Oh, it looks like a bug. The fonts should be white :palm_tree: 

https://github.com/factor/factor/pull/1623

**Comment by nicolas-p** [comment]
That's clearly a bug. What does the help browser look like?

**Comment by erg** [comment]
On mac:

https://i.imgur.com/WUbW7L7.png

**Comment by nicolas-p** [comment]
I've just downloaded _factor-macosx-x86-64-2016-05-10-02-39.dmg_ from the Factor website. Everything looks fine.

**Comment by erg** [comment]
Ok, it's partially user error here. I'm just doing ``dark-theme theme set-global`` (which I want to work eventually).

What's the recommended way to switch themes on Windows, without the menu?

It's hard to read things on the stack:
![Dark on dark](https://i.imgur.com/KLZYuXM.png)

**Comment by nicolas-p** [comment]
The two words I implemented to switch themes are called `light-mode` and `dark-mode`.

**Comment by nicolas-p** [comment]
I had written a tip of the day for this but @mrjbq7 chose not to include it (maybe because it caused a dependency loop).

**Comment by erg** [comment]
Could the stack items be a light grey so they're readable? Otherwise it's looking nice!

**Comment by nicolas-p** [comment]
Do you mean the `--- Data stack:` string? This is something I forgot to change.

**Comment by nicolas-p** [comment]
Actually I think you meant the numbers on the stack in your screenshot. They are light grey and perfectly readable on the Factor I've just downloaded.

**Comment by erg** [comment]
The 🔑 is to bootstrap and use ``dark-theme``.

Great work!

**Comment by mrjbq7** [comment]
You should be able to `dark-mode` and `save` then all new Windows will be in new theme.

**Comment by erg** [comment]
This only works if you bootstrap since the patch.
