### ISSUE TITLE
dark theme polish

### ISSUE THREAD

**Issue by erg** [factor/factor#1627]
This is on linux.

![restarts](https://i.imgur.com/xKyh7BQ.jpg)

**Comment by mrjbq7** [comment]
Spacing looks good, background is just drawn from top to bottom of ligatures. Why is the background light? Maybe not themed properly to match popup background color.

**Comment by nicolas-p** [comment]
This is one of several places where the dark theme still needs work. There's also:
- "Show errors" in the Error List
- right-click menus
- `~quotations~` and other things like this
- the summary in the Inspector
- the Slot Editor window (which needs margins as well)

**Comment by nicolas-p** [comment]
Also, `ui.gadgets.theme` could be renamed `ui.theme.images`. What do you think?

**Comment by mrjbq7** [comment]
I have fixes for a few of these almost ready but didn't finish. Will try to commit in the next few days.

**Comment by nicolas-p** [comment]
We need this for the slot editor window:

```factor
IN: ui.gadgets.slots
: <slot-editor> ( close-hook update-hook ref -- gadget )
    vertical slot-editor new-track
        swap >>ref
        swap >>update-hook
        swap >>close-hook
        add-toolbar
        <source-editor> >>text
        dup text>> margins <scroller> 1 track-add
        dup revert white-interior ;
```

**Comment by mrjbq7** [comment]
Also deploy tool.  See #1659.

**Comment by nicolas-p** [comment]
There's also the box in the listener that tells you what vocabularies you should be USING.

**Comment by mrjbq7** [comment]
Changing the listener font doesn't update the cursor height.

Also, try this:

```factor
"sans-serif" 40 set-listener-font
dark-mode
"math" words.
```

The stack effects are not the same font size.

Also paste it again now:

```factor
"sans-serif" 40 set-listener-font
"math" words.
dark-mode
```

The line-heights are broken--the lines overlap each other.

**Comment by odiferousmint** [comment]
Any news on this? When I type `dark-mode`, it does not change the white background:

![2020-08-30-181455_600x715_scrot](https://user-images.githubusercontent.com/43568459/91664029-b77faa00-eaec-11ea-832e-57c38b9a041e.png)

This also does not look nice and possibly a bug:
![2020-08-30-181351_228x224_scrot](https://user-images.githubusercontent.com/43568459/91664006-93bc6400-eaec-11ea-9a2d-ebae8b646085.png)

Not sure why this is happening given the first screenshot. Perhaps a bug?

I'm not sure I do like the font and the color theme (somewhere it's dark red, somewhere it's dark green-ish cyan-ish, etc.), to be honest. I prefer `DejaVu Sans Mono`, and `monokai` and the like. Or maybe we could switch to black-ish, and grayscale.

**Comment by mrjbq7** [comment]
The theme switching doesn't really work to change the current window.

You can start a new listener that looks a lot better since it is initialized with all the expected colors.

More themes welcome, and improvements (that black text on dark background doesn't look great).

See ``ui.theme`` for the generic methods your new theme has to define.

I'd be in favor of reducing the number of methods too, to a smaller set of colors required to be defined.  It grew organically from places that used colors, but hasn't had a round of cleanup yet.

**Comment by odiferousmint** [comment]
Where does `solarized-base01` and the like come from? I have not found anything, only that it is being used in `basis/ui/theme/theme.factor`. That said, in Browser, if you get into `dark-theme`, it will show the values but not `solarized-base01`, etc. which I am not sure if is a bug or intended[1].

![2020-08-31-061203_538x15_scrot](https://user-images.githubusercontent.com/43568459/91682165-eaf42000-eb50-11ea-9634-c9895b59c4bb.png)
![2020-08-31-061155_359x323_scrot](https://user-images.githubusercontent.com/43568459/91682167-eb8cb680-eb50-11ea-9e54-5e9933310919.png)

Regardless, where is that `solarized-base01`, etc. come from? Grep found nothing.

**Comment by mrjbq7** [comment]
https://github.com/factor/factor/blob/master/basis/colors/constants/solarized-colors.txt

**Comment by odiferousmint** [comment]
Oh, I see! Thank you.

**Comment by mrjbq7** [comment]
Closing now that dark mode is pretty okay.
