### ISSUE TITLE
two vocab-exists? words

### ISSUE THREAD

**Issue by erg** [factor/factor#1628]
I bet we only need one.

```factor
"help.lint.checks"
"ui.tools.listener"
```

**Comment by mrjbq7** [comment]
I kind of like the one in ``ui.tools.listener`` better, which does a ``find-vocab-root``... the other checks for membership in ``all-disks-vocab-names`` which seems a little less correct.

Not sure best place for it... it depends on ``vocabs.loader``, so can't go in ``vocabs``...

**Comment by mrjbq7** [comment]
Fixed, defined it in ``vocabs.loader``...
