### ISSUE TITLE
Esc should close context menus

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1632]
Pressing Esc on the keyboard while a popup menu is active should cancel the menu, at least on Windows, not sure about other platforms.

**Comment by mrjbq7** [comment]
Which popup menu doesn't close with escape?  are you talking about a right-click menu?

**Comment by AlexIljin** [comment]
Yes, I'm talking about the right-click menu. Both in Listener and in Browser I could not find a single context menu that would react on Esc. It does not matter whether I right-click a selection (the menu contains a single Copy command) or on a link-type entity, which has menu with words like Edit, Fix, Forget, etc. -- none of these menus can be cancelled from keyboard. Or even navigated/selected using keyboard. And there are no accelerators, but that's an entirely different issue.

**Comment by bjourne** [comment]
That's the custom on Linux too. Context menues should grab keyboard input when they are displayed. That way, you could have ESC close them and arrow keys move up and down among the items in the list.

**Comment by mrjbq7** [comment]
This is fixed by #1726, although we don't have up/down keyboard support.
