### ISSUE TITLE
Strict vocabulary filename requirements make scripting hard

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1639]
see: https://github.com/exercism/xfactor/issues/5

[Exercism.io](http://exercism.io) is a site for helping people learn to code and learning new languages. I help maintain the [Factor language track](https://github.com/exercism/xfactor) on there.
 
An Exercism exercise folder on the github side has two parts: 
* A reference implementation containing `example` somewhere in the name -- these do not get served to the client, but are used for testing the integrity of the unit tests & for continuous integration
* Unit tests `exercise-name-tests.factor` these do get served to the client, and there is no problem since the user's implementation and the server-side implementation should both pass the same tests.

If the reference implementations do not contain `example` somewhere in the filename, then they will be sent to the client along with the exercise, which defeats the point of the challenge. But, Factor does not know about `leap`'s implementation here:

```
├── exercises
    ├── hello-world
    │   ├── example.factor              -- reference implementation
    │   ├── hello-world.factor          -- stub to get started (this exercise only)
    │   └── hello-world-tests.factor    -- unit tests
    └── leap
        ├── example.factor              -- reference implementation
        └── leap-tests.factor           -- unit tests
```
If I add `exercises` to the list of vocab roots as described [here](http://docs.factorcode.org/content/article-add-vocab-roots.html) and then `USE: leap`, I get a `lexer-error no-vocab "Vocabulary does not exist"` error. It works fine when `leap/example.factor` is renamed to `leap/leap.factor`.

Stringent filename requirements are fine when all code is under the `resource:work` folder in neatly organised ways where filenames don't otherwise matter. In the context of Factor being as useful as Python or Perl or even C or... well, *any* other platform, this is _such_ a usability problem I think it's a bug.

Would it be possible to make loading specific files possible, regardless of their name? A global variable to allow loading vocabularies by folder name (on a first-find basis) instead of file name?

Or is there some existing functionality to make this possible?

**Comment by jonenst** [comment]
You can name your server side implementation file example.factor if you put it in a child vocabulary name example:
```
├── exercises
    ├── hello-world
    │   ├── example
    │   │   └── example.factor              -- reference implementation
    │   ├── hello-world.factor          -- stub to get started (this exercise only)
    │   └── hello-world-tests.factor    -- unit tests
    └── leap
        ├── example
        │   └── example.factor              -- reference implementation
        └── leap-tests.factor           -- unit tests
```

Also, how did you plan to run the same test suite against different implementations ?

**Comment by jonenst** [comment]
Also, for "scripting" (ie with #! factor at the begining of an executable factor file, or directly calling on the command line ```factor scriptfoo.factor```), you can name your file the way you want. But then you can't use features of vocabularies, like "foo" test to test the foo script.

**Comment by catb0t** [comment]
No, that defeats the purpose of having exactly one unit test file per exercise that both the reference implementation _and_ user code should pass. 

On CI and git, the `exercise-example.factor` should pass `exercise-tests.factor` (so it must be in the same vocab), and on the client side, the user's implementation (named `exercise.factor`) should pass the same `exercise-tests.factor`.

**Comment by catb0t** [comment]
> with #! factor at the begining of an executable factor file, or directly calling on the command line factor scriptfoo.factor), you can name your file the way you want. But then you can't use features of vocabularies, like "foo" test to test the foo script.

That's okay, but defeats the purpose of Factor's interactive development, IMO.

**Comment by jonenst** [comment]
How do exercise-example.factor and exercise.factor implement the functionality to be tested by exercise-tests.factor ? Do they both provide words with the same name ? Do they use GENERIC: words with different implementations ?

**Comment by mrjbq7** [comment]
It's unclear to me what is desired here.  You want two separate implementations of a vocabulary that you can switch between?  (e.g., ``USE: leap`` either uses ``leap/example.factor`` or ``leap/leap.factor`` depending on if the user has implemented anything)?  Is the ``example.factor`` meant to be executed or just sample code for the user to look at?

Do you want definitions that exist in ``example.factor`` being slowly overwritten by definitions that the user provides? (e.g., ``"leap" refresh`` or ``refresh-all`` will pick up changes to the ``user.factor``)?

Or is the issue that an empty ``leap`` directory doesn't allow ``USE: leap`` before ``leap/leap.factor`` is created?

We work similarly to other languages.  Like in Python, if you ``import foo``, there is a "where is foo" process that looks at the current directory and then other paths where libraries are found.  Scripts are supported in a similar fashion mostly for being used like ``python foo.py``.

You can always use ``run-file`` to execute an arbitrary Factor script from the listener.  And you could use ``parse-file`` to essentially include another Factor file into your vocabulary.  If you want some kind of "include" functionality we can build it if not already available.  But I'm a little unclear what is requested.

**Comment by mrjbq7** [comment]
From re-reading your post, it seems you could do this on your server:

```
IN: scratchpad "leap/example.factor" run-file

IN: scratchpad "leap" test
```

And because your ``leap/example.factor`` has ``IN: leap`` and other definitions created that presumably you are using to verify your tests, that should all work fine.

**Comment by catb0t** [comment]
I guess I didn't explain that very well. Sorry about that.

On the server, we have:

```
├── exercises
    └── leap
        ├── leap-example.factor         -- reference implementation, should pass unit tests
        └── leap-tests.factor           -- unit tests
```
When a user recieves the `leap` exercise to the Factor folder on their own box, it looks like:
```
└── exercism/factor/leap
    ├── leap.factor                 -- user's implementation (file created by them), should pass unit tests
    └── leap-tests.factor           -- unit tests
```

The `leap-tests.factor` file is the same in both places. The `leap-example.factor` file will not be sent to the client because it has `example` in its name, but it should pass the tests on the server side. The user's code should pass the same tests, but our `leap-example.factor` and the user's `leap.factor` will never come into contact with one another.

Ideally, `USE: leap` would load `leap-example.factor` on the server and `leap.factor` on the user side, but I understand why the vocab implementation makes that hard.

@mrjbq7's idea seems to work. Here's what happens when the file is named `leap.factor` (the expected behaviour): 

```factor
IN: scratchpad: USE: leap 
Loading /home/cat/projects/git/xr/xfactor/exercises/leap/leap.factor
IN: scratchpad "leap" test
Loading /home/cat/projects/git/xr/xfactor/exercises/leap/leap-tests.factor
Leap year:
not very common
Unit Test: { { f } [ 2015 leap-year? ] }
introduced every 4 years to adjust about a day
Unit Test: { { t } [ 2016 leap-year? ] }
... etc ...
```
And here's what happens after `"projects/git/xr/xfactor/exercises" set-current-directory`:
```factor
IN: scratchpad current-directory get .
"/home/cat/projects/git/xr/xfactor/exercises"

IN: scratchpad "leap/leap-example.factor" run-file
Loading leap/leap-example.factor

--- Data stack:
IN: scratchpad 2012 leap-year? .
t

IN: scratchpad "leap" test

IN: scratchpad "leap/leap-tests.factor" run-test-file
Loading leap/leap-tests.factor
Leap year:
not very common
Unit Test: { { f } [ 2015 leap-year? ] }
introduced every 4 years to adjust about a day
Unit Test: { { t } [ 2016 leap-year? ] }
... etc ...
```
Yay! A little glue code to automate that should work okay. (I still wish it were easier, if I'm honest.)

**Comment by mrjbq7** [comment]
Glad it will work. 

Regarding "easier", are you wanting to make some kind of default name (`example.factor`) that you can set to be looked up if `leap.factor` is not found?

I'm curious how other languages work in exercism and whether this feeling is partly due to how our testing framework works.

**Comment by jonenst** [comment]
If I understand correctly, in  exercism/xpython ( https://github.com/exercism/xpython/blob/master/test/check-exercises.py ), they make a temp directory, copy the foo_example.py as foo.py, run the tests there and delete the temp directory... 

> In the context of Factor being as useful as Python [...] this is such a usability problem I think it's a bug.

Considering how they do the tests for exercism/xpython, I don't think you can say that factor is not as useful/usable as python...

So IMHO, exercism/xfactor is really cool, but the test framework doesn't need to change.

ps: In java, they use gradle's "source sets" and a custom build to do it: https://github.com/exercism/xjava/blob/master/exercises/build.gradle. They end up using symlinks (https://github.com/exercism/xjava/blob/master/exercises/allergies/src/example/java/Allergen.java) for common stuff. So it seems pretty ad hoc there too.

**Comment by mrjbq7** [comment]
Also @catb0t, we love new features so if this train of thought ever solidifies into something we can patch, I'm all for it.  :-)

**Comment by catb0t** [comment]
@jonenst I agree, I don't think the test framework was ever in need of change, I just found the name requirements very... claustrophobic, but considering I've [come up with something](https://github.com/catb0t/xfactor/blob/add-dev-test-env/exercism-testing/exercism-testing.factor) that should work at least for now, this is mostly a non-issue. 

>  are you wanting to make some kind of default name (example.factor) that you can set to be looked up if leap.factor is not found?

That would be kinda cool, but I don't think it's really necessary at this point. 

Thanks for your time (And I promise I'll stop creating issues for things that I think are bugs but are actually just me not understanding) :)

**Comment by mrjbq7** [comment]
Feel free to keep creating those type of issues.  I (we?) don't mind at all.

**Comment by jonenst** [comment]
Same here, I don't mind at all !
