### ISSUE TITLE
Documentation to HTML / XML?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1643]
I've just written some documentation, and I think this documentation is the best thing to ever grace a computer. I want to make it into HTML, but I don't want to have to rewrite it all by hand (plus, Factor's help tool is really nice for writing simple markup). 

How does `docs.factorcode.org` take `*-docs.factor` and turn it into HTML that I am reading? I guess it uses `fuel` and FHTML code interpolation but that seems like a lot of complex work just to export some documentation as markup that a browser can understand. 

Does Factor's ginourmous standard library have something for this already that I can't find? If it doesn't, it definitely should (but I shouldn't be the one to implement it).

**Comment by mrjbq7** [comment]
Factor has support for [formatted output](http://docs.factorcode.org/content/article-io.styles.html), which uses a common set of styles and basic structure to output formatted text (with very minimal support for images).

We can display that formatted output in the Listener (treating it as a [visual REPL](http://re-factor.blogspot.com/2010/09/visual-repl.html)).  But we can also use the ``html.streams`` vocabulary to render that formatted output to HTML or the ``pdf.streams`` vocabulary to render it to a PDF.

If you'd like to see how the help HTML files are generated, look at the ``help.html`` vocabulary where we use the ``html.streams`` with a couple small changes to support linking between pages, adding a navigation bar across the top, and compress repeated CSS styles to save a little on file sizes.

**Comment by mrjbq7** [comment]
In fact, these are all the same:

```IN: scratchpad "handbook-tools-reference" help```

http://docs.factorcode.org/content/article-handbook-tools-reference.html

https://github.com/mrjbq7/re-factor/blob/master/docs/tools.pdf
