### ISSUE TITLE
peg.javascript should recognise escaped quotes

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1648]
I'd fix this in a pull request if I could understand [the tokenizer lines in question](https://github.com/factor/factor/blob/master/extra/peg/javascript/tokenizer/tokenizer.factor#L51) well enough to add this.

```factor
IN: scratchpad HEREDOC: END
"abc\"def\""
END 
javascript
```
Should return: 

```
T{ ast-begin
    { statements V{ T{ ast-string { value "abc\"def\"" } } } }
}
```
But instead it gives:

```
T{ ast-begin { statements V{ } } } 
```

**Comment by catb0t** [comment]
Oh, I did fix it, it just didn't reload right away!

**Comment by mrjbq7** [comment]
Should just be:

```diff
+                    | "\\\"" => [[ CHAR: \" ]]
```

**Comment by mrjbq7** [comment]
P.S. if you change this and do a PR, can you make these changes too (for clarity):

```diff
-EscapeChar        =   "\\n" => [[ 10 ]]
-                    | "\\r" => [[ 13 ]]
-                    | "\\t" => [[ 9 ]]
+EscapeChar        =   "\\n" => [[ CHAR: \n ]]
+                    | "\\r" => [[ CHAR: \r ]]
+                    | "\\t" => [[ CHAR: \t ]]
```

**Comment by catb0t** [comment]
Yes, that's what I thought but I had to restart Factor for the change to make a difference.

And sure, I will.

**Comment by mrjbq7** [comment]
I tried it too and the EBNF change didn't seem to take effect until restarting Factor.  That implies something in EBNF might not refresh properly with a vocab reload maybe?  Dunno.

**Comment by mrjbq7** [comment]
Also, add a test! :-)
