### ISSUE TITLE
VM C++ comments

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1651]
For consistency they should all be `/* */` or `//`. It seems like `/* */` is used more often so we should go with that syntax.

**Comment by AlexIljin** [comment]
Seems like a pretty arbitrary rule, if you ask me.

And you don't.

And I'm still replying.

There is a point in having two kinds of comments in C++, and it seems to stem from the fact that `/* */` comments can't be nested like so:` /* /* */ */`. Therefore if you want to comment out (temporarily?) a block of text that already contains some comments in it... You get the idea.

So, it's better to stick to the line-level comments with `//`, which can at any moment be wrapped with an outer level of `/**/` block-comment. Some may consider that comments inside functions are to be made with `//`, so as to freely chop out blocks of functions during debugging, or entire functions for that matter.

I myself prefer to always use `//` to avoid the merest possibility of awkward block formatting like this:

```
/* text
 * comment
 * text
 * comment
 * text */
```

**Comment by AlexIljin** [comment]
There are languages out there that **do** support the block comment nesting. And some of them even don't have line comments, possibly because of that feature making them unnecessary.

I'm talking, of course, of the Oberon family of languages, but I'm sure there are others.

**Comment by AlexIljin** [comment]
@bjourne: I've looked at the code, and I see your point. The `/**/` is used almost everywhere, so `//` really stands out.

I've made a patch, will do PR soon.

**Comment by bjourne** [comment]
Yes, you are right that `//` is technically superior. But I think it is better to be consistent as much as possible. I wouldn't mind a pr that changes `/* */` to `//` everywhere in the code.

**Comment by AlexIljin** [comment]
@bjourne: "I wouldn't mind a pr that changes `/* */` to `//` everywhere in the code."

And here it is: #1696
