### ISSUE TITLE
Maybe wrong cache directory path on Unix

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1653]
On unices the cache directory is hardcoded to `~/.factor-cache`. On Linux I think it should instead be `~/.cache/factor` because that is what the [XDG spec says](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html). On os x it looks like `~/Libraries/Caches/factor` or something similar would be right.

**Comment by mrjbq7** [comment]
+1

**Comment by mrjbq7** [comment]
I implemented an ``xdg`` vocabulary, maybe we should use that to make sure it's relative to ``xdg-cache-home``?

https://github.com/factor/factor/blob/master/extra/xdg/xdg.factor

**Comment by bjourne** [comment]
Sounds good.

**Comment by mrjbq7** [comment]
Fixed in deac792fc735a852e8544c870aa2bffc49fa17db.
