### ISSUE TITLE
Doesn't interpret mapped keys correctly on OS X

### ISSUE THREAD

**Issue by mykdavies** [factor/factor#1654]
My enter key doesn't work so I've used Karabiner to remap my right shift key to enter. All other applications respect this mapping, but in Factor, it seems to treat it only as a carriage return, i.e. the cursor moves down one line, but doesn't execute the given line.

**Comment by catb0t** [comment]
What happens when you press <kbd>LSHIFT+ENTER</kbd>? This is in the GUI, right? It's almost definitely because Factor interprets your keypress as <kbd>SHIFT+ENTER</kbd>, which is line continuation, which is what you're experiencing.

**Comment by jonenst** [comment]
Can you try the following:
```"gesture-logger" run```
It should open 2 windows. A small (100x100 px) black one and a bigger white one with text. All interactions with the black window will be printed to the white window.

On Ubuntu, when I press enter on the black window, it prints
```
T{ key-down { sym "RET" } }
T{ key-up { sym "RET" } }
```

**Comment by mykdavies** [comment]
@catb0t thanks, but LSHIFT + ENTER worked no differently (I tried most combinations of modifier keys before raising this :-) ).

@jonenst you've found the problem, I was getting 

`T{ key-down { sym "ENTER" } }
T{ key-up { sym "ENTER" } }`

Changing the mapping so that `SHIFT_R` instead sends `RETURN` then gives me the behaviour you saw. Having done some reading on `RETURN` vs `ENTER`, it appears that this is the mapping I should have made in the first place. 

It appears that it is possible, though not common, for applications to treat RETURN and ENTER differently, so I can't claim that this is a bug at this point. 

Happy to close if that makes sense. Thanks for your help both.

**Comment by jonenst** [comment]
Yeah, I think it's nice that you can differentiate between "RET" and "ENTER" if you want to. That's what the UI listener (which inherits from the more general editor) does.

**Comment by mykdavies** [comment]
@jonenst  Great, thanks for the very quick replies, and apologies for any distraction.
