### ISSUE TITLE
Bad Button Display

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1658]
Running `"demos" run` produces a screen of buttons. The buttons look bad, see below:
![demomenu](https://cloud.githubusercontent.com/assets/169039/16148492/956567b2-3492-11e6-84a6-700ef12d446f.png)
I believe this might be related to the new theming engine, although I didn't have time to look into it.
Windows 8.1 64-bit, running latest 32-bit Factor from the master branch.

**Comment by catb0t** [comment]
It's the theming. Also happens with `deploy-tool`.

**Comment by mrjbq7** [comment]
Ugh. Due to a combination of new button theme with gradient and Windows text not supporting alpha (can't remember which issue number but open for awhile). I thought I had a fix for it but the real fix is probably to use a newer API to do the text rendering. 

In the meantime we had a few places we disabled gradient and just used a solid color on Windows to workaround until fixed.

Good report. Need to fix before 0.98.

**Comment by AlexIljin** [comment]
@mrjbq7: "Windows text not supporting alpha"

Why do we need alpha? Windows can draw text with opaque and with transparent background, which is all that's needed here. What functions do we use for text output?

**Comment by mrjbq7** [comment]
Yes, Windows can draw text with transparent backgrounds but the API that we use cannot (easily?) because we render into a bitmap image that should have an alpha channel with transparency background. I'd be happy if you wanted to work on it.

**Comment by mrjbq7** [comment]
#152

**Comment by mrjbq7** [comment]
https://github.com/factor/factor/blob/master/basis/windows/uniscribe/uniscribe.factor

**Comment by mrjbq7** [comment]
On Linux and Mac, the text is rendered using the foreground color as the text color and the background color as the background, respecting the `alpha` slot to provide transparency. The alpha is a floating point number that can go from 0.0 to 1.0 although is most frequently 0.0 *or* 1.0.

It would be super great to support alpha/transparency in the Windows don't rendering backend.  You can test your code by creating an image for a given font and string text and then rendering it using `image.` or open in an image editor to confirm it works before hooking into the UI if that's easier. 

I was hoping to work on this for 0.98 but my patch didn't quite fix the bug and then I got distracted.

**Comment by AlexIljin** [comment]
@mrjbq7: "we render into a bitmap image that should have an alpha channel with transparency background"

Oh, I see how that could be a problem. Thanks for the links. In theory this should be easy, but to get a good implementation - not so much. I'll see what I can do, although no promises. I have some other things going on at the moment.

**Comment by mrjbq7** [comment]
The UI backend is in `ui.text.uniscribe`. You can provide another "ui.text.windows" vocabulary to test in parallel. Also, if you don't want to take it on it's okay. At least we should workaround issues like the demo buttons. That's probably a change that should go in ui.gadgets.buttons.

**Comment by nicolas-p** [comment]
As a workaround, I would set the text background (only on Windows) to a light grey colour (the one in the middle of the gradient). You would still see a rectangle when looking closely but I think it's enough for a temporary workaround.

**Comment by kusumotonorio** [comment]
I tried my idea. I've only tried a little, but it seems to work well.
![chroma-key](https://user-images.githubusercontent.com/47816570/58634571-8ed79600-8326-11e9-80ac-1bc7caf329bf.png)

**Comment by kusumotonorio** [comment]
It seems my test code works fine at slides too.

![button_slide](https://user-images.githubusercontent.com/47816570/58674618-98471980-838b-11e9-8c98-b37aafe2fac3.png)

**Comment by mrjbq7** [comment]
!!!!

**Comment by AlexIljin** [comment]
I'm on the second day of a 4-day weekend here, and I have some time to spend on this.
Can't wait to see the code!

**Comment by kusumotonorio** [comment]
There is a problem that the label on the button gets a little thick, so I am trying to improve it.
In any case, I will make it possible for you to see it soon. Please wait a little longer.

**Comment by kusumotonorio** [comment]
I committed it.  
https://github.com/factor/factor/compare/master...kusumotonorio:win-transparent-background-text

I'm going to revert unnecessary changes.

**Comment by kusumotonorio** [comment]
I did refactoring.

**Comment by AlexIljin** [comment]
It's great to finally see the code! This tells me a lot about image manipulation in Factor.
I see you are doing some math in there to subtract the background color from each pixel of the text image and assign transparency values.
I will experiment with this a little to see if my approach, which I described earlier, would work as well, and then we can compare notes, maybe do some benchmarks to pick the best solution.

@kusumotonorio, could you come up with a way to measure performance of text drawing with the solution you createad?

**Comment by AlexIljin** [comment]
[This branch](https://github.com/factor/factor/compare/master...AlexIljin:win-transparent-text-background) is based on the idea of copying a color channel into the alpha channel. It works for me, both with and without font smoothing.

Here's some smoothed blue text, for example:
![factor_blues](https://user-images.githubusercontent.com/169039/58755023-92f8e480-84db-11e9-85b2-2a3e9687311f.png)

The background for the text can either be transparent, or opaque, no intermediate values are supported. Also my code doesn't support the font foreground colors with transparency, it only supports non-transparent foregrounds for the font color. Do we ever want to be able to produce translucent text? If so, the two alpha channels need to be multiplied.

For testing this text rendering I'd really like to have a gadget with sliders for R, G, B and A components for text color and text background, which would render a sample text over a textured background. This would help debug all the possibilities of the text rendering. Can anyone help creating such a gadget?

In the meantime I was using code like the following to do tests with basic background transparency:
```
{
    { font-style bold }
    { font-size 18 }
    { foreground T{ rgba f 1 1 1 0.5 } }
} "thing" <styled-label>
T{ rgba f 0.4 0.6 0.9 0.5 } <solid> >>interior gadget.
```

**Comment by mrjbq7** [comment]
This is awesome you guys!

Seems like you've both got something working which is like 99% of the problem.  Appreciate the help!  So, the approach that @AlexIljin is doing might be simper and a lot faster, I made a couple comments on one of his commits just now.

Seems like supporting slightly transparent foreground text might be easily possible too using that approach...

**Comment by mrjbq7** [comment]
It'll be really really really great to get this bug fixed...!

**Comment by AlexIljin** [comment]
I have updated the branch and tested the transparent foreground font color as well as the transparent background. It all seems to work, and with very little performance hit thanks to optimizations suggested by @mrjbq7.

If there will be no more suggestions, I can make a PR.

**Comment by mrjbq7** [comment]
Make a PR!

**Comment by erg** [comment]
Fixed as well.
