### ISSUE TITLE
deploy-tool UI dark-theming is incorrect

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1659]
Normal light theme:
![whitemenu](https://cloud.githubusercontent.com/assets/3238748/16163104/69e56c5a-34a5-11e6-9c82-8f02abdfc294.png)

Dark theme (after `dark-mode save`):
![blumenu](https://cloud.githubusercontent.com/assets/3238748/16160694/7e96cae4-3497-11e6-94ee-ac70988b12a1.png)

This is on Linux with X and GTK.

**Comment by mrjbq7** [comment]
The dark theme isn't finished... There is a bug open to track it's todo's.

**Comment by mrjbq7** [comment]
Fixed in 1ce733ef72920446a6f8d5e17c07ccb62b786809.

**Comment by catb0t** [comment]
Cool!
