### ISSUE TITLE
More rosetta-code vocabularies?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1660]
The `rosetta-code` meta-vocabulary and [Rosetta Code: Factor](https://rosettacode.org/wiki/Category:Factor) are quite out of sync. There is also an [endless list](http://rosettacode.org/wiki/Reports:Tasks_not_implemented_in_Factor) of more Rosetta Code tasks which have yet to be implemented in Factor. 

Sometimes I spend my free time doing some of the unsolved ones and contributing the solution to Rosetta Code. I wonder if Factor upstream would appreciate pull requests for expansion / updates (not just correction) to the `rosetta-code` vocab?

Personally, I've found `rosetta-code` helpful in learning Factor and I'm sure others do as well.

**Comment by mrjbq7** [comment]
Would love PR's that improve and expand it. 

Also probably we should split out into its own factor/Rosetta-code repository since it's not as generally useful maybe? Dunno.

**Comment by catb0t** [comment]
Also, there's the `24-game` vocab which isn't under `rosetta-code` but [maybe should be](http://rosettacode.org/wiki/24_game#Factor)?

**Comment by erg** [comment]
I have a whole lot of changes in a branch. Just keep doing the same old for awhile, no need to reorganize everything 🍰

**Comment by bjourne** [comment]
@cab0t, the game is in `extra/24-game/24-game.factor` but perhaps it should be moved.
