### ISSUE TITLE
GENERIC# syntax word is odd

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1670]
Because it is the only declaration word that doesn't end with a `:` character. I think it should because it would make the syntax more regular, easier to syntax highlight and so on. So I think it should be called `GENERIC#:` instead. What do you think?

**Comment by mrjbq7** [comment]
Sounds good to me. How does that fit your new lexer ideas @erg?

**Comment by erg** [comment]
Oh i already did that in the locals-and-roots branch.

I will make a mailing list post describing what i've been wirking on tomorrow.

**Comment by mrjbq7** [comment]
Should we make this change?  Sooner the better for stuff like this...

**Comment by bpollack** [comment]
I know I've been rather absent lately, but I'm completely fine with this proposal. I know it'll sound silly, but I was a bit surprised back in March when I was blitzing on Factor stuff to discover that the reason I'd never grokked what `GENERIC#` did was because it was a definition word.
