### ISSUE TITLE
Error when loading factor-mode with SMIE

### ISSUE THREAD

**Issue by statonjr** [factor/factor#1672]
What I did:

Started Emacs

What happened:

Emacs halted initialization of `factor-mode` and threw an error saying that `smie-prec2->grammar` couldn't be found.

What I expected to happen:

`factor-mode` to load properly.

I added `(require 'smie)` to `factor-smie.el` and that fixed the error. Not sure if that's the correct fix.

**Comment by mrjbq7** [comment]
@bjourne

**Comment by bjourne** [comment]
You found the correct fix. :) I'll make the change shortly.
