### ISSUE TITLE
SQLite: Unsigned Value Stored as Signed

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1673]
The following test fails:
```
{ 2147483648 } [
    TUPLE: num-test num ;
    num-test "NUM_TEST" { { "num" "NUM" INTEGER } } define-persistent
    "num-test-bad.db" <sqlite-db> [
        num-test ensure-table
        num-test new 2147483648 >>num insert-tuple
        num-test new select-tuple
    ] with-db num>>
] unit-test
```

Instead of returning the same value that was written, it returns -2147483648. If you look inside the num-test-bad.db with an external utility, you can see that it actually contains the negative value. The following test passes:
```
{ "-2147483648" } [
    "sqlite3.exe num-test-bad.db \"select * from NUM_TEST;\""
    utf8 [ readln ] with-process-reader
] unit-test
```

Doing the equivalent code with sqlite3.exe works as expected:
```
{ "2147483648" } [
    "sqlite3.exe num-test-good.db \"create table NUM_TEST(num integer); insert into NUM_TEST(num) values(2147483648); select * from NUM_TEST;\""
    utf8 [ readln ] with-process-reader
] unit-test
```

**Comment by erg** [comment]
INTEGER calls sqlite-bind-int-by-name which uses a c ``int`` type in the
ffi. Your integer is negative as a signed 32bit int (0x8000,0000) so the db
stores it as negative.

If you want to use 64bit ints, try BIG-INTEGER in the framework to use a
signed 64bit, or UNSIGNED-BIG-INTEGER for unsigned 64bit.

I don't believe at this time that your code demonstrates a bug, but if
there's anything to fix, I'm willing to!

Doug

**Comment by AlexIljin** [comment]
Thank you! Using UNSIGNED-BIG-INTEGER fixed the issue for me.

PS: I don't thing SQLite can store 64-bit values as unsigned.
