### ISSUE TITLE
>url parsing could be improved

### ISSUE THREAD

**Issue by erg** [factor/factor#1675]
A ``site:port`` with no protocol doesn't expand as well as it could. We could also take ports into account and add an https protocol for port 443 (but still allow the user to also specify ``http://reddit.com:443`` if they knew it wasn't https, for example.)

There might be more test cases to find, but here's one that I ran across.
 
```factor
"reddit.com:443" >url describe
url
protocol f
username f
password f
host     f
port     f
path     "reddit.com:443"
query    f
anchor   f

! This one is how the previous one could look
"https://reddit.com:443" >url describe
url
protocol "https"
username f
password f
host     "reddit.com"
port     443
path     "/"
query    f
anchor   f
```

**Comment by mrjbq7** [comment]
I agree with maybe parsing as a host:port rather than a path, but I don't agree with choosing https and port 443.

**Comment by erg** [comment]
I'm trying to make a proxy server and android is sending a request like below. Note that there is no explicit https but there's a port 443. So there should be some way to convert this to a Factor url, even if it's not ``>url``.

```
CONNECT lh3.googleusercontent.com:443 HTTP/1.1
Host: lh3.googleusercontent.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 6 Build/MMB29X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/49.0.2623.105 Mobile Safari/537.36 GSA/6.0.23.21.arm
```

**Comment by bjourne** [comment]
Protocol name can be gotten using `443 htons f getservbyport name>>`.

**Comment by mrjbq7** [comment]
Okay, I added that as ``port-protocol`` to match the existing ``protocol-port`` in ab66a737448e60d6671bcd2f67c74271325678f4.

**Comment by bjourne** [comment]
Regarding the parsing, I don't think it can be fixed. The rules for how urls should be parsed are here: https://tools.ietf.org/html/rfc1808.html So in the `reddit.com:443` example, it should interpret `reddit.com` as the scheme and `443` as the path.

**Comment by erg** [comment]
This format is used by an http ``CONNECT`` in a proxy request, so there should definitely be a word besides ``>url`` if it's not possible to do it there.

**Comment by bjourne** [comment]
That would be nice. Like an `>url-dwim` which is able to parse ambiguous urls with common sense. E.g `www.google.com` would be parsed as `http://www.google.com` and `lh3.googleusercontent.com:443` as `https://lh3.googleusercontent.com`.

**Comment by mrjbq7** [comment]
Something like this?

```factor
: >url-dwim ( string -- url )
    "://" over subseq? [
        >url
     ] [
        "http://" prepend >url
        dup port>> port-protocol [ >>protocol ] when*
     ] if ;
```

**Comment by mrjbq7** [comment]
Also, I guess I should say @erg was asking about a ``Host:`` http header, which you can just do this:

```factor
: split-host ( string -- host port/f )
    ":" split1 string>number ;
```

**Comment by bjourne** [comment]
Or the `parse-host` word.

**Comment by mrjbq7** [comment]
Yeah, @erg you can use ``parse-host``, that's way better.  Should we close this issue?

**Comment by erg** [comment]
Ok. The situation isn't as bad as I thought. Thanks for the help!
