### ISSUE TITLE
Question about bare metal

### ISSUE THREAD

**Issue by Immortalin** [factor/factor#1688]
Is it possible to do baremetal, freestanding(I.e. no OS) x86/64 development?

**Comment by bjourne** [comment]
No, not really. :p

**Comment by bpollack** [comment]
I think @bjourne is being unfair. You'd just need to rewrite the VM as an actual systems kernel, modify it to run multiple images communicating over some type of RPC mechanism, and then write some vocabularies for driver support. We'd definitely welcome pull requests that provided any of the above functionality.

**Comment by AlexIljin** [comment]
There are small open-source kernels out there that can run on bare metal x86. The two I know of are [Native Oberon](http://www.oberon.ethz.ch/archives/systemsarchive/native_new) and [A2](https://en.wikipedia.org/wiki/Bluebottle_OS) (formerly known as Blue Bottle). The first one is smaller and simpler, but the latter is being maintained to this date.

Both are self-hosting, i.e. they have GUI, text editors and compiler built-in, so you can do development, networking and have some file systems support. So, having full source code available, you can create a Factor VM on top of a stripped-down version of either of them, or just have Factor programs run alongside the Oberon code.

PS: Oberon is one of the "interesting" languages mentioned by Slava Pestov on the concatenative wiki: http://concatenative.org/wiki/view/Oberon

**Comment by erg** [comment]
I think this is out of scope for this version of Factor. Closing for now.
