### ISSUE TITLE
Win64 deployment <scroller> crash on Win7 64

### ISSUE THREAD

**Issue by radebrecht** [factor/factor#1691]
This code
```
USING: ui ui.gadgets.labels ui.gadgets.scrollers ;
IN: deploytest

: (main) ( -- )
  "test" <label> <scroller> "test" open-window ;

: main ( -- )
  [ (main) ] with-ui
;

MAIN: main
```
deploys and the resulting .exe crashes with:
![image](https://cloud.githubusercontent.com/assets/98628/17766781/143c69bc-652d-11e6-9132-1b05787cdbdb.png)

When I leave out the `<scroller>` bit, it runs fine.

Tested on Windows7 64.

On OSX the code runs fine, no crash.

**Comment by jonenst** [comment]
Works on Ubuntu 14.04 as well

**Comment by bjourne** [comment]
The problem appears to be that on windows the ui theme is not copied over. It crashes because it can't find an image from the theme.

**Comment by mrjbq7** [comment]
That's weird because ``copy-vocab-resources`` seems to work.  If it doesn't that might mean ``copy-resources`` doesn't have ``ui.theme.images`` in the manifest vocabs?

**Comment by bjourne** [comment]
I changed the string from `"resource:"` to `""` and it seem to make it work. I don't know if it causes any unwanted side effects. But the string is empty on Linux too, so it seems logical.

**Comment by radebrecht** [comment]
Yep, patching `tools.deploy.windows` did the trick. I don't understand the internals well enough to know whether this is a good permanent solution or not. I can work with it for the moment. It would be better to have the ui images baked into the .exe, though.
