### ISSUE TITLE
Opengl error on ubuntu

### ISSUE THREAD

**Issue by Immortalin** [factor/factor#1693]
I am getting the following error:

``` shell
An error occurred while drawing the world T{ world f ~array~ ~array~ f f ~vector~ ~array~ ~debugger~ t t f....
This world has been deactivated to prevent cascading errors.
Required OpenGL version 1.0 not supported ((null) available)
If you have several libGL.so installed, Factor tried the first one in: ldconfig -p | grep libGL.so$
You can change the library used like so: LD_LIBRARY_PATH=/usr/lib/fglrx ./factor
```

This is the output of `ldconfig -p | grep libGL.so

``` Shell
    libGL.so.1 (libc6,x86-64) => /usr/lib/nvidia-361/libGL.so.1
    libGL.so.1 (libc6) => /usr/lib32/nvidia-361/libGL.so.1
    libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so
    libGL.so (libc6,x86-64) => /usr/lib/nvidia-361/libGL.so
    libGL.so (libc6) => /usr/lib32/nvidia-361/libGL.so
```

**Comment by jonenst** [comment]
Hi,
does glxgears work on your computer ? It's in the mesa-utils package.

if yes, what's the output of  ```ldd $(which glxgears) | grep libGL.so```
also, what's the output of ```ls -l $( locate libGL.so )``` ?

Regards,
Jon

**Comment by jonenst** [comment]
Also,
do any of these work ?
```LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ ./factor```
```LD_LIBRARY_PATH=/usr/lib/nvidia-361/ ./factor```
```LD_LIBRARY_PATH=/usr/lib32/nvidia-361/ ./factor```

**Comment by bjourne** [comment]
Since @Immortalin hasn't responded I close this one.
