### ISSUE TITLE
Deploy not working

### ISSUE THREAD

**Issue by calsioro** [factor/factor#1694]
Factor version: 0.98 x86.64 (1777, heads/master-ed29fbd93f, Mon Aug  8 20:45:47 2016) [Microsoft Visual C++ 190023506]
OS: Windows 7

When using `deploy-tool` on a vocabulary, I get an OS error on file access:
"The process cannot access the file because it's being used by another process."
I think it's the image it's building.

The same happens with `deploy`, or `deploy-image-only`.
I've tried with a vocabulary of my own, then with `tetris` because it has deploy settings already made.
Then I made a vocabulary "test":

    USING: kernel io ;
    IN: test
    : test ( -- ) "test" print ;
    MAIN: test 

They all fail.
I tried deleting all the temp files by hand, and `delete-staging-images`.

I tried mostly with the GUI tools, but made some attempts on the text mode listener too.
On the traceback tool, I see a path with the vocab name I'm deploying and ".image" extension (in the retain stack). I'm guessing this is the file that errors. For instance: "C:\Users\Fede\AppData\Local\Temp/factorcode.org\Factor/test.image".

I tried different deploy settings for both my vocabs, but not for tetris.

This happened on the previous version I was using too (Factor 0.98 x86.64 (1579, heads/master-0-g46fd0b5, Wed Dec 24 11:35:50 2014)) and I decided to try the last one to see if it was fixed.

**Comment by calsioro** [comment]
I'm completely lost...
Today I tried again, not making any change to my Factor version or configuration.
Both `"hello-world" deploy` and `"hello-ui" deploy` worked as expected! (Well, hello-ui opens a console window, but that's a different issue I should look at).

My application finally deployed too, but doesn't start (probably an error on my side).

My guess is something is interfering with Factor's deploy system in my machine, but I'm lost as to what it could be (or where to look at).

I'll make some more tests

**Comment by bjourne** [comment]
So deploy now works? Perhaps it was the anti-virus kicking in? Deploy creates an exe file in the deploy directory and then tries to write to it but if the AV sees the exe first, it could lock it and perform scanning resulting in the "used by another process message".

**Comment by calsioro** [comment]
Yes, it's working now. :D
You're right, it's probably the AV! Why didn't think of disabling it?
I'll have it in mind if it happens again :/

For more details, the failed attempts did leave a broken .exe file, so it might have failed on appending to it (or what deploy does with the image file) at some stage.
