### ISSUE TITLE
Path joining should use the native separator

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1701]
It would be nice if the native path separator was used for path joining, for Windows sake:
```factor
"C:\\tmp" "foo\\bar" append-path .
"C:\\tmp/foo\\bar"
```
It's a purely cosmetic issue because forward slashes work fine on Windows, but here `"C:\\tmp\\foo\\bar"` would look better.

**Comment by mrjbq7** [comment]
Fixed by #1702 (b477c432932784e9bb8f62d804b9135ce2c694db).

**Comment by bjourne** [comment]
Hopefully, someone are not using append-path for url manipulation. E.g. `"http://www.google.com/" "blaha" append-path` wont work anymore... I didn't think of that. Of course we have `url-append-path` for those cases..
