### ISSUE TITLE
factorcode.org's HTTPS certificate expired.

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1704]
My browser says 

> This server could not prove that it is paste.factorcode.org; its security certificate expired 31 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Tuesday, September 6, 2016. Does that look right? If not, you should correct your system's clock and then refresh this page.

is this going to be fixed or should I tell HTTPSEverywhere to ignore *.factorcode.org?

**Comment by bpollack** [comment]
It'll be fixed, though I'm having difficulty reaching the usual server admins. I'll try to fix it myself in a bit. Thanks for the heads-up.

**Comment by mrjbq7** [comment]
@erg can you generate another SSL cert?

**Comment by bpollack** [comment]
@mrjbq7 Sorry, I forgot to follow up. I don't have root on that box, but I can trivially fix it if you can give me sudo permissions. Up to you.

**Comment by mrjbq7** [comment]
I think @erg can give you permissions? @erg!

**Comment by bpollack** [comment]
@erg seems to be pretty MIA for at least a few weeks, @mrjbq7 ; I've been unable to contact him through normal channels. I have access to the box, but I can't do anything on it. (In fact, there's probably a grumbly email in `root`'s mailbox from when I double-checked I really can't `sudo`.)

**Comment by mrjbq7** [comment]
Hmm, I can probably give you access, but also -- I think @erg might have fixed it?  I no longer get an error loading https on paste.factorcode.org.

**Comment by bpollack** [comment]
I'm also seeing that @mrjbq7 ; not sure what happened, but we're good now.
