### ISSUE TITLE
get same checksum from coreutils and Factor?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1708]
The checksums generated by `sha*sum`, `md5sum` and other GNU `coreutils` never match those reported by Factor for the same input. 
```
$ echo asd | sha224sum
efe98c238ebc5de4627a57459a1968725336adc611ff25581427fd41  -

$ echo asd | md5sum
e07910a06a086c83ba41827aa00b26ed -
```
Factor says the SHA-224 and MD5 sums of the string "asd" are `cda1d665441ef8120c3d3e82610e74ab0d3b043763784676654d8ef1` and `7815696ecbf1c96e6894b779456d330e`, respectively. Is it possible to get the same input to generate the same output in Factor as `coreutils`?

**Comment by jonenst** [comment]
Hi,
that's because echo adds an extra '\n' character at the end of your string. Try with
```sh
$ # -n suppresses the extra newline char
$ echo -n asd | md5sum
7815696ecbf1c96e6894b779456d330e  -
```
or
```factor
"asd\n" ascii encode md5 checksum-bytes bytes>hex-string print
e07910a06a086c83ba41827aa00b26ed
```

**Comment by catb0t** [comment]
Ah, that part didn't occur to me.

What about this, then?
```
    $ echo *
    a b c
    $ cat *
    file 1
    file 2
    file 3
    $ factor -e=" \ 
    > USING: globs io sequences sorting io.files io.encodings.utf8 ; \ 
    > \"*\" glob natural-sort [ utf8 file-lines ] map concat [ print ] each "
    file 1
    file 2
    file 3
```
The outputs are the same using Factor's glob and the shell's glob. A `diff` on the outputs shows they match exactly.
```
    $ factor -e=" \
    > USING: math.parser checksums checksums.sha globs io sequences sorting io.files io.encodings.utf8 ; \
    > \"*\" glob natural-sort [ utf8 file-lines ] map concat sha-224 checksum-lines bytes>hex-string print "

    0feaf7d5c46b802404760778091ed1312ba82d4206b9f93c35570a1a
    $ cat * | sha224sum
    d1240479399e5a37f8e62e2935a7ac4b9352e41d6274067b27a36101
```
Changing the encoding to `ascii` doesn't change the output, nor does `"\n" join sha-224 checksum-bytes` instead of `checksum-lines`.

**Comment by jonenst** [comment]
I'm guessing it's because '"\n" join' (which is what checksum-lines and
your alternative are using) doesn't add the '\n' char to the last line of
the last file, wherease your file has it and so cat leaves it. That would
be a bug in checksum-lines...

Le 10 sept. 2016 19:52, "cat" <notifications@github.com> a écrit :

Ah, that part didn't occur to me.

What about this, then?

    $ echo *
    a b c
    $ cat *
    file 1
    file 2
    file 3
    $ factor -e=" \
    > USING: globs io sequences sorting io.files io.encodings.utf8 ; \
    > \"*\" glob natural-sort [ utf8 file-lines ] map concat [ print ] each "
    file 1
    file 2
    file 3

The outputs are the same using Factor's glob and the shell's glob. A diff
on the outputs shows they match exactly.

    $ factor -e=" \
    > USING: math.parser checksums checksums.sha globs io sequences
sorting io.files io.encodings.utf8 ; \
    > \"*\" glob natural-sort [ utf8 file-lines ] map concat sha-224
checksum-lines bytes>hex-string print "

    0feaf7d5c46b802404760778091ed1312ba82d4206b9f93c35570a1a
    $ cat * | sha224sum
    d1240479399e5a37f8e62e2935a7ac4b9352e41d6274067b27a36101

Changing the encoding to ascii doesn't change the output, nor does "\n"
join sha-224 checksum-bytes instead of checksum-lines.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/factor/factor/issues/1708#issuecomment-246125679>, or mute
the thread

**Comment by calsioro** [comment]
This code:

```
[
    { "a" "b" "c" } 3 [1,b]
    [ number>string "file " prepend [ write ] curry
      ascii swap with-file-writer ] 2each
    
    "*" glob natural-sort [ utf8 file-lines ] map concat
    [ "\n" append ] map "" join  ! Add newlines between and at the end

    sha-224 checksum-bytes bytes>hex-string print
 ] with-test-directory
```
gives the same hash:
d1240479399e5a37f8e62e2935a7ac4b9352e41d6274067b27a36101

**Comment by catb0t** [comment]
Thank you!

**Comment by catb0t** [comment]
@calsioro and I [were talking](https://chat.stackexchange.com/rooms/45210/conversation-between-cat-and-fede-s) about this and there's at least one bug here, with how `checksum-lines` works, but `cat`, `file-lines` and `file-contents` giving three different lengths is weird too.

**Comment by mrjbq7** [comment]
I'm not sure there is a bug in that, but feel free to give more information. The `cat` program inserts new lines, the `file-lines` word removed them and `file-contents` does not have any extra new lines added.

**Comment by jonenst** [comment]
The cat program does not insert new lines. It just concatenates the contents of the files. Just like ```[ binary file-contents ] map concat```

To me, there are 2 bugs, in checksum-lines:
  - it always uses '\n' and not the OS dependent line ending
  - it doesn't add '\n' to the last line.

**Comment by jonenst** [comment]
Also, regarding the three different lengths you get, "exercism/self-update/self-update.factor" is missing a '\n' char at the end of the last line. That's why you get surprising results. This discussion is also relevant: https://github.com/factor/factor/issues/1546

**Comment by catb0t** [comment]
@jonenst Aha, thank you, now the checksums match!

**Comment by calsioro** [comment]
Now i feel silly, i had it in front of my eyes! If you use `file-contents` you don't need any additional newlines, just concat should work.
This gives the right checksum:
```
[ "*/*.factor" glob natural-sort [
      utf8 file-contents
    ] map concat ] with-exercism-root
sha-224 checksum-bytes bytes>hex-string
```

**Comment by mrjbq7** [comment]
Ahh right @jonest, I was wrong about `cat` (confused by the discussion above). I wonder if we shouldn't just remove `checksum-lines`, or just define it in terms of `\n` (so it doesn't produce different values on different platforms).

**Comment by jonenst** [comment]
Well checksum-lines is already defined in term of ```\n``` in the default implementation (and also in the specialized crc32 implementation)
M: checksum checksum-lines
    [ B{ CHAR: \n } join ] dip checksum-bytes ;

So I guess checksum-lines is fine if it's meant to abstract away the newline differences between platforms. The docs should emphasize this difference.

Also, if checksum-lines was not forgetting the last newline (ie not using join), it would have the advantage that on unix with correct text files, ```file-lines checksum-lines``` would be the same as ```file-contents checksum-bytes```.

**Comment by AlexIljin** [comment]
Why is this issue still open? Is there anything actionable here?

**Comment by AlexIljin** [comment]
@catb0t: with [this PR](https://github.com/factor/factor/pull/1713) you can call CoreUtils directly from Factor using the same `checksums` interface. Native hash implementations are faster than Factor's, so it makes sense to use them if the target file is large enough for the speedup to compensate for the external process startup overhead. In my experiments (on Windows with an SSD drive) the file size threshold for SHA-1 is about 227Mb: larger files will be hashed by `sha1sum.exe` faster than by `openssl-sha1`.

**Comment by catb0t** [comment]
Yeah, you're right, I'll close this.

I saw that PR and it looks really nice! :D
