### ISSUE TITLE
Listener stuck with bad-vocab-name error

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1711]
Start the Listener and type `USE: aoeu/u`. After that you'll get the following error open in a separate window: `Vocab name cannot contain ":/\ "`, and it'll be nearly impossible to type anything in the Listener. The only two workarounds I found are

- to select a piece of the vocab name and press Spacebar, and
- click the Restart Listener in the toolbar.

**Comment by mrjbq7** [comment]
Hah, that is annoying!

**Comment by mrjbq7** [comment]
Fixed in fd801e7946f9ab08723e87440a4b07fac8916c5f.
