### ISSUE TITLE
peg.ebnf error

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1716]
```
USING: peg.ebnf ;
IN: peg-ebnf-error

SYMBOLS: query response ;

EBNF: parse-error-demo
    query/response = "Q " | "R " => [[ "Q " = query response ? ]]
;EBNF
```
In the Listener:

```
IN: scratchpad "R " parse-error-demo .
response
IN: scratchpad "Q " parse-error-demo .
"Q "
```
The last output is expected to be the `query` symbol, but it returns the "Q " string.

**Comment by jonenst** [comment]
You can use parentheses to control the precedence of the operators.
```factor
SYMBOLS: query response ;

EBNF: parse-error-demo
    query/response = ( "Q " | "R " ) => [[ "Q " = query response ? ]]
;EBNF
IN: scratchpad "Q " parse-error-demo .
query
IN: scratchpad "R " parse-error-demo .
response
```

if you look at https://github.com/factor/factor/blob/master/extra/peg/javascript/parser/parser.factor , most of it uses different actions for the different choices, so maybe that's why this precedence was chosen.

**Comment by AlexIljin** [comment]
Ah, that would explain it! Thanks a lot!
