### ISSUE TITLE
Make reader/writer sub-vocabulary an implementation detail

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1728]
It might be nice for encodings where we have readers and writers (like `json.reader` and `json.writer`) for us to merge the reader and writer words (like `>json` and `json>`) to the main `json` vocabulary and make the `json.reader` and `json.writer` vocabularies an implementation detail.  Alternatively, the code they contain could just be merged directly in and deleted so the main vocabulary has both reader and writer code (like `msgpack`).

Vocabularies this might apply to:
- `bson` (``bson.reader``and``bson.writer``)
- `json` (`json.reader` and``json.writer``)
- `xml` (`xml` and `xml.writer`)

This would (like the change to `unicode`) cleanup the typical use-case.

**Comment by catb0t** [comment]
53 files in 19 different top-level vocabularies have to change, aside from the individual `.reader` and `.writer` vocabularies themselves, not to mention countless non-distribution user vocabularies

maybe this should be left to 0.99 final or 1.0?

**Comment by jonenst** [comment]
You mean .100 or .101 ? :)

**Comment by mrjbq7** [comment]
Made this change for ``json`` and ``bson``, closing.
