### ISSUE TITLE
fix for broken factorcode.org example

### ISSUE THREAD

**Issue by cwalston** [factor/factor#1741]
Hi - 
Ran across an errant example on the factorcode.org page that needs updating,
(at least for the  0.98 Factor version, factor-macosx-x86-64-2016-11-02-14-01.dmg):

--------------
USING: inspector io.files.info io.pathnames system tools.files ;

home directory.
home file-system-info free-space>> .
image file-info describe
--------------

Here ``image'' leaves a word; ``file-info'' wants a path. The last line should be:
 
image-path file-info describe

Cheers,
~cw

**Comment by mrjbq7** [comment]
Fixed in bbcd039c6cb4f73a2e0a262eb32a7d100f4aa40b.  But still needs to get refreshed on the actual factorcode.org website.
