### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by trans** [factor/factor#1743]
Evaluating Factor for a project, but I found no library for YAML. Is there one?

**Comment by jonenst** [comment]
There is one : http://docs.factorcode.org/content/article-yaml.html

Feel free to give feedback about it.

**Comment by trans** [comment]
Wow, I am surprised. Form the looks of it, it appears  to be fairly thorough support. The only thing I didn't see, is support for custom tags. e.g. `!foo`.

**Comment by mrjbq7** [comment]
Maybe that could be a separate issue, if you need it.
