### ISSUE TITLE
libudis86.dll for 32-bit platform is missing from downloads.factorcode.org/dlls

### ISSUE THREAD

**Issue by alex-ilin** [factor/factor#1750]
I have compiled both 32-bit and 64-bit DLLs from v1.7.2 sources found [here](https://github.com/vmt/udis86).

Here's the [download link](https://yadi.sk/d/pIOudMorzTkPY) for the binaries. I have minimally tested both 32- and 64-bit versions, and they at least produce the expected output from the tiny code sample that I fed them. My 64-bit version is smaller than the one currently found at our download site, possibly due to Release vs. Debug build.

Please, put both files in http://downloads.factorcode.org/dlls/.

**Comment by bjourne** [comment]
Hard for you to know, but it links to the wrong C library "msvcr100.dll". It's a redistributable dll shipped with vs2010 and you're supposed to bundle it with the program you are shipping. So it is probably better if you recompile with vs2013 which will cause the dlls to link against "msvcr120.dll" which we already have other dlls that link to. 

Even better is to link to "msvcrt.dll" which is shipped with Windows itself, so you don't need to add anything extra, but modern versions of VS doesn't let you do that.

**Comment by bjourne** [comment]
How did this issue go? Did you or @bpollack get a 32bit build of the library?

**Comment by AlexIljin** [comment]
I did create the 32-bit build of the library, as seen in the download link.
I currently have access to VS2005 and VS2015. I have no idea how to link against the `"msvcrt.dll" which is shipped with Windows itself`, because I'm not a hardcore C user. I have no access to VS2013.
I could give it another try if someone guided me through the process.

**Comment by bjourne** [comment]
Ok. So then we also need a suitable C runtime for the `libudis86.dll` you built. That means you need to locate the 32bit `msvcr100.dll` file on your computer and add that to the zip file. Then we can add it to the dll directory.

Or you could recompile libudis86 32bit version with Visual Studio 2015, but then you would need to add that compiler's C runtime. I don't know exactly what it is called, but it should be something like `msvcr1XX.dll`. You can check with the depends.exe tool: http://www.dependencywalker.com/

**Comment by erg** [comment]
Where are we at with this?

**Comment by alex-ilin** [comment]
If the 32-bit DLL is in the folder, then this issue can be closed.
I have no more 32-bit PCs to maintain, so I'm not interested in this anymore.
In fact, I can close it myself, since I opened it.
