### ISSUE TITLE
Difference between mirror clear-assoc and delete-at

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1757]
I just noticed that in the ``mirrors`` vocabulary, the``M\ mirror delete-at`` sets a slot to ``f``:

```factor
M: mirror delete-at ( key mirror -- )
    [ f ] 2dip set-at ;
```

But  the ``M\ mirror clear-assoc`` sets the slot to its initial value:

```factor
M: mirror clear-assoc ( mirror -- )
    [ object-slots ] [ object>> ] bi '[
        [ initial>> ] [ offset>> _ swap set-slot ] bi
    ] each ;
```

Probably those should be consistent?

**Comment by mrjbq7** [comment]
```factor
IN: scratchpad TUPLE: foo { a integer initial: 12 } ;

IN: scratchpad T{ foo f 2 } dup make-mirror clear-assoc a>> .
12

IN: scratchpad T{ foo f 2 } "a" over make-mirror delete-at a>> .
Bad store to specialized slot
value f
class integer

Type :help for debugging help.
```

**Comment by mrjbq7** [comment]
It also looks like ``M\ mirror clear-assoc`` doesn't respect read-only slots:

```factor
IN: scratchpad TUPLE: foo { a integer initial: 12 read-only } ;

IN: scratchpad T{ foo f 15 } dup make-mirror clear-assoc a>> .
12
```

**Comment by bjourne** [comment]
Imho, it would be better if `clear-assoc` and `delete-at` threw errors. They don't make sense because you can't remove slots from tuples. Its analogous to how you can't resize arrays -- you can't (or shouldn't be able to) resize mirrors.

**Comment by mrjbq7** [comment]
You mean better if those words did not work and mirrors were effectively read-only?

**Comment by jonenst** [comment]
Mirrors wouldn't be read-only, you would still be able to modify the value of slots with set-at. I agree with @bjourne, clear-assoc and delete-at should throw for mirrors.
