### ISSUE TITLE
Open Url in Context Menu Throws an Error

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1759]
**Steps to reproduce:**
- `USE: urls URL" http://google.com"`;
- right-click on the url object in the listener's Data stack;
- select `Open Url` in the context menu.

**Expected:**
The URL is opened in the default browser.
**Actual:**
```
Generic word absolute-path does not define a method for the url class.
Dispatching on object: URL" http://google.com/"
```

**Comment by catb0t** [comment]
We have a `webbrowser` vocab with an `open-url` word yet this is trying to open it as a `file:///`, interesting.

**Comment by mrjbq7** [comment]
Looks like a regression with `webbrowser.windows`.  It should be pretty easy to just do absolute-path when not a URL.  Maybe a little cleanup is in order also.

**Comment by bjourne** [comment]
Looks like it was me. I added `absolute-path` to make the word handle relative paths. Should be fixed now.

**Comment by mrjbq7** [comment]
@AlexIljin can you check if this is fixed for you?  If so will close.

**Comment by AlexIljin** [comment]
OK, I'll check. 24.12.2016, 21:17, "John Benediktsson" <notifications@github.com>:@AlexIljin can you check if this is fixed for you? If so will close.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.   ---=====---Александр

**Comment by AlexIljin** [comment]
Trying to reload all vocabs from the current master, I see some error:

```
resource:basis/compiler/compiler.factor

3: USING: accessors assocs classes classes.algebra combinators
6: compiler.cfg.optimizer compiler.codegen compiler.crossref
                                                            ^
No suitable arithmetic method
left    f
right   f
generic >=
```

I guess it'll take some time.

**Comment by AlexIljin** [comment]
Yes, it's fixed now. Thanks to @bjourne!

**Comment by mrjbq7** [comment]
Hmm, if it's been a long time since you updated that might have an issue with reload.  You could try bootstrapping again using `build.cmd`.

**Comment by AlexIljin** [comment]
@mrjbq7: thanks, but in this case it was faster to download the latest nightly.
