### ISSUE TITLE
unnecessary untagging of fixnums for bit-count

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1764]
I noticed that bit-count untags the input (sar rax 0x4) but it doesn't need to:
```factor
[ { array-capacity } declare bit-count ] disassemble
```

```
00007f4f7acd06d6: 498b06        mov rax, [r14]
00007f4f7acd06d9: 48c1f804      sar rax, 0x4
00007f4f7acd06dd: f3480fb8c0    popcnt rax, rax
00007f4f7acd06e2: 48c1e004      shl rax, 0x4
00007f4f7acd06e6: 498906        mov [r14], rax
00007f4f7acd06ef: c3            ret
```

I tried to fixed it with the following patch but I don't know the compiler enough to know if that's the correct way to do it. What do you think @bjourne, I think you are the one who spent the most time working on the compiler recently?
```diff
diff --git a/basis/compiler/cfg/representations/peephole/peephole.factor b/basis/compiler/cfg/representations/peephole/peephole.factor
index f505cb7..a165a37 100644
--- a/basis/compiler/cfg/representations/peephole/peephole.factor
+++ b/basis/compiler/cfg/representations/peephole/peephole.factor
@@ -281,3 +281,12 @@ M: ##not optimize-insn
         }
         [ call-next-method ]
     } cond ;
+
+M: ##bit-count optimize-insn
+    {
+        { [ dup src>> rep-of tagged-rep? ] [
+            [ no-use-conversion ]
+            [ finish ]
+            [ emit-def-conversion ] tri ] }
+        [ call-next-method ]
+    } cond ;
```

After this patch, I get the correct assembly:
```
00007f4f7ad1a6a6: 498b06        mov rax, [r14]
00007f4f7ad1a6a9: f3480fb8c0    popcnt rax, rax
00007f4f7ad1a6ae: 48c1e004      shl rax, 0x4
00007f4f7ad1a6b2: 498906        mov [r14], rax
```

Jon

**Comment by bjourne** [comment]
Looks very good! Though perhaps there could be a problem if `src>>` has tagged-rep and `dst>>` has int-rep? I'm not sure if that situation could ever happen in practice, but to be safe it could be better to use `dup inert-tag/untag-unary?` for the test. Otherwise I can't see any problem, looks like a good optimization with no possible bad side-effects.

**Comment by jonenst** [comment]
Hi @bjourne, I thought about this and I didn't reach the same conclusion as you. Please correct me if I'm wrong. In the case where dst>> has int-rep?, I think we should still skip the src untagging. See the following 4 snippets. In the second one, if we only do the optimization when inert-tag/untag-unary?, we would get an extra sar before popcnt (I tested and it's indeed there). So ```dup src>> rep-of tagged-rep?``` is better ?


```
[ { array-capacity } declare bit-count ] disassemble
00007fced0d0a056: 498b06        mov rax, [r14]
00007fced0d0a059: f3480fb8c0    popcnt rax, rax
00007fced0d0a05e: 48c1e004      shl rax, 0x4
00007fced0d0a062: 498906        mov [r14], rax
```

```
[ { array-capacity } declare bit-count { array-capacity } declare 1 + ] disassemble
00007fced0dfaab6: 498b06        mov rax, [r14]
00007fced0dfaab9: f3480fb8c0    popcnt rax, rax
00007fced0dfaabe: 48ffc0        inc rax
00007fced0dfaac1: 48c1e004      shl rax, 0x4
00007fced0dfaac5: 498906        mov [r14], rax
```

```
 [ { array-capacity } declare 1 + bit-count ] disassemble
00007fced0e1e256: 498b06        mov rax, [r14]
00007fced0e1e259: 48c1f804      sar rax, 0x4
00007fced0e1e25d: 48ffc0        inc rax
00007fced0e1e260: f3480fb8c0    popcnt rax, rax
00007fced0e1e265: 48c1e004      shl rax, 0x4
00007fced0e1e269: 498906        mov [r14], rax
```

```
 [ { array-capacity } declare 1 +  bit-count
  { array-capacity } declare 1 + ] disassemble
00007fced0e1d6c6: 498b06        mov rax, [r14]
00007fced0e1d6c9: 48c1f804      sar rax, 0x4
00007fced0e1d6cd: 48ffc0        inc rax
00007fced0e1d6d0: f3480fb8c0    popcnt rax, rax
00007fced0e1d6d5: 48ffc0        inc rax
00007fced0e1d6d8: 48c1e004      shl rax, 0x4
00007fced0e1d6dc: 498906        mov [r14], rax
```

Also, I'm not sure if checks are needed at all to default back to the base method. Why not simply do this ?
```factor
M: ##bit-count optimize-insn
    [ no-use-conversion ] [ finish ] [ emit-def-conversion ] tri ;
```
That's because the base method is:
```factor
 ##bit-count \ optimize-insn next-method see

M: vreg-insn optimize-insn
    [ emit-use-conversion ] [ finish ] [ emit-def-conversion ] tri ;
```

Do you want me to make a PR with this patch ?

**Comment by bjourne** [comment]
Hm, you're right it wont insert a redundant representation as I thought. So it looks good!

**Comment by jonenst** [comment]
Looking at
M: fixnum (bit-count)
    fixnum-bit-count { fixnum } declare ; inline

Is it possible to better declare the interval here ? Something like what you did with array-capacity ? Is it possible to do it inline, something like ```cell-bits tag-bits get 1 + - declare-max-bound``` ?

Also, I'm looking at ways to test this

**Comment by mrjbq7** [comment]
Doesn't ``fixnum`` already do that?  Or are you trying to declare the interval of the output?

**Comment by jonenst** [comment]
Yes declaring the interval of the ouput to be 0-27 on 32bits and 0-59 on 64bits. This way more stuff can be optimized after the call to bit-count (like tests for > 100 and dead code removal for example, or overflow checks elimination)

**Comment by jonenst** [comment]
Oh there's fixnum-bits, so it's fixnum-bits 1 -

**Comment by bjourne** [comment]
Easiest is probably to set the "outputs" property on `fixnum-bit-count`. Look at how the `tag` word does it.

**Comment by jonenst** [comment]
So I added tests and membership to the peephole-optimisable? union in #1771
