### ISSUE TITLE
math.ranges [1,b] on mac 0.97 produces declaration error

### ISSUE THREAD

**Issue by roachmd** [factor/factor#1768]
Interesting Observation. At least I don't know why
factor-macosx-x86-64-0.97

`1 100 [a,b] 0 [ + ] reduce .`
`5050`

`100 [1,b) 0 [ + ] reduce .`
`4950`

`100 [1,b] 0 [ + ] reduce .`

<Listener input>

Asset: [1,b]

Stack effect declaration is wrong
inferred ( -- )
declared ( 1 100 -- range )

`100 [0,b] 0 [ + ] reduce .`
`5050﻿`

**Comment by mrjbq7** [comment]
Hmm, I can't reproduce on 0.97:

```factor
: foo ( -- )
    1 100 [a,b] 0 [ + ] reduce .
    100 [1,b) 0 [ + ] reduce .
    100 [0,b] 0 [ + ] reduce .
    100 [1,b] 0 [ + ] reduce . ;
```

Can you explain a bit more how you got that error?

Thanks,
John.

**Comment by roachmd** [comment]
Okay, I was working through some exercises from 7 languages in 7 days. Using clear, then restart listener. I got the same error. 

But, today I restarted the whole UI and It works as expected. So now I can't reproduce.

**Comment by mrjbq7** [comment]
Okay, well if you notice it again, please let us know!

Also, welcome and if we can help in anyway with your exercises, or any project you try and do with Factor, let us know that too!

**Comment by mrjbq7** [comment]
P.S., their fizzbuzz gets a little complicated, don't let that scare you away.  Hah.

**Comment by roachmd** [comment]
Thank you....I'm enjoying the language thus far.  Feels far more natural to me.

**Comment by mrjbq7** [comment]
Shameless self-promotion: I have over 200 random but sometimes useful blog posts about Factor here:

https://re-factor.blogspot.com/

**Comment by roachmd** [comment]
HA,  I've been to that site. Excellent examples.
