### ISSUE TITLE
OpenGL graphics bugs

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1787]
The bunny model looks weird when rendered with the Nvidia 367 driver on Ubuntu Linux 16.04. Ran with `./factor -run=bunny`. See the screenshot. 
![bad-bunny](https://cloud.githubusercontent.com/assets/142475/22419660/d2720c88-e6de-11e6-9140-6f6c3ab475ec.png)

**Comment by erg** [comment]
@bjourne How does it look now, after #1881 or #1859?

**Comment by catb0t** [comment]
Nvidia 384 driver on Ubuntu 17.10 

![screenshot from 2018-01-04 14-23-17](https://user-images.githubusercontent.com/3238748/34580503-473a4df0-f15b-11e7-92f3-67665764bf52.png)

**Comment by mrjbq7** [comment]
I think fixed, closing.  Thanks!
