### ISSUE TITLE
cannot start factor in Xmonad (tiling window manager)

### ISSUE THREAD

**Issue by listx** [factor/factor#1801]
I compiled the latest master HEAD 30f73d63f4 in Ubuntu Xenial 64-bit with `./build.sh update` . When I run `./factor` the Factor window appears to instantiate and then destroy itself constantly, resulting in the window taking up space, then no space, taking up space again, etc ad nauseam. This results in a rapidly "flashing" area that becomes unusable because window focus does not stay on the factor window.

Does anyone use Factor with a tiling window manager?

**Comment by jonenst** [comment]
Hi, this is probably unrelated to the window manager (I sometimes use
i3wm). You get the same thing on "regular" window managers when the wrong
libGL.so is loaded.

So I launch factor with
LD_LIBRARY_PATH=/usr/lib/fglrx ./factor

This is for the ATI proprietary drivers. Use the correct path for nvidia
drivers.

Does it help?
Cheers

**Comment by listx** [comment]
Wow, your trick did it for me! I am on Nvidia drivers, so I did

```
LD_LIBRARY_PATH=/usr/lib/nvidia-364 ./factor
```

I discovered the correct path by looking at `/etc/ld.so.conf.d` and then doing `cat x86_64-linux-gnu_GL.conf` (that file looked most pertinent to the problem`.

**Comment by mrjbq7** [comment]
It would be nice to get this fixed.

We link to ``libGL.so``, which seems maybe to be the wrong one on some Linux installations.

**Comment by listx** [comment]
I am satisfied for now with the workaround, but feel free to reopen this issue.
