### ISSUE TITLE
emacsclient not working when server was started as daemon

### ISSUE THREAD

**Issue by timor** [factor/factor#1808]
On my system, the emacs server is started as a systemd service using `--daemon`.

If I run `emacsclient` normally, it will open a terminal version, so if started from a window, nothing will appear.  This seems to apply to factor, too.  For these cases, there is `emacsclient -c`, which will actually open a new frame in the window manager.

Is there a way to tell factor to call emacsclient with "-c" as a command line switch?

**Comment by mrjbq7** [comment]
You can see the command line that we use here:

https://github.com/factor/factor/blob/master/basis/editors/emacs/emacs.factor#L22

If you want to modify it, you could either modify the sources yourself, or in your ``.factor-rc`` file, define your own override of ``M\ emacsclient editor-command``, something like this:

```factor
USING: editors editors.emacs kernel make math.parser namespaces
sequences ;

M: emacsclient editor-command ( file line -- command )
    [
        emacsclient-path get [ find-emacsclient ] unless* ,
        "-a=emacs" ,
        "-c" ,
        "--no-wait" ,
        number>string "+" prepend ,
        ,
    ] { } make ;
```

If this is a really useful feature, we could merge some kind of support for customizing the emacs command line, like an ``emacsargs`` symbol, then we could just do:

```diff
diff --git a/basis/editors/emacs/emacs.factor b/basis/editors/emacs/emacs.factor
index f2d2240cf7..a565bfb54a 100644
--- a/basis/editors/emacs/emacs.factor
+++ b/basis/editors/emacs/emacs.factor
@@ -19,11 +19,14 @@ M: windows find-emacsclient
         [ "emacsclient.exe" ]
     } 0|| ;
 
+SYMBOL: emacsclient-args
+
 M: emacsclient editor-command ( file line -- command )
     [
         emacsclient-path get [ find-emacsclient ] unless* ,
         "-a=emacs" ,
         "--no-wait" ,
+        emacsclient-args get %
         number>string "+" prepend ,
         ,
     ] { } make ;
```

And then in your ``.factor-rc``, we could just do:

```factor
USING: editors.emacs namespaces ;

{ "-c" } emacsclient-args set-global
```

**Comment by timor** [comment]
I'll go with the second route, since I don't want to change this for every user.  Thank you.

**Comment by timor** [comment]
Oh the first approach is also per user.  Nevermind.

**Comment by mrjbq7** [comment]
Well, if you want this for all users, you can either make this change in the Factor image and `save` it, or put that in your `.factor-boot-rc` And it will get baked into the image when you bootstrap. 

I might have other suggestions if I understood what environment you were hoping to do this in.  

We have made much improvement but the shared image files don't make it easy to share a factor installation between users. We almost have that fixed but it's still got a few things left.

**Comment by timor** [comment]
As for the environment, there should be nothing special about it except for emacs running as a daemon already.  Any .factor-rc approach sounds correct to me.  I patched our installation with your emacsclient-args approach, and it seems to be working fine. The emacs daemon runs as a systemd user service, so it should be a per-user configuration.

Btw, is there support for something like a site-start initialization file? That way, a distribution can easily set some system-specific defaults without having to recompile an image.

**Comment by mrjbq7** [comment]
You mean like a global `.factor-rc`?  Not currently. The closest we get is a '`.factor-boot-rc` that modifies the image at bootstrap-time. But if you operate from a binary release that file isn't loaded.

**Comment by mrjbq7** [comment]
P.S. I implemented the ``emacsclient-args`` patch so if you ``./build.sh update`` or download a nightly build, you'll get that without needing to patch your local installation.

0fd663e25ddc2f802ee887011813ba6af6e8fa47

It will be in the 0.98 release that we hope to make in the next few weeks.

**Comment by timor** [comment]
@mrjbq7: I closed the task because I noticed the commit and installed the latest build already.  :)

Thanks a lot.
