### ISSUE TITLE
group-all-by

### ISSUE THREAD

**Issue by nicolas-p** [factor/factor#1809]
The `toolz` package for Python [defines](http://toolz.readthedocs.io/en/latest/api.html#toolz.itertoolz.groupby) a `groupby` function:

```python
>>> names = ['Alice', 'Bob', 'Charlie', 'Dan', 'Edith', 'Frank']
>>> groupby(len, names)  
{3: ['Bob', 'Dan'], 5: ['Alice', 'Edith', 'Frank'], 7: ['Charlie']}
```

The same in Factor gives:
```factor
{ "Alice" "Bob" "Charlie" "Dan" "Edith" "Frank" } [ length ] group-by .
V{
    { 5 V{ "Alice" } }
    { 3 V{ "Bob" } }
    { 7 V{ "Charlie" } }
    { 3 V{ "Dan" } }
    { 5 V{ "Edith" "Frank" } }
}
```

I would like a word that behaves like the Python version.
The first implementation that comes to mind:
```factor
: group-all-by ( seq quot: ( elt -- key ) -- groups )
    [ sort-with ] [ group-by ] bi ; inline
```
```factor
{ "Alice" "Bob" "Charlie" "Dan" "Edith" "Frank" } [ length ] group-all-by .
V{
    { 3 V{ "Bob" "Dan" } }
    { 5 V{ "Alice" "Edith" "Frank" } }
    { 7 V{ "Charlie" } }
}
```
But there might be a better way.

**Comment by mrjbq7** [comment]
You want ``collect-by`` in ``assocs``.  (It used to be in ``math.statistics`` in 0.97):

```factor
{ "Alice" "Bob" "Charlie" "Dan" "Edith" "Frank" } [ length ] collect-by .
H{
    { 3 V{ "Bob" "Dan" } }
    { 5 V{ "Alice" "Edith" "Frank" } }
    { 7 V{ "Charlie" } }
}
```

I like the ``group-by`` name better but kept the old name for (better) compatibility.

In ``grouping.extras``, I'm not sure why @bjourne chose to keep it order-preserving, but maybe because he needed it and we already had ``collect-by``.

**Comment by nicolas-p** [comment]
Glad to see that it already exists. I spent an hour looking for this word and couldn't find it.

**Comment by mrjbq7** [comment]
Hmm, we need better search then!

**Comment by mrjbq7** [comment]
Or maybe we should move that word somewhere else.

**Comment by nicolas-p** [comment]
A useful feature would be search by stack effect.

I would be able to type `( seq quot -- assoc )` in the search bar and it would give me all the words that match this effect.

**Comment by mrjbq7** [comment]
Something like this maybe:

```factor
: effect-in-names ( effect -- names )
    in>> [ dup pair? [ first ] when ] map ;

: effect-out-names ( effect -- names )
    out>> [ dup pair? [ first ] when ] map ;

: effect-names ( effect -- {in,out} )
    [ effect-in-names ] [ effect-out-names ] bi 2array ;

: search-for-effect ( effect -- words )
    effect-names all-words [ stack-effect effect-names = ] with filter ;
```

Then...

```factor
IN: scratchpad ( seq quot -- assoc ) search-for-effect .
{ collect-by }
```

**Comment by nicolas-p** [comment]
Very good! Then the next step would be to integrate this in the search bar.

**Comment by bjourne** [comment]
Originally I wrote the `group-by` word order-preserving to make it work well with the utf7-decoder. Admittedly, most of the time, the order-preserving of that word just gets in your way. I wouldn't mind if the `collect-by` word was renamed to `group-by` and the group by word renamed to `group-by-ordered` or something.
