### ISSUE TITLE
GTK Linux drag fails sometimes

### ISSUE THREAD

**Issue by erg** [factor/factor#181]
If you grab the bottom right corner in different places, sometimes your grab will end up with the resize-mouse-cursor but the window will not resize. In such a case, you can move the mouse around and see various elements in the Factor UI come into focus away from the mouse cursor. The offset from the mouse seems to be the width/height of the window itself.

**Comment by bjourne** [comment]
It works fairly well now, doesn't it? That it didn't work before can have been a bug in Unity that they have fixed.
