### ISSUE TITLE
factorcode.org is down

### ISSUE THREAD

**Issue by linkmonitor** [factor/factor#1810]
I get an ERR_CONNECTION_REFUSED error when trying to visit factorcode.org.

**Comment by mrjbq7** [comment]
Looks like something related to SSL caused a memory fault. It's back up and running now, but we should try and figure out what happened.  @bjourne @bpollack @erg

**Comment by bpollack** [comment]
@mrjbq7 Do you have any logs I can look at?

**Comment by erg** [comment]
@bpollack The ``SSL`` struct is way too outdated. I tried to make a patch but had to revert it.

dup of #1860
