### ISSUE TITLE
factorcode.org SSL cert expired

### ISSUE THREAD

**Issue by winny-** [factor/factor#1815]
Hi, I was browsing programming languages on GitHub and noticed factorcode.org's SSL cert just expired:

```
factorcode.org uses an invalid security certificate. The certificate expired on March 22, 2017 at 2:38 PM. The current time is May 22, 2017 at 10:22 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE 
```

(timezone America/Chicago)

**Comment by erg** [comment]
I can fix this soon. We should support the ACME protocol to automate it.

**Comment by joewreschnig** [comment]
We're trying to [remove unauthenticated URLs from the MELPA Emacs package archive](https://github.com/melpa/melpa/issues/3004), and Fuel is one of the packages still using raw git://.

Is there anything I can do to help move this along? I have some experience setting up certbot and acme-tiny (I recommend certbot if possible), but none with the Factor web server.

**Comment by mrjbq7** [comment]
What about https with github?

**Comment by joewreschnig** [comment]
How is GitHub syncing with the official repo?

**Comment by mrjbq7** [comment]
We use a script to mirror from Factorcode to GitHub.  So technically Github is just a mirror but we do our issue development and discussions on Github but keep our primary git on Factorcode.

We can also just fix the SSL cert issue and the you can use the primary repo.

**Comment by joewreschnig** [comment]
What I mean is, does the script run on Factorcode and push directly to GitHub, or does it run somewhere else and pull from Factorcode, then push that to GitHub? In the first case it's a secure channel (Factorcode's local files are authoritative, GitHub is authenticated) but in the second case it's not (Factorcode neither authoritative nor authenticated).

**Comment by mrjbq7** [comment]
It runs on Factorcode under a secure user and syncs. But it's okay whatever you need can be accommodated.

**Comment by erg** [comment]
Fixed. Someone please implement ACME!

**Comment by bpollack** [comment]
Need more time, @erg. I'm trying to get there. :)
