### ISSUE TITLE
rename index -> subseq-index, index-from -> subseq-index-from

### ISSUE THREAD

**Issue by erg** [factor/factor#1826]
Like ``start``, ``index`` is pretty vague.

**Comment by mrjbq7** [comment]
It's not a subseq

**Comment by erg** [comment]
Maybe ``find-object`` and ``find-object-from``?

**Comment by mrjbq7** [comment]
Hmm, I'm not opposed to index it's `indexOf` in a lot of other languages.

**Comment by catb0t** [comment]
Python uses `iterable.index` as well, like `str.index` and `list.index`, and I don't think it's particularly vague in Factor or Python.

**Comment by erg** [comment]
Ok! Good as is :D
