### ISSUE TITLE
Fresh bootstrap brings Nvidia Linux x64 to its knees 

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1827]
I just bootstrapped the latest version on a Linux x64 system with proprietary Nvidia drivers, and Factor just hangs and makes my system unusable.

I had never tried it with an Nvidia system before but it runs fine on lots of Linux x64 machines. I'm guessing if I install the open source `nouveau` drivers it will work?

**Comment by mrjbq7** [comment]
I wonder if this is the issue choosing the right GL drivers.

**Comment by catb0t** [comment]
This system doesn't have an intel GPU as well, if that makes a difference.

**Comment by erg** [comment]
This is a dup of some other issues. We have to fix the driver order...

You can do ``ldconfig -p`` and symlink your nvidia driver in front of the mesa one.

**Comment by catb0t** [comment]
@erg I searched for `nvidia` but I didn't find anything this would be a duplicate of since those are all crashes but Factor itself actually runs. Sorry ):

**Comment by catb0t** [comment]
By the way, what do you mean,

> symlink your nvidia driver in front of the mesa one
? 

```
$ ldconfig -p | grep mesa
$ 
```

I installed all the Factor deps but I don't use a mesa driver. Isn't that for Intel?

**Comment by erg** [comment]
I just added a bunch more tags and issues are incompletely tagged.

https://github.com/factor/factor/issues/1693
https://github.com/factor/factor/issues/1456

Not sure if this is exactly a dup of thse.

**Comment by erg** [comment]
``ldconfig -p | grep libGL.so``

I think it uses the first one in the list. The ``libglext-dev`` package that installs mesa I think.

**Comment by catb0t** [comment]
Here's what I have in that case:

```
$ ldconfig -p | grep libGL.so
	libGL.so.1 (libc6,x86-64) => /usr/lib/nvidia-381/libGL.so.1
	libGL.so.1 (libc6) => /usr/lib32/nvidia-381/libGL.so.1
	libGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so
	libGL.so (libc6,x86-64) => /usr/lib/nvidia-381/libGL.so
	libGL.so (libc6) => /usr/lib32/nvidia-381/libGL.so

```

Should I make Factor try to use libGL.so instead of libGL.so.1? How do I do that?

**Comment by mrjbq7** [comment]
https://github.com/factor/factor/blob/master/basis/opengl/gl/gl.factor

Look for libGL.so and change to libGL.so.1 and refresh-all and save.

**Comment by catb0t** [comment]
Does Factor still use OpenGL on Windows? Because it builds and runs fine on the same machine, on Windows, with Nvidia graphics. I guess it's a bug in the driver?

**Comment by mrjbq7** [comment]
Yes it uses OpenGL on all platforms. Maybe a bug with nvidia drivers with how we use it? A separate discussion on macOS about using OpenGL 3.2 core mode instead of compatibility mode.

**Comment by catb0t** [comment]
Changing `"gl" "libGL.so" cdecl add-library` to `"gl" "libGL.so.1" cdecl add-library` and running `factor -e="refresh-all save"` fixed it, thanks! Just need to remember to do that after updating Factor.

The following packages provide the following libraries:

```
$ ldconfig -p | grep 'libgl\.so' -i  | cut -f2 -d'>' | xargs dpkg -S 
nvidia-381: /usr/lib/nvidia-381/libGL.so.1
nvidia-381: /usr/lib32/nvidia-381/libGL.so.1
libgl1-mesa-dev:amd64: /usr/lib/x86_64-linux-gnu/libGL.so
nvidia-381: /usr/lib/nvidia-381/libGL.so
nvidia-381: /usr/lib32/nvidia-381/libGL.so
```

I guess the question for the fix becomes, how to ensure that on Nvidia systems `libmesa`'s `libGL.so` is preferred? What about changing `libGL.so.1` to `libGL.so` as the default?

**Comment by catb0t** [comment]
> erg added the [knees] label 5 days ago

i'm glad we can classify the really important things around here :D

**Comment by bjourne** [comment]
Why did we stop using find-library here? I know we had a discussion about it, but I forgot it.

**Comment by mrjbq7** [comment]
@bjourne three reasons I think:

1) Because we weren't sure ``find-library`` returned the correct value on all platforms.

2) Because we needed to make sure ``update-library`` is called in a startup hook in case the path changes from run to run.

3) Because I was hoping we could find a DLL name that would "just work" through the normal ``dlopen`` system calls...

**Comment by bjourne** [comment]
I wonder if we can't make find-library work by returning the filename of the library? Right now, it returns the absolute path which is wrong.

**Comment by mrjbq7** [comment]
Well finding the absolute path is useful too, I modeled this after a python utility similarly named.

**Comment by erg** [comment]
I think this is fixed.

**Comment by catb0t** [comment]
The box I originally produced this bug on isn't working right now, but when I fix it I'll let you know if it's still an issue!

**Comment by catb0t** [comment]
happy to say i haven't seen any problems with this now that I've got the Nvidia machine working!
