### ISSUE TITLE
32-bit - Y U Crash?

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1828]
Hello!

  I have created the following vocab:

```
USING: arrays checksums checksums.openssl kernel sequences ;
IN: crash-factor

: 1hash ( bytes -- hash ) openssl-sha1 checksum-bytes ;
: 5hash ( bytes -- h h h h h ) 1hash dup 1hash dup 1hash dup 1hash dup 1hash ;
: hashes ( seed -- seed' seq ) 300000 iota [ drop 5hash [ 4array ] dip swap ] map ;
: crash ( -- h h h h h h ) B{ } hashes swap hashes swap hashes swap hashes swap hashes ;
```

To run it, use: `USE: crash-factor crash`.

I'd like someone to tell me why does it crash the 32-bit build of Factor. Is it simply memory exhaustion, or is it something else?

The code was developed to reproduce a crash that was happening with much smaller memory load, but involving reading about 300'000 records from an SQLite DB twice (always good the first time, always crash the second). With this code I see that the Factor.exe process uses about 500Mb of memory at the time of the crash. It's about a quarter of the way to its theoretical limit for the 32-bit build. That's why I suspect GC issues or at least some fixable error of some kind.

I have tried to debug the app, but had little success. Despite having no VS2015 solution file in the Git repository, I managed to create a 32-bit debug build, and crash it with the vocab from under VS2015, but I see nothing useful I can do with it. First it throws a whole lot of `factor::must_start_gc_again` exceptions (which I think is a normal way it operates), then it says "factor.exe has triggered a breakpoint" while pointing at line 590 of the slot_visitor.hpp (again, many times - and I didn't set any breakpoints in VS), and then I see a lot of the following messages:

```
Debug Error!

Program: C:\Programs\Dev\factor.git\Debug\factor.exe

abort() has been called
```

And "The program '[10932] factor.exe' has exited with code 3 (0x3)." at the end.

Maybe I misunderstand, but it looks like debugging fails to be useful in this case, especially with the breakpoint nonsense, and the unclear reason for abort(). I was hoping to see some "OutOfMemory" or "AccessViolation" exception immediately before the termination, but no such luck. Could someone try my vocab and see if it crashes?

I have so far reproduced the crash of the 32-bit Factor build (but not 64-bit Factor) on two PCs: Win XP 32-bit, and Win 8.1 64-bit.

Edit: corrected from "VS 2016" to "VS 2015".

**Comment by mrjbq7** [comment]
Hmm, 0x3 is file path not found in some windows error codes, no? Or maybe it's different if an `errno`?

**Comment by AlexIljin** [comment]
In this case it's whatever the executable returned as its exit code.

**Comment by catb0t** [comment]
On my Linux x64, the `crash` word with 300k takes about 15 seconds, and uses at most 20% CPU and 1% of memory.

On the same box but with the 32-bit Factor build, and using `sha1` instead of trying to install the 32-bit `libopenssl.so`, it takes 15 seconds to do `3000` instead, and 30k is 2 minutes and 6 seconds.

The 300k version will take more than 20 minutes possibly but I'm just waiting on it to return -- it does not appear to be hanging. 

I don't have access to a Mac box but I'll try my own Windows machines later.

**Comment by catb0t** [comment]
300k took 21 minutes, as I predicted. This box has a 2.2 GHz CPU but I don't know what that scales to when the bus and caches are truncated to 32 bits.

Is it possible it's something in your environment that's affecting it? Running it through VS, even in Release mode, could have an effect. Have you tried running it in standalone 32 bit Factor?

**Comment by AlexIljin** [comment]
@catb0t: yes, standalone Factor crashes for me on both machines I mentioned. That's what prompted me to try it under VS. Otherwise I never would have tried to use VS.

The native `sha1` implementation is very slow, that's why I recommend using `openssl-sha1`, which only takes seconds to do the same work. The point of the work is only to generate many objects with bits of data in them, to fill up the memory, which triggers the crash.

The following code works equally well to generate the same amount of data and crash Factor x32, although not as fast as `openssl-sha1`:

```
USING: arrays kernel random sequences ;
IN: crash-factor

: 1hash ( bytes -- hash ) length random-bytes ;
: 5hash ( bytes -- h h h h h ) 1hash dup 1hash dup 1hash dup 1hash dup 1hash ;
: hashes ( seed -- seed' seq ) 300000 <iota> [ drop 5hash [ 4array ] dip swap ] map ;
: crash ( -- h h h h h h ) 40 random-bytes hashes swap hashes swap hashes swap hashes swap hashes ;
```

Tested and crashed just now on the freshly downloaded and clean copy of "Factor 0.98 x86.32 (1842, heads/master-acffb259f7, Sat Jun  3 02:15:25 2017)
[Microsoft Visual C++ 190023506] on windows"

Using the same fresh build I came up with a much simpler code to reproduce the issue. Hopefully, it's the same issue, and not a different one. The crash is generic, and looks no different. Just run this: `USE: byte-arrays 10 [ 1024 1024 50 * * <byte-array> ] times`. The code tries to allocate 500 Mb worth of `byte-array`s. Memory use for Factor.exe shows about 537 Mb at the time of the crash.
Trying to go `9 [ ... ] times` doesn't crash, but you may possibly encounter different results. Try to go as high as `30 [ ... ] times` if it doesn't crash on your system (that'll allocate 1.5 Gb of arrays).

500 Mb of user data is way lower than the 2 Gb that should be available to the 32-bit app, so I consider it a bug. Possibly there is an error in the memory management math somewhere. What do you say? Let me know what you think in the comments below, leave a "like" and subscribe to my channel, and, as always, stay awesome, bros!

**Comment by catb0t** [comment]
Oh, that snippet is weird. In 32-bit mode on Windows, I get "factor.exe has stopped working" immediately after running it and then Factor does crash, right away. With x64, it runs fine in a couple seconds, so this is definitely a Windows + 32-bit problem.

**Comment by bpollack** [comment]
You know, we had an OpenSSL crash on the main Factor site the other week that I couldn't track down (stack trace was almost certainly incorrect). If we _are_ looking at something with the GC or alien, that could explain both situations.

**Comment by AlexIljin** [comment]
@bpollack; is the server running a 32-bit build on a Windows PC?

**Comment by AlexIljin** [comment]
I was able to figure out that data_heap::grow calls segment::segment, which fails to allocate the necessary block: `VirtualAlloc` returns `null`. Given that the 2 Gb limit is not reached, and the physical memory has at least 6 Gb free, I fail to see the reason.

**Comment by mrjbq7** [comment]
Is it possible you aren't measuring total process memory properly?

**Comment by mrjbq7** [comment]
(Also factor objects have some small object header overhead which is in addition to what's stored as data for each one)

**Comment by mrjbq7** [comment]
Another related bug is we should crash with a better out of memory error when that happens.

**Comment by AlexIljin** [comment]
@mrjbq7: "Is it possible you aren't measuring total process memory properly?"
I'm seeing both Process Explorer's Private Memory indication, and when debugging I see VS 2015 display of the debugged process's memory. They are in agreement.

Anyway, you guys, googling around a little, I found this linker option: `/LARGEADDRESSAWARE`. Apparently, we are not using it, and enabling it makes this code work fine: `USE: byte-arrays 21 [ 1024 1024 50 * * <byte-array> ] time`. Double the allocation! I'll make a PR with the option. When the value is up to `22`, it crashes again, this time with 1.3 Gb used by the process.

I think it doesn't go all the way up to 2 (or even 4) Gb is in the logic for allocation in `data_heap::grow`: it doubles the current `tenured_size` when asking for the new memory block, and 1.3 Gb times 2 is not possible to allocate even with `/LARGEADDRESSAWARE`.

Is there a way we could do better in this area?

@mrjbq7: "Another related bug is we should crash with a better out of memory error when that happens."
Apparently, `fatal_error("Out of memory in VirtualAlloc")` is called, which I guess outputs the message to console. Of course, nobody runs a GUI application with the console on Windows.

**Comment by AlexIljin** [comment]
A thing we could do better, I think, is not to try allocating huge chunks of contiguous memory space, because that leads to address space fragmentation. Say, if we could get memory in 500 Mb chunks max, we could get a greater total amount.

**Comment by bpollack** [comment]
No, but I find the chance we have a bug *in the GC* specific to Windows minimal, and find the chance that inexplicable crashes with OpenSSL on multiple platforms are specific to OpenSSL equally unlikely.
