### ISSUE TITLE
Factor fails to build on musl libc

### ISSUE THREAD

**Issue by m-cz** [factor/factor#1836]
Running `./build.sh update` on a system with musl as a libc gives:

```
[...]
gcc -Wall -pedantic -DFACTOR_VERSION="0.98" -DFACTOR_GIT_LABEL="heads/master-13e7ed39866985a1fa3b728219bcea8b3773fcbe" -fomit-frame-pointer -Wl,--no-as-needed -m64 -O3 -fPIC -shared -o libfactor-ffi-test.so vm/ffi_test.o
In file included from vm/platform.hpp:15:0,
                 from vm/master.hpp:92:
vm/os-unix.hpp:36:76: error: expected initializer before '__THROW'
   extern int __xpg_strerror_r (int __errnum, char *__buf, size_t __buflen) __THROW __nonnull ((2));
                                                                            ^~~~~~~
make[1]: *** [GNUmakefile:222: vm/master.hpp.gch] Error 1
make[1]: Leaving directory '/home/mcz/src/factor'
make: *** [GNUmakefile:170: linux-x86-64] Error 2
make failed
```

Defining `__THROW` (and `__nonnull`) seems like appropriate fix.

On a side note: [AFAIK](https://github.com/rofl0r/musl/blob/master/src/string/strerror_r.c#L20) with musl there's no need to link strerror_r to __xpg_strerror_r because the former is POSIX-compilant.

**Comment by bjourne** [comment]
I think musl is in the wrong here for defining `_GNU_SOURCE` and not providing the GNU-specific `strerror_r`. Oh well, it wasn't  that hard to fix the bug though.
