### ISSUE TITLE
future-proofing nth and at argument ordering for 0.98

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1841]
I can't find the issues or commits anymore, but there was discussion and some code changes about reversing the order of the arguments to functions like `nth` and `at`. 

I'm trying to write user-facing code that will work in 0.97, 0.98-dev (current master head) and 0.98 when it releases in the unspecified future. Should I leave my uses of `nth` and `at` as they were for 0.97, or are the aim / direction currently ambiguous?

**Comment by mrjbq7** [comment]
We will not be changing ``nth`` and ``at``.  We had been discussion whether we should have a name for ``swap nth`` (like we do for ``swap at`` which is ``of``).

The discussion you might remember was swapping the arguments of ``start``, ``start*``, and ``subseq?``.  That might still happen, especially since we renamed ``start`` to ``subseq-start`` and ``start*`` to ``subseq-start-from``.

**Comment by mrjbq7** [comment]
We are not trying to cause headaches to anyone but have been trying to stabilize some of the naming conventions as we get to 0.98 and then 0.99 with the new lexer, but if you feel you need more stability in some direction, let us know.

**Comment by catb0t** [comment]
Yeah, I was definitely thinking of `start` and `start*`, oops. 

But will the old names will exist alongside the new `subseq-*` ones for backwards compatibility? And if they do, will they share the same argument ordering?

I don't *need* stability in a direction; I can just change the usage instructions to require Factor > 0.97 --  I'm happy to write in this language whatever direction it goes.

**Comment by erg** [comment]
Actually I think ``nth`` is more natural swapped around now. It would be a huge pain to change it -- the only way I'd change it is if we had a tool that could do it automatically for the whole codebase all at once. It should be possible to write one...

Closing this!
