### ISSUE TITLE
Access to the the Factor site / Fuel repository over HTTPS

### ISSUE THREAD

**Issue by joewreschnig** [factor/factor#1849]
As part of trying to [address security concerns in MELPA](https://github.com/melpa/melpa/issues/3004) I'm trying to find an authenticated URL we can pull Fuel from.

Currently MELPA uses git://factorcode.org/git/factor.git. I'd like to switch this to https://factorcode.org/git/factor.git/. But https://factorcode.org/ (also linked in this repo's header) has an expired SSL certificate. Is this still a supported URL?

We can also use this GitHub mirror, if the mirror is done over an authenticated channel. (For example, if the server running factorcode.org pushes the data to GitHub itself during post-commit.)

**Comment by AlexIljin** [comment]
Thank you for trying to fix this, @joewreschnig, and for bringing it to our attention! We have someone here responsible for the server. Unfortunately, that's not me, I'll just link the related issue here: #1815 .

**Comment by joewreschnig** [comment]
Sorry I didn't see that issue before! I'll move over there.

**Comment by AlexIljin** [comment]
That's no problem! In fact, the expired cert and the Git-over-HTTPS are different issues, which may require different actions to fix them. I'll let @erg and others handle this further.
