### ISSUE TITLE
Nightly builds are broken

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1851]
The "Development release" builds on factorcode.org are broken since 2017-06-04 for Windows, and since 2017-05-14 for MacOS X. The last 32-bit Linux build is dated in 2006.

Could someone fix at least the Windows builds?

**Comment by bjourne** [comment]
@erg, @mrjbq7 what's the plan here? Anything we can do to resurrect the broken build machines? Or is the idea to replace them with something else?

**Comment by erg** [comment]
I checked in a travis.yml file from @jonenst that we should continue to work on. Even after disabling the deploy tests it's too slow to finish before the hour timeout+kill. Maybe we can test core/, basis/, and extra/ as separate jobs or turn off a few more of the long-running unit tests?

**Comment by jonenst** [comment]
Maybe we just have to make smarter tests. Most of the time, when core or the vm are not modified, we could start the previous image (full image of load-all), do a refresh-all and test only the vocabs USING: the modified vocabs ? And when core or the vm are modifed, and also periodically, do a full bootstrap/test-all with many parallel jobs. The number of parallel jobs is not limited. It would be nice in that case to do the bootstrap only once and have all jobs download the newly boostrapped image, but I'm not sure if that's possible.

**Comment by jonenst** [comment]
https://travis-ci.org/facebook/react/jobs/32250596

from https://github.com/facebook/react/issues/1768

**Comment by jonenst** [comment]
Also from https://docs.travis-ci.com/user/caching/
> Caching directories (Bundler, dependencies) #
Caches lets Travis CI store directories between builds, which is useful for storing dependencies that take longer to compile or download.

Just keeping the image with load-all between runs would help a lot ?

**Comment by nicolas-p** [comment]
Any news about this? The macOS builds have been broken for seven months now.

**Comment by erg** [comment]
Nightly builds are clean!

**Comment by bjourne** [comment]
Amazing work! :+1:
