### ISSUE TITLE
`ensure-d` docs

### ISSUE THREAD

**Issue by samrat** [factor/factor#1854]
The `ensure-d` docs in `backed-docs.factor` currently says: "Does something important..". :)

Could somebody clarify what this word does?

**Comment by bjourne** [comment]
:) Was added my be while I was going through the compiler code. I think the word ensures that the datastack is long enough or something like that.

**Comment by AlexIljin** [comment]
@bjourne, I think you meant to use `tail*` there, but used `tail`. Am I right?

**Comment by AlexIljin** [comment]
I've never looked into that vocab, but from reading the code it looks like `ensure-d` makes sure that `meta-d` has at least `n` values (if not, it it calls `make-values` and `introduce-values` on the missing amount, then appends them to `meta-d`).

After that it sets `inner-d-index` = min(`inner-d-index`, length(`meta-d`) - `n`).

The returned `values` is a copy of the `meta-d`'s `tail` that is exactly `n` items long. `inner-d-index` is _lowered_ to point at the start of the returned region in `meta-d`.

In other words, assuming that `inner-d-index` is never negative before the call to `ensure-d`, there are two scenarios:
1. if `n` >= length(`meta-d`), increase `meta-d` length to `n`, set `inner-d-index` = 0, return a copy of `meta-d` contents.
2. if `n` < length(`meta-d`), set `inner-d-index` = min(`inner-d-index`, length(`meta-d`) - `n`), return a copy of last `n` values of `meta-d` contents.

As you can see, `inner-d-index` in some cases may be lower than the start of the ensured region, but the one thing is true: `inner-d-index`+`n` <= length(`meta-d`), so you can be sure that at least `n` items will fit in `meta-d` if you start allocating them from `inner-d-index`.

**Comment by AlexIljin** [comment]
Created pull request #1855.

**Comment by mrjbq7** [comment]
Fixed by #1855 and c457c019bb2d5f2a09021581fa7fd12429cd5ca1.
