### ISSUE TITLE
0.98-branch for Factor 0.98 release

### ISSUE THREAD

**Issue by erg** [factor/factor#1857]
I did some work during the hurricane and changed everything except functors to work with what hopefully will be the new parser in the ``modern-harvey`` branch. In order to make one last release that is compatible with what is published on blogs, in books, and in code repositories other than the official one, there's a new ``0.98-branch`` that we will release Factor from in the near future. I branched from the current head of master, so we will have to revert some patches if we want better compatibility.

We use factorcode.org as the main repository and use github as a mirror, but 0.98 development should take place on github and can use pull requests and merge commits. If there are patches that you want included in 0.98 and the main repository, open pull requests against both 0.98 and master.

I hope to push the new parser changes to master soon so development can continue!

**Comment by jonenst** [comment]
Great news !

**Comment by erg** [comment]
I'm keeping the new stuff in another branch until .98 is released. master is the .98 branch after all. Closing!
