### ISSUE TITLE
OpenGL multisampling

### ISSUE THREAD

**Issue by nicolas-p** [factor/factor#1859]
I am trying to use multisampling to draw an antialised triangle. I'm not very familiar with OpenGL so I used [this tutorial](http://lazyfoo.net/tutorials/OpenGL/28_antialiasing_and_multisampling/index.php).

I tried many things but the triangle is still aliased:

<img width="230" alt="capture d ecran 2017-09-09 a 22 34 59" src="https://user-images.githubusercontent.com/11431580/30243658-3482adea-95af-11e7-8d76-beeb10b9ceb2.png">

```factor
USING: accessors kernel opengl.gl ui ui.gadgets
ui.gadgets.canvas ui.gadgets.worlds ui.pixel-formats ui.render ;
IN: triangle

TUPLE: test < canvas ;
TUPLE: triangle < gadget ;

M: triangle draw-gadget*
    drop
    GL_BLEND glEnable
    GL_DEPTH_TEST glDisable
    GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA glBlendFunc
    
    GL_MULTISAMPLE glEnable
    
    GL_TRIANGLES glBegin
    1.0 0.0 0.0 glColor3f
    30.0 40.0 glVertex2f
    1.0 1.0 0.0 glColor3f
    50.0 200.0 glVertex2f
    1.0 0.0 1.0 glColor3f
    200.0 30.0 glVertex2f
    glEnd
    
    GL_MULTISAMPLE glDisable
    GL_BLEND glDisable ;
    
M: test pref-dim*
    drop { 250 250 } ;

: test-window ( -- )
    [ test new-canvas triangle new add-gadget
      <world-attributes> 
      { windowed double-buffered multisampled } >>pixel-format-attributes
      "Test" >>title open-window ] with-ui ;
      
test-window
```

Could you tell me what I am doing wrong?

(My machine is a 2012 Retina MacBook Pro with NVIDIA GeForce GT 650M and Intel HD Graphics 4000)

**Comment by erg** [comment]
.95 has proper opengl initialization but it broke in a cross-platform way since then and I havent debugged it yet. I believe this is related.

Doug

**Comment by jonenst** [comment]
I tried 0.95 from http://downloads.factorcode.org/releases/ and the triangle was still aliased

**Comment by nicolas-p** [comment]
I have just tested 0.92 and 0.95, and saw that the aliasing was much worse than on 0.98, but then I realised it's just because the new version has Retina support.

**Comment by jonenst** [comment]
So I looked into this today, I got it to work.
A correct config to have multisamples is :
      { windowed double-buffered multisampled T{ samples f 4 } T{ sample-buffers f 1 } } >>pixel-format-attributes

it works in 0.97 and before. It doesn't work on master right now.

Actually it was broken not so long ago (in January 2017) by    4756c30d3f91eff6b5e31e59b2ed4bb2da2f2775 and 39811fc7e745a7081b6e03b3743d36148f849f76
which removed the possibility of supplying values to pixel format attributes (see the class-of and value>> usage that were removed).

@bjourne  what do you want to do ? revert your patches or something else ?

**Comment by nicolas-p** [comment]
Good find!

I dug up an old nightly build that I still had on my computer (2016-07-16) and I can confirm that adding `T{ samples f 4 } T{ sample-buffers f 1 }` makes the above triangle completely smooth.

**Comment by nicolas-p** [comment]
Apparently it's not even necessary to write `GL_MULTISAMPLE glEnable`

**Comment by jonenst** [comment]
> Apparently it's not even necessary to write GL_MULTISAMPLE glEnable

Yeah, I noticed it on ubuntu with intel's drivers as well. In the tutorial you linked to, the multisample mode is explicitly disabled in the initialisation. Commenting the line "glDisable( GL_MULTISAMPLE )" in LUtil.cpp results in a nice looking triangle directly. As the author says "Finally, we disable line/polygon smoothing and multisampling in our initGL() function. For this demo we want aliased polygons to be our default behavior. "

**Comment by erg** [comment]
Do we have to revert them or can we just debug the problem and fix it?

**Comment by jonenst** [comment]
Well looking at the commits, they are just a refactoring. So an easy solution would be to revert. But I agree with the refactoring, the FUNCTOR: was unnecessary. Here's a patch that restores all the functionality (and adds a test).. So we just have to choose which implementation is best :)

```diff
diff --git a/basis/ui/pixel-formats/pixel-formats.factor b/basis/ui/pixel-formats/pixel-formats.factor
index a67786eb35..4cd3f15b71 100644
--- a/basis/ui/pixel-formats/pixel-formats.factor
+++ b/basis/ui/pixel-formats/pixel-formats.factor
@@ -1,5 +1,6 @@
 USING: accessors alien.c-types alien.data assocs destructors fry
-kernel math sequences specialized-arrays ui.backend ;
+kernel math sequences specialized-arrays ui.backend
+combinators words classes ;
 SPECIALIZED-ARRAY: int
 IN: ui.pixel-formats
 
@@ -57,8 +58,18 @@ TUPLE: pixel-format < disposable world handle ;
 M: pixel-format dispose*
     [ (free-pixel-format) ] [ f >>handle drop ] bi ;
 
+: (pixel-format-attribute) ( attribute table -- arr/f )
+    [ dup class-of ] dip at [ swap value>> suffix ] [ drop f ] if* ;
+
+: pixel-format-attribute>array ( obj table -- arr/f )
+    {
+        { [ over pixel-format-attribute? ] [ (pixel-format-attribute) ] }
+        { [ over word? ] [ at ] }
+        [ 2drop f ]
+    } cond ;
+
 : pixel-format-attributes>int-array ( attrs perm table -- arr )
-    swapd '[ _ at ] map sift concat append
+    swapd '[ _ pixel-format-attribute>array ] map sift concat append
     ! 0 happens to work as a sentinel value for all ui backends.
     0 suffix int >c-array ;

diff --git a/basis/ui/pixel-formats/pixel-formats-tests.factor b/basis/ui/pixel-formats/pixel-formats-tests.factor
index 67690e4ab1..a9c6504599 100644
--- a/basis/ui/pixel-formats/pixel-formats-tests.factor
+++ b/basis/ui/pixel-formats/pixel-formats-tests.factor
@@ -1,14 +1,23 @@
-USING: specialized-arrays.instances.alien.c-types.int tools.test
-ui.pixel-formats ;
+USING: alien.c-types specialized-arrays literals tools.test ui.pixel-formats ;
+SPECIALIZED-ARRAY: int
 IN: ui.pixel-formats.tests
 
 CONSTANT: attrib-table {
     { windowed { 99 } }
     { double-buffered { 7 } }
+    { samples { 100001 } }
 }
 
+SYMBOL: garbageword
+CONSTANT: garbageint 234
+
 ! pixel-format-attributes>int-array
-{ int-array{ 9 2 99 7 0 } } [
-    { windowed double-buffered } { 9 2 } attrib-table
+! it should ignore garbage, even the color-bits because it's not
+! in the table
+{ int-array{ 9 2 99 7 100001 2 0 } } [
+    {
+        windowed "garbage" $ garbageint double-buffered
+        garbageword T{ samples f 2 } T{ color-bits f 24 }
+    } { 9 2 } attrib-table
     pixel-format-attributes>int-array
 ] unit-test
```

**Comment by nicolas-p** [comment]
I compiled Factor recently from the latest sources, and multisampling works fine now. Can this be closed?

**Comment by catb0t** [comment]
@nicolas-p reproduced on 6bbd1c99fb

**Comment by erg** [comment]
Closed!

**Comment by nicolas-p** [comment]
I can't get multisampling to work on Windows using
```
{ windowed 
  double-buffered
  multisampled
  T{ samples f 4 }
  T{ sample-buffers f 1 }
} >>pixel-format-attributes
```
Is there more to do to make it work?
