### ISSUE TITLE
C-Break doesn't work in 64-bit builds

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1867]
For some reason, the Ctrl-Break hotkey doesn't interrupt the busy loop in the 64-bit build. Sample code to reproduce the issue:
```
: ∞ ( -- ) ∞ ;
∞
```

**Comment by erg** [comment]
There are two ways to build the Windows vm -- I think we don't use the ``x86-64-vista`` build on the build machine. I can update that tonight.

**Comment by bjourne** [comment]
@AlexIljin does it work when you build yourself? Last I tried, it did work.

**Comment by AlexIljin** [comment]
Hm... I haven't tried to pull that parlor trick in a long while, mostly relying on the fresh builds from factorcode.org. Does that version (from the site) work for you? If so, I could try the latest build and see for myself.
As to building my own copy, that could be too much of a hassle. Maybe for the weekend...

**Comment by AlexIljin** [comment]
OK, I've tested both 32- and 64-bit nightly builds from 2018-01-16-17-13, and in both C-Break works.
The only weird thing is that it isn't enabled by the listener, which I think I remember implementing. Maybe it needs an option to be set in the rc-file, I'll look into it.

The point is that if you add `enable-ctrl-break` in front of a piece of code that gets executed by the listener, the C-Break then works for the duration of that one invocation. I'm closing this issue.

**Comment by mrjbq7** [comment]
I think you currently have to ``t handle-ctrl-break set-global``.

**Comment by mrjbq7** [comment]
We made it opt-in until we had more people trying it out.

**Comment by AlexIljin** [comment]
Thanks! It got lost from my rc-file, probably during Windows reinstallation...
