### ISSUE TITLE
cap vocabulary has too small of resolution

### ISSUE THREAD

**Issue by erg** [factor/factor#1888]
```factor
USE: cap
ui-windows get-global random second screenshot.
```

![capture](https://user-images.githubusercontent.com/27430/34317603-fb512978-e777-11e7-8e94-5720905c5167.PNG)

**Comment by catb0t** [comment]
it's because `2x?` is set to `t` by `cap:screenshot`. fixed by #1898
![cap](https://user-images.githubusercontent.com/3238748/34582774-21e9831a-f163-11e7-8b82-d97bba10bef8.png)
