### ISSUE TITLE
concurrency.distributed: a client-side issue with `local-node`

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1897]
Suppose you want to exchange messages between two Factor processes, one being the server, the other being the client, and you want the exchange to by synchronized, i.e. using `send-synchronous` and `reply-synchronous`.

In the first Factor instance you start the server:
```
USING: concurrency.distributed concurrency.messaging io.servers threads ;
9010 local-server <node-server> start-server
[ receive f swap reply-synchronous ] "reply-synch-server" spawn
dup name>> register-remote-thread
```

In the second Factor instance you initiate the client query to the server:
```
USING: concurrency.distributed concurrency.messaging io.servers ;
9010 local-server "reply-synch-server" <remote-thread>
f swap send-synchronous
```

Expected: the client immediately gets the synchronous reply from the server, and the server thread is terminated.

Actual: `send-synchronous` fails with the following error:
```
Generic word insecure>> does not define a method for the POSTPONE: f class.
Dispatching on object: f
```

I tracked down the source of the `f` in question, and it comes from `local-node get`, which is reasonable, since we only started the server node in the first Factor instance. Do we really need the `local-node` while doing `send-synchronous` from the client? Am I doing something wrong with the client implementation? The regular `send` works fine for me, but not the synchronized counterpart.

**Comment by AlexIljin** [comment]
The code that produces the error is in `concurrency.distributed`:
```
M: thread (serialize) ( obj -- )
    id>> [ local-node get insecure>> ] dip <remote-thread> (serialize) ; 
```

**Comment by mrjbq7** [comment]
I think ``send-synchronous`` only works locally in a single Factor, not from another Factor instance.

**Comment by mrjbq7** [comment]
Actually, I'm wrong.  This works fine, you just have to create a ``local-node`` for the reply to be received on.

Factor 1 (listening on port 9010):

```factor
9010 local-server start-node

[
    [ receive [ data>> ] keep reply-synchronous t ] loop
] "reply-synch-server" spawn
dup name>> register-remote-thread
```

Factor 2 (listening on port 9011):

```factor
9011 local-server start-node

9010 local-server "reply-synch-server" <remote-thread>
12 swap send-synchronous
```

**Comment by mrjbq7** [comment]
It could use better documentation, I suppose.
