### ISSUE TITLE
html.parser chokes on html elements inside text attributes

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1899]
`html.parser:parse-html` breaks when processing (malformed) HTML like 

```factor
USE: html.parser
"<img alt='some <br> thing' src='xyz.png'>" parse-html
```
the result is 

```factor
V{
    T{ tag { name "img" } { attributes H{ { "alt" "some" } } } }
    T{ tag { name "br" } { attributes H{ } } }
    T{ tag { name text } { text " thing' src='xyz.png'>" } }
}
```
In this situation you would have to use a Regexp to find the `src` value, which is unfortunate.

This HTML is absolutely incorrect and malformed --

but, I really think that the `<br>` should be considered part of the string literal value of the `alt` attribute, not only because there was no closing `>` to the `img` tag before the beginning of the `<br>`.

Doing this would make the rest of the `img` element parse properly.

**Comment by catb0t** [comment]
the workaround in the case of `<br>` is to say `"<br>" "\n" replace` but this won't work for larger snippets; the fact that HTML is parsed inside substrings is almost a vulnerability.

**Comment by erg** [comment]
The html parser is kind of half-baked. We need a proper html5 parser or a binding to a proper html5 parser library.

I do think it's still worth fixing this bug though.

**Comment by AlexIljin** [comment]
@catb0t: From what I remember implementing an XML parser some time ago, the characters <, > and some others are absolutely top priority, and they MUST be escaped when used outside of their intended purpose. They serve as synchronization tokens for the parser in case of malformed input. In this regard the what `html.parser` does is absolutely correct. Giving higher priority to parsing strings doesn't seem like a good idea to me.

**Comment by AlexIljin** [comment]
In short: there is no bug to fix from what I see here.

**Comment by mrjbq7** [comment]
I agree it's not great HTML since it should be escaped ``&lt;br&gt;``, but one of the html5 parsers for python handles it:

```python
>>> from html5_parser import parse
>>> from lxml.etree import tostring
>>> root = parse("<img alt='some <br> thing' src='xyz.png'>")
>>> print(tostring(root))
<html><head/><body><img alt="some &lt;br&gt; thing" src="xyz.png"/></body></html>
```

**Comment by bjourne** [comment]
Bindings for [libxml2](http://xmlsoft.org/) would be awesome.

**Comment by catb0t** [comment]
I spent a little while reading through the documents on Gumbo and LibXML2 and I think that composing them together like [nostrademons/gumbo-libxml](https://github.com/nostrademons/gumbo-libxml) does will be the useful basis for whoever ends up writing the HTML5 binding. 

On the other hand, this issue will not be fixed until such a binding, therefore this can be closed.
