### ISSUE TITLE
cap vocabulary uses the gl buffer of the currently focused window instead of the target window

### ISSUE THREAD

**Issue by erg** [factor/factor#1900]
If you do ``"terrain" run`` and try to screenshot that window, it gets your listener window size and sometimes it gets the gl buffer from the listener window as well. I think we need to set which buffer it's reading from, which is not a parameter to ``glReadPixels`` but a state you have to set by calling ``glReadBuffer`` or something else.

- [ ] size is wrong
- [ ] buffer contents is wrong

Once this is fixed we can set the random seed for terrain to a known value and compare the rendering to a screenshot to make sure it doesn't regress graphically.

```
"terrain" run

USE: cap
ui-windows get-global last second screenshot.
```

**Comment by mrjbq7** [comment]
Fixed in b6f2f8564308509fda48753c6159367706d32215.
