### ISSUE TITLE
HTTP and other protocol link support in help.markup

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1902]
This is a proposal to include a Help System markup element which can link to things outside the Factor browser, with support for any protocol.
- Web pages with http: https:
- other real protocols like ftp: or telnet:
- "virtual" protocols like steam: and skype: 
- etc

I'd like to be able to say:
```
{ $description "Performs a " { $url URL" https://en.wikipedia.org/wiki/FFT" "Fast Fourier Transform" } " on the sequence." }
```
that renders as 
> Performs a [Fast Fourier Transform](https://en.wikipedia.org/wiki/FFT) on the sequence.

mostly so that we can link to resources on obscure mathematical functions like Kronecker transform from within the help system, or disambiguate a word like [outer](http://docs.factorcode.org:8080/content/word-outer%2Cmath.matrices.html)'s documentation :)

i'd appreciate feedback on this (including whether the Factor distribution wants it) before i try to implement it, though.

**Comment by mrjbq7** [comment]
Doesn't that work already?

**Comment by mrjbq7** [comment]
```factor
USING: help.markup urls ;
{
    $description "Performs a "
    { $url URL" https://en.wikipedia.org/wiki/FFT" "Fast Fourier Transform" }
    " on the sequence."
} print-element
```

**Comment by mrjbq7** [comment]
If you want to right-click and "open url", that works.  As for the other protocol support, if it isn't handled natively by the machinery in ``webbrowser``, I'd love any improvements that make that nicer.
