### ISSUE TITLE
Rename m. to m.m?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1903]
I'm working on giving `math.matrices` better documentation and cleaning up some of its names.

I wonder if [`m.`](http://docs.factorcode.org:8080/content/word-m.,math.matrices.html) (dot product of two matrices) should become `m.m`?

We have:
- [`v.m`](http://docs.factorcode.org:8080/content/word-v.m,math.matrices.html) and [`m.v`](http://docs.factorcode.org:8080/content/word-m.v,math.matrices.html) in `math.matrices` which compute the dot product of a matrix and a vector or vice versa
- `.`, `callstack.`, `infer.`, `simple-table.`, `leaks.` and so on which output to a stream some data
- `m-`, `m+`, `m~`, `m*`, `m/` which perform the mathematical operation on two matrices

`m.` would to me signal that some `m` is going to be prettyprinted.

Here are the vocabularies which have to change:

```
extra/project-euler/common/common
extra/rosetta-code/pythagorean-triples/pythagorean-triples
extra/rosetta-code/conjugate-transpose/conjugate-transpose
extra/koszul/koszul
extra/game/debug/tests/tests
extra/gpu/util/wasd/wasd
extra/benchmark/pidigits/pidigits
extra/benchmark/3d-matrix-scalar/3d-matrix-scalar
```

Note they are all in `resource:extra`, so this would not be particularly impactful. (13 times in 8 files)

**Comment by AlexIljin** [comment]
I'm 100% behind the idea of renaming `m.` to `m.m` for consistency.
And then also for renaming `m.m` further to `m*m`, `v.m` to `v*m` and `m.v` to `m*v`.

**Comment by mrjbq7** [comment]
Or maybe ``vdot`` and ``mdot``...

**Comment by AlexIljin** [comment]
I agree that `v.` is strongly associated with `.`, which is print command in our language.
When I wrote my previous suggestion I thought we are doing simple matrix product (`m*m` or `m*`).
But now that I know there is the "dot product", which is a different mathematical operation, I'm thinking maybe we could use something like `v.*` for "vector dot product" and `m.*` for "matrix dot product".

**Comment by bjourne** [comment]
But where do you end? :) Should `v+` be renamed `v+v` and `v-` `v-v` too?

**Comment by catb0t** [comment]
I kind of like `vdot` and `mdot` actually, although maybe they are kind of silly? I think what I'll do is rename `v.` and `m.` to `vdot` and `mdot` and then provide aliases which are `v⋅` and `v·` and `m⋅` and `m·` (U+22C5 Dot Operator and U+00B7 Middle Dot). 

Is it evil if the aliases look alike but are aliases for the same word? :thinking:

**Comment by mrjbq7** [comment]
Reminds me of ``math.unicode``!

**Comment by catb0t** [comment]
Hmm, maybe `math.unicode` could provide `GENERIC: · ( m1 m2 -- m3 )` and `GENERIC: ⋅ ( m1 m2 -- m3 )` and then `math.matrices` and `math.vectors` can implement those words for vectors and matrices? 

But then we have `basis` vocabs which rely on `extra` vocabs again. I got Factor to compile and run without `extra` but `load-all` of `basis` and `core` needs `extra`.

**Comment by mrjbq7** [comment]
Maybe those fancy unicode aliases go in math.unicode calling ``vdot`` and ``mdot``?

**Comment by catb0t** [comment]
That's a perfect solution, I like it :)

**Comment by catb0t** [comment]
https://github.com/factor/factor/pull/1948#issuecomment-551344584

> Note to future me / others: `vdot` is used literally and separately from `math.vectors:v.` in files like `resource:basis/xmode/modes/latex.xml` and `resource:basis/xmode/modes/povray.xml`, as well as `resource:extra/webapps/fjsc/www/termlib/readme.txt`, and therefore non-.factor files must be excluded from the `[mv]dot[mv]?` or `[mv]\.[mv]?` regexes

* `basis/xmode/modes/latex.xml`: `vdot` etc
* `basis/xmode/modes/povray.xml`: ditto
* `extra/webapps/fjsc/www/termlib/readme.txt`: `v. [version number]` 
* `extra/chipmunk/ffi/ffi.factor`: `cpvdot`

**Comment by mrjbq7** [comment]
These were renamed, closing this.
