### ISSUE TITLE
snake-game causes UI corruption

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1906]
If you run the snake-game and then it finishes by running into itself, then the listener window gets weirdly corrupted.

**Comment by catb0t** [comment]
What operating system? Mac OS? I've never seen this with snake-game on Windows or Linux (integrated graphics).

**Comment by mrjbq7** [comment]
On macOS, do ``"snake-game" run``, then just close the window, it makes the Listener all bugged out.

**Comment by mrjbq7** [comment]
It has something to do with the ``dispose`` of the textures in ``M\ snake-gadget ungraft*``.  If you comment out the dispose then it doesn't seem to corrupt the listener.

**Comment by mrjbq7** [comment]
Hmm, the UI corruption only seems to occur on macOS. Tested on Windows and Linux and those seem unaffected.

**Comment by AlexIljin** [comment]
That's why I wanted to see a screenshot: I don't have macOS anywhere near me.

**Comment by mrjbq7** [comment]
So the problem is when ``ungraft*`` is called on the gadget, the ``gl-context`` is not necessarily set to the proper one for the world that it is contained in.

**Comment by mrjbq7** [comment]
Fixed in 4a50385af1bc7123b6a0b9f6e6c5e84e927d7b47.

I also noticed that ``M\ image-gadget ungraft*`` has to do the same trick to dispose of it's image textures.  Perhaps we want to change ``ungraft*`` so that it's called with the GL context of the world it is grafted to.  Dunno.
