### ISSUE TITLE
(was v0.97 ; now nightly) on Windows : listener contents clipped, unusable

### ISSUE THREAD

**Issue by mdolidon** [factor/factor#1907]
Hello. I wanted to look at Factor for practical evaluations, after the docs made it look very promising.

Unfortunately, when trying it out on Windows, I face a simple display bug : the contents are clipped, especially so on the left border. I tried to shake / resize / maximize / minimize / restart / scroll and many combinations thereof, to no avail. That's when you realize how important the left-most character of an answer can be.

I haven't found any similar open issue yet, though you know how undeterministic that kind of search can be when a newcomer does it.

Screenshot : 
![image](https://user-images.githubusercontent.com/6281420/35150344-5c82bbdc-fd1a-11e7-8873-96d13eedccac.png)

Windows system infos say : Windows 10 Professional ; version 1709 ; os version 16299.125
x64 based processor ; the same problem can be seen with both the 32 bit and the 64 bit binary.

With regards.

**Comment by catb0t** [comment]
0.97 is from 2014, I would suggest using one of the recent 0.98 [nightly](http://builds.factorcode.org/package?os=windows&cpu=x86.64) [builds](http://builds.factorcode.org/package?os=windows&cpu=x86.32).

Nightly builds are always usable, but 0.97 is too old to be usable on many operating systems, and there are many changes which make 0.98 non-backwards-compatible with 0.97.

**Comment by mdolidon** [comment]
All right. I was assume I should go for "stable" first. :) Indeed this looks better with the latest nightly. However, the website's screenshots show a toolbar on top, which I don't get myself.

If this screenshot looks right to you, then please accept my thans and feel free to close this issue.

![image](https://user-images.githubusercontent.com/6281420/35159443-8a2e6728-fd3a-11e7-9fe7-b13dfd6997c1.png)

**Comment by mrjbq7** [comment]
No, that's not typical.  It may be a result of a minor UI refactor i was working on last night to make ``MAIN-WINDOW:`` applications more easy to write.  Let me investigate.

**Comment by mrjbq7** [comment]
Hmm, I can't seem to reproduce either before or after my patch last night on Windows 10.  I have reverted for now, so perhaps the next nightly build or you can update to latest using ``build.cmd`` and see if that makes a difference.

**Comment by mdolidon** [comment]
It'll be a pleasure to test the update. However please allow me until Monday, as I left that laptop in the office and only have Linux at home. I'll keep this thread posted.

**Comment by mdolidon** [comment]
@bjourne : I have not explicitely configured any accessibility setting. However, following your advice, I've ticked the checkbox and tried all three options shown by the dropdown. I kept the one that says something like "let the application deal with DPI scale", as it looked the sharpest and most natural. However there are still no toolbars. Besides, there is a large gap between the location of the mouse pointer as seen on by the system vs. as seen by the app  : 

![image](https://user-images.githubusercontent.com/6281420/35212300-f847a55a-ff59-11e7-87ac-7ed2f9111b44.png)

I'll wait for the Windows nightly build to be updated.

I've tried the Linux version this week-end, and found no such issue. The UI is very pleasant, and the very navigatable documentation is a big plus for people who may jump in !

**Comment by bjourne** [comment]
But you are using a hidpi screen, aren't you? That is what is causing the fonts to look fuzzy. It would be interesting to see a screenshot from your system without high dpi scaling enabled.

**Comment by mrjbq7** [comment]
Hmm, sorry it's not working for you!

I've used it on HiDPI screens before, and not seen this problem, seems like some kind of scaling, since the status bar at the bottom looks cut off and the padding that should be on the left (for example) of the ``IN: scratchpad`` is missing.  It's almost like it's magnified *just a little bit*.

As for the mouse pointer, it seems like it's shifted by exactly the toolbar (that should be displayed above but isn't) amount?  Very odd.  I want to fix this bug! Need to figure out how to reproduce.

**Comment by mdolidon** [comment]
Passing note : the issue remains the same with the 25th Jan nightly build.

**Comment by mrjbq7** [comment]
Hi @mdolidon, haven't forgotten about you.

Ran into a problem with ``resize-window`` on Windows where we weren't adjusting one of our calls to Windows API since the dimensions we pass are "client area" but the ones the API expects is "window area" which is larger because of the window style applied.

Could you try a latest nightly build and see if this problem still exists, and also if this code works for you:

```
"Resize" [ drop world get { 200 200 } resize-window ] <button>
T{ world-attributes { title "Testing" } { pref-dim { 200 200 } } }
open-window
```

That window should start ``200 x 200`` and then when you click on it, should be resized to the same size (so should NOT resize).

**Comment by mdolidon** [comment]
Hello mrjbq7.
With the nightly build from 15th of March : 
- the horizontal scaling problem has disappeared ; I now see the left of the listener's input and ouput correctly.
- the vertical scaling problem appears when I shrink the window to very small vertical sizes. With usual sizes the display is good, except for one thing : I still never see the toolbar that I expect at the top.
- your sample code works right. And when I manually make the window bigger and the click the button, it does rescale to the initial size.

**Comment by mrjbq7** [comment]
Sounds like this is fixed!
