### ISSUE TITLE
Rename macosx to macos

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1909]
Apparently macOS is here to stay... so, at some point we should deprecate / rename ``macosx`` to ``macos`` or ``macOS``.

**Comment by catb0t** [comment]
is this more complex than just using a regex on the entire codebase like `s/macosx/macos/g`?

**Comment by mrjbq7** [comment]
Probably yes, although I'm not sure it's worth it.  And I'm a little sentimental to OS X. 😄

**Comment by jryans** [comment]
The commits from https://github.com/factor/factor/pull/3051 have been merged and tests are passing. @mrjbq7, perhaps it’s time to close this issue?

**Comment by mrjbq7** [comment]
Awesome!
