### ISSUE TITLE
jamshred goes into an infinite loop after a few frames

### ISSUE THREAD

**Issue by erg** [factor/factor#1910]
```
"jamshred" run
```

Locks up Factor after a few frames.

**Comment by mrjbq7** [comment]
What platform?  Works on my macbook

**Comment by erg** [comment]
Macbook. 10.13.3 beta 5

**Comment by erg** [comment]
This bug is probably caused by the mouse not working. jamshred works (no mouse of course).

jamshred.factor lines 81-82:
```factor
    ! { motion [ handle-mouse-motion ] }
    ! { mouse-scroll [ handle-mouse-scroll ] }
```

**Comment by erg** [comment]
Looks like this page is the same bug:
https://discourse.libsdl.org/t/macos-raw-mouse-woes/22895

**Comment by bjourne** [comment]
I have the same bug on Linux. But only when using the gtk ui backend, the  x11 ui backend works fine.

**Comment by erg** [comment]
Duplicate of https://github.com/factor/factor/issues/1877

The 2012 Retina Macbook Pro hardware is broken and Apple will likely never fix it.

**Comment by erg** [comment]
Still broken for me on M1

**Comment by erg** [comment]
I think it hits an infinite loop in `(move-player)`. If I add a 100ms sleep in (move-player) then it never gets too unresponsive.

Also saw this in the terminal spam.

2022-01-08 11:56:47.352 factor[9785:2362849] void * _Nullable NSMapGet(NSMapTable * _Nonnull, const void * _Nullable): map table argument is NULL
