### ISSUE TITLE
make bootstrap.primitives standalone vocab with MAIN:  

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1931]
see https://github.com/factor/factor/pull/1908#pullrequestreview-90296997

> mrjbq7 14 days ago  
> So, core/bootstrap/primitives.factor is a script used in the bootstrap process, not meant to be a vocab you can import, which leads to the error using $vocab-link. I think bootstrap.image.primitives is only used by core/bootstrap/primitives.factor in the entire project.

> catb0t 14 days ago
> well, can we put the script core/bootstrap/primitives.factor in a primitives folder so that help-lint passes? or should i just ignore the linter?

> mrjbq7 14 days ago
> The quickest way is to make it a $snippet instead of a $vocab-link.
> Maybe longer-term we could make bootstrap.primitives it's own vocab and move the top-level script code into a MAIN: word.

> catb0t 14 days ago
> that makes sense, i'll put this in the next set of commits i make on this pull

> mrjbq7 14 days ago
It's also funny that the "script" for bootstrap/primitives.factor actually does define itself as a vocab when you run it and puts some words in the vocab that it uses in the script part. Anyway, good cleanup suggestion for later! Thanks!

**Comment by mrjbq7** [comment]
i moved the stage1 bootstrap scripts to ``basis/bootstrap/``, and longer term these should possibly be separated into a ``boot/`` directory as an implementation detail, not as a vocab maybe.

closing this issue for now.
