### ISSUE TITLE
Migrate a/an and some other "english" words into basis/english

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1942]
As I wondered in #1930, there are other vocabs / words in core and basis which implement functionality that belongs in `english`.

Is anyone going to disagree with a pull request to move words like `a/an` from `help.markup`:

https://github.com/factor/factor/blob/b14d6085d64687a03423735df95b88508572fb7b/basis/help/markup/markup.factor#L343-L345

into `basis/english`?

**Comment by mrjbq7** [comment]
Seems fine to me.

**Comment by catb0t** [comment]
Closed since #1947 is open now.
