### ISSUE TITLE
http client ssl error

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1946]
"https://www.google.fr/" http-get 2drop ! OK
"https://www.velib-metropole.fr/" http-get 2drop ! KO

it throws the following exception:
```error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure```

**Comment by catb0t** [comment]
They both work just fine for me on Ubuntu Linux 17.10, what OS are you using, and which certificates do you have installed?

**Comment by mrjbq7** [comment]
Both work for me with latest Factor git and macOS 10.13.3.

**Comment by jonenst** [comment]
can't reproduce either.. they must have changed their ssl config.
