### ISSUE TITLE
``USE: python`` causes an error when the dll is not found

### ISSUE THREAD

**Issue by erg** [factor/factor#1952]
Happens on Windows especially since the dll is not usually in the path and it breaks ``load-all``.

```
Cannot resolve C library function
Library: DLL" python2.7"
Symbol: Py_IsInitialized
DlError: The specified module could not be found.
See http://concatenative.org/wiki/view/Factor/Requirements
```

**Comment by bjourne** [comment]
We've had this problem before: ccfd9101f08e9d5e20dde76071aad3eeeb4eeb9b :) So let's remove the hooks and strongly require users to call `py-initialize` manually before using the binding?

**Comment by erg** [comment]
I went with a different solution -- only call if the symbol is present.

Maybe we can turn this into a proper idiom or whatever and use it in more places? (Maybe even in the python shutdown hook, now that I think about it...)

**Comment by bjourne** [comment]
Yeah, that works for now. Ideally we would want a system so that some hooks are only run at "import-time" So that if you run `USE: python` or otherwise import it, the hook is run but not otherwise. We can look at that after the 0.98 release.

**Comment by erg** [comment]
I fixed the shutdown hook just now.

What do you think about the case where someone loads a library and the dll is missing, then moves in the dll...Factor never recovers until you restart.

**Comment by mrjbq7** [comment]
User error. Seems like a dlclose/dlopen would be annoying on every dlcall.

**Comment by mrjbq7** [comment]
Or at the very least, 0.99 material!
