### ISSUE TITLE
absolute-path is broken on tilde paths

### ISSUE THREAD

**Issue by erg** [factor/factor#1974]
```factor
"~" absolute-path  ! the file named tilde relative to the current directory
! c:\users\erg ! error

"./~" absolute-path  ! the file named tilde relative to the current directory
! c:\users\erg\~ ! correct
```

The first path expands into the user's home directory but it should just be a file named ``~``, which is a legal path name.

Tilde to home path expansion should only happen in the context of a shell and not in the basic io operations.

**Comment by mrjbq7** [comment]
It's not broken, it works just fine like the shell.

**Comment by mrjbq7** [comment]
The first case is just the home directory.

It works perfectly.

**Comment by mrjbq7** [comment]
I find the home expansion useful... dunno.
