### ISSUE TITLE
math:log2 should support non-integers

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1980]
unless i'm missing something very obvious, it should be easy to use `166+2/3 log2` or `105.273 log2`. i will create a pull request to add this method on `(log2)` and change `log2` to not reject non-integers.

**Comment by erg** [comment]
``log2`` is specifically integer ``log2``. You can use ``log 2 log /f`` instead.

**Comment by catb0t** [comment]
Well, I suppose it makes sense for the optimisation, but is there a reason not to have `log2` generic in the first place, and then it has the same optimisation for integers as currently?

**Comment by erg** [comment]
I'm not sure, maybe it's just as fast either way.

**Comment by mrjbq7** [comment]
Integer log 2 not equal to float log 2.

**Comment by catb0t** [comment]
This is like the distinction between `2^` and `2 ^`, yes? Well, fair enough, I won't mess with it then, two different math generics shouldn't have different meaning.

**Comment by jonenst** [comment]
There's integer-log2. I think I kept it separate from log2 because of https://github.com/factor/factor/issues/1580#issuecomment-203133856
