### ISSUE TITLE
Factor omits a logn function

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1981]
perhaps it has been intentionally omitted or I just can't find it, but there is no `logn` function I can see in the standard library. 

`logn(x) = log(x) / log(n)` or `: logn ( n x -- log ) [ log ] bi@ swap / ;` , so it is very easy to implement logn.

like in #1980, unless someone tells me otherwise i will create a pull request with this feature.

**Comment by erg** [comment]
I would reverse the parameters so you don't need the ``swap``.

**Comment by catb0t** [comment]
Well, in math you would write log<sub>25</sub>1624 so I put the parameters `n x` for that reason. But if you think that's unnecessary then it can be `x n` instead.

**Comment by erg** [comment]
Think of it like this.

You have a number on the stack, say 5, and you want to take the ``log25`` of it.

```
: logn ( x n -- log ) [ log ] bi@ / ;
5 25 logn .
```

**Comment by catb0t** [comment]
I suppose that makes more sense, you're right!

**Comment by mrjbq7** [comment]
I would think applying “log 25” to numbers makes more sense than applying X to log 25.

+1 for not swapping: ( x n — result )
