### ISSUE TITLE
ENUM: is not namespaced properly, redefine errors

### ISSUE THREAD

**Issue by erg** [factor/factor#1984]
``Completed`` is defined as two different numbers but the same symbol in Factor.

```factor
ENUM: DraggingState < int32_t
    { Started 0 }
    { Continuing 1 }
    { Completed 2 } ;

ENUM: HoldingState < int32_t
    { Started 0 }
    { Completed 1 }
    { Canceled 2 } ;
```

```
! Similar error looks like this
resource:basis/windows/surface-dial/surface-dial.factor

52: ENUM: DraggingState < int32_t
55:     { Completed 2 } ;
                   ^
Re-definition of Completed
```

**Comment by mrjbq7** [comment]
I’m not sure we should namespace automatically.  Otherwise we’d have to write code that used the namespaced name everywhere. 

If you have a vocab with this problem maybe the developer should do manual namespacing?

**Comment by erg** [comment]
I guess I blame C for allowing nested namespaces while Factor does not.

Best practices would be to do manual namespacing like you suggested or to add some kind of nested namespace feature to Factor (proposals?)

```factor
ENUM: DraggingState < int32_t
    { DraggingState-Started 0 }
    { DraggingState-Continuing 1 }
    { DraggingState-Completed 2 } ;

ENUM: HoldingState < int32_t
    { HoldingState-Started 0 }
    { HoldingState-Completed 1 }
    { HoldingState-Canceled 2 } ;
```
