### ISSUE TITLE
macOS console.app reports: AEGetDescData of non-desc type 'reco' not a good idea

### ISSUE THREAD

**Issue by erg** [factor/factor#1986]
``10.13.4 Beta (17E190a)``

```
error	19:12:27.157059 -0500	factor	        AEGetDescData of non-desc type 'reco' not a good idea
```

**Comment by hendriks73** [comment]
`AE` error messages are typically connected to the Apple Event subsystem. So to find the cause for this, you might want to look for AppleScript code.

**Comment by mrjbq7** [comment]
Don't see this on newer macOS, closing.
