### ISSUE TITLE
Problems running FUEL in MacOS

### ISSUE THREAD

**Issue by amherag** [factor/factor#1989]
Hello,

I just cloned the factor repository, ran `./build update`, ran `./factor`, evaluated `"fuel" run` in the REPL and got this:

```
IN: scratchpad "fuel" run
Loading resource:extra/fuel/fuel.factor
Loading resource:extra/fuel/eval/eval.factor
Loading resource:extra/fuel/pprint/pprint.factor
Loading resource:extra/fuel/help/help.factor
Loading resource:extra/fuel/help/help-docs.factor
Loading resource:extra/fuel/xref/xref.factor
Loading resource:basis/tools/scaffold/scaffold.factor
Loading resource:basis/tools/scaffold/scaffold-docs.factor
The fuel vocabulary does not define an entry point.
To define one, refer to \ MAIN: help
```

Any ideas?

**Comment by mrjbq7** [comment]
That's not how you use ``fuel-mode`` in Emacs.

You should look through the README to see how to install and use it:

https://github.com/factor/factor/blob/master/misc/fuel/README.md

**Comment by amherag** [comment]
I can use FUEL by running it inside Emacs. But I want to have an external instance , so, as pointed out I'm the README, I can use `"fuel" run` And connect to it.

I was able to do this in previous versions (the binary release, 0.97) but now I can't.

**Comment by mrjbq7** [comment]
I only see a comment about ``"fuel.remote" run`` where are you seeing ``"fuel" run`` and what did you expect it to do?

**Comment by amherag** [comment]
Oh duh, I clearly remember it was "fuel" run. And not "fuel.remote" run. Thanks and sorry.
