### ISSUE TITLE
Why isn't Factor's `float` arbitrary precision?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1990]
The most significant digits for a float in Factor is `1e+309`; `1e+310` is `1/0.`. 

 I know that `bignum` is arbitrary precision integers, so why not the same for `float` -- or have an arbitrary precision floating point type? 

Or is it something that was never needed and so nobody worked on it? 

My question arises because x86-64's `LDBL_MAX` is `1.18e+4392` and I was surprised that this does not fit into a Factor `float` even though it easily fits into a hardware `double`.

**Comment by mrjbq7** [comment]
What is the double bit pattern that produces ``1.18e+4392``?

I think the largest double is ``DBL_MAX`` or approximately 1.8e308.

Factor floats are 64-bit floats (``double`` in C).

Are you trying to use a ``long double``?

https://en.wikipedia.org/wiki/Long_double

**Comment by mrjbq7** [comment]
> long double - extended precision floating point type. Matches IEEE-754 extended floating-point type if supported, otherwise matches some non-standard extended floating-point type as long as its precision is better than double and range is at least as good as double, otherwise matches the type double. Some x86 and x86_64 implementations use the 80-bit x87 floating point type.

**Comment by mrjbq7** [comment]
Doesn't work in Python either:

```
>>> 1.18e+4392
inf
```

**Comment by mrjbq7** [comment]
Largest 64-bit double is this one:

```factor
IN: scratchpad 0x7fefffffffffffff bits>double .
1.797693134862316e+308
```

**Comment by jonenst** [comment]
Correct me if I'm wrong but the point of floating point values is to have a
fixed number of bits and have more or less precision depending on the
magnitude if the number.

You can have arbitrary precision decimal values with ratios.

Do you mean we could have better support for literal decimals and printing
ratios in base 10 (but what about 1/3 with an Infinite decimal
representation) ?

**Comment by catb0t** [comment]
`decimals` is what I was looking for but I forgot its name, thank you!

**Comment by mrjbq7** [comment]
Great. A future todo is to allow user defined classes (things like decimal) to participate in the math tower so math genetics can be extended.
