### ISSUE TITLE
`get` on t and f seem to leak addresses?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1998]
I'm not sure what's going on here or if it's wrong, and also I can't tell if this has been reported. 

```
IN: scratchpad f get

--- Data stack:
string-limit?
IN: scratchpad get

--- Data stack:
t
IN: scratchpad get

--- Data stack:
c-object-pointers?
IN: scratchpad get

--- Data stack:
f
IN: scratchpad get

--- Data stack:
string-limit?
IN: scratchpad get

--- Data stack:
t
IN: scratchpad get

--- Data stack:
c-object-pointers?
IN: scratchpad get

--- Data stack:
f
```

`f get` gives the symbol `string-limit?`, `string-limit?` is `t` and `t get` gives the symbol `c-object-pointers?` which is `f`, and `f get` gives `string-limit?`... 

but is it a problem?

**Comment by mrjbq7** [comment]
I don't get that on a fresh bootstrap.

And I don't see any code that might have swapped the key/value in the namespaces for those variables.

Thoughts on how that might have happened?

**Comment by catb0t** [comment]
Yes, I had `string-limit? t set` in my `.factor-rc` and never noticed until right now. Whoops!
