### ISSUE TITLE
ShellExecute return value is a pointer? 

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1999]
If I call for example: 

```factor
f "runas" "something nonexistent" f f SW_SHOW ShellExecuteW
``` 

the return value is `ALIEN: 2`, which is a pointer to address `0x2`. In fact the operation failed with `ERROR_FILE_NOT_FOUND`. (Factor: `Win32 error 0x2: The system cannot find the file specified.`)

If I call: 

```factor
f "runas" "cmd.exe" f f SW_SHOW ShellExecuteW
```

which is an operation that succeeds, the return value is `ALIEN: 2a` a pointer to address `0x2a`. Calling `alien-address` on it gives `42`, and this is a successful (> 32) value for the return of [`ShellExecute`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762153(v=vs.85).aspx).

But the  MSDN docs seem to say the return value is a `HINSTANCE` value, not a pointer (I think?). 

In Factor `HINSTANCE` -> `HANDLE` -> `PVOID` -> `void*`.

Regardless of that, the Factor `alien` docs say 

> Usually alien objects do not have to be created and dereferenced directly; instead **declaring C function parameters and return values as having a pointer type such as void\* takes care of the details.**

It seems incorrect that 

1. I should find the function's return value in the returned pointer's address, rather than the value at the pointer.
2. The returned pointer is invalid (2 and 42 will never be mapped addresses)
3. The returned pointer is not automatically dereferenced by the FFI as the docs imply (but it would be a segfault anyway)
     * is this because `HINSTANCE` does not end in a `*`?

**Comment by erg** [comment]
Since ``HINSTANCE`` is an alien, you can get at the value with ``42 <alien> alien-address``. I prefer to keep the win32 api signatures as they are in the microsoft docs and header files.

I don't think there's a problem having any ``alien`` unless you actually ``deref`` it, e.g. ``42 <alien> int deref``.

Maybe we can close this as not a bug? Or maybe I don't understand your issue. :)

**Comment by catb0t** [comment]
yeah, i forgot how to use `<alien>` i think :)
