### ISSUE TITLE
Misunderstanding with stack effect of MessageBox

### ISSUE THREAD

**Issue by v0idNULL** [factor/factor#2008]
What does uType) mean in the stack effect of windows.user32.MessageBox?

**Comment by erg** [comment]
``uType`` has type ``UINT`` and it's a some flags that are bit-or-ed together.

https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-messagebox

**Comment by v0idNULL** [comment]
So I think there is mistyping in stack effect. uType) instead of uType.

**Comment by erg** [comment]
I think your codebase might be outdated?

https://github.com/factor/factor/blob/master/basis/windows/user32/user32.factor#L1868

**Comment by v0idNULL** [comment]
@erg How can it be? I have 0.97 release build for Windows x86-64.
![browser-scrnshrt](https://user-images.githubusercontent.com/4871017/42295746-e7264bc0-8030-11e8-8bbb-9afc96198167.png)

**Comment by mrjbq7** [comment]
Is it still weird on master branch? (Development release)

**Comment by erg** [comment]
.97 is years old, sorry about our release process. I need to release .98 asap...please use the most recent version instead of .98, it's plenty stable.

Check out the bottom grid instead.

http://factorcode.org/ "Development release"

**Comment by mrjbq7** [comment]
Yeah but does the bad stack effect exist in 0.98 @erg? I can’t check windows. 

See the extra paren after uType:

... uType) — ... )

**Comment by mrjbq7** [comment]
Hah, excellent. You probably said that but I misunderstood. Thanks!!
