### ISSUE TITLE
travisci hangs when testing kernel vocab

### ISSUE THREAD

**Issue by erg** [factor/factor#2013]
Looks like this line breaks travisci (it's in ``"kernel" test``):

```
Unit Test: { { } [ 1000 [ [ 3 throw ] ignore-errors ] times ] }
Unit Test: { { } [ 1000 [ [ -1 f <array> ] ignore-errors ] times ] }


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

This test is also preventing us from testing all ``core-vocabs``

https://api.travis-ci.org/v3/job/401153070/log.txt

```factor
-1 f <array> ! throws this on linux64
Invalid array size: -1
Maximum: 288230376151711743
```

**Comment by erg** [comment]
TravisCI can run ``[ -1 f <array> ] must-fail`` one time and keep going, so I'm trying to only run it 10 times instead of 1000 to see if it just takes a long time to recover from a fault. (That could be a new bug)

**Comment by erg** [comment]
It works with 10 iterations. Maybe we can figure out why it fails with 1000 someday.

**Comment by catb0t** [comment]
on Linux x86-64 with a slow (1.9GHz) chipset, both of the following work fine for me

```factor
[ 1000 [ -1 f <array>] times ] must-fail ! fast

1000 [ [ -1 f <array> ] must-fail ] times ! uses a lot of CPU, but completes
```

**Comment by erg** [comment]
Maybe the comment is way off -- the test finishes instantly on my computers, too. But changing it from 1000 reps makes TravisCI keep testing.

**Comment by mrjbq7** [comment]
If it uses an increasing amount of cpu / memory then maybe we have a resource leak related to must-fail? Or maybe it needs to GC after each iteration?

**Comment by erg** [comment]
The comment above the test is ``! Don't leak extra roots if error is thrown``

**Comment by erg** [comment]
Travis-ci sucks. Closing this until it happens somewhere else.
