### ISSUE TITLE
Improvement: add tags to Git repository

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2026]
Currently the Git repository has not a single tag.
The only way to identify the currently released Factor version (0.97) is to check the SHA1 at e.g.
http://builds.factorcode.org/release?os=linux&cpu=x86.64

Wouldn't it be nice to just add a tag to that commit?
Similarly for other important milestones.

I leave it to you to come up with any sensible naming scheme, although just a version number of the release is probably good enough.

**Comment by mrjbq7** [comment]
Hmm, we used to have tags synced they must have gotten messed with some recent git-fu. Thanks for report.

**Comment by mrjbq7** [comment]
I think we have the tags working now.  Let me know if it's not great for you.

**Comment by nomennescio** [comment]
$git tag -l
0.94
0.95
0.96
0.97
0.98
unmaintained
