### ISSUE TITLE
Clean boot image: where?

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2027]
Looking at
http://concatenative.org/wiki/view/Factor/Build%20farm
and
http://concatenative.org/wiki/view/Factor/Building%20Factor

it is suggested that the clean branches follow a released revision, instead of bleeding edge.
To bootstrap, a 'clean' boot image is located in
http://downloads.factorcode.org/images/clean/

Looking at the Git repository, all clean-* branches are identical to master, i.e. bleeding edge, and the boot image also seem to correspond to 'master'.

Now I want to build a released version (which after almost four years is still 0.97) with modified build flags, and need to bootstrap with a corresponding boot image. Where can I find the boot image for 0.97?

**Comment by mrjbq7** [comment]
You can make your own boot images.

IN: scratchpad make-my-image

**Comment by nomennescio** [comment]
How to make the boot image for Factor 0.97?

**Comment by nomennescio** [comment]
Or: which boot image can I use to bootstrap Factor 0.97?

**Comment by mrjbq7** [comment]
Just download the release and make your own image to bootstrap from if you need to for some reason.  

Master branch is way better. It’s about to be released as 0.98 and lots of bugs fixed and features added.

**Comment by erg** [comment]
Run .97 and run the ``make-my-image`` command.

But the nightly is way better, I would never run .97 again except to see if a bug is a regression.

**Comment by nomennescio** [comment]
OK, well, I would love to run 0.98 as soon as it is released! I'm currently trying to get Factor incorporated into the Codewars framework (I think it would be a great environment to further promote the language), and am building a basic framework to that end. I would only advise to use a released version for such a context, hence I'm looking into 0.97, preferably a pre-packaged version to be used with 'apt-get'.

**Comment by nomennescio** [comment]
Next to that, I'm trying to create a build with the NO_UI=1 flag, to avoid loading dynamic gtk* libs at startup. Is there any dependency with the boot image on that? I could of course try to make a boot image on a regular 0.97, but only if there are no such dependencies.

**Comment by erg** [comment]
The boot image is the same no matter UI or not.

If you wait til Mon/Tues we hopefully will have released .98  (it's just waiting on the changelog i think)

**Comment by mrjbq7** [comment]
The boot images have no such dependency. Also, if you run terminal only factor the UI isn’t loaded. 

./factor -run=listener

**Comment by erg** [comment]
``Same info before or after John``

:p

**Comment by nomennescio** [comment]
Monday for 0.98? That's fantastic!

**Comment by erg** [comment]
Does it do the same thing on the nightly build if you download it? (It shouldn't do that, trying to debug)

**Comment by nomennescio** [comment]
No, the nightly build indeed does startup a console only version without requiring the gtk* libs, nice!

**Comment by nomennescio** [comment]
Summary: 0.98 is much better and will be released soon. You can create the 0.97 boot image by running 0.97 and executing make-my-image.

I conclude that the 0.97 boot image is not available on factorcode.org.

It seems the clean* branches were intended to follow releases, and not be identical to 'master'. Is that still the intention? If so, please update these branches (and corresponding images in http://downloads.factorcode.org/images/clean/). If not, could you please update the documentation on factorcode.org? In any case, the reference to 'http://downloads.factorcode.org/images/latest/' is pointing to a non-existent directory.

This information would help people trying to build Factor themselves.

**Comment by nomennescio** [comment]
Congratulations on the 0.98 release!

**Comment by mrjbq7** [comment]
Thank you!

**Comment by nomennescio** [comment]
I noticed the clean branches are now sticking to 0.98, is that therefore now still policy?

**Comment by nomennescio** [comment]
Oh, I just updated and saw they moved with master...
Is that really the intention?

**Comment by mrjbq7** [comment]
The clean branches are the latest development release where the build bots run with no test failures.

Sometimes they don’t get updated due to test failures, but usually when that happens it’s because our (home grown) continuous test framework isn’t running for machine hardware reasons.

**Comment by nomennescio** [comment]
OK, so releases are marked by tags, release branches are build that pass all tests, and master is bleeding edge and might potentially not pass tests.
