### ISSUE TITLE
SMTP NTLM Authentication

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#2031]
Hi, all!

  I'd like to use the client NTLM authentication with our `smtp` vocab, but currently the available options are `no-auth` and `plain-auth`. Could anyone give me pointers on how NTLM authentication actually works and what it would take to add the support? I'd be happy to contribute the implementation.

**Comment by AlexIljin** [comment]
Found this useful link: https://msdn.microsoft.com/en-us/library/cc246870.aspx

**Comment by bpollack** [comment]
NTLM auth is deprecated even in all-Windows shops; has been since somewhere around 2010 at the latest. Are you sure you want to support this?

**Comment by AlexIljin** [comment]
Unfortunately, that's what my business SMTP server works on. The only upside is that it can't be accessed outside the LAN/VPN.

**Comment by AlexIljin** [comment]
NTLM authentication requires me to use DES encryption (ECB mode, no padding needed). Do you know where I can borrow one? E.g. is it available from the libcrypto API?

**Comment by bpollack** [comment]
It's definitely in OpenSSL's cypher collection, so that's at least one viable place. I doubt I added the needed constants, but shouldn't be a big deal. That said, 3DES is honestly not too bad to write from scratch; it's old and quite simple. It might be worth just writing a native version.

**Comment by bpollack** [comment]
@AlexIljin I was debating just writing a 3DES library for Factor. Did you beat me to it/just add the constants to use OpenSSL?

**Comment by AlexIljin** [comment]
@bpollack, I didn't have time to dig into that yet. If you do a 3DES, please make a single DES available as well. I think NTLM uses single DES.

**Comment by bpollack** [comment]
That doesn't match my memory and I hope to heck you're wrong, but since 3DES requires DES as part of it (it's `encrypt(decrypt(encrypt()))`), I'll have to anyway.

**Comment by AlexIljin** [comment]
It seems that I may not need this anymore in the near future, so I'll close the issue to keep the tracker clean.
