### ISSUE TITLE
quote-shell and words for parsing Bourne Shell command lines

### ISSUE THREAD

**Issue by catb0t** [factor/factor#2042]
does Factor already have something like [Python's shlex](https://docs.python.org/3/library/shlex.html) for shell-escaping and splitting on shell quote boundaries? I feel confident I've seen it before but I can't remember the name.

**Comment by mrjbq7** [comment]
Are you thinking of this?

https://github.com/factor/factor/blob/master/basis/simple-tokenizer/simple-tokenizer.factor

**Comment by mrjbq7** [comment]
@erg also added this which is more like a shell parser, into an AST of sorts you could process. 

https://github.com/factor/factor/blob/master/extra/shell/parser/parser.factor

**Comment by catb0t** [comment]
`simple-tokenizer` is perfect for this, and the `shell.parser` will come in handy i think. thanks!
