### ISSUE TITLE
TravisCI log files have funny encoding?

### ISSUE THREAD

**Issue by erg** [factor/factor#2058]
Not that important, but maybe we can fix this?

https://api.travis-ci.org/v3/job/420872190/log.txt

```
" is encoded as â€œ
```

**Comment by catb0t** [comment]
```
$ file log.txt 
log.txt: UTF-8 Unicode text, with very long lines, with CRLF, CR, LF line terminators, with escape sequences
```

I always thought the funny characters were ESC or just a Travis bug? maybe contact support

**Comment by bpollack** [comment]
It's not `"`; it's `✓` and `•`. The log is output as UTF-8, but, because Travis is not serving up an encoding (just `text/plain`), both Chrome and Firefox, plus tools like HTTPie, are falling back to assuming ISO-8851. This might be fixable.

**Comment by bpollack** [comment]
Seems like the only way to fix this is just to know on the rendering side to use UTF-8. Looking in the web UI, that's what Travis does; it's just on the remote side it's an issue. (And it's hopelessly broken if you toss `?deansi=true` into the log URL, AFAICT.)

**Comment by erg** [comment]
We stopped using travis-ci. Closing for now.
