### ISSUE TITLE
Support tab as valid white space in listener

### ISSUE THREAD

**Issue by rjperrella** [factor/factor#2060]
Would it be wrong to support tab as a valid white-space character in the listener? I find myself pasting code from other sources into the listener and it gets upset at the tab character.

**Comment by mrjbq7** [comment]
I've always disliked mixing tabs and spaces, but two possible solutions:

1) you can monkey patch the lexer so your Factor instance ignores tabs (maybe putting in your ``.factor-rc`` or use ``.factor-boot-rc`` to modify it when bootstrapped, or paste this code in and ``save``).

```factor
IN: lexer
: forbid-tab ( c -- c ) ;
```

2) make a ``lexer`` sub-class that skips tabs and spaces in its implementation of the ``skip-blank`` word.

3) perhaps modify the listener when getting copy-paste to ``replace`` the tabs with spaces...

**Comment by rjperrella** [comment]
Agreed . I generally don't use them either. But since Factor assigns no meaning to white-space, it seems harmless enough.  If it's not important enough to fix for others, I can monkeypatch for now. Thanks!

**Comment by mrjbq7** [comment]
It’s a good question. If we have others that want it or would like an easy way to enable it, then it might make sense to add. I just don’t generally like tabs and spaces together so that’s a personal bias. If it helps Factor developers, by all means let’s consider making it easier than monkey patching. 

It might require one or two small additions besides just not throwing an error from forbid-tab. I didn’t quite test the monkey patch but it’s likely not complex.

**Comment by mrjbq7** [comment]
Not production ready, maybe, but useful attempt at throwing a restart:

```diff
diff --git a/basis/listener/listener.factor b/basis/listener/listener.factor
index 46806b5404..3399fe7fb1 100644
--- a/basis/listener/listener.factor
+++ b/basis/listener/listener.factor
@@ -36,6 +36,11 @@ SYMBOL: handle-ctrl-break
     [ disable-ctrl-break ] [ ] cleanup ; inline
 
 : parse-lines-interactive ( lines -- quot/f )
+    dup [ CHAR: \t swap member-eq? ] any? [
+        "input contains tabs"
+        { { "Ignore Tabs" t } { "Continue" f } }
+        throw-restarts [ [ CHAR: \t swap remove ] map ] when
+    ] when
     [ [ parse-lines ] with-ctrl-break ] with-compilation-unit ;
 
 : read-quot-step ( lines -- quot/f )
```

**Comment by mrjbq7** [comment]
(That version strips tabs from everything, including strings and other objects, which isn't perfect).

Better would be to probably instrument the lexer to strip (or not) the tabs when it sees them.

Anyway...
