### ISSUE TITLE
Long strings in Inspector show only integer values, not characters

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2063]
When using the Inspector on long strings (Factor 0.98), the prefix of the string is shown as a string of characters, but the Contents pane shows key-value pairs where the key is the index in the string, and the value just an integer value of the (utf8?) character code, but NOT the value displayed as character.

This makes inspecting a string in the Inspector unnecessary difficult. Please show (also) characters.

**Comment by mrjbq7** [comment]
Do you like the indexed character by character view? Or prefer some other way to inspect the string?

**Comment by nomennescio** [comment]
My internal Unicode look-up table is quite limited, so I would prefer a presentation which (also) shows the corresponding glyph/grapheme for each indexed character.

**Comment by AlexIljin** [comment]
Unicode is tricky to display by-code-point, as some have to be collated to produce the correct glyph, but for 90 of the cases I, too, find it inconvenient to Inspect a `string` as a run of digits.

@nomennescio, have a look at the `prettyprint.config` vocabulary. Setting `string-limit?` to `f` may eliminate the need for Inspecting the `string`s in the first place. See also `length-limit` and `line-limit`.

**Comment by nomennescio** [comment]
@AlexIljin thanks for the tip on prettyprint.config. I would still need to inspect strings occasionally.

**Comment by AlexIljin** [comment]
Having just experimented with the settings mentioned above (by me), I can sadly say that the only useful result comes from those if you want to prettyprint a string with the `.` word. The Inspector still shows the truncated string in its window heading, the Data Stack in the Listener also truncates the sting, as well as the Walker in its Data stack view. Those are all the places that often make me sad when I can't see the end of a long pathname my code is working on.

**Comment by mrjbq7** [comment]
It’s easy enough to change the behavior and have less sadness if we know what changes to make!

**Comment by AlexIljin** [comment]
Counterintuitively, all the three places of sadness I mentioned derive their limitation from `prettyprint.config:margin` - which is supposed to be the wrapping margin, and not an "ellipsis generator". Reading the docs, I would expect the ellipsis to be controlled by the `length-limit` in the various Data Stack representations.

BTW, I don't recommend setting `margin` to `f`, and then calling the Inspector for a `string` : )) That case is, apparently, not handled well.

So, my suggestion would be to use `line-limit` instead of `margin` when displaying the strings in the Data/Retain stacks in Listener, Walker and Inspector, as well as when prettyprinting them with `.`. And support the documented option to set it to `f` - with horizontal scroll bars where necessary.

**Comment by mrjbq7** [comment]
Would you like something like this?

```diff
diff --git a/basis/ui/tools/inspector/inspector.factor b/basis/ui/tools/inspector/inspector.factor
index 059b68680c..dedfa8432c 100644
--- a/basis/ui/tools/inspector/inspector.factor
+++ b/basis/ui/tools/inspector/inspector.factor
@@ -1,8 +1,9 @@
 ! Copyright (C) 2006, 2009 Slava Pestov.
 ! See http://factorcode.org/license.txt for BSD license.
-USING: accessors arrays assocs classes combinators fonts fry
-hashtables inspector io io.styles kernel math.vectors mirrors
-models models.arrow namespaces prettyprint sequences sorting ui
+USING: accessors arrays assocs classes combinators
+combinators.short-circuit fonts formatting fry hashtables
+inspector io io.styles kernel math.vectors mirrors models
+models.arrow namespaces prettyprint sequences sorting strings ui
 ui.commands ui.gadgets ui.gadgets.labeled ui.gadgets.panes
 ui.gadgets.scrollers ui.gadgets.status-bar ui.gadgets.tables
 ui.gadgets.tables.private ui.gadgets.toolbar ui.gadgets.tracks
@@ -66,7 +67,14 @@ M: inspector-renderer column-titles
 GENERIC: make-slot-descriptions ( obj -- seq )
 
 M: object make-slot-descriptions
-    make-mirror [ <slot-description> ] { } assoc>map ;
+    make-mirror
+    [ [ <slot-description> ] { } assoc>map ] keep
+    { [ enumerated? ] [ seq>> string? ] } 1&& [
+        [
+            dup [ value>> ] [ value-string>> ] bi
+            "%c (%s)" sprintf >>value-string
+        ] map!
+    ] when ;
```

**Comment by nomennescio** [comment]
I'm not sure how I can review the result of such a patch easily, but if I look at the code I think I understand what you did: format values for strings as integer and as string values "%c (%s)", which seems OK to me.

**Comment by mrjbq7** [comment]
Well, instead of:

```
Key | Value
0     115
1     116
2     114
3     105
4     110
5     103
```

It's instead:

```
Key | Value
0     s (115)
1     t (116)
2     r (114)
3     i (105)
4     n (110)
5     g (103)
```

But maybe it should instead be:

```
Key | Value
0     115 (s)
1     116 (t)
2     114 (r)
3     105 (i)
4     110 (n)
5     103 (g)
```

You can still click each row and "push" their character (as an integer) to the stack...

It doesn't really change the issue with being cut off like ``"this is long text..."`` but maybe that's a separate improvement.

**Comment by nomennescio** [comment]
Well, I'm fine with either solution.

**Comment by mrjbq7** [comment]
I wonder if instead it should just be:

```
Key | Value
0     s
1     t
2     r
3     i
4     n
5     g
```

You can always push the number ...

**Comment by AlexIljin** [comment]
The variability of the number of digits is much greater than that of the character widths (especially when a fixed-width font is used, as in my case). So, "%s (%d)" would align much better along a vertical line.

Consider this example:
```
Key | Value
0     T (64)
1     o (111)
2     р (1088)
3     G (71)
4     e (101)
5     а (1072)
6     r (114)
```
versus
```
Key | Value
0     84 (T)
1     111 (o)
2     1088 (р)
3     71 (G)
4     101 (e)
5     1072 (а)
6     114 (r)
```
Omitting the number would also be fine for most cases, or could be a configuration option.

**Comment by mrjbq7** [comment]
Here's code that does character-by-character (and unprintables are either ``\x01`` or ``\u{200b}``).

```diff
diff --git a/basis/ui/tools/inspector/inspector.factor b/basis/ui/tools/inspecto
r/inspector.factor
index 059b68680c..da32481aa0 100644
--- a/basis/ui/tools/inspector/inspector.factor
+++ b/basis/ui/tools/inspector/inspector.factor
@@ -1,13 +1,14 @@
 ! Copyright (C) 2006, 2009 Slava Pestov.
 ! See http://factorcode.org/license.txt for BSD license.
-USING: accessors arrays assocs classes combinators fonts fry
-hashtables inspector io io.styles kernel math.vectors mirrors
-models models.arrow namespaces prettyprint sequences sorting ui
-ui.commands ui.gadgets ui.gadgets.labeled ui.gadgets.panes
-ui.gadgets.scrollers ui.gadgets.status-bar ui.gadgets.tables
+USING: accessors arrays assocs classes combinators fonts
+formatting fry hashtables inspector io io.styles kernel math
+math.parser math.vectors mirrors models models.arrow namespaces
+prettyprint sequences sorting strings ui ui.commands ui.gadgets
+ui.gadgets.labeled ui.gadgets.panes ui.gadgets.scrollers
+ui.gadgets.status-bar ui.gadgets.tables
 ui.gadgets.tables.private ui.gadgets.toolbar ui.gadgets.tracks
 ui.gestures ui.operations ui.theme ui.tools.browser
-ui.tools.common ui.tools.inspector.slots ;
+ui.tools.common ui.tools.inspector.slots unicode ;
 
 IN: ui.tools.inspector
 
@@ -68,6 +69,16 @@ GENERIC: make-slot-descriptions ( obj -- seq )
 M: object make-slot-descriptions
     make-mirror [ <slot-description> ] { } assoc>map ;
 
+M: string make-slot-descriptions
+    [
+        swap [ dup number>string ] dip dup
+        dup printable? [ 1string ] [
+            dup 0xff <
+            [ "\\x%02x" sprintf ]
+            [ "\\u{%x}" sprintf ] if
+        ] if slot-description boa
+    ] map-index ;
+
 M: hashtable make-slot-descriptions
     call-next-method [ key-string>> ] sort-with ;
 
```

**Comment by nomennescio** [comment]
Shouldn't that test be: ```dup 0xff <=``` ?

**Comment by mrjbq7** [comment]
Hah, probably yes. 

Also, any thoughts on if any of these would be preferred for you?

**Comment by nomennescio** [comment]
I think I prefer
``` 
0     T (64)
1     o (111)
2     р (1088)
3     G (71)
4     e (101)
5     а (1072)
6     r (114)
```
because I'm not sure people would never want to see the numeric value.

**Comment by nomennescio** [comment]
Oh, and I do like your hex/unicode code-point format instead of plain integers.

**Comment by mrjbq7** [comment]
A variant that properly encodes the supported escapes, otherwise printable, otherwise hex or unicode escapes:

```diff
+M: string make-slot-descriptions
+    [
+        swap [ dup number>string ] dip dup
+        dup printable? [ 1string ] [
+            dup 0xff < [
+                H{
+                    { CHAR: \a "\\a" }
+                    { CHAR: \b "\\b" }
+                    { CHAR: \e "\\e" }
+                    { CHAR: \f "\\f" }
+                    { CHAR: \n "\\n" }
+                    { CHAR: \r "\\r" }
+                    { CHAR: \t "\\t" }
+                    { CHAR: \v "\\v" }
+                    { CHAR: \0 "\\0" }
+                } ?at [ "\\x%02x" sprintf ] unless
+            ] [
+                "\\u{%x}" sprintf
+            ] if
+        ] if slot-description boa
+    ] map-index ;
```

**Comment by mrjbq7** [comment]
Note: the change above only affects the UI inspector, the command line inspector just uses ``make-mirror``...

**Comment by AlexIljin** [comment]
Will this change ever be added into the Factor source? I noticed that Inspector still doesn't display characters in the latest build.

**Comment by AlexIljin** [comment]
Created a [PR](#2090) with a slightly updated version of the last code suggested by @mrjbq7.
Extracted some of commentary into the new issue #2091, so that this issue could be closed when the PR is merged.

**Comment by AlexIljin** [comment]
@mrjbq7, think my PR produced a more consistent output.

**Comment by mrjbq7** [comment]
I decided I didn't like showing the integer code point.  You can get it by double clicking or right clicking to push its value, and edit slot also works with the integer code point.  I think that's less frequently used than wanting to see the character contents.  I guess, it's a question of style, but I liked the "one to one" mapping of index to character.

**Comment by AlexIljin** [comment]
I see your point. I'll keep it in my Factor fork, though, because sometimes inspecting a string is all about finding weird Unicode codepoints that otherwise look as normal ASCII characters. See the "TopGear" example above that has Cyrillics intermixed with Latin.

**Comment by AlexIljin** [comment]
Clicking those individually... : )

**Comment by AlexIljin** [comment]
This issue may be closed, I think.
