### ISSUE TITLE
Chat for Factor request

### ISSUE THREAD

**Issue by v0idNULL** [factor/factor#2067]
My humble request for launching some chat for informal conversation about Factor. Maybe something like Gitter or Slack. Or forum via Discourse, maybe. I don't know. I think mailing list is not comfortable enough. If this request is not convenient for some reason, just delete it.

**Comment by mrjbq7** [comment]
It's not a bad idea.  We've got the ``#concatenative`` IRC channel but I know that I've been too busy to hang out there lately.

**Comment by bpollack** [comment]
I'd really prefer Discourse (or something asynchronous like that) over yet another chat. We've already got the underused IRC channel and an underused mailing list. I think doing something to increase the visibility of our discussions (like what Discourse does) could be valuable, but I don't think switching to a proprietary chat offering would accompliah that.

**Comment by catb0t** [comment]
https://gitter.im/ is designed for exactly this, it's open source and i'm guessing if there was interest, an instance could be hosted on factorcode.org

**Comment by erg** [comment]
I created a gitter. Let's see how it goes. I've been using the Kitten gitter and it's nice to have messages about it in my email.

We still have #concatenative on freenode irc.

https://gitter.im/factorcode/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
