### ISSUE TITLE
USE: furnace fails due to missing dependencies

### ISSUE THREAD

**Issue by bpollack** [factor/factor#2068]
Diving in already, but `USE: furnace` includes `furnace/alloy/alloy.factor`, which has `USING: ... furnace.auth.login.permits`, which includes `furnace/auth/login/permits/permits.factor`, which has `USING: ...` for `furnace.auth`, which goes back to `furnace/auth/login/login.factor`, which attempts to fetch `get-permit-uid`, which is not yet defined (it's in `auth/login/permits/permits.factor`).

**Comment by bpollack** [comment]
Seems like a circular dependency; choosing to reload `permits.factor` resolves things. But that's begging the question a bit.

**Comment by mrjbq7** [comment]
It might be my buggy requires patch for the docs loading thing. I was going to look also but have been busy.

**Comment by bpollack** [comment]
@mrjbq7 I thought so, but when I went back to 91b17cb28b (which I assume is what you're mentioning), I could still repro. So I'm not sure that's it. I'll try to bisect it later today if I have a few.

**Comment by bpollack** [comment]
Wait, I did that silly; the issue was absolutely introduced in 91b17cb28b0106d20505d4bf223015f4fe119871. Lemme see if I can find another approach here.
