### ISSUE TITLE
Memoizing xdg-* functions seems like a bad idea

### ISSUE THREAD

**Issue by spacefrogg** [factor/factor#2071]
Somewhen during the summer the way, how `MEMO:` functions get memoized, changed. Or the way how the bootstrap process works, for that matter. The `xdg-*` functions fail to pickup changes of the environment due to being memoized and saved in the image, which obviously defies their meaning.

**Comment by mrjbq7** [comment]
Not sure why I added ``memoize`` when when I migrated it from ``extra`` to ``basis`` in 73d430bfb9ac222128c5cd750a61ce49e095b04c.

Removed in f3d1d785cd2c369615989757d3301f7b4548696a.

Thanks!
