### ISSUE TITLE
How do you quit the interpreter?

### ISSUE THREAD

**Issue by WiggyWire** [factor/factor#2074]
So I been looking through the docs I can't find out how to quit the interpreter? Ok control + c then inexplicably q ^d. These key bindings seem to have been created with the opposite of ease of use in mind.

Also why is it so slow and bloated?

**Comment by AlexIljin** [comment]
If it weren't so slow and bloated, it would not be modern now, would it?

To quit the interpreter you could use the `exit` word from the `system` vocab.

**Comment by catb0t** [comment]
(On Unix) Ctrl+C sends a signal, SIGINT ('interrupted') to the running process, Ctrl+D sends 0x04, `End of Transmission` which is the standard  way to tell a program reading stdin to stop reading stdin. `read`, `cat`, `python3`, etc all exit when Ctrl+C and Ctrl+D are pressed.

**Comment by jonenst** [comment]
Can you elaborate on what you find slow and bloated in the listener ?

**Comment by erg** [comment]
It's standard unix exit stuff. If you have a specific bloat complaint, report it on the email list or file a new issue.
