### ISSUE TITLE
Build farm nightly builds have broken 

### ISSUE THREAD

**Issue by catb0t** [factor/factor#2077]
All the development builds have crashed, the last good ones were all on 7 September. Is this because of #2068 (or already reported)? 

I've bootstrapped on Windows and Linux x64 many times since then without problems, it's just the build machines.  

http://builds.factorcode.org/dashboard

**Comment by erg** [comment]
It's because of #2068.

**Comment by catb0t** [comment]
Thanks!

**Comment by AlexIljin** [comment]
Great work, @erg, now I can have the latest build!
