### ISSUE TITLE
R/ (regexp syntax) can't end with backslash

### ISSUE THREAD

**Issue by jonenst** [factor/factor#2079]
The following works and removes the content between the slash and the backslash
```factor
"a/   \\bc" "/.*\\" <regexp> "" re-replace print
! abc
```

The following works and removes the content between the slash and the next character after a backslash
```factor
"a/   \\bc" R/ \/.*\\./ "" re-replace print
! ac
```

The following throws "Unterminated regexp" at compile time : 
```factor
"a/   \\bc" R/ \/.*\\/ "" re-replace print
! throws
```

The last one should work and produce the same regexp object as the first one no ?

**Comment by mrjbq7** [comment]
I think this is fixed with 2136abc1d64705805c5274337a799077f4b317e4.

**Comment by mrjbq7** [comment]
Reverting the fix, I misunderstood something and want to get clean builds before fixing again.

**Comment by mrjbq7** [comment]
Maybe this is a good fix:

26abdf4a23def8a62513d60d96dade8554ef9c0e
