### ISSUE TITLE
Fix Factor's floating point round trip printing with Ryu algorithm

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2083]
- [ ] Add 32bit Ryu
- [ ] Add 16bit Ryu
- [ ] Add additional word to golf Ryu output while still maintaining round trips, e.g. 3.14e0 is 3.14
- [ ] Benchmark/optimize
- [ ] Consider using c++ ryu in vm for speed in addition to having the Factor version
- [ ] Replace float printer with Ryu

---

See this example from the mailing list:

```factor
IN: scratchpad { -13.8 -21.8 -3.99 -3.0 -15.7 126.98 -8.9 100.0 -21.8 } sum .
137.99
IN: scratchpad { -13.8 -21.8 -3.99 -3.0 -15.7 126.98 -8.9 100.0 -21.8 } sum 100 * .
13799.0
```

vs.

```python
>>> a = [-13.8, -21.8, -3.99, -3.0, -15.7, 126.98, -8.9, 100.0, -21.8]
>>> sum(a)
137.98999999999998
>>> sum(a) * 100
13798.999999999998
>>> int(sum(a) * 100)
13798
```

**Comment by catb0t** [comment]
(it was pointed out on the mailing list, but if you add `>integer` to the Factor snippet, it prints `13798` even though the input appeared to be `13799.0`)

**Comment by jonenst** [comment]
It's a bug. It's #1555 .

**Comment by erg** [comment]
Someone should port this algorithm:

https://news.ycombinator.com/item?id=17632158

**Comment by AlexIljin** [comment]
Porting an algorithm sounds like a fun task. I could try.

**Comment by AlexIljin** [comment]
Could you point out which functions we need from here: https://github.com/ulfjack/ryu

**Comment by erg** [comment]
@AlexIljin There's also this: https://github.com/quinnj/Ryu.jl/blob/master/src/Ryu.jl

There looks like a lot of boilerplate in the first version.

**Comment by AlexIljin** [comment]
The Julia code supports 16-, 32- and 64-bit floats. Am I right that we only need the 64-bit support?

**Comment by erg** [comment]
We have float16 (half floats), float32, and float64. You can do any/all of those!

**Comment by AlexIljin** [comment]
I can't find float16 in the help system, and `math.floats.half` vocabulary says it's only for FFI. If I wanted to differentiate between different float variable sizes that were given to a word input, how would I do that? I can test if number is a `float?`, which would be a double-precision float according to the docs, but I can't find more specific words to tell float16 from float32.

In Julia the code is generic, for example based on argument type it looks up the exponent sizes (probably some values are dummies):
```
exponentbits(::Type{Float16}) = UInt32(0)
exponentbits(::Type{Float32}) = UInt32(0)
exponentbits(::Type{Float64}) = UInt32(11)
```
How can I do the same in Factor?

**Comment by mrjbq7** [comment]
We have float64 native type. I’d start there.

**Comment by AlexIljin** [comment]
I have ported the algorithm, and it produces exactly the same numbers for the starting code in this thread:
```
IN: scratchpad { -13.8 -21.8 -3.99 -3.0 -15.7 126.98 -8.9 100.0 -21.8 } sum f print-float .
137.99
IN: scratchpad { -13.8 -21.8 -3.99 -3.0 -15.7 126.98 -8.9 100.0 -21.8 } sum 100 * f print-float .
13799.0
```

**Comment by AlexIljin** [comment]
While working on this, I wanted to make sure the original Julia code was working. Had to familiarize myself with their package management in the process, but in the end it turned out that [it doesn't actually work](https://github.com/quinnj/Ryu.jl/issues/1).

I have ported the unit-tests from the original C implementation, and most of them are passing now, but some give me trouble I can't yet understand

**Comment by jonenst** [comment]
When I looked into this for #1555 I came to the conclusion that https://github.com/google/double-conversion was a good way to solve all the problems.

How does this solution compare to using https://github.com/google/double-conversion ?

**Comment by AlexIljin** [comment]
The Ryu author cites some prior art and provides benchmarks, which demonstrate that it's way faster than the Grisu3 and the Jaffer's/JDK algorithms. From what I can see here, the Google's double-conversion library, was pulled from their V8 JavaScript engine. Here's [a blog post](http://www.serpentine.com/blog/2011/06/29/here-be-dragons-advances-in-problems-you-didnt-even-know-you-had/) that says that V8 is based on Grisu.

**Comment by AlexIljin** [comment]
I have pushed the latest state here: https://github.com/AlexIljin/ryu
Some tests are still failing, but some are passing!

**Comment by erg** [comment]
@AlexIljin This is awesome!

I'm going to run it and try to track down a bug or two if I can.

Check out this idea on variables: https://github.com/factor/factor/issues/2089#issuecomment-450184994

**Comment by erg** [comment]
```factor
{ -13.8 -21.8 -3.99 -3.0 -15.7 126.98 -8.9 100.0 -21.8 } [ d2s ] map ...
{
    "-1.38e1"
    "-2.18e1"
    "-3.99e0"
    "-3e0"
    "-1.57e1"
    "1.2698e2"
    "-8.9e0"
    "1e2"
    "-2.18e1"
}
```

**Comment by mrjbq7** [comment]
sum d2s ?

**Comment by AlexIljin** [comment]
I have added some missing tests and fixed the last bug. The initial work is done.
```
IN: scratchpad { -13.8 -21.8 -3.99 -3.0 -15.7 126.98 -8.9 100.0 -21.8 } sum d2s .
"1.3798999999999998e2"
```

A note from the author: "core Ryu only supports generating shortest round-trip-safe output". So this is not something we could use for all our float formatting, but he is working on further formatting options.

**Comment by AlexIljin** [comment]
The Factor implementation is now referenced from the Ryu authors' readme.
Spreading the word...

**Comment by jonenst** [comment]
From my rigorous benchmarks™ the factor ryu code is only 4 times slower than what's used on my ubuntu system for number>string ( the c++ stdlib std::ostringstream in default mode (general) with a precision of 16 and C locale )

Of course the ryu code is better for us because it produces shortests float representations that round trip (ie we can change the benchmark code to dup d2s string>number assert= !)

```factor
USING: benchmark.parse-float ryu math.parser math.functions ;
! like parse-float-benchmark from extra/benchmark/parse-float.factor
 : parse-ryu-benchmark ( -- )
    test-floats [
        [ d2s string>number ] [ 1e-10 ~ t assert= ] bi
    ] each ;
[ parse-ryu-benchmark ] profile 14 top-down-max-depth profile.
[ parse-float-benchmark ] profile 14 top-down-max-depth profile.

! ryu
! depth   time ms  GC %  JIT %  FFI %   FT %
!  14     521.0   1.92   0.00  70.25   0.00   print-float
!
! stringstream
! depth   time ms  GC %  JIT %  FFI %   FT %
!  14     135.0   0.74   0.00  70.37   0.00   M\ float >base

```

**Comment by jonenst** [comment]
Note: 135ms for 100k doubles for ostringstream means 1350 nanos per double, which is somewhat consistent with the benchmarks here: https://github.com/miloyip/dtoa-benchmark

ryu is expected to do 30 nanos per double (40x faster) cf https://github.com/dtolnay/ryu
(I get this on my machine:
```
$ cargo run --example benchmark --release
             Average   Stddev
pretty32:      21.617    1.958
pretty64:      29.493    2.346
```
)

(ryu looks awesome for performance!)

**Comment by jonenst** [comment]
There are lots of bignum operations, but ryu is supposed to be fixed-width. Is this because we only have 60bits signed integers ie in range [-2^59;2^59), or is there something else going on ? Also I can benchmark this on a 32 bit plaform (where we have only 28bits signed ints) later

also there are a lot more bignum operations for small numbers of digits:

```factor
USING: benchmark.parse-float ryu math.parser math.functions ;

 : parse-ryu-benchmark2 ( -- )
    100000 [
        0.1 d2s drop
    ] times ;
 : parse-ryu-benchmark3 ( -- )
    100000 [
        0.123456789123456789 d2s drop
    ] times ;

[ parse-ryu-benchmark2 ] profile 15 top-down-max-depth profile.
[ parse-ryu-benchmark3 ] profile 15 top-down-max-depth profile.

! small number of digits
! depth   time ms  GC %  JIT %  FFI %   FT %
!   14     890.0   1.24   0.00  85.17   0.00 T{ thread f "Listener" ~curried~ ~quotation~ 34 ~box~ f t f H{ }...
!   15     530.0   0.94   0.00  97.74   0.00   bignum/i

! large number of digits, like in the random test
! depth   time ms  GC %  JIT %  FFI %   FT %
!   14     447.0   0.89   0.00  71.59   0.00 T{ thread f "Listener" ~curried~ ~quotation~ 34 ~box~ f t f H{ }...
!   15     138.0   0.72   0.00  97.83   0.00   bignum/i
```

**Comment by AlexIljin** [comment]
I think we need to add more aggressive type hinting for the compiler. At the moment the code is too generic. Also, I think it would be beneficial to get rid of (most of) the locals, but I'm not sure if that would improve performance of the compiled code.

**Comment by jonenst** [comment]
Well if bignum/i appears in the profile, it means actual bignums are used so adding type hinting won't help. Maybe add >integer calls would help, it coerces bignums to fixnums when they fit.

**Comment by AlexIljin** [comment]
Which is faster: `x dup 10 /i 10 * =` or `x 10 rem zero?`?

**Comment by jonenst** [comment]
10 mod zero? is faster, it uses the idiv instruction directly.

Le ven. 28 déc. 2018 à 19:19, Alexander Iljin <notifications@github.com> a
écrit :

**Comment by AlexIljin** [comment]
Umm... I asked about `rem` not `mod`.

**Comment by jonenst** [comment]
on my machine 10 mod zero? is faster than dup 10 /i 10 * number= which id
faster than 10 rem zero?

Le ven. 28 déc. 2018 à 20:13, Alexander Iljin <notifications@github.com> a
écrit :

**Comment by mrjbq7** [comment]
Why not use divisor?

**Comment by AlexIljin** [comment]
OK, so `rem` is the slowest. Thank you! I won't change that part, then.

**Comment by AlexIljin** [comment]
@jonenst, I have improved performance of the code, could you run your benchmarks again, please?

**Comment by AlexIljin** [comment]
@erg, are you 100% sure about that? Are locals as compiler-optimizable as stack manipulations?
At least stack shuffling is easier to debug in the Watcher, I learned that much. : )

**Comment by AlexIljin** [comment]
I mean, isn't there a separate Retain stack at run-time, from which values need to be pulled? Or is the Retain stack completely optimized out?
Are you saying the following two loops are completely run-time equivalent, no matter how many locals are used by the surrounding code?
```
0 :> i!
[ i count < ] [
...
  i 1 + i!
] while
```
```
0 [ dup count < ] [
...
  1 +
] while
```
For me it looks like there will be extra variable access code on every iteration if locals are used.

**Comment by erg** [comment]
Updated the top comment to make a todo list for finally fixing this issue.

**Comment by AlexIljin** [comment]
I didn't know that `number>string` was using a `PRIMITIVE` call into the VM code. It absolutely makes sense to put Ryu into the VM as well, especially since it's C++ code in the first place. Makes me question why we need the Factor version. : ))
The problem is, Ryu is not very formatting-friendly. It always outputs the "e" character, which is not very readable, even if fast.
In C++ code Ryu will shine due to the absence of the bignum arithmetic.

**Comment by mrjbq7** [comment]
It would be nice if we could make the std c++ be correct/ish even if slow. Mostly because of the quirky ryu e0/e1/e2 etc outputs.

**Comment by erg** [comment]
there's also https://github.com/jk-jeon/dragonbox

**Comment by mrjbq7** [comment]
Should be fixed now!
