### ISSUE TITLE
ulid library

### ISSUE THREAD

**Issue by erg** [factor/factor#2092]
https://github.com/ulid/spec/blob/master/README.md

We need this! Or not, just saw it on hackernews.

**Comment by AlexIljin** [comment]
The code is tiny! I can port the Delphi implementation, as that's the language I'm most familiar with.
I could use it instead of GUIDs in my DB structures.

**Comment by AlexIljin** [comment]
Actually, I see that a lot of implementations are only generating the ULIDs, but not parsing them. Most don't even handle the documented case of same-millisecond generation case.

**Comment by AlexIljin** [comment]
It works, but I still plan to add some tests and a tiny bit of documentation (basically, a link to the GitHub spec).

**Comment by AlexIljin** [comment]
What does the `jellyfish` label mean?

**Comment by mrjbq7** [comment]
Cool libraries we should work on some day. Was some kind of inside joke, the origins of which have been lost to time.

**Comment by mrjbq7** [comment]
@AlexIljin can you add some tests and make a PR?

**Comment by AlexIljin** [comment]
Yes, I'll do it.

**Comment by catb0t** [comment]
this should be closed as #2097 was merged.
