### ISSUE TITLE
Travisci on windows

### ISSUE THREAD

**Issue by erg** [factor/factor#2094]
I disabled travisci for windows again because I can't get it to find Visual Studio and compile.

I'm trying to install Visual Studio Enterprise and run the ``vcvarsall.bat`` script to load up the env for the compiler, but it's hard to see if it worked or not and it still won't execute ``build.cmd`` after.

Here's a branch if anyone wants to fix it.

https://github.com/factor/factor/tree/travis-windows

Note: there's a bug where any ``choco install foo`` hangs the build if there are TravisCI secure variables from the Settings page. I removed all secure variables from the build so ``choco install`` works now. The build is still broken, but not for this reason.

**Comment by catb0t** [comment]
AppVeyor? appveyor.com

**Comment by erg** [comment]
We don't need travis ci anymore. Closing for now.
