### ISSUE TITLE
heaps bug

### ISSUE THREAD

**Issue by jonenst** [factor/factor#2103]
Heaps have a bug when you remove entries from the middle of the heap:

```
[let
<min-heap> :> heap
0  dup heap heap-push
5  dup heap heap-push
2  dup heap heap-push
6  dup heap heap-push* :> DEL
3  dup heap heap-push
4  dup heap heap-push
1  dup heap heap-push
DEL heap heap-delete
heap [ drop . ] slurp-heap
]
0
1
3
2 ! BUG
4
5
```
@mrjbq7 looking at the source code, it seems you rewrote them in 3aa14d7570c 

The following patch fixes the bug but I don't think it should go in as is (see questions/suggestions after the patch):

```
diff --git a/basis/heaps/heaps.factor b/basis/heaps/heaps.factor
index b92bfe3..fae8d8f 100644
--- a/basis/heaps/heaps.factor
+++ b/basis/heaps/heaps.factor
@@ -133,7 +133,7 @@ M: heap heap-push*
     ] while drop
 
     tmp over heap data-set-nth
-    heap n rot sift-down ; inline
+    heap 1 rot sift-down ; inline
 
 PRIVATE>
 
```

Reading the source, I had the following questions/suggestions:
   - sift-up and sift-down are exchanged compared to the binary heaps wikipedia article https://en.wikipedia.org/wiki/Binary_heap , rename them ?
  - your sift-up bubbles the element down to a leaf of the tree and then bubbles it back up to the highest possible node, why not stop at the right time during the bubble down (like you did for your sift-down)
   - The bug was that when removing elements, after the bubble down, the bubble up part was limited to where the element was deleted. But in some cases you need to bubble it up even higher. Here, why not bubble down or up according to the value of the parent directly?

let me know what you think

Cheers

**Comment by mrjbq7** [comment]
Hmmmm! Bug!

The intent was to follow similar logic to the comment in siftdown and siftup here, which has some alleged advantages. 

https://github.com/reingart/pypy/blob/master/lib-python/2.7/heapq.py

I’m traveling today, but will look later.

**Comment by mrjbq7** [comment]
Could be a problem only affecting min-heaps?

I noticed there are two versions of sift-up and sift-down... one for min-heaps and one for max-heaps.  Maybe the bug is we only have one version.

```factor
[let
<max-heap> :> heap
0  dup heap heap-push
5  dup heap heap-push
2  dup heap heap-push
6  dup heap heap-push* :> DEL
3  dup heap heap-push
4  dup heap heap-push
1  dup heap heap-push
DEL heap heap-delete
heap [ drop . ] slurp-heap
]
5
4
3
2
1
0
```

**Comment by jonenst** [comment]
```
[let
<max-heap> :> heap
6  dup heap heap-push
3  dup heap heap-push
5  dup heap heap-push
0  dup heap heap-push* :> DEL
1  dup heap heap-push
2  dup heap heap-push
4  dup heap heap-push
DEL heap heap-delete
heap [ drop . ] slurp-heap
]
```
```
6
5
3
4
2
1
```
We need only one sift-up and one sift-down, the only difference between a min-heap and the max-heap is the ordering which is already correctly handled by the heap-compare generic word.

By the way I generated the counter example with:
```

:: foo ( n -- ?  )
<max-heap> :> heap
H{ } clone :> entries

n [
{
{ 1/2 [ random-32 dup [ heap heap-push* ] [ entries set-at ] [ "push %d\n" printf ] tri ] }
{ 1/2 [ entries keys [ random [ entries at heap heap-delete ] [ entries delete-at ] [ "delete %d\n" printf ] tri ] unless-empty ] }
} casep
] times
heap V{ } clone [ [ nip push ] curry slurp-heap ] keep >array dup natural-sort reverse =
 ;
 [ 8 foo nl ] loop
```

Note that using slurp-heap, we modify the heap so we may end up "fixing" it when slurping, but the heap invariant breakage can be seen directly on the data: here's a shorter counter example that looks good when using slurp-heap, but already has the buggy behavior. it's exactly the same problem as before: we remove the bottom left zero and replace it with the last element (4), so 4 should bubble up to 3 but it doesn't (the code only allows to bubble down)
```
[let
<max-heap> :> heap
6  dup heap heap-push
3  dup heap heap-push
5  dup heap heap-push
0  dup heap heap-push* :> DEL
1  dup heap heap-push
4  dup heap heap-push
heap data>> heap. nl
DEL heap heap-delete
heap data>> heap. nl
heap [ drop . ] slurp-heap
]
```
```
   6
 3   5
0 1 4 f

   6
 3   5
4 1 f f

6
5
4
3
1
```

**Comment by mrjbq7** [comment]
Sure, let’s fix the bug. And see how performance is impacted. I’m not super attached to the code, let’s make it better!

**Comment by jonenst** [comment]
Yes!

>
