### ISSUE TITLE
Compatibility with macOS Mojave dark mode

### ISSUE THREAD

**Issue by nicolas-p** [factor/factor#2108]
- In macOS Mojave with dark mode selected in System Preferences, the title bar of every Factor window is still light

- It is possible to get a title bar that matches the rest of the system (light or dark) by executing this command:
```defaults write org.factorcode.Factor NSRequiresAquaSystemAppearance 0```

- But then every window only displays the bottom left quarter of its contents, with 2x zoom (something to do with Retina, probably). Resizing the window only slightly brings everything back to normal

<img width="766" alt="capture d ecran 2019-01-12 a 23 13 48" src="https://user-images.githubusercontent.com/11431580/51079009-bd2e3f00-16bf-11e9-92e7-81f4ddb1fabe.png">

So here's a list of improvements that we could make:

- [x] Make Factor automatically take a dark title bar if macOS is in dark mode (the equivalent of the command above but without having to type it)

- [ ] Make Factor automatically switch its interface to dark mode if macOS is in dark mode, but let the user override this by having three options in the "Switch Theme" menu: Light, Dark, Auto

- [ ] Fix the bug that makes windows display only a quarter of their contents

- [x] Bonus: When I designed the dark mode, I chose a dark blue theme (Solarized) that I really like, but it doesn't match the dark grey that Apple chose. Do you think it should be changed to match the rest of the system? (I'm not saying I want to change it, but I'd like to know what you think.)

**Comment by mrjbq7** [comment]
Some possible code ideas to switch automatically (although currently, we don't re-render the listener when switching), in ``ui/backend/cocoa/views/views.factor``:

```factor
    ! Dark Mode

    METHOD: void viewDidChangeEffectiveAppearance [
        self -> effectiveAppearance -> name [
            CF>string {
                { "NSAppearanceNameAqua" [ light-theme ] }
                { "NSAppearanceNameDarkAqua" [ dark-theme ] }
            } case switch-theme
        ] when*
    ] ;
```

**Comment by mrjbq7** [comment]
Okay, initializing the theme and switching when the OS changes it is working.

**Comment by mrjbq7** [comment]
I think this is all working properly now.
