### ISSUE TITLE
macOS input methods don't work, need to upgrade to NSTextInputClient in ui.backend.cocoa.views (Japanese)

### ISSUE THREAD

**Issue by erg** [factor/factor#2111]
From the mailing list:

1) Enable Japanese Hiragana input methods
2) Observe that typing out characters and selecting a completion should replace your typed characters, which aren't even showing up

``NSTextInput`` is deprecated and ``NSTextInputClient`` is the replacement. If that doesn't completely solve it, we can continue.

https://bugzilla.mozilla.org/show_bug.cgi?id=875674

https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html

**Comment by kusumotonorio** [comment]
I think the replacement from NSTextInput to NSTextInputClient can't solve this problem unless its methods are implemented appropriately.
In an opposite way, even with NSTextInput, I anticipate the appropriate implementation of methods can solve it.

I'm writing a experimental code for it. But I'm in trouble.
In setMarkedText:selectedRange: ,  I can't convert text from a NSString to a factor string by CF>string. I got the error "Unix signal #6 (SIGABRT)". 
The word works fine in insertText: .

```
    ! Text input
    METHOD: void insertText: id text
    [
        self window :> window
        window [
            text CF>string window user-input
        ] when
    ] ;

    METHOD: char hasMarkedText [ 0 ] ;

    METHOD: NSRange markedRange [ 0 0 <NSRange> ] ;

    METHOD: NSRange selectedRange [ 0 0 <NSRange> ] ;

!    METHOD: void setMarkedText: id text selectedRange: NSRange range [ ] ;

    METHOD: void setMarkedText: id text selectedRange: Nsrange range 
[ 
        self window :> window
        window [
! ok -->          "abc"
! ok -->          "xyz" <CFString> CF>string 
! "alien "        text class-of "%s " sprintf
            text CF>string   ! Error  Unix signal #6 (SIGABRT) 
            window world-focus user-input* drop
        ] when
] ;
```

**Comment by kusumotonorio** [comment]
I've got stuck.
For example, I use the return key to confirm the conversion string, but I can not operate well because the key input to IM such as return passes over to Factor.

I expected the key input to be received first by the IM, and the app received the input that was not consumed, but it seems that the IM can't receive the input unless the Factor backend sends a key-down event.
![inline-input](https://user-images.githubusercontent.com/47816570/55955306-03357780-5c9c-11e9-98e8-e41b2fadaac0.png)

**Comment by kusumotonorio** [comment]
It is now possible to display underlines during inline Japanese conversion. I have made several other improvements and believe that I have achieved my goal.

You can see a video of the conversion and input:
https://kusumotonorio.github.io/images/factor-inline-3.mov

![factor-inline-3](https://user-images.githubusercontent.com/47816570/58382489-9d137280-8005-11e9-92af-00308387ed3b.png)

**Comment by mrjbq7** [comment]
Cool!!! 

Did you already make a PR for that?

Thanks!!!

**Comment by kusumotonorio** [comment]
I haven't done it yet. I will continue to improve it for a while.

**Comment by kusumotonorio** [comment]
I did the PR for this issue.

https://github.com/factor/factor/pull/2156/

**Comment by erg** [comment]
This issue seems resolved. Reopen if not.
