### ISSUE TITLE
How to get bit-identical `factor.image`s from the same boot image?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#2114]
If I say 

```
./factor -i=boot.unix-x86.64.image 
sha256sum ./factor.image > old.sum
./factor -i=boot.unix-x86.64.image 
sha256sum ./factor.image > new.sum
```
With all else equal, then `old.sum` contains `ef7ef315c54db8b8f1b7ec56525b0bb4d5843571dcf1e820e22d44f17e2bc593` and `new.sum` contains `aa688561ecfc5382ae400b9a5ec8fb6e2a0cfdf9bdf8e2a97821bae312d4c8d5`. 

What causes these to be different, despite the boot image and Factor VM being the same? Does the bootstrap process compile in things like the current time, or is the x86 compiler nondeterministic? 

I'm interested in a way to get  the same checksum from consecutive re-compiles with the same VM/boot image -- maybe with an optional command-line flag to the bootstrap process. Any hints?

**Comment by catb0t** [comment]
This is because hashtables don't have a defined order, isn't it? That's sort of insurmountable...

**Comment by slavapestov** [comment]
- Hashtable order is non deterministic
- The memory address where the image is mapped is non-deterministic (and thus all interior pointers etc)
- More non-determinism from background coroutines allocating memory then 'sleep'ing

It's an insurmountable problem I think.

**Comment by catb0t** [comment]
Yeah, that makes sense! time to re-write the entire compiler ;)

**Comment by timor** [comment]
Is this also true for deployed applications?

**Comment by catb0t** [comment]
@timor you can test this yourself by building `hello-ui` twice and checksumming the resulting binaries after each build. If the checksums aren't the same for two builds, they will never match. 

I can't test on mobile but since even the basic lookup layouts use hashtables, it's almost definitely nondeterministic.
