### ISSUE TITLE
Race condition with clicking UI background

### ISSUE THREAD

**Issue by erg** [factor/factor#2117]
Type something that will error like ``asdfasdf`` and hold down enter. The ui should scroll and keep throwing restarts. Put your cursor where you can click the ui background while holding enter and click the background several times rapidly. It will try to call ``focusable-child*`` on ``f`` for some reason and you'll see a popup if you do it right.

```
IN: scratchpad :s
f
f
T{ no-method f f focusable-child* }
IN: scratchpad :r
DL{ ~send-gesture-tuple~ ~send-gesture-tuple~...
DL{ ~send-gesture-tuple~ ~send-gesture-tuple~...
DL{ ~send-gesture-tuple~ ~send-gesture-tuple~...
{ ~popup~ ~glass~ }
T{ button-down f f f }
2
1
f
IN: scratchpad :c
(U)
Quotation: [ set-namestack init-catchstack self quot>> call => stop ]
(O)
Word: update-ui-loop
(O)
Word: send-queued-gestures
(O)
Method: M\ propagate-gesture-tuple send-queued-gesture
(O)
Word: resend-gesture
(O)
Method: M\ object handle-gesture
(O)
Word: request-focus
(O)
Word: focusable-child
(O)
Method: M\ object focusable-child*
(O)
Word: no-method
(O)
Method: M\ object throw
(U)
Quotation: [
    OBJ-CURRENT-THREAD special-object error-thread set-global
    current-continuation => error-continuation set-global
    [ original-error set-global ] [ rethrow ] bi
]
```

**Comment by catb0t** [comment]
I can't reproduce this on Linux because clicking the UI background closes the error restart window. Is that not true for macos? Maybe it's cocoa only...

**Comment by erg** [comment]
I'm actually on Windows. I'll try on macOS.

**Comment by AlexIljin** [comment]
My Factor on Windows hanged dead with no error when I tried that trick. The text cursor stopped blinking, and I could not even drag the Listener window by the title.

Next time I tried that, I got a system error dialog with WerFault.exe.
![2019-02-24 20_11_52-factor exe](https://user-images.githubusercontent.com/169039/53304041-516bf400-3871-11e9-86ac-31cfca3a418e.png)

**Comment by nomennescio** [comment]
Cannot reproduce: Factor@bebdb54543aa12d9510fecf43addc608091c7655 on Windows. As soon as I click the background Factor stops executing the word.

**Comment by erg** [comment]
```
(U) Quotation: [ set-namestack init-catchstack self quot>> call => stop ]
(O) Word: update-ui-loop
(O) Word: send-queued-gestures
(O) Method: M\ propagate-key-gesture-tuple send-queued-gesture
(O) Method: M\ interactor handle-gesture
(O) Word: resend-gesture
(O) Method: M\ object handle-gesture
(O) Word: request-focus
(O) Word: focusable-child
(O) Method: M\ object focusable-child*
(O) Word: no-method
(O) Method: M\ object throw
(U) Quotation: [
    OBJ-CURRENT-THREAD special-object error-thread set-global
    current-continuation => error-continuation set-global
    [ original-error set-global ] [ rethrow ] bi
]
```
