### ISSUE TITLE
mnapply behaves mysteriously for n > 3

### ISSUE THREAD

**Issue by kevinpatton** [factor/factor#2120]
`mnapply` behaves mysteriously for n > 3. As you can see, its stack effect size grows exponentially as n increases past 3.

    USE: generalizations
    IN: scratchpad 1 1 [ * . ] 2 1 mnapply ! works as expected
    1
    IN: scratchpad 1 1 2 2 [ * . ] 2 2 mnapply ! works as expected
    1
    4
    IN: scratchpad 1 1 2 2 3 3 [ * . ] 2 3 mnapply ! works as expected
    1
    4
    9
    IN: scratchpad 1 1 2 2 3 3 4 4 [ * . ] 2 4 mnapply ! huh?
    ! Error: stack underflow
    IN: scratchpad [ 1 1 2 2 3 3 4 4 [ * . ] 2 4 mnapply ] infer.
    ( x x -- x x )
    IN: scratchpad [ 1 1 2 2 3 3 [ * . ] 2 3 mnapply ] infer.
    ( -- )
    IN: scratchpad [ 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 [ * . ] 2 9 mnapply ] infer.
    ( x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x -- x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x )
    IN: scratchpad [ [ * . ] 2 4 mnapply ] infer.
    ( x x x x x x x x x x -- x x )
    IN: scratchpad 1 1 2 2 3 3 4 4 5 5 [ * . ] 2 4 mnapply
    4
    1
    25
    16
    
    --- Data stack:
    3
    3

P.S. I could be misinterpreting the intent of the word. My understanding of how it is supposed to work is that it is a generalization of words like `2tri@` which would be equivalent to `2 3 mnapply`. (P.P.S. this is my first time submitting a bug report so sorry if I did anything wrong.)

**Comment by mrjbq7** [comment]
Thank you!

Fixed in ada81e77f54f6e4a92345bb2f8e5b02cc2c8ecc9.
