### ISSUE TITLE
Invalid code example in the "prettyprint-literal" article

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#2122]
The example code is:
```
TUPLE: rect w h ;

SYNTAX: RECT[
    scan-word
    scan-word \ * assert=
    scan-word
    scan-word \ ] assert=
    <rect> suffix! ;
```
After running this code in the listener, the example literal `RECT[ 100 * 200 ]` throws the error: "No word named “100” found in current vocabulary search path".

**Comment by mrjbq7** [comment]
This works:

```factor
SYNTAX: RECT[

    scan-number

    scan-token "*" assert=

    scan-number

    scan-token "]" assert=

    <rect> suffix! ;
```

Probably related to some refactoring of the ``scan-`` words awhile back.

**Comment by erg** [comment]
Fixed I believe.
