### ISSUE TITLE
Build machine broken?

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#2134]
Hello!

  It seems that all development builds except Linux x64 are almost a month old. Is something broken on the build server?

**Comment by AlexIljin** [comment]
Still broken.

**Comment by erg** [comment]
The Corsair H100 water cooler leaked out and destroyed the GTX970. I am getting a new fan soon and it'll be back up.

**Comment by erg** [comment]
It's back with a Noctua NH-D15S and a Radeon 370.
