### ISSUE TITLE
lines, unlines, words, unwords

### ISSUE THREAD

**Issue by nicolas-p** [factor/factor#2140]
I think we could steal these useful fonctions from Haskell. Their definitions would be:
```
: lines ( seq -- seq ) "\n" split ; inline
: unlines ( seq -- seq ) "\n" join ; inline
: words ( seq -- seq ) " " split ; inline
: unwords ( seq -- seq ) " " join ; inline
```

Some usage statistics in the Factor codebase:
`"\n" split` used 18 times
`"\n" join` used 59 times
`" " split` used 50 times
`" " join` used 57 times

There are currently no words named `unlines`, `words` or `unwords` but there is already a word called `lines` in the `io` vocabulary. If this is a problem, here are some alternative names:
```
: split-lines ( seq -- seq ) "\n" split ; inline
: join-lines ( seq -- seq ) "\n" join ; inline
: split-words ( seq -- seq ) " " split ; inline
: join-words ( seq -- seq ) " " join ; inline
```

**Comment by jonenst** [comment]
There's https://docs.factorcode.org/content/word-string-lines,splitting.html
which also handles "\n\r"

Le mar. 7 mai 2019 à 08:24, Nicolas Pénet <notifications@github.com> a
écrit :

**Comment by mrjbq7** [comment]
We also do [ blank? ] split-when a lot.

**Comment by erg** [comment]
The current `io:lines` could be `read-lines` and `string-lines` could be `lines` (it handles \r\n and \n). Then `unlines` is fine with the simple definition.

For `words`/`unwords`, there is also ``" " split1`` and ``" " split1-slice`` that we might want words for.

**Comment by erg** [comment]
Ok! I did this one more or less.

`string-lines` -> `split-lines`
`unlines` => `join-lines`
`words` -> `split-words`
`unwords` -> `join-words`

`io:lines` -> `io:read-lines`
`io:contents` -> `io:read-contents`

The one thing to watch out for is `split-lines` is not the same as `"\n" split` in that it eats the last single newline if there is one (double newline gets a `""` entry in the array). Some unit tests relied on the extra newline like `{ "a" "b" "c" "" }` but are now the more natural `{ "a" "b" "c" }`.
