### ISSUE TITLE
Table gadget performance patches?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2144]
Review these two patches for possibly improving table gadget performance:

[ table gadget: improved performance with large datasets ]
https://github.com/klazuka/factor/commit/a5d94bbd2d482fc210c31bb92b936439586d8528

[  core-text: lazy text render ]
https://github.com/klazuka/factor/commit/e98b3620b3b8d025e55610c2d3aacc1f63890d57

**Comment by AlexIljin** [comment]
The second commit already has a comment from you:
```
 mrjbq7 commented on e98b362 on Aug 28, 2011

I merged this into Factor's main branch. Thanks!
```

**Comment by mrjbq7** [comment]
Hah!
