### ISSUE TITLE
Library: DLL" yaml" missing

### ISSUE THREAD

**Issue by luftluft** [factor/factor#2147]
`
IN: scratchpad "a" >yaml
Cannot resolve C library function
Library: DLL" yaml"
Symbol: yaml_emitter_initialize
DlError: dlopen(yaml, 9): image not found
See http://concatenative.org/wiki/view/Factor/Requirements

Type :help for debugging help.
`
Factor 0.99 x86.64 (1903, heads/master-13b0da9182, Jun 11 2019 08:54:59)
[Clang (GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29))] on macosx

**Comment by mrjbq7** [comment]
We don't bundle ``libyaml``, you can get it for macOS like this:

```
$ brew install libyaml
```

Then try it again.

Long term it might be nice to have our own cross-platform Factor implementation of YAML encoding/decoding, but right now we use ``libyaml``.

**Comment by ak11ci** [comment]
hello @mrjbq7,

I‘ve run `brew install libyaml` to install libyaml,and there's no error.

But it looks like no work in factor.

`USE: yaml`

Input: `"a" >yaml`

```
Cannot resolve C library function
Library: DLL" yaml"
Symbol: yaml_emitter_initialize
DlError: dlopen(yaml, 9): image not found
```
macos m1

Factor 0.99 x86.64 (2098, heads/master-8515fe960b, Oct 30 2021 00:19:36)
[Clang (GCC Apple LLVM 12.0.5 (clang-1205.0.22.11))] on macosx
