### ISSUE TITLE
stirling word in math.extras is broken

### ISSUE THREAD

**Issue by chunes** [factor/factor#2149]
I get `cannot execute a word before it has been compiled` when I try to use it.

**Comment by melted** [comment]
It works if one removes the private markers around
```factor
<PRIVATE

DEFER: stirling

: (stirling) ( n k -- x )
    [ [ 1 - ] bi@ stirling ]
    [ [ 1 - ] dip stirling ]
    [ nip * + ] 2tri ;

PRIVATE>
```
I thought moving the `DEFER:` outside the private area would fix it, but apparently it doesn't (it works for `bernoulli` below).
