### ISSUE TITLE
After running the Factor Listener for a long time, empty error window pops up. Time-out in draw-world.

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2173]
While running the Factor Listener 0.98 64 bits on Windows, after several hours, an empty error window pops up. The Listener and Browser are still responsive, and I can close the error window. Don't know what is causing it, or the seriousness of this error. See attachment for screenshot.
![Factor-Error](https://user-images.githubusercontent.com/24315005/64067679-d4a94080-cc2c-11e9-8d56-ccf7583aebdb.png)

**Comment by erg** [comment]
Try getting the error in another window with ``:s`` and ``:c``

**Comment by nomennescio** [comment]
![CropperCapture 30](https://user-images.githubusercontent.com/24315005/64078545-4db3a100-ccdc-11e9-8274-27b8f28679a7.png)

**Comment by erg** [comment]
Maybe it just times out sometimes and we're being too pedantic about checking error values? If you change the error checking to just ``drop`` the return value it might be more correct. (Best fix might be to make a version of ``win32-error=0/f`` that ignores error 258?)

```factor
M: win-base select-gl-context
    [ hDC>> ] [ hRC>> ] bi wglMakeCurrent drop
    GdiFlush drop ;
```

**Comment by mrjbq7** [comment]
Looks like a call to wglMakeCurrent timed out?

https://github.com/factor/factor/blob/master/basis/ui/backend/windows/windows.factor#L692

Maybe an issue with flushing previous rendering context?

https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-wglmakecurrent

**Comment by erg** [comment]
Whoa.

**Comment by erg** [comment]
Try this?
```
diff --git a/basis/windows/errors/errors.factor b/basis/windows/errors/errors.factor
index 83a8df0148..2bd86e02f9 100644
--- a/basis/windows/errors/errors.factor
+++ b/basis/windows/errors/errors.factor
@@ -728,7 +728,12 @@ ERROR: windows-error n string ;
 : win32-error ( -- )
     GetLastError (win32-error) ;

+: win32-error-ignore-timeout ( -- )
+    GetLastError
+    dup 258 = [ drop ] [ (win32-error) ] if ;
+
 : win32-error=0/f ( n -- ) { 0 f } member? [ win32-error ] when ;
+: win32-error=0/f-ignore-timeout ( n -- ) { 0 f } member? [ win32-error-ignore-timeout ] when ;
 : win32-error>0 ( n -- ) 0 > [ win32-error ] when ;
 : win32-error<0 ( n -- ) 0 < [ win32-error ] when ;
 : win32-error<>0 ( n -- ) zero? [ win32-error ] unless ;
```

```factor
M: win-base select-gl-context
    [ hDC>> ] [ hRC>> ] bi wglMakeCurrent win32-error=0/f-ignore-timeout
    GdiFlush drop ;
```
