### ISSUE TITLE
Running from the commandline shows no output (Windows)

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2175]
Consider the program hw.factor:
USING: io kernel ;
IN: hw

: hello-world ( -- ) "Hello World!" print ;
MAIN: hello-world

When running this from the cmd.exe commandline with
factor.exe -run=hw
it does not show any output.

Similarly when running the same executable from Cygwin Bash.

When running the same file (!) from within Debian, it correctly prints to stdout.

It seems stdout is not being created on Windows?

**Comment by mrjbq7** [comment]
Or not being flushed on exit?

**Comment by nomennescio** [comment]
Changed code to
: hello-world ( -- ) "Hello World!" print flush ;

with no change in results.
If I load the same vocabulary in the Listener, the output does show.

**Comment by nomennescio** [comment]
I am running Debian under VirtualBox on the same machine, so Windows, Cygwin and Linux are accessing the same file and the same underlying OS.

**Comment by melted** [comment]
The `factor.com` executable is compiled as a console app and has stdin and stdout hooked up.

**Comment by nomennescio** [comment]
OK, that works, but it is a bit strange to use the .com executable format. Manipulating stdin and stdout handles in a Windows application is a bit of a pain, but it helps if these can be inherited from the parent process. I guess it's good enough. Will check if I find any peculiarities.

**Comment by nomennescio** [comment]
Looking through the documentation on factorcode, I found the reason for having two executables: it is stated that for console output, you need to display a console windows, which need to be marked by an executable flag, and is not possible by win32. That statement is false, see issue

**Comment by erg** [comment]
``factor.exe`` opens detached from the console, while ``factor.com`` opens attached to it. The idea is you call the one that you need, and I believe that's the only difference.

What's the action here, can we close this?

**Comment by nomennescio** [comment]
Possibly related to https://github.com/factor/factor/issues/2287

**Comment by nomennescio** [comment]
Solved by #2204
