### ISSUE TITLE
Unexpected "Cookie value must not be f" error

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2176]
I'm trying to make a connection to a server, using session cookies. I have a running example with working curl parameters. which I'm trying to translate to Factor. Upon my first GET http-request, I receive three cookies, and I want to set these for the subsequent POST http-request. However, just storing the cookies from the response object into the request object raises an unexpected "Cookie value must not be f" error, Upon inspection, I received this cookie (prettyprinted):

T{ cookie { name "Secure" } }

(raw)

T{ cookie f "Secure" f f f f f f f f f }

What's the problem here? How to solve?

**Comment by mrjbq7** [comment]
Using put-cookie?

https://docs.factorcode.org/content/word-put-cookie,http.html

**Comment by mrjbq7** [comment]
Did you ever figure this out?

**Comment by nomennescio** [comment]
No, I abandoned it for now because I could not proceed.

**Comment by erg** [comment]
``put-cookie`` is clearly broken as it is calling ``name>>`` on a ``request`` or ``response`` object which both don't have that slot.
```factor
<request> T{ cookie { name "Secure" } } over put-cookie

Generic word name>> does not define a method for the request class.
Dispatching on object: T{ request f f URL" " URL" " "1.1" H{ ~array~ ~array~ } f...
```

**Comment by mrjbq7** [comment]
No it isn't!

```
<request> T{ cookie { name "Secure" } } put-cookie
```

**Comment by mrjbq7** [comment]
Do you have any example code showing the issue?

**Comment by nomennescio** [comment]
I probably did some things horribly wrong, but this was what started this report:
```
TUPLE: rtc server cookies ;

: <rtc> ( server-url -- rtc-instance ) rtc new swap >>server ;

: <rtc-request> ( rtc rest-path -- request ) [ server>> present ] dip append >url H{ } clone >>query
  request new swap >>url
  <url> >>proxy-url
  "1.1" >>version
  max-redirects >>redirects
  H{ } clone >>header
  V{ } clone >>cookies
  "vibrowser" "user-agent" set-header
  ! "rtcaway" "user-agent" set-header
  "keep-alive" "connection" set-header
  ! "close" "connection" set-header
;

CONSTANT: REST-identity       "secure/authenticated/identity"
CONSTANT: REST-security-check "secure/authenticated/j_security_check"

! :: kv! ( assoc key value -- assoc ) value key assoc set-at assoc ;

:: <rtc-session> ( username password server-url -- rtc )
  server-url <rtc> dup dup
  REST-identity <rtc-request> "GET" >>method http-request* drop cookies>> >>cookies
  dup cookies>> swap REST-security-check <rtc-request> swap >>cookies
  "application/x-www-form-urlencoded" <post-data> { "j_username=" username "&j_password=" password } concat utf8 encode >>data utf8 >>content-encoding
  ! "text/plain" <post-data> binary >>content-encoding H{ { "j_username" username } { "j_password" password } } clone >json >byte-array >>data
  >>post-data "POST" >>method http-request* 2drop
;
```

I think I did also some experimenting by hand. I had a hard time getting to understand things from the documentation; it was many times too obscure for me.
