### ISSUE TITLE
Release schedule/plan?

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2177]
When re-viewing Slava's excellent Google talk from 2008, it struck me the original plans to release Factor 1.0 and Factor 2.0 were already laid out; Factor 2.0 should be completely rewritten, and build with native threading in mind. As for a timeline: "within a year or two".

That was 11 years ago. I'm not sure what happened in between, but it seems Slava abandoned Factor, and all the (very much appreciated) efforts put in afterwards seem to be still delaying to go over the magic "1.0" boundary, let alone think about a completely rewritten 2.0 version.

 Is there any release schedule or plan on how to move the language forward towards those magic goals Slava once laid out?

**Comment by mrjbq7** [comment]
Short answer is yes. 

Long answer is different contributors have different priorities. Slava had some professional obligations that I think reduced his ability to contribute to Factor. 

Quite a lot of stabilization has been done and new libraries and experiments with new “2.0” parsing techniques as well as experiments on better concurrency approaches. Native threads are probably still some distance away but mostly because no one is currently pushing on that. 

As for “2.0”, I’m still leaning towards having a 0.100 release at some point just for fun and to break people’s version number parsing assumptions. But also because version numbers are sort of meaningless unless you start providing certain kinds of stabilization guarantees, for example binary compatibility. 

We have a team of new contributors starting a 6-8 month project on improvements and while I’m not sure which direction they are going to head in, I think we should see some nice additions coming down the pipeline. 

If you have stuff you think is important for your use cases, (for example, NixOS support), please push on it and help us help you and vice versa.

**Comment by kusumotonorio** [comment]
I'm a newcomer, but I can imagine that the lack of Slava to develop Factor is a major obstacle to its release. I understand that some contributors have continued to good improve, but it seems to be getting harder to keep up with the surrounding environment before the release. Changes such as the rise of ARM CPUs and OpenGL's decay also need to be addressed in near forture.

If something like me can contribute to Factor improvement, I think it means that contributors are in short supply. To increase the number of developers, I think it is necessary to establish the syntax of Facotr and publish a book explaining it.

**Comment by odiferousmint** [comment]
> As for “2.0”, I’m still leaning towards having a 0.100 release at some point just for fun and to break people’s version number parsing assumptions

Not sure that is a good idea, or at least not for that reason alone. Why not just go with 1.0 instead, then?

> while I’m not sure which direction they are going to head in

Yeah, this may be an issue though. Is there a way to bring Slava back, if for anything, just for looking over the development of the project to make sure it does not diverge too far from its philosophy? I would really love if he would be able to review any future commits or decisions, especially ones involving design. If not, why not? Can it be solved in any way?

> establish the syntax of Factor and publish a book explaining it.

By establishing I hope you are not referring to changing it. I am all up for publishing a book on it, or on Factor itself. For the time being, one could benefit from:

- https://concatenative.org/wiki/view/Factor/Learning
- https://docs.factorcode.org/content/article-syntax.html
- https://www.dnd.utwente.nl/~tim/colorforth/Leo-Brodie/thinking-forth.pdf

**Comment by mrjbq7** [comment]
I think you misunderstand. @erg and I are the current maintainers, with many contributors, and provide the philosophical direction. We both have well over a decade of contributions and have used Factor professionally .  This is not a “one developer” language and while we have lost some things with Slava’s reduced presence, we have by no means stalled.

**Comment by odiferousmint** [comment]
> I think you misunderstand. @erg and I are the current maintainers, with many contributors, and provide the philosophical direction. We both have well over a decade of contributions and have used Factor professionally . This is not a “one developer” language and while we have lost some things with Slava’s reduced presence, we have by no means stalled.
> […](#)
> On Sep 8, 2019, at 6:28 AM, odiferousmint ***@***.***> wrote: As for “2.0”, I’m still leaning towards having a 0.100 release at some point just for fun and to break people’s version number parsing assumptions Not sure that is a good idea, or at least not for that reason alone. Why not just go with 1.0 instead, then? while I’m not sure which direction they are going to head in Yeah, this may be an issue though. Is there a way to bring Slava back, if for anything, just for looking over the development of the project to make sure it does not diverge too far from its philosophy? I would really love if he would be able to review any future commits or decisions, especially ones involving design. If not, why not? Can it be solved in any way? establish the syntax of Factor and publish a book explaining it. By establishing I hope you are not referring to changing it. I am all up for publishing a book on it, or on Factor itself. For the time being, one could benefit from: https://concatenative.org/wiki/view/Factor/Learning https://docs.factorcode.org/content/article-syntax.html https://www.dnd.utwente.nl/~tim/colorforth/Leo-Brodie/thinking-forth.pdf — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you for clarification. This is good to hear. Keep up the good work! By the way, have you thought of giving people the means to financially support the project, perhaps on Patreon or wherever?

**Comment by timor** [comment]
@kusumotonorio 
> If something like me can contribute to Factor improvement, I think it means that contributors are in short supply...

I would rather say that speaks for the Factor code base and your dedication :)

I recently got to look at parts of the compiler implementation in more detail.  I can not remember having a more pleasant experience looking at and working with someone else's code...

**Comment by ArnautDaniel** [comment]
There's a certain comfort to the small size I think.  And the lead devs are really awesome here. 

For my part, even though I've had several other projects I've had to tend to, I'd like to try to finish my Factor book this holiday season.  I'm hoping there can be some draw in using Factor to make games with Raylib.  At least it seems like a good way to entice people to try their hand at concatenative programming and get a graphical result.  

@kusumotonorio is working on some cool stuff bringing a prolog-esque library in.  

Then, of course, there's plenty of devs way above us working on other sweet stuff.  Version numbers are arbitrary.  Factor still has a lot going on, and a seemingly respectable level of passion projects.

**Comment by erg** [comment]
We will try to release more often starting with .99 pretty soon. Closing as this is not actionable. (Reopen if there's an action to take)
