### ISSUE TITLE
Writer monad log reads backwards

### ISSUE THREAD

**Issue by kevinpatton** [factor/factor#2185]
As you may well know, the purpose of the writer monad is to produce a concatenated log of the effect of function compositions. For instance, this would be a way to calculate the golden ratio while logging what was done:

    USING: monads math math.functions prettyprint ;
    FROM: monads => do ;
    
    {
        [ 5 "Started with five, " <writer> ]
        [ sqrt "took square root, " <writer> ]
        [ 1 + "added one, " <writer> ]
        [ 2 / "divided by two." <writer> ]
    } do .

Unfortunately, this prints:

    T{ writer
        { value 1.618033988749895 }
        { log
            "divided by two.added one, took square root, Started with five, "
        }
    }

Redefining the `writer` method for `>>=` to change `append` to `prepend` rectifies the issue:

    M: writer >>=
        [ run-writer ] curry
        [ dip [ run-writer ] compose dip prepend <writer> ] curry ;

Now the above example works as intended:

    T{ writer
        { value 1.618033988749895 }
        { log
            "Started with five, took square root, added one, divided by two."
        }
    }

**Comment by mrjbq7** [comment]
Fixed in 9a8b1f8d8e66e69873601f7e1eb400f53ea136a0, thanks!
