### ISSUE TITLE
Fix naming inconsistencies

### ISSUE THREAD

**Issue by odiferousmint** [factor/factor#2186]
I suppose any inconsistencies in naming could go here. One instance I ran into just now is the mixed use of `n-bit` and `nbit`, for example: `64-bit`, `32bit?`, `8-bit`, `8-bit?`, `8bit?<<`, `each-8bit`, `extended-8-bit-registers?`, and so forth. I suppose we could agree on one form and rename it everywhere for consistency. Thoughts? By the way, if you want, you may change the name of the issue to `Naming inconsistencies` or `Inconsistencies in naming`, or anything of the like you see fit.

**Comment by mrjbq7** [comment]
Fixed in 8660606ca7c9e5f2970c835eafbc96fc74c33955 and 7ac200dc2bf979ff4a43c4802804625cb8390524
