### ISSUE TITLE
Running build.sh net-bootstrap fails on Cygwin64 with CLANG

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2199]
When trying to run build.sh net-bootstrap from Cygwin64 with clang installed, I got the following error:
```
Building factor with 8 cores
make factor factor-ffi-test factor-lib CONFIG=vm/Config.windows.x86.64
make[1]: Entering directory '/d/project/build/factor'
windres.exe vm/factor.rs vm/resources.o
make[1]: *** No rule to make target 'vm/mvm-windows.hpp', needed by 'vm/master.hpp.gch'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/d/project/build/factor'
make: *** [GNUmakefile:185: windows-x86-64] Error 2
make failed
```

The mvm-windows.hpp comes from
`vm/Config.windows:PLAF_MASTER_HEADERS += vm/os-windows.hpp vm/mvm-windows.hpp`

No such file exist in the repo, although there is a mvm-windows.cpp and mvm.hpp.
Even worse,
 git log --full-history  -- vm/mvm-windows.hpp
shows such a file has never existed.

How come?

**Comment by mrjbq7** [comment]
We use ``build.cmd`` on windows, not sure if we've ever used ``build.sh`` in a cygwin environment like that?  @erg ?

**Comment by nomennescio** [comment]
It seems Cygwin support is fully built in. It would be great to have a free alternative to the MS proprietary toolchain working again. It seems like a minor issue. The Nmakefile does not reference that header file either, so maybe it can just be removed from GNUmakefile.

**Comment by nomennescio** [comment]
Just tried a little bit; it's more than just removing the vm/mvm-windows.hpp from the GNUmakefile. The current configuration only uses flags for the Cygwin g++ compiler, which are not suitable for the Cygwin clang c++ compiler. And it seems it misses some declarations. I will try to make it work, cannot be that difficult.

**Comment by nomennescio** [comment]
Seem Cygwin does not support the no-cygwin flag since gcc 4.0. To 'cross-compile' Windows binaries something else is needed instead. This might actually be a bit more work than anticipated.

**Comment by nomennescio** [comment]
Have successfully compiled both 32 bit and 64 bit versions of Factor under Cygwin using MinGW-W64 g++, which required only minor adaptations to the existing code. The only thing failing currently is running the 32 bit version due to missing DLLs, which I will try to fix.

**Comment by nomennescio** [comment]
The missing DLLs are just the MinGW-W64 runtime DLLs, which typically need to be installed separately, or delivered along the executable, Experiments to link everything fully static are on halt due to the difficulty of getting all linked DLLs to be substituted with static equivalents. A static executable of Factor with a limited number of libs statically linked in is already 10 times as big as the original one.

**Comment by bpollack** [comment]
Visual Studio 2019 adds native clang support. Have you tried simply updating things and trying with that version? If not, I can give it a shot later today. It might involve less work than getting everything to a good place with MinGW.

**Comment by nomennescio** [comment]
VS2019 isn't exactly free.

**Comment by mrjbq7** [comment]
Isn’t there a community edition that’s free for open source?

**Comment by bpollack** [comment]
Yes, there is, and since clang is MIT-licensed, I was wondering if that would qualify here. That said, if MinGW is properly building native Windows Factor versions, that's pretty nice.

**Comment by nomennescio** [comment]
MinGW build Factor:

![Factor-MinGW](https://user-images.githubusercontent.com/24315005/68211843-a3f0d900-ffd8-11e9-9019-7ac988c3a3f6.png)

**Comment by nomennescio** [comment]
Support for MingW support was merged
