### ISSUE TITLE
Change factor.exe to support stdio streams in a meaningful way

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2204]
In a recent issue (#2200) I discussed the need for factor.com if factor.exe could also handle stdio streams. Apparently there is a need to have factor.com to be running in the Console subsystem, so let's keep it that way. However, there is still a want to have a Factor program which does not run in the Console subsystem (which puts some unwanted restrictions on a program), but in the Win32 subsystem, but with support for stdio streams inherited from the parent process (as is typical for shells running in Mintty-like terminals).

I did some experiments and found out this is already supported out of the box, except for one tiny piece of code in `windows.factor`:
```
M: windows init-stdio
    console-app?
    [ init-c-stdio ]
    [ null-reader null-writer null-writer set-stdio ] if ;
```

The `console-app?` word checks if a Console is attached to this process (which is false for Win32 processes), in which case stdio is replaced by null-writers and a null-reader.

What if this was replaced by just the following code?
```
M: windows init-stdio
    init-c-stdio ;
```

In the experiment I did I got the following results:
* factor.com Console apps keep working as is
* factor.exe GUI apps keep working as is
* factor.exe apps that try to do stdio WITHOUT the parent process having supplied valid stdio handles (e.g. by running it from a cmd.exe Console window): keep working as is, i.e. no output on stdio AND no errors
* factor.exe apps that are executed by double-clicking in Windows File Explorer: keep working as is

So far so good, no change in observable behavior. Now what about using stdio on Win32 processes?

* factor.exe apps that try to do stdio WITH the parent process having supplied valid stdio handles (e.g. by running inside a Cygwin or MSys Mintty terminal) : do output/input over stdio handles instead of supplying null-writers

Exactly what I want! What about the last case, doing stdio from the Listener UI?

* factor.exe apps that force stdio from within the Listener UI WHEN stdio is supplied: works as expected sending data towards stdio 
* factor.exe apps that force stdio from within the Listener UI WHEN NO stdio is supplied: generate error message popup "I/O error `#9` Bad file descriptor"

ONLY the last case has different behavior. And I think you can argue that it is more than acceptable; you're forcefully trying to send data over non-existent stdio streams. Which is similar what would happen if you were to use stdio on files that were corrupted or similar things.

So my proposal is to change the code in windows.factor to the above code that allows stdio streams in Win32 processes.

But what would we gain? Well at least no annoying Console windows flying around if all we want to do is simple stdio. But there's something else.

When doing stdio the right way, stdio streams should be binary i.e. not translate a single newline into a  pair carriage return and newline characters. Why? Because in situations where carriage returns are REALLY needed (and there are only a FEW, most applications happily accept newline separated lines), one can always explicitly emit these. More importantly however, that makes using stdio in filters ('pipes') really useful if binary data is involved, i.e. for most data.

Secondly, another useful change is the parsing of the commandline arguments. In the Microsoft C library some defaults cause wildcard expansion/file globbing. Similar behavior is simulated by default in the MinGW compiler. However, most applications do NOT want such behavior, but want to parse directly the commandline arguments as processed by the shell only. Especially in filter-like applications, the application should be able to do any command line processing if it so wishes.

So that brings me to the final proposal:
* change windows.factor to remove the `console-app?` check to support stdio in Win32 processes
* in factor.exe, use binary streams, leave factor.com as is
* in factor.exe disable commandline wildcard expansion/file globbing, leave factor.com as is

For the last two bullets, the only additional thing required will be a slight change in one of the .cpp files to prevent globbing, and to set stdio streams to binary mode (which steers the C library). Using defines one can generate two objects out of a single file, linking the one into factor.com, the other into factor.exe. I can probably look into that as well.

In that way really meaningful commandline applications can be developed using factor.exe, which can run both in Cygwin/Msys AND in cmd.exe using BOTH stdio AND a GUI, without the need to flash a Console Window, all the while keeping factor.com as is for those who need its behavior. 

(Note that the practice of using stdio in Win32 applications is much older than this proposal, and can be seen in e.g. the Putty.exe application).

**Comment by mrjbq7** [comment]
So, in the "normal case" of launching ``factor.exe`` as a GUI application (double-click, etc.), your suggestion is that writing to ``stdio`` gets an error instead of being just lost forever via the ``null-writer``?  I'd have to think about that, but maybe we can detect ``stdio`` not being available and keep the current behavior in that case.

**Comment by mrjbq7** [comment]
What happens if you run ``factor.exe`` with this change from a CMD?  Does it effectively work like the current ``factor.com``?

**Comment by nomennescio** [comment]
> So, in the "normal case" of launching `factor.exe` as a GUI application (double-click, etc.), your suggestion is that writing to `stdio` gets an error instead of being just lost forever via the `null-writer`? I'd have to think about that, but maybe we can detect `stdio` not being available and keep the current behavior in that case.

Yes. However, it's not a real use-case, as one really has to take the trouble to explicitly write to stdio in the first place. By default, all output goes to the Listener anyway.

But indeed, a check could be added for valid stdio handles. I've considered that myself before I made this proposal. I think it does not add much; if the user wants he can always add such an explicit check himself, and for other situations, getting such an error can also occur due to conditions out of control of the user (broken pipes, failing disk systems etc.)

**Comment by nomennescio** [comment]
> What happens if you run `factor.exe` with this change from a CMD? Does it effectively work like the current `factor.com`?

For the stdio part, more or less yes (except for the part that no Console is being created). For the binary streams and file globbing; that's different (and more useful if you want to write meaningful commandline applications in Factor) from factor.com

**Comment by bpollack** [comment]
This is a much more reasonable proposal. I want to think about the implications of this exact design a smidge; while launching a Unix GUI app in the foreground and having output on the terminal is common, launching a GUI `.exe` and having the command prompt be locked up with its output's not as common. But I think a small tweak to the proposal somewhere (an ideological `factor.com /foreground`, although I'm not sure we'd call it that) would allow us to retire `factor.com`, and give you what you want.

@erg, any thoughts here? I'm stale on Windows Factor at the moment and may not be fully thinking through some of this.

**Comment by nomennescio** [comment]
@bpollack 

Starting the GUI from Windows File Explorer will not lock anything up at all.
Starting from cmd.exe will sync with the application.
Starting from bash.exe will allow the application to move from and to the background.

**Comment by nomennescio** [comment]
This proposal is only dealing with the stdio streams and commandline globbing.

There are still some other points to consider, but those need not to be immediately addressed at the same time, but can be handled separately:
* signals (out-of-band signalling)
* "ctrl_c_handler"
* Unicode (no, Windows *W functions are NOT Unicode) support

Typical Console subsystem programs combine many of these aspects into one "Console" approach, while I think it's better to treat these aspects independently of each other.

**Comment by nomennescio** [comment]
With no ctrl_c_handler installed, the default behavior is that in the GUI CTRL-C is ignored (=good), while in the Terminal window CTRL-C causes the factor.exe to exit (=good). I'm not sure about handling of resources in the latter case.

**Comment by mrjbq7** [comment]
This issue is going in too many directions for me.  I don't understand what it means to disable globbing, or what the issue is.  I don't understand what the issue is with "binary stdio" versus our current approach when the more typical case is textual output, you can always ``re-decode`` the ``output-stream`` to make it binary in your application.

The reason it's confusing might be terminology, or my unfamiliarity with your windows setup.  Let's take them one-at-a-time.

If you want ``factor.exe`` to work like ``factor.com`` does right now, that's fine.  Is this a sufficient change?  Is there anything else required?  Can we continue to support the ``null-writer`` case to avoid the error message when writing into the void?

**Comment by nomennescio** [comment]
I understand there's a lot of nitty-gritty detail involved that's hard to understand without delving into the details. Of course it's possible to approach this one step at a time. 

The eventual goal is to have these details in a reasonable default so that it abstracts from platform details, and allows to run factor code that does stdio from a shell without too much surprises, but ideally to be indistinguishable. That would allow a single code base to serve multiple platforms. This is exactly what Cygwin and Msys have accomplished, where there's enough commonality to run the same code on both Unices and Windows.

**Comment by nomennescio** [comment]
As for the `null-writer`, it's still there of course, but should not need to overwrite stdio handles if not run from factor.com. I think removing it is probably good enough. Alternatively a check could be implemented to see if valid handles are supplied. I'm not sure that such a check is possible without disturbing these streams.

**Comment by nomennescio** [comment]
Committed patch to inherit stdio handles : 943b4b4

**Comment by nomennescio** [comment]
Discussion: John doesn't like this without a fix for the `#9` error, which will be made.
Furthermore, this patch showed that on Github Actions, factor was not printing fatal errors because it had no valid stdout handle.
Probably creating a Console is not supported on Github Actions in certain contexts.

**Comment by nomennescio** [comment]
Proposed solution: check for valid std handles, use those, if none, use null reader/writers

**Comment by nomennescio** [comment]
NOTE: Factor's special objects `OBJ-STDIN`, `OBJ-STDOUT`, `OBJ-STDERR` are C library `FILE*`, and are hence compiler (not platform!) specific.

**Comment by nomennescio** [comment]
Let's define a meaningful way differently; the current issue is that Factor.exe is a Windows application and factor.com a Console application, which are designed to respond differently to streams. This is mainly because how historically command.com worked, and some people *really* want the *exact* behavior as a Console subsystem program. However both subsystem share the same initialization code. It's more useful to detect that difference, and introduce different behavior for the two executables based on that.

**Comment by nomennescio** [comment]
> What about AllocConsole?

Hi John, AllocConsole is what you *don't* want in `factor.exe`; it will
1. create a popup window with console handles (what is what you *don't* want when writing GUI applications)
2. overwrite existing std handles from the parent process.

The confusion arises because the way DOS/Windows traditionally handled std streams. Since Win32 however std streams are fully inherited by child processes, and should preferably be used. Since Windows 10 MS itself switched to a different model in using terminals, and made Console more or less obsolete. Using a shell like Cygwin or MSys Bash will correctly setup std streams for child processes, and all output will show in the terminal window.

You can still use `factor.com` to get the behavior you want.

**Comment by nomennescio** [comment]
Some background; on Unix terminals are devices with associated streams, and a command interpreter launches child processes and binds std handles for child processes, parses the command line, does file globbing etc.

That's not how `command.com` and `cmd.exe` work; they don't pass std handles to child processes, and they leave command-line parsing to the application, where sometimes the C lib does a bit of globbing, but only very limited. That has led that many "console applications" are expected to do that work by themselves, and many do so badly.

When porting "unix-like" commandline utilities, it's preferred to avoid that, and use the `-mwindows` flag, and stop the C lib to do globbing, and instead rely on an outer shell to do it for you. That's exactly how MSys and Cygwin are working, and it makes implementing commandline utilities a lot more similar to how you would write them under Unix; std streams are setup for you, and your commandline arguments are found as arguments to `main`.

This is also how `factor.exe` now works with this patch, so it's behaving very similar to Unix and MacOSX.

**Comment by nomennescio** [comment]
The nice thing of course is that is is also working nicely with std redirection

**Comment by nomennescio** [comment]
https://learn.microsoft.com/en-us/windows/console/getstdhandle

"When attaching to a new console, standard handles are always replaced with console handles unless STARTF_USESTDHANDLES was specified during process creation."

Thereby destroying any redirections to files or pipes that the parent process has carefully set up.
