### ISSUE TITLE
gdi+ InvalidParameter on ui.render.tests

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2210]
Reported on the mailing list by @AlexIljin:

```
   This crashes on Windows:

  "ui.render.test" run

  with the error `gdi+-error` and fields "status InvalidParameter".
```

**Comment by kusumotonorio** [comment]
```Factor
: check-rendering ( gadget -- )
    screenshot
    [ render-output set-global ]
    [
        "vocab:ui/render/test/reference.bmp" load-image
        bitmap= "is perfect" "needs work" ?
        "Your UI rendering " prepend
        message-window
    ] bi ;
```
There isn't `test/reference.bmp` in: `https://github.com/factor/factor/tree/master/basis/ui/render`.

**Comment by mrjbq7** [comment]
We'll need two versions of that bitmap, if we ever save it -- one for retina screens (HiDPI) and one for non-retina.

**Comment by kusumotonorio** [comment]
If they have a file with that name in that location, Factor won't crash, but... 
I think we should add code to check for the presence of the file.

**Comment by mrjbq7** [comment]
Ahh, I see.

So two problems.

1) The ``reference.bmp`` doesn't exist.

2) The GDI+ image backend (``images.loader.gdiplus:stream>image*``) throws an error when loading an image that doesn't exist.

The second one isn't that big a deal, I mean you'd expect some kind of error, or it to return ``f`` or something indicating it failed for some reason.  It's not a particularly nice error message, though.

**Comment by mrjbq7** [comment]
I'm not sure about the crash, on my Windows 10 (64-bit) instance, it seems to give a nice error message.

**Comment by mrjbq7** [comment]
Oh, nevermind.  It's different when run ``"ui.render.test" run``...

**Comment by mrjbq7** [comment]
Here's where the bitmap is:

https://github.com/factor/factor/tree/master/extra/ui/render/test

**Comment by mrjbq7** [comment]
So, now I think it's a bug somehow calling GDI+ when loading that bitmap...

```
$ file extra/ui/render/test/reference.bmp 
extra/ui/render/test/reference.bmp: PC bitmap, Windows 3.x format, 223 x 100 x 24
```

**Comment by mrjbq7** [comment]
It might be a weird bitmap, trying to open in Windows 10 gives "It looks like we don't support this file format."

**Comment by kusumotonorio** [comment]
I was misunderstanding.
Certainly the file exists in `extra/ui/render/test`.
However, when I try to open it, it reports that the file is corrupt or too large.
Its size is 65.3KB.

Speaking of which, I think I had the same thing before.

**Comment by kusumotonorio** [comment]
Because I added another bitmap file to `basis/ui/render/test`, Factor did not read the corrupted file in `basis/ui/render/test`. Therefore, Factor did not crash.

**Comment by kusumotonorio** [comment]
If you download and open the following file, it will be reported as corrupted. To resolve this issue, we must replace this file with an undamaged one.

https://github.com/factor/factor/blob/master/extra/ui/render/test/reference.bmp
