### ISSUE TITLE
Unable to build on MacOS

### ISSUE THREAD

**Issue by rgrinberg** [factor/factor#2224]
This is the error that I get after runnning `./build.sh update`

```
Factorcode md5:
Disk md5: 55ddfe7044cf0f3a257edb0ddeb20fb5
Downloading boot image boot.unix-x86.64.image.
curl -f -O http://downloads.factorcode.org/images/master/boot.unix-x86.64.image
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    371      0 --:--:-- --:--:-- --:--:--   370
fatal_error: Cannot read image header: 0x0

Copying factor.image to factor.image.fresh...
./build.sh: line 644: 70628 Abort trap: 6           ./$FACTOR_BINARY -i=$BOOT_IMAGE
cp: factor.image: No such file or directory
```

**Comment by mrjbq7** [comment]
Do you have network connectivity? Seems like downloading the boot image failed?

**Comment by rgrinberg** [comment]
Seems like my internet is working fine. I tried running the curl commands manually and they seem to complete successfully

**Comment by erg** [comment]
We should have it checksum the boot image before building.

**Comment by mrjbq7** [comment]
Hmm, I've seen nothing unusual that would lead to that error.  It's most often a corrupted or not downloaded properly boot image.  And bootstrap works properly for me @erg not an issue with corrupted uploads.

These are the current boot image sizes:

```
-rw-r--r--    1 jbenedik  staff    2432012 Nov 28 07:52 boot.unix-x86.32.image
-rw-r--r--    1 jbenedik  staff    4125576 Nov 28 07:52 boot.unix-x86.64.image
-rw-r--r--    1 jbenedik  staff    2432236 Nov 28 07:52 boot.windows-x86.32.image
-rw-r--r--    1 jbenedik  staff    4125800 Nov 28 07:52 boot.windows-x86.64.image
```

Some ideas:

1) Try again, for lack of other ideas I uploaded new boot images.

2) Try downloading with a web browser or ``wget``, perhaps some weird curl interaction with the webserver.  We've seen that only once before from an old windows host and interactions with the network host that provides our download server.

3) If you have a working binary (e.g., from a recent release), you can update locally doing:

```
$ ./factor
IN: scratchpad make-my-image
^D
$ ./factor -i=boot.unix-x86.64.image
...
$ ./factor
! UPDATED !
```

**Comment by erg** [comment]
Which version of macos?

**Comment by mrjbq7** [comment]
10.14 and 10.15

**Comment by erg** [comment]
@rgrinberg which macos is broken for you?

**Comment by rgrinberg** [comment]
The issue was a missing redirect flag. Thank you all, sorry for the noise.

**Comment by mrjbq7** [comment]
@erg did you notice it trying http first and redirecting to https? We should probably be doing the https url by default?

**Comment by erg** [comment]
We can update to https urls. I have nginx redirecting to https by default
now, and I think it has been working because wget is the default downloader
but is not installed by default on Macs.
