### ISSUE TITLE
 First search time on Windows Factor

### ISSUE THREAD

**Issue by kusumotonorio** [factor/factor#2239]
When Windows Factor does its first search in a browser window, it takes a long time to display the results.
Mac Factor and Linux Factor display results immediately.

**Comment by mrjbq7** [comment]
Our implementation of ``(exists?)`` on windows might be slow.

Also, our vocabulary directory traversal can be improved.

I'm looking at the second issue now.

**Comment by mrjbq7** [comment]
Some timing notes:

```factor
IN: scratchpad reset-word-timing
IN: scratchpad \ (exists?) add-timing
IN: scratchpad \ directory-entries add-timing
```

On Windows (well, a Windows VM):

```factor
IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
Running time: 0.3883959 seconds

IN: scratchpad word-timing.
(exists?)         0.1550898 5476
directory-entries 0.1647466 2738
```

On macOS:

```factor
IN: scratchpad IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
Running time: 0.296982399 seconds

IN: scratchpad word-timing.
(exists?)         0.040386384 7193
directory-entries 0.182621026 3600
```

**Comment by mrjbq7** [comment]
Note: we implement Windows version of ``(exists?)`` in ``vm/os-windows.cpp`` (see ``windows_stat``).

**Comment by kusumotonorio** [comment]
The interesting thing about this is that running `gc ["" disk-vocabs-recursive-for-prefix] time` first after starting Windows Factor can be very slow, whereas `reset-word-timing \ (exists?) add-timing \ directory-entries add-timing` first before doing it can be faster.

**Comment by mrjbq7** [comment]
Can you give me an idea of what kind of times it’s taking for you? First time and subsequent times?

**Comment by kusumotonorio** [comment]
Both are when I launch factor and do them immediately.

**Comment by kusumotonorio** [comment]
All three of the following are the first results of running Windows Factor.

The first one only does `gc [ "" disk-vocabs-recursive-for-prefix ] time`.

The following example shows ` \(exists?) add-timing` followed by `gc [ "" disk-vocabs-recursive-for-prefix ] time`.

Finally, they are executed simultaneously.

```Factor
Press F1 at any time for help.
Factor 0.99 x86.64 (1940, heads/master-b430f8e0a7, Feb  7 2020 16:14:31)
[Microsoft Visual C++ 190023506] on windows

IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
Running time: 74.68079210000001 seconds

Additional information was collected.
dispatch-stats.  - Print method dispatch statistics
gc-events.       - Print all garbage collection events
gc-stats.        - Print breakdown of different garbage collection events
gc-summary.      - Print aggregate garbage collection statistics

--- Data stack:
{ ~array~ ~array~ ~array~ ~array~ ~array~ }
IN: scratchpad 
```
```Factor
Press F1 at any time for help.
Factor 0.99 x86.64 (1940, heads/master-b430f8e0a7, Feb  7 2020 16:14:31)
[Microsoft Visual C++ 190023506] on windows

IN: scratchpad IN: scratchpad reset-word-timing
IN: scratchpad \ (exists?) add-timing
IN: scratchpad \ directory-entries add-timing
IN: scratchpad Command: continue-restart
2: Note:
Added "io.files.private" vocabulary to search path
IN: scratchpad Command: continue-restart
3: Note:
Added "io.directories" vocabulary to search path
IN: scratchpad IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
Running time: 0.7991841 seconds

Additional information was collected.
dispatch-stats.  - Print method dispatch statistics
gc-events.       - Print all garbage collection events
gc-stats.        - Print breakdown of different garbage collection events
gc-summary.      - Print aggregate garbage collection statistics

--- Data stack:
{ ~array~ ~array~ ~array~ ~array~ ~array~ }
IN: scratchpad 
```

```Factor
Press F1 at any time for help.
Factor 0.99 x86.64 (1940, heads/master-b430f8e0a7, Feb  7 2020 16:14:31)
[Microsoft Visual C++ 190023506] on windows

IN: scratchpad IN: scratchpad reset-word-timing
IN: scratchpad \ (exists?) add-timing
IN: scratchpad \ directory-entries add-timing
IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
IN: scratchpad Command: continue-restart
2: Note:
Added "io.files.private" vocabulary to search path
IN: scratchpad Command: continue-restart
3: Note:
Added "io.directories" vocabulary to search path
Running time: 18.7356508 seconds

Additional information was collected.
dispatch-stats.  - Print method dispatch statistics
gc-events.       - Print all garbage collection events
gc-stats.        - Print breakdown of different garbage collection events
gc-summary.      - Print aggregate garbage collection statistics

--- Data stack:
{ ~array~ ~array~ ~array~ ~array~ ~array~ }
IN: scratchpad 
```

**Comment by AlexIljin** [comment]
Let me chime in with something, perhaps, obvious. I suspect that most of the time is taken up by Windows reading file metadata from the disk (directory contents). Windows caches that data in memory, so that the second run immediately following the first one will be orders of magnitude faster. To get real performance data, one has to dismount the volume with Factor between runs.

**Comment by erg** [comment]
There are API calls that get only the names and not all the metadata. That's all we need in this case?

**Comment by mrjbq7** [comment]
I have a patch that I'm almost finished with that cuts the time for ``disk-vocabs-recursive-for-prefix`` by about 40%, with a lot less calls to ``exists?``.  When it's ready, I'll be curious how much it improves your Windows experience.

**Comment by AlexIljin** [comment]
Sorry, I'm not in the topic, but why do we go through the disk in the first place? I thought the help search walks through the help topics of the already loaded units, so it should only go through the memory of the Factor process. If it has to also do disk scan, can it be, like, a second pass of the help search, after the first pass results are already displayed to the user?

**Comment by mrjbq7** [comment]
The vocabulary search looks for vocabularies that aren’t loaded yet.

**Comment by mrjbq7** [comment]
@kusumotonorio I made a patch in 1a1ee4b4a84f60d881c16728a6d7b43cd8e8d2ed.

Could you try it on your Windows?  I suspect the way our ``(exists?)`` check works (specifically the``windows_stat`` function) probably causes the file system to do more work than it needs to.  That should be improved separately, but the new recursive disk vocab logic doesn't need to check file existence that way, or as often.

**Comment by kusumotonorio** [comment]
@mrjbq7 Thank you.  I'll try it. Give me some time.

**Comment by mrjbq7** [comment]
This is possible a better thing to use for ``(exists?)`` and seems to prevent the pathological freeze as well as being 50% faster:

```c
  const DWORD attributes = GetFileAttributes(path);
  if (INVALID_FILE_ATTRIBUTES != attributes)
    return true;
  else if (ERROR_FILE_NOT_FOUND == GetLastError())
    return false;
  else
    // handle some other error, maybe use another method of existence checking
```

There are a few other things we could use, including using ``PathFileExists``.

**Comment by kusumotonorio** [comment]
I tried it with 32-bit Windows 7.
The first run took more than a minute, but was reduced to about 5 seconds.
If I take enough time to do the tests from the Windows restart, I might get a shorter time. I'll try again.

```Factor
Press F1 at any time for help.
Factor 0.99 x86.32 (1914, heads/master-0ea9f8935d, Sep 11 2019 09:24:35)
[Microsoft Visual C++ 190023506] on windows

IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
Running time: 5.316204894 seconds

Additional information was collected.
dispatch-stats.  - Print method dispatch statistics
gc-events.       - Print all garbage collection events
gc-stats.        - Print breakdown of different garbage collection events
gc-summary.      - Print aggregate garbage collection statistics

--- Data stack:
{ ~array~ ~array~ ~array~ ~array~ ~array~ }
IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
Running time: 0.558231583 seconds

Additional information was collected.
dispatch-stats.  - Print method dispatch statistics
gc-events.       - Print all garbage collection events
gc-stats.        - Print breakdown of different garbage collection events
gc-summary.      - Print aggregate garbage collection statistics

--- Data stack:
{ ~array~ ~array~ ~array~ ~array~ ~array~ }
{ ~array~ ~array~ ~array~ ~array~ ~array~ }
IN: scratchpad 
```

**Comment by kusumotonorio** [comment]
If I have enough time to restart the OS, the first run of this test seems to be short. 
Great!

```Factor
Press F1 at any time for help.
Factor 0.99 x86.32 (1914, heads/master-0ea9f8935d, Sep 11 2019 09:24:35)
[Microsoft Visual C++ 190023506] on windows

IN: scratchpad gc [ "" disk-vocabs-recursive-for-prefix ] time
Running time: 0.66209759 seconds

Additional information was collected.
dispatch-stats.  - Print method dispatch statistics
gc-events.       - Print all garbage collection events
gc-stats.        - Print breakdown of different garbage collection events
gc-summary.      - Print aggregate garbage collection statistics

--- Data stack:
{ ~array~ ~array~ ~array~ ~array~ ~array~ }
IN: scratchpad 
```

**Comment by kusumotonorio** [comment]
In fact, when I do a search, the initial response is much faster and the user experience is not inferior to the Factor of other operating systems. Great job!

**Comment by mrjbq7** [comment]
One difference with my suggested patch for file ``(exists?)`` on Windows is that ``GetFIleAttributes`` does not follow symbolic links but the current approach using ``GetFileInformationByHandle`` does (which matches the behavior of ``stat`` on macOS/Linux).

Perhaps a better patch would be to check the attributes returned, and if it's a link, to do the current approach.  I will give it some thought later.

**Comment by mrjbq7** [comment]
Hmm, except we don't add the flag ``FILE_FLAG_OPEN_REPARSE_POINT``, so perhaps my patch is identical behavior.  But different from windows to unix.

**Comment by kusumotonorio** [comment]
The issue I have pointed out has improved dramatically. Should we close this issue?
