### ISSUE TITLE
Using mnorm on matrix with negative-only entries causes div-by-zero error

### ISSUE THREAD

**Issue by timor** [factor/factor#2244]
If i run
```factor
USE: math.matrices
{ { -1 0 } { 0 0 } } mnorm
```
I get a division by zero error.  Is this word not supposed to be defined for matrices having negative values?

**Comment by mrjbq7** [comment]
I think the issue is less with the negatives, and more with the zero values.

What would you expect the result to be?

**Comment by timor** [comment]
It works with e.g. `{ { 5 0 } { 0 0 } }`

I need to normalize so that the absolute value does not exceed `1.0`, i.e. either the minimum value is `-1.0` or the maximum is `1.0`.  But I don't know if that fits the intention of the word.

E.g.
`{ { -2 0 } { 0 1 } }` would become `{ { -1 0 } { 0 0.5 } }`

**Comment by mrjbq7** [comment]
There are probably various use cases, for example all of these from ``numpy.linalg.norm``:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html

**Comment by timor** [comment]
Well I suppose each of these warrant their own word.

So do you think that throwing a div-by-zero for this particular usage of the current `mnorm` is acceptable behavior?

**Comment by timor** [comment]
Oh I just noticed that the python function is actually calculating matrix norms as opposed to "normalizing" a matrix like `mnorm` does.

**Comment by mrjbq7** [comment]
Gotcha. Well, normalizing to [0,1] or [-1,1] maybe different. In some cases a “-2..0” range should maybe normalize to 0..1?

**Comment by catb0t** [comment]
> Oh I just noticed that the python function is actually calculating matrix norms as opposed to "normalizing" a matrix like `mnorm` does.

I wasn't aware of the difference when I rewrote `math.matrices`. I suggest renaming `mnorm` to `normalize-matrix` everywhere, and implementing a new `mnorm` which calculates the **norm** of the matrix, and the docs for each word must elucidate the difference. 

I could make a PR to do that, and I think it would solve this entirely.

**Comment by mrjbq7** [comment]
Great!

**Comment by catb0t** [comment]
Now that I've actually read about vector and matrix norms and it's clear that there is no single "base" definition, which is what a word called `mnorm` looks like, vs `m-1norm` etc. 

So we already have `m-1norm`, `m-infinity-norm`, and `frobenius-norm` (aka Hilbert-Schmidt norm), the last of which is actually the "base" definition I thought was missing from Factor (called ||A||<sub>E</sub> in *Numerical Analysis*, but called Frobenius by modern sources) defined and working properly. 

The PR will be a small change to the actual implementation, with bigger docs and tests fixes.
