### ISSUE TITLE
Resizing macOS window causes text jitters

### ISSUE THREAD

**Issue by erg** [factor/factor#2251]
Start Factor on macOS, then resize the window by dragging the corner. Notice that the text jitters instead of remaining stable. Dragging seems to cause the calculations to happen two different ways.

**Comment by erg** [comment]
The text stretches in whichever direction you are resizing, and it looks larger the faster you do it. Happens both on my 2011 Macbook Pro and my 2017 Macbook Pro.

**Comment by mrjbq7** [comment]
I’ll try to reproduce later!

If that’s the case then should be easy to paint on the old dim not the new one

**Comment by mrjbq7** [comment]
Is this fixed?  I can't reproduce.

**Comment by erg** [comment]
It seems fixed! I wish we had a gitid of the fix.

**Comment by mrjbq7** [comment]
This one maybe e2fa0a6392717c6458097836540d351def70b4f0
