### ISSUE TITLE
Win64 builds broken

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#2252]
The latest Win64 build is five days old. @erg, could you fix it? I can't wait to try the latest version with the GUI texture rendering bug fixed.

**Comment by erg** [comment]
Somehow it looks like the win64 build is loading too much code and having a gc error. I can take a look at it later, but the easiest thing to do is just build your own Factor from your working Windows with ``build.cmd update``.

**Comment by erg** [comment]
I can't get a code heap larger than 67MB. (``-codeheap=67000``)

Related to #2254

**Comment by AlexIljin** [comment]
I don't have a C++ compiler installed.

**Comment by erg** [comment]
I'm trying to fix it. On one machine the code heap is not large enough and it doesn't grow correctly (the machine has 64GB RAM) for some reason after extra/logic was merged, and on another there is a random failure in ``help-lint-all``. If either of these issues are fixed there will be new builds.

What do you have against installing Visual Studio C++ compiler on at least one machine so you can do a build from scratch?

**Comment by AlexIljin** [comment]
I need to deal with all that "community edition" with obligatory account crap, and then there'll be no way to make sure it's uninstalled properly. I already have a WinSDK folder, but no traces of how to uninstall it. I don't even remember when I installed it, or which software brought it with it. Maybe I got it last time when I installed VS Community Edition to create the Ctrl-Break support in Factor. That was a few years ago, and I have deleted VS since.

I mostly work in Delphi nowadays, so I don't need C compilers, and I was never a fan of C/C++ anyway, so they are of not much use for me. I recently had 20Gb free on drive C, then Win 10 got itself updated, and now I only have 11Gb left. Not much room for more development environments.

Lastly, what you say about 64Gb RAM not being enough makes me question whether I should even begin this. I've only got 16Gb RAM in this laptop, and the swap file is on drive C...

I don't currently own another PC.

**Comment by AlexIljin** [comment]
If I install Visual Studio, will I be able to build Factor with only 16Gb of RAM?

**Comment by mrjbq7** [comment]
Only!

**Comment by erg** [comment]
It's not that 64GB RAM is not enough, it's that the 67MB code heap doesn't grow correctly. I was confused if I said anyhting about RAM not being enough.

**Comment by AlexIljin** [comment]
> Only!
You wrote that:
> I can't get a code heap larger than ~67MB~ 67GB even with 64GB RAM.
and
> On one machine the code heap is not large enough and it doesn't grow correctly (the machine has 64GB RAM)

Now, I don't know what kind of build process fails to complete in 64Gb RAM, but I **only** have 16 : ))

**Comment by AlexIljin** [comment]
> It's not that 64GB RAM is not enough, it's that the 67MB code heap doesn't grow correctly. I was confused if I said anyhting about RAM not being enough.

I'm confused again: 67**M**B or 67**G**B?

**Comment by erg** [comment]
64GB of ram is enough for anything. There's a bug

**Comment by mrjbq7** [comment]
To be clear, there is a “grow the heap too quickly to load all the code bug” for which an initial code heap of 2GB on the build bot works around, instead of initial code heap Of 67MB. 

Go get a C compiler !

**Comment by AlexIljin** [comment]
> Go get a C compiler !

**sigh** 3.56 Gb to install Visual Studio...

**Comment by mrjbq7** [comment]
Wild.  We'll have new binaries soon I think also.

**Comment by AlexIljin** [comment]
I built it, and it was surprisingly painless.

**Comment by erg** [comment]
Great news, win64 is clean again!

**Comment by AlexIljin** [comment]
Great! I can reclaim the 3.5 Gb on drive C:
: ))
