### ISSUE TITLE
Mac Factor Rarely Down

### ISSUE THREAD

**Issue by kusumotonorio** [factor/factor#2256]
Mac Factor rarely goes down.
I'm not sure what it is when it happens, but I think the message was like this:

```
Cannot create slice: to > length
from 0
to   2
seq  B{ }
```
I'm not sure, but I suspect that the cause is the code I wrote in the past and incorporated into the master.

It is the following word in :
https://github.com/factor/factor/blob/41db42a5714819ab271ba04fae547a226fd7e47d/basis/ui/text/core-text/core-text.factor
```Factor
M:: core-text-renderer x>offset ( x font string -- n )
    x font string
    [ 2drop 0 ] [
        cached-line line>>
        swap scale 0 <CGPoint> CTLineGetStringIndexForPosition
    ] if-empty
    2 * 0 swap string utf16n encode subseq
    utf16n decode length ;
```
This is probably best done as follows:
```Factor
M:: core-text-renderer x>offset ( x font string -- n )
    x font string
    [ 2drop 0 ] [
        cached-line line>>
        swap scale 0 <CGPoint> CTLineGetStringIndexForPosition
        2 * 0 swap string utf16n encode subseq
        utf16n decode length
    ] if-empty ;
```

**Comment by mrjbq7** [comment]
Fixed in ee4e977fbb5f6bc5b99377441d02ba4fac718b8c

**Comment by kusumotonorio** [comment]
Just a few minutes ago, Mac Factor went down with a similar error for the first time in a very long time.
At that time, I got a little clue in the debugger.

I'd like to find out what caused it and fix it if I can, but I don't know where the error occurred when `>codepoint-index` was called.
Has your Mac Factor been down recently with such an error?
![2020-11-21 17 39 27](https://user-images.githubusercontent.com/47816570/99873109-f756b900-2c25-11eb-930c-4a69c123367a.png)

**Comment by kusumotonorio** [comment]
I don't know the procedure for reproducing this issue, so I can't show you what is actually happening, but I can raise the same exception by doing the following:
```Factor
"" 1 >codepoint-index .
```
Therefore, I suspect that changing `>codepoint-index` to the following would avoid the Mac Factor going down.

```Factor
:: >codepoint-index ( str utf16-index -- codepoint-index )
    str length 0 = [ 0 ] [
        0 utf16-index 2 * str utf16n encode subseq utf16n decode length
    ] if ;
```

**Comment by mrjbq7** [comment]
I’ll look at this, seems to be a good fix but I wonder why we are trying to get index 1 from an empty string.

**Comment by kusumotonorio** [comment]
Certainly. Normally, we should investigate why such things happen.
It happened when I switched windows. I can't guess which callback was called and why, because I wasn't in the middle of typing.

**Comment by kusumotonorio** [comment]
I think the code I wrote earlier is too ad-hoc. The following might be better.
```Factor
:: >codepoint-index ( str utf16-index -- codepoint-index )
        str utf16n encode dup length :> ( encodded encodded-length ) 
        0 utf16-index 2 * encodded-length min encodded subseq utf16n decode length ;
```
