### ISSUE TITLE
Cannot configure with emacsclient

### ISSUE THREAD

**Issue by anquegi** [factor/factor#2262]
I'm followig the [emacs setup](https://concatenative.org/wiki/view/Editor%20integration):

But I'm not getting properly working,

first, I cannot get working with emacs client, so I need to wait that emacs is completely launched. after waiting it only shows the *scrtach* buffer, and everytime I do edit the editor is opening a new emacs instance.

my configuration .factor-rc file is:

```
~ via ⬢ v12.4.0 took 20s
➜ cat .factor-rc
USING: namespaces editors.emacs ;
"/usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacs" \ emacsclient-path set-global
```
I can also run factor inside emacs with FUEL and it is working well. the only thing is the autocompletion can be setup with company

**Comment by mrjbq7** [comment]
Have you tried pointing it to ``emacsclient``?

**Comment by anquegi** [comment]
I tested with:

USING: namespaces editors.emacs ;
"/usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacsclient" \ emacsclient-path set-global

and nothing happens

If I started a server named factor and call to that:

USING: namespaces editors.emacs ;
"/usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacsclient --server-file=factor -c" \ emacsclient-path set-global

and I get this error:
```

T{ process
    { command
        {
            "/usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacsclient -..."
            "-a=emacs"
            "--no-wait"
            "+109"
            "/Users/toni/learn/factor/factor/core/math/math.factor"
        }
    }
    { detached t }
    { environment H{ } }
    { environment-mode +append-environment+ }
    { group +new-group+ }
    { status 255 }
}
```

**Comment by mrjbq7** [comment]
I’m wondering if it’s Factor or your emacs or how we call it. 

If you run that command in the Terminal does it work? (Maybe remove the quotes below as appropriate)

$ "/usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacsclient -..."
            "-a=emacs"
            "--no-wait"
            "+109"
            "/Users/toni/learn/factor/factor/core/math/math.factor"

**Comment by anquegi** [comment]
Sorry for being late, I think that the problem is that cannot find server running
I get this:
```
➜ /usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacsclient -a=emacs --no-wait +109 /Users/toni/learn/factor/factor/core/math/math.factor
/usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacsclient: can't find socket; have you started the server?
/usr/local/Cellar/emacs-head/HEAD-556cc72_1/bin/emacsclient: To start the server in Emacs, type "M-x server-start".
```

But what I need to do

**Comment by mrjbq7** [comment]
https://www.emacswiki.org/emacs/EmacsClient

**Comment by anquegi** [comment]
Finally I get this working for my emacs configuration in MAC OS X after reading again what you pointed.
Factor documentation:
https://concatenative.org/wiki/view/Emacs%20Integration
but I need to name the file .factor-rc (with initial dot)

Then I pointed to my emacscliente in /usr/local/bin/emacsclient which is a symbolik link to my emacs installed wwith homebrew in Cellar...

and finally to find the server file I read this things:
 [https://stackoverflow.com/questions/23148787/why-emacsclient-cant-find-socket-after-executing-emacs-daemon](https://stackoverflow.com/questions/23148787/why-emacsclient-cant-find-socket-after-executing-emacs-daemon),

 and 

[https://emacs.stackexchange.com/questions/35587/emacs-client-cant-find-server-in-terminal](https://emacs.stackexchange.com/questions/35587/emacs-client-cant-find-server-in-terminal)

for me, or in my opinion I need to point always the server-file at least in OSX, installed with homebrew, so I added this options and also -c for creating a new frame in emacs.factor 

> /factor/basis/editors/emacs/emacs.factor

```
USING: combinators.short-circuit editors io.standard-paths
kernel make math.parser namespaces sequences system ;
IN: editors.emacs

SINGLETON: emacsclient
emacsclient editor-class set-global

SYMBOL: emacsclient-path
SYMBOL: emacsclient-args

HOOK: find-emacsclient os ( -- path )

M: object find-emacsclient ( -- path )
    "emacsclient" ?find-in-path ;

M: windows find-emacsclient
    {
        [ { "Emacs" } "emacsclientw.exe" find-in-applications ]
        [ { "Emacs" } "emacsclient.exe" find-in-applications ]
        [ "emacsclient.exe" ]
    } 0|| ;

M: emacsclient editor-command ( file line -- command )
    [
        emacsclient-path get [ find-emacsclient ] unless* ,
        emacsclient-args get [ { "--server-file=server" "-a=emacs" "--no-wait" "-c"} ] unless* %
        number>string "+" prepend ,
        ,
    ] { } make ;

```

I get this working

➜ brew services
Name              Status  User Plist
emacs-head        started toni /Users/toni/Library/LaunchAgents/homebrew.mxcl.emacs-head.plist

![Captura de pantalla 2020-04-09 a las 16 38 33 (2)](https://user-images.githubusercontent.com/2518346/78907128-95738580-7a80-11ea-9b81-1ce2eb59244e.png)

I added this information, at least is working for me, so maybe it can be useful for others. Thanks for doing factor
