### ISSUE TITLE
downloads.factorcode.org certificate is not trusted on openSUSE Leap 15.1

### ISSUE THREAD

**Issue by erg** [factor/factor#2263]
The cert is good, but it looks like they don't trust LetsEncrypt.

```bash
Downloading boot image boot.unix-x86.64.image.
wget -nd http://downloads.factorcode.org/images/master/boot.unix-x86.64.image
--2020-03-19 20:11:58--  http://downloads.factorcode.org/images/master/boot.unix-x86.64.image
Resolving downloads.factorcode.org (downloads.factorcode.org)... 159.65.160.116
Connecting to downloads.factorcode.org (downloads.factorcode.org)|159.65.160.116|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.factorcode.org/images/master/boot.unix-x86.64.image [following]
--2020-03-19 20:11:59--  https://downloads.factorcode.org/images/master/boot.unix-x86.64.image
Connecting to downloads.factorcode.org (downloads.factorcode.org)|159.65.160.116|:443... connected.
ERROR: cannot verify downloads.factorcode.org's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to downloads.factorcode.org insecurely, use `--no-check-certificate'.
wget failed

# fix

wget --no-check-certificate -nd http://downloads.factorcode.org/images/master/boot.unix-x86.64.image
```

**Comment by odiferousmint** [comment]
> they don't trust LetsEncrypt.

Seems strange to me.

1. Have you found any rationale for this decision?
2. Is this an issue with this particular version of openSUSE only?
3. Is this an issue with openSUSE only?

**Comment by bpollack** [comment]
It's probably local to the OpenSSH installation on OpenSUSE. I really don't think this is worth fixing, @erg--at least not on our end. We can ship the actual CA cert chain for Let's Encrypt in the repo if you really want and tell wget to use it, but that seems like a lot of work for something that's not our bug.

**Comment by jonenst** [comment]
Or maybe just add an option (switched off by default) to add the ' --no-check-certificate' with huge warnings ?

**Comment by bpollack** [comment]
Yeah, that’d also work.

**Comment by mrjbq7** [comment]
I think it's not worth fixing, we should trust modern certs.
