### ISSUE TITLE
Bootstraping Factor Triggers a bug.

### ISSUE THREAD

**Issue by Gamer2014** [factor/factor#2269]
On Ubuntu 18.04.4 LTS (Bionic Beaver), While following the steps for building from a clean branch of Factor at "https://concatenative.org/wiki/view/Factor/Building%20Factor"

I received the error message after executing this step:   ./factor -i=boot.unix-x86.64.image

You have triggered a bug in Factor. Please report.
critical_error: The die word was called by the library.: 0
Starting low level debugger...
Basic commands:
  q ^D             -- quit Factor
  c                -- continue executing Factor - NOT SAFE
  t                -- throw exception in Factor - NOT SAFE
  .s .r .c         -- print data, retain, call stacks
  help             -- full help, including advanced commands

> 

What steps can I take to get around this error/bug?

**Comment by mrjbq7** [comment]
Do you have a boot image?

**Comment by mrjbq7** [comment]
I recommend trying the basic steps to build from source:

https://github.com/factor/factor#building-factor-from-source

**Comment by Gamer2014** [comment]
Yes, I downloaded boot.unix-x86.64.image from https://downloads.factorcode.org/images/master/

I will try the basic build as you suggested & let you know the results. Thank you.

**Comment by mrjbq7** [comment]
It's odd that it wouldn't work.  Did the build produce any output before the error message?

**Comment by Gamer2014** [comment]
Here is the output from my console:

darkprogrammer@Atari-Dev:~/factor$ ./factor -i=boot.unix-x86.64.image
*** Stage 2 early init... done
Loading resource:basis/bootstrap/stage2.factor
Loading resource:basis/command-line/command-line.factor
Loading resource:basis/fry/fry.factor
Loading resource:basis/locals/backend/backend.factor
Loading resource:basis/debugger/debugger.factor
Loading resource:basis/combinators/short-circuit/short-circuit.factor
Loading resource:basis/generalizations/generalizations.factor
Loading resource:basis/macros/macros.factor
Loading resource:basis/memoize/memoize.factor
Loading resource:basis/hashtables/identity/identity.factor
Loading resource:basis/hashtables/wrapped/wrapped.factor
Loading resource:basis/math/ranges/ranges.factor
Loading resource:basis/compiler/errors/errors.factor
Loading resource:basis/summary/summary.factor
Loading resource:basis/grouping/grouping.factor
Loading resource:basis/io/styles/styles.factor
Loading resource:basis/colors/colors.factor
Loading resource:basis/colors/constants/constants.factor
Loading resource:basis/ascii/ascii.factor
Loading resource:basis/hints/hints.factor
Loading resource:basis/io/streams/string/string.factor
Loading resource:basis/delegate/delegate.factor
Loading resource:basis/delegate/protocols/protocols.factor
Loading resource:basis/deques/deques.factor
Loading resource:basis/present/present.factor
Loading resource:basis/alien/c-types/c-types.factor
Loading resource:basis/cpu/architecture/architecture.factor
Loading resource:basis/strings/tables/tables.factor
Loading resource:basis/libc/libc.factor
Loading resource:basis/alien/destructors/destructors.factor
Loading resource:basis/functors/functors.factor
Loading resource:basis/functors/backend/backend.factor
Loading resource:basis/locals/types/types.factor
Loading resource:basis/interpolate/interpolate.factor
Loading resource:basis/locals/locals.factor
Loading resource:basis/locals/parser/parser.factor
Loading resource:basis/locals/errors/errors.factor
Loading resource:basis/locals/rewrite/closures/closures.factor
Loading resource:basis/locals/rewrite/point-free/point-free.factor
Loading resource:basis/locals/rewrite/sugar/sugar.factor
Loading resource:basis/sequences/generalizations/generalizations.factor
Loading resource:basis/macros/expander/expander.factor
Loading resource:basis/locals/macros/macros.factor
Loading resource:basis/locals/fry/fry.factor
Loading resource:basis/multiline/multiline.factor
Loading resource:basis/alien/syntax/syntax.factor
Loading resource:basis/alien/enums/enums.factor
Loading resource:basis/alien/libraries/libraries.factor
Loading resource:basis/alien/libraries/unix/unix.factor
Loading resource:basis/alien/parser/parser.factor
Loading resource:basis/alien/arrays/arrays.factor
Loading resource:basis/libc/linux/linux.factor
Loading resource:basis/prettyprint/prettyprint.factor
Loading resource:basis/prettyprint/config/config.factor
Loading resource:basis/prettyprint/custom/custom.factor
Loading resource:basis/prettyprint/sections/sections.factor
Loading resource:basis/vocabs/prettyprint/prettyprint.factor
Loading resource:basis/prettyprint/backend/backend.factor
Loading resource:basis/prettyprint/stylesheet/stylesheet.factor
Loading resource:basis/literals/literals.factor
Loading resource:basis/hashtables/wrapped/prettyprint/prettyprint.factor
Loading resource:basis/hashtables/identity/prettyprint/prettyprint.factor
Loading resource:basis/locals/definitions/definitions.factor
Loading resource:basis/see/see.factor
Loading resource:basis/locals/prettyprint/prettyprint.factor
Loading vocab:bootstrap/bootstrap-error.factor
Loading resource:basis/debugger/debugger.factor
You have triggered a bug in Factor. Please report.
critical_error: The die word was called by the library.: 0
Starting low level debugger...
Basic commands:
  q ^D             -- quit Factor
  c                -- continue executing Factor - NOT SAFE
  t                -- throw exception in Factor - NOT SAFE
  .s .r .c         -- print data, retain, call stacks
  help             -- full help, including advanced commands

**Comment by Gamer2014** [comment]
Here's the Console output from the basic build.  This failed also.

darkprogrammer@Atari-Dev:~$ git clone git://github.com/factor/factor.git
Cloning into 'factor'...
remote: Enumerating objects: 217, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 417147 (delta 87), reused 91 (delta 48), pack-reused 416930
Receiving objects: 100% (417147/417147), 236.15 MiB | 6.19 MiB/s, done.
Resolving deltas: 100% (300326/300326), done.
Checking out files: 100% (10806/10806), done.

darkprogrammer@Atari-Dev:~$ cd factor
darkprogrammer@Atari-Dev:~/factor$ ./build.sh update
Finding OS...
Finding ARCH...
Finding num cores...
Checking for all(x86_64-w64-mingw32-gcc x86_64-w64-mingw32-g++)...found!
Finding WORD...
./build.sh: line 325: ./factor-word-size: cannot execute binary file: Exec format error
OS=linux
ARCH=x86
NUM_CORES=4
WORD=126
DEBUG=
REPRODUCIBLE=
CURRENT_BRANCH=master
FACTOR_BINARY=factor
FACTOR_LIBRARY=libfactor.a
FACTOR_IMAGE=factor.image
MAKE_TARGET=linux-x86-126
BOOT_IMAGE=boot.x86.126.image
MAKE_IMAGE_TARGET=x86.126
GIT_PROTOCOL=git
GIT_URL=git://github.com/factor/factor.git
DOWNLOADER=wget -nd
CC=x86_64-w64-mingw32-gcc
CXX=x86_64-w64-mingw32-g++
MAKE=make
COPY=cp
DELETE=rm
Checking for any(chmod)...found chmod!
Checking for any(uname)...found uname!
Checking for any(git)...found git!
Checking for any(wget curl)...found wget!
Checking for any(clang x86_64-w64-mingw32-gcc i686-w64-mingw32-gcc gcc)...found x86_64-w64-mingw32-gcc!
Checking for any(clang++ x86_64-w64-mingw32-g++ i686-w64-mingw32-g++ g++ cl)...found x86_64-w64-mingw32-g++!
Checking for any(make gmake)...found make!
Checking for any(md5sum md5)...found md5sum!
Checking for any(cut)...found cut!
Checking for library GL...not found.
Checking for library X11...not found.
Checking for library pango-1.0...not found.
Checking for library gobject-2.0...not found.
Checking for library gtk-x11-2.0...not found.
Checking for library gdk-x11-2.0...not found.
Checking for library gdk_pixbuf-2.0...not found.
Checking for library gtkglext-x11-1.0...not found.
Checking for library atk-1.0...not found.
Checking for library gio-2.0...not found.
Checking for library gdkglext-x11-1.0...not found.
Checking for library pango-1.0...not found.
Fetching the git repository from github.com...
git fetch git://github.com/factor/factor.git master
From git://github.com/factor/factor
 * branch                  master     -> FETCH_HEAD
Updating the working tree...
From git://github.com/factor/factor
 * branch                  master     -> FETCH_HEAD
Already up to date.
Backing up factor...
cp: cannot stat 'factor': No such file or directory
cp: cannot stat 'libfactor.a': No such file or directory
cp: cannot stat 'boot.x86.126.image': No such file or directory
cp: cannot stat 'factor.image': No such file or directory
Done with backup.
rm -f vm/*.gch
rm -f vm/*.o
rm -f factor.dll
rm -f factor.lib
rm -f factor.dll.lib
rm -f libfactor.*
rm -f libfactor-ffi-test.*
rm -f Factor.app/Contents/Frameworks/libfactor.dylib
Building factor with 4 cores
make: *** No rule to make target 'linux-x86-126'.  Stop.
make failed

**Comment by mrjbq7** [comment]
Weird that it can’t detect WORD size and reports “126”?

**Comment by erg** [comment]
What does ``uname -s`` return?

Are you using msys2? mingw? Please link me to an installer and I can try it.

It looks like the C test program is returning 126 when you run it, which
means you don't have permissions. I can add a check that it returns only
32/64 so we error earlier.

If you compile this program you can also try to debug it:

# foo.c:
int main() { return (long)(8 * sizeof(void*));}

# gcc or whatever for cc here
cc -o foo foo.c
./foo
echo $?

**Comment by Gamer2014** [comment]
Based on what Doug Coleman wrote I changed the permissions on the build.sh file to:

-rwxr-xr-x   1 darkprogrammer darkprogrammer  21468 Mar 30 20:22 build.sh

This is the output that it produced:
darkprogrammer@Atari-Dev:~/factor$ ./build.sh update
Finding OS...
Finding ARCH...
Finding num cores...
Checking for all(x86_64-w64-mingw32-gcc x86_64-w64-mingw32-g++)...found!
Finding WORD...
./build.sh: line 325: ./factor-word-size: cannot execute binary file: Exec format error
OS=linux
ARCH=x86
NUM_CORES=4
WORD=126
DEBUG=
REPRODUCIBLE=
CURRENT_BRANCH=master
FACTOR_BINARY=factor
FACTOR_LIBRARY=libfactor.a
FACTOR_IMAGE=factor.image
MAKE_TARGET=linux-x86-126
BOOT_IMAGE=boot.x86.126.image
MAKE_IMAGE_TARGET=x86.126
GIT_PROTOCOL=git
GIT_URL=git://github.com/factor/factor.git
DOWNLOADER=wget -nd
CC=x86_64-w64-mingw32-gcc
CXX=x86_64-w64-mingw32-g++
MAKE=make
COPY=cp
DELETE=rm
Checking for any(chmod)...found chmod!
Checking for any(uname)...found uname!
Checking for any(git)...found git!
Checking for any(wget curl)...found wget!
Checking for any(clang x86_64-w64-mingw32-gcc i686-w64-mingw32-gcc gcc)...found x86_64-w64-mingw32-gcc!
Checking for any(clang++ x86_64-w64-mingw32-g++ i686-w64-mingw32-g++ g++ cl)...found x86_64-w64-mingw32-g++!
Checking for any(make gmake)...found make!
Checking for any(md5sum md5)...found md5sum!
Checking for any(cut)...found cut!
Checking for library GL...not found.
Checking for library X11...not found.
Checking for library pango-1.0...not found.
Checking for library gobject-2.0...not found.
Checking for library gtk-x11-2.0...not found.
Checking for library gdk-x11-2.0...not found.
Checking for library gdk_pixbuf-2.0...not found.
Checking for library gtkglext-x11-1.0...not found.
Checking for library atk-1.0...not found.
Checking for library gio-2.0...not found.
Checking for library gdkglext-x11-1.0...not found.
Checking for library pango-1.0...not found.
Fetching the git repository from github.com...
git fetch git://github.com/factor/factor.git master
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 2), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (6/6), done.
From git://github.com/factor/factor
 * branch                  master     -> FETCH_HEAD
Updating and restarting the build.sh script...
From git://github.com/factor/factor
 * branch                  master     -> FETCH_HEAD
Updating 2d85dafa98..905e2cfb6b
Fast-forward
 build.sh | 9 +++++++++
 1 file changed, 9 insertions(+)
Finding OS...
Finding ARCH...
Finding num cores...
Checking for all(x86_64-w64-mingw32-gcc x86_64-w64-mingw32-g++)...found!
Finding WORD...
/home/darkprogrammer/factor/build.sh: line 326: ./factor-word-size: cannot execute binary file: Exec format error
Word size should be 32/64, got 126
darkprogrammer@Atari-Dev:~/factor$

**Comment by mrjbq7** [comment]
There seem to be a couple of problems. 

This is causing the build update to fail:

Finding WORD...
./build.sh: line 325: ./factor-word-size: cannot execute binary file: Exec format error

But maybe the underlying cause of that is causing the subsequent die when bootstrapping an image. 

Question;

Does a binary download work on your computer?

**Comment by Gamer2014** [comment]
Looks like a binary will work.  here's a screenshot.

![Screenshot from 2020-03-30 20-53-21](https://user-images.githubusercontent.com/7112112/77975988-b7734800-72c9-11ea-83cf-4e75f2597307.png)

**Comment by erg** [comment]
The permissions are failing on the script that determines the word size, 32
or 64, not on build.sh. Don't change the permissions on build.sh

build.sh generates a C file that compiles (CC returns 0) but then fails to
execute because of permissions. I tried to give some instructions to make
this C program in my previous email so you can debug the permissions on
that generated file.

What is the output of umask?
$ umask
0022

What is the output of ``uname -s``?
$ uname -s
MINGW32_NT-10.0-18363

Compile and run this and fix the permissions if necessary:
// foo.c
int main() { return (long)(8 * sizeof(void*));}

gcc -o foo foo.c
./foo
# expect permissions error
# chmod a+x foo
# expect it to work, then ``echo $?`` for 32 or 64

**Comment by Gamer2014** [comment]
Doug:

darkprogrammer@Atari-Dev:~$ uname -s
Linux


darkprogrammer@Atari-Dev:~$ gcc -o foo foo.c
darkprogrammer@Atari-Dev:~$ ./foo
darkprogrammer@Atari-Dev:~$ echo $?
64
darkprogrammer@Atari-Dev:~$

**Comment by erg** [comment]
Ok, it looks like ``build.sh`` is finding a gcc for Windows 32 called ``x86_64-w64-mingw32-gcc`` instead of regular ``gcc``. I wonder why...

**Comment by erg** [comment]
Oh! I figured it out. For some reason you have that compiler installed but you're on Linux. The script doesn't care...

```bash
set_cc() {

    # on Cygwin we MUST use the MinGW "cross-compiler", therefore check these first
    # furthermore, we prefer 64 bit over 32 bit versions if both are available
    test_programs_installed x86_64-w64-mingw32-gcc x86_64-w64-mingw32-g++
    if [[ $? -ne 0 ]] ; then
        [ -z "$CC" ] && CC=x86_64-w64-mingw32-gcc
        [ -z "$CXX" ] && CXX=x86_64-w64-mingw32-g++
        return
    fi

    test_programs_installed i686-w64-mingw32-gcc i686-w64-mingw32-g++
    if [[ $? -ne 0 ]] ; then
        [ -z "$CC" ] && CC=i686-w64-mingw32-gcc
        [ -z "$CXX" ] && CXX=i686-w64-mingw32-g++
        return
    fi

    test_programs_installed clang clang++
    if [[ $? -ne 0 ]] && clang_version_ok ; then
        [ -z "$CC" ] && CC=clang
        [ -z "$CXX" ] && CXX=clang++
        return
    fi

    # gcc and g++ will fail to correctly build Factor on Cygwin
    test_programs_installed gcc g++
    if [[ $? -ne 0 ]] ; then
        [ -z "$CC" ] && CC=gcc
        [ -z "$CXX" ] && CXX=g++
        return
    fi

    $ECHO "error: high enough version of either (clang/clang++) or (gcc/g++) required!"
    exit_script 10
}
```

**Comment by erg** [comment]
My bad for not reading the issue more closely. Please ``git pull`` and try again.

**Comment by Gamer2014** [comment]
Doug & John, thank you both so much for looking into this & figuring out the solution.  For the life of me I can't remember installing that version of the compiler.  sorry for the commotion I caused!

**Comment by erg** [comment]
No problem, I fixed the script in several ways so it's worth it. Have fun!
