### ISSUE TITLE
pageup/pagedown don't work if there is only one line in the editor

### ISSUE THREAD

**Issue by erg** [factor/factor#2295]
They are supposed to go to the beginning/end of the line, but this only works if there are several lines.

```
asdf<cursor>  ! press page up, should go to beginning of line
<cursor>asdf  ! page down should go end of line
```

It works if there are two+ lines.

Fix will likely go in
```factor
USE: ui.gadgets.editors
USE: documents.elements
```

Up and down work correctly; do it like that code path.

**Comment by mrjbq7** [comment]
Fixed by 130c1d8dd67fb367cfbdaca339310594937e302c.
