### ISSUE TITLE
Enter doesn't always close autocomplete window

### ISSUE THREAD

**Issue by erg** [factor/factor#2297]
The autocomplete window should probably always close if you hit enter. If there are no auto-complete candidates, then it stays open.

```
<tab><enter> ! should close auto-complete
```

Edit: Actually maybe this is a bad idea.

```
asdfasdfasdf<tab><enter> ! should close it too?
```

**Comment by mrjbq7** [comment]
Fixed in 878de2f1fc60fe1775d3a1c54292cb986134a7bc.
