### ISSUE TITLE
Default values for various command line switches

### ISSUE THREAD

**Issue by timor** [factor/factor#2302]
I want to try non-default values for some of the command line arguments like `-retainstack=...` or `-callstack=...` to debug an issue.  However, I cannot find the default values of these parameters.  It would be nice if they showed up in `factor -help` as well.

**Comment by mrjbq7** [comment]
Added default values in 564720281de536b8f4a1e0324c3dac8323ae74dc.

Thanks for the suggestion!

(There is some risk that these get out of sync with ``os/image.cpp``, so we can keep an eye on that.)
