### ISSUE TITLE
x11 text is garbled

### ISSUE THREAD

**Issue by erg** [factor/factor#2304]
```
"demos" run
```

Not all of the x11 text, just here.

I'm not very good at gimp.

![Untitled](https://user-images.githubusercontent.com/27430/84352345-c6585f80-ab82-11ea-8c10-2cacb9993715.png)

**Comment by sfesenko** [comment]
I believe, this issue was introduced by commit eb7aad96c07200fabbc146c7472c639af66df94a.

**Comment by mrjbq7** [comment]
Thanks for that, I reverted for now.

**Comment by timor** [comment]
But why?

**Comment by mrjbq7** [comment]
I will go back and look at that commit relative to my HiDPI efforts. I was trying to allow sub pixel locations of text but that may be the wrong approach, or inconsistent on Linux renderers, or another code path might assume truncation as the original code did. 

Anyway, it’s better now! Thanks!
