### ISSUE TITLE
``right-alt + u`` should be auto-use on linux

### ISSUE THREAD

**Issue by erg** [factor/factor#2308]
``left-alt + u`` enables ``auto-use``
``right-alt + u`` is just a ``u``

this works on windows and mac

Does this have anything to do with alt-gr? Do we support that correctly everywhere?

**Comment by mrjbq7** [comment]
Needs more alt-right??

**Comment by erg** [comment]
```
➜  factor-master git:(master) ✗ sudo showkey
kb mode was ?UNKNOWN?
[ if you are trying this under X, it might not work
since the X server is also reading /dev/console ]

press any key (program terminates 10s after last keypress)...
keycode  28 release
keycode 100 press  ! right alt, alt-gr
keycode 100 release
keycode  56 press   ! left alt
keycode  56 release
```

**Comment by mrjbq7** [comment]
Can you see what ``event-modifiers`` is looking at?

I'm not sure how to get my right-alt to be alt-gr, at least with US English keyboard.

```diff
 : event-modifiers ( event -- seq )
-    state>> modifiers modifier ;
+    state>> [ dup . flush ] with-global modifiers modifier ;
```

**Comment by erg** [comment]
It's 128 for right alt-u.

**Comment by erg** [comment]
![MVIMG_20200627_162855](https://user-images.githubusercontent.com/27430/85932636-5c82ca00-b893-11ea-977e-572f7500e134.jpg)
