### ISSUE TITLE
Linux tray icon is stretched

### ISSUE THREAD

**Issue by erg** [factor/factor#2311]
![MVIMG_20200616_180912](https://user-images.githubusercontent.com/27430/84843804-82e07400-b00e-11ea-88a4-7fc4c850a4a3.jpg)

**Comment by itmuckel** [comment]
Which window manager? Other applications look normal despite the height of the task bar?

**Comment by erg** [comment]
arch linux.
```
echo $XDG_CURRENT_DESKTOP

GNOME-Classic:GNOME:
```

Other applications look normal in the tray.

**Comment by bpollack** [comment]
Well you sent me into a hell of a rabbit hole on this one, @erg, but good news: it's not us. And it's fixed in the next version of GNOME. https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1239

**Comment by bpollack** [comment]
(And https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2578 is the actual issue, which is what I meant to link to.)

**Comment by erg** [comment]
Thanks for finding this! Closing.

**Comment by mrjbq7** [comment]
Whoa! Good research!!
