### ISSUE TITLE
Typo: vocaulary should be vocabulary in hierarchy-docs.factor

### ISSUE THREAD

**Issue by odiferousmint** [factor/factor#2314]
Found a typo:

```
basis/vocabs/hierarchy/hierarchy-docs.factor:49:    { "root" "a vocaulary root" } { "prefix" string }
```

Is it a good idea to report such typos on a per-issue basis, or should we have an open issue for all typos? If you already have such an issue opened would you please give me a link?

**Comment by erg** [comment]
We correct them as they are found. So make a PR per typo or batch a few up if you are going to find more. Thanks!
