### ISSUE TITLE
resource:extra/cli/git: unknown-cpuinfo-line "vmx flags"

### ISSUE THREAD

**Issue by odiferousmint** [factor/factor#2315]
I ran: `"resource:extra" load-root`

and when it tried to load `resource:extra/cli/git/git.factor`, I got the following error:

```
unknown-cpuinfo-line
string "vmx flags"
```

Any ideas for a potential solution? I have not attempted to debug it yet.

**Comment by erg** [comment]
There's a word in unix.linux.proc that reads /proc/cpuinfo and throws an error if there are unknown fields. It shouldn't stop anything from loading, that's something to look into.

```
: line>processor-info ( processor-info string -- processor-info )

! Add a case for "vmx flags" around line 97
! add a slot for vmx-flags around line 51
! repeat until no unknown fields
! submit a patch
```

For bonus points, fix whatever is throwing an error on load.

I'll get to this one on the weekend if you don't make a patch! Cheesrs!
