### ISSUE TITLE
macOS font rendering too narrow after space

### ISSUE THREAD

**Issue by erg** [factor/factor#2324]
If you type a `` h`` (a space and then an ``h``) then the rendering looks clipped on the left side.

The first line is correct, the second line has a rendering imperfection.

<img width="156" alt="Screen Shot 2020-08-15 at 4 47 54 PM" src="https://user-images.githubusercontent.com/27430/90322233-7c3f8180-df17-11ea-8392-878add0a8be2.png">

**Comment by mrjbq7** [comment]
@erg do you still have this problem?

**Comment by erg** [comment]
It's fixed. Was it https://github.com/factor/factor/commit/379c043b7d7d9b2d0373c897c57e58eefcb02487 that fixed it?
