### ISSUE TITLE
``HEXCOLOR: cc`` error in case

### ISSUE THREAD

**Issue by erg** [factor/factor#2325]
```
HEXCOLOR: cc
1: HEXCOLOR: cc
               ^
Fall-through in case
object 2

```

**Comment by mrjbq7** [comment]
I implemented the "flex hex" model in ``colors.flex-hex`` that works for "CC" which turns into "0C0C00", I think.

For this issue, I'm going to just add an error in 699ebc960bfc01361df0e0dc9ec95150d4bffe05.
