### ISSUE TITLE
Unexpected interaction between `with` and `'[`

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#2328]
In the following code I would expect the 0 to be untouched, and in the innermost quotation 1 would get summed up with 2 to produce 3.
`{ 0 3 } [ 0 2 '[ 1 t [ _ + ] with when ] call ] unit-test`
Instead, the output is `1 2`, because 2 is summed up with 0.

**Comment by AlexIljin** [comment]
I'm guessing there is no issue after all. For example, `1 t [ 2 + ] with when` complains about stack underflow, which is understandable, since `with` wants to have an extra argument, which was taken away by `when`.
I guess I'm still not fully understanding how `with` works, sorry for the noise.

**Comment by jonenst** [comment]
Yes,
```factor
x y [ ] with
```
Is like
```factor
y [ x swap ]
```
Most of the time, y is supposed to produce a value for the quot to swap with x, like in
```factor
1 { 0 1 2 } [ - ] with map
```
When doesn't produce a value for the quot so or reaches below.
