### ISSUE TITLE
filter-all-subseqs-range and filter-all-subseqs in sequences.extras have incorrect stack effects

### ISSUE THREAD

**Issue by chunes3** [factor/factor#2332]
They both have the stack effect

    ( ... seq range quot: ( ... subseq -- ... ) -- seq )

but they are filters — they should have stack effect

    ( ... seq range quot: ( ... subseq -- ... ? ) -- seq )

They work okay if you use them in the listener, but in an optimizing compiler context you'll get errors for trying to use them.

**Comment by mrjbq7** [comment]
Fixed in 36b2ac97efd94119dbf0aa8618ae6c68265a43b8.
