### ISSUE TITLE
Add parsing words for defining inverses

### ISSUE THREAD

**Issue by lolbinarycat** [factor/factor#2334]
The `inverse` vocab is really cool, and somewhat unique to factor. However, the lack of parsing words (as far as I can tell) makes it somewhat annoying to use. The implementation is pretty trivial, Ex: `SYNTAX: DUAL: scan-word scan-word define-dual ;`.

**Comment by mrjbq7** [comment]
Good idea!

How about this patch?

a84a34c5e2b74e0db8baa81647755a0ae0427425

**Comment by lolbinarycat** [comment]
Seems good!
