### ISSUE TITLE
Update unicode tables

### ISSUE THREAD

**Issue by phred** [factor/factor#2335]
The tables included with `unicode.data` are for Unicode 5.2, updated 11 years ago:
https://github.com/factor/factor/tree/a84a34c5e2b74e0db8baa81647755a0ae0427425/basis/unicode/data

The latest spec (as of fall 2020) is Unicode 14.0.0, and the tables are available here:
https://unicode.org/onlinedat/online.html

Since `uncode.data` is itself a parser for the official flat file format this should be pretty straightforward. Happy to take a crack at this!

**Comment by mrjbq7** [comment]
I thought we'd updated to 11 in 2019?

44cbe83984f89ff8c53e2dd0b2ced1c268f922f0

**Comment by phred** [comment]
Ah cool, I guess I was was browsing an old tree then!

**Comment by erg** [comment]
Yes please update to Unicode 14 if you want!

**Comment by mrjbq7** [comment]
I think we might have some stuff updated to 12.0 maybe also?

3f1d7c8b4f2fae6975c51f4d38a767f0b151dbd4

Let's update to 14!

**Comment by mrjbq7** [comment]
If you have time, you could download the appropriate data files and update in the ``basis/unicode/...`` directories:

https://www.unicode.org/Public/UNIDATA/

Then run the unicode tests and see if it works!

I can also try looking early this week if you don't have time.

**Comment by phred** [comment]
I'm looking for easy issues to work on and currently between gigs, so I should be able to give it a whirl. (:
