### ISSUE TITLE
error loading json.reader: no word named "while*"

### ISSUE THREAD

**Issue by lolbinarycat** [factor/factor#2339]
I got the same error with the `xkcd` vocab, did something happen to this word?

**Comment by mrjbq7** [comment]
No, ``while*`` is in the ``kernel`` vocabulary:

https://docs.factorcode.org/content/word-while__star__,kernel.html

Not sure what you are seeing, but both ``json.reader`` and ``xkcd`` load fine for me.

**Comment by mrjbq7** [comment]
Did you ever figure out what this was?

**Comment by lolbinarycat** [comment]
Nope, still dosen't show up for me.

**Comment by mrjbq7** [comment]
Have you changed the ``vocab-roots`` variable in your local Factor image?

The ``kernel`` vocabulary (which contains ``while*``) is in ``resource:core`` and so necessarily would be loaded into the image unless somehow modified locally.

**Comment by lolbinarycat** [comment]
I just looked through `kernel.factor` and `while*` is indeed in there. I guess for some reason it doesn't get loaded?

**Comment by mrjbq7** [comment]
I mean you can always delete words from the image and cause problems:

```
IN: scratchpad << \ while* forget >>
IN: scratchpad USE: xkcd
1: USE: xkcd
            ^
resource:extra/xkcd/xkcd.factor

4: USING: accessors formatting html.entities html.parser
                                            ^
resource:extra/html/entities/entities.factor

30:     [
31:         [ dup next-escape ] [ escape, ] while* drop ,
                                                  ^
No word named “while*” found in current vocabulary search path

The following restarts are available:

:1      Defer word in current vocabulary
:2      Load resource:extra/html/entities/entities.factor again
:3      Load resource:extra/xkcd/xkcd.factor again

Type :help for debugging help.
```

**Comment by mrjbq7** [comment]
Try this:

```
IN: scratchpad "kernel" reload
```

It might take awhile though.

**Comment by mrjbq7** [comment]
You could always bootstrap with a fresh install of Factor.

```
$ ./build.sh update
```
