### ISSUE TITLE
Would it be useful to track pure words?

### ISSUE THREAD

**Issue by lolbinarycat** [factor/factor#2345]
words could be declared pure similar to how `inline` is used. It would be an error to use a non-pure word in a pure word. a word is pure if it does not mutate any objects and it has no side effects.

**Comment by lolbinarycat** [comment]
You wouldn't even have to declare every word pure, if you made purity a tri-state between `+pure+`, `+impure+`, and `f` (unknown). when a word was declared pure, you could then check words of unknown purity, essentaily lazily computing the purity of functions (that don't have a declared purity).

**Comment by timor** [comment]
Would that be conceptually different from the `flushable` and `foldable` declarations?

**Comment by lolbinarycat** [comment]
I guess flushable is basically what I was describing. My greater idea was actually haskell-style fusion, where a pure function that returns a new object is swapped out for a mutative version that doesn't allocate.

**Comment by timor** [comment]
Well if you write a word which creates a tuple with only read-only slots, and declare it inline, the Factor compiler unboxes the constructors if the tuple does not escape.  But maybe that does not fit your use case.  Also, if all arguments to the constructor turn out to be literal, they are replaced by a (stack-allocated) tuple literal.

**Comment by erg** [comment]
I think this is just `flushable`, which seems to be from SBCL https://gist.github.com/guicho271828/15162239f3a3bdb203c54392b0d64e04

We could call it `pure` instead. (rename flushable to pure?)


```
\ flushable help

Vocabulary
syntax

Syntax
: foo ... ; flushable

Word description
Declares that the most recently defined word has no side effects, and thus calls to this word may be pruned by the compiler if the outputs are not used. 

Note that many words are flushable but not foldable, for example clone and <array>.

Definition
USING: words ;
IN: syntax
SYNTAX: flushable last-word make-flushable ;
```

**Comment by catb0t** [comment]
I've always liked flushable as the Factor-ism for "pure" - it's just how we refer to the concept of pureness as it relates to the Factor runtime.

**Comment by erg** [comment]
`flushable` ftw
