### ISSUE TITLE
convert from parent class

### ISSUE THREAD

**Issue by lolbinarycat** [factor/factor#2348]
If I have my own tuple class that inherits from a different tuple class, Eg:
```
TUPLE: foo < url { bar initial: 5 } ;
```
How do I convert from the parent tuple to my tuple (in this example converting a `url` to a `foo`)?

**Comment by mrjbq7** [comment]
```factor
URL" http://google.com" tuple-slots foo slots>tuple
```

**Comment by mrjbq7** [comment]
It might look like the return object is a ``url``, but you can ``describe`` it (or do a ``class-of`` and see it's a ``foo``).

**Comment by lolbinarycat** [comment]
That does work, thanks!

**Comment by mrjbq7** [comment]
This wouldn't currently work in the other direction:

```factor
URL" http://google.com"
tuple-slots foo slots>tuple ! creates a foo
tuple-slots url slots>tuple ! throws an exception too-many-slots
```

It's not hard to make a ``convert-to`` type of word that just truncates instead of throwing that error... maybe we should have that.

**Comment by mrjbq7** [comment]
I didn't clean this up into a few smaller words that are shared with the ``tuple-slots`` and ``slots>tuple`` words, but here is a version that maybe does both directions the way you'd expect:

```factor
: convert-to ( obj class -- tuple )
    [ tuple-slots ] [ tuple-class check-instance ] bi*
    check-slots [
        all-slots [ length short head ] keep
        dup length tail-slice
        [ [ initial>> ] map append ] unless-empty
    ] keep tuple-layout <tuple> [
        [ tuple-size <iota> ]
        [ [ set-array-nth ] curry ]
        bi 2each
    ] keep ;
```

**Comment by mrjbq7** [comment]
If you think it useful, and have a good name for ``convert-to``, maybe we should add this as a feature, for now closing.
