### ISSUE TITLE
(Unnecessary?) size increase in Factor due to unused UCA CollationTest

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2360]
In development versions of Factor, compared to the release version, the size of Factor on (SSD!) disk has increased significantly from about 200 MB to currently 275 MB. When looking for causes of these changes, I discovered one very large file (17.5MB) to be added, which does not seem to be used at all:
basis\unicode\UCA\CollationTest\CollationTest_NON_IGNORABLE.txt

It's sitting next to another large file (19.5MB)
basis\unicode\UCA\CollationTest\CollationTest_SHIFTED.txt

Both account to nearly 14% of the total size of Factor on disk.

Is it possible to reduce the size by removing the unused file and/or using a preprocessed/compressed input file?

**Comment by mrjbq7** [comment]
Good point!  ``CollationTest.zip`` is provided that we could use an unzip on demand for the tests.  I'll look into this later.

**Comment by mrjbq7** [comment]
Fixed in d97ac02d372950a89a83d119e02e5581913b2cfb.

I'd like to actually make UCD.zip also compressed, but that's a bit more work for some future point.

**Comment by nomennescio** [comment]
Wow! You solved that fast, you're amazing.
