### ISSUE TITLE
No support for getting an element of a shaped array?

### ISSUE THREAD

**Issue by chunes3** [factor/factor#2363]
Oddly, the `arrays.shaped` vocabulary provides support for setting an element of a shaped array with the `set-shaped-column-major` and `set-shaped-row-major` words, but there are no equivalents that I can find for getting an element. Perhaps words like the following could be added:

```
USING: accessors arrays.shaped kernel sequences ;

: get-shaped-column-major ( seq shaped -- elt )
    shaped-bounds-check
    [ shape calculate-column-major-index ] [ underlying>> ] bi nth ;

: get-shaped-row-major ( seq shaped -- elt )
    shaped-bounds-check
    [ shape calculate-row-major-index ] [ underlying>> ] bi nth ;
```

**Comment by mrjbq7** [comment]
Thanks!

Fixed in bf5d5d09e21c385db1e8e895f59069483394d1da.

We also have another multidimensional array library in the `tensors` vocabulary, restricted to floats right now but can be extended to more data types.
