### ISSUE TITLE
refresh on Windows on master locks Factor and then crashes

### ISSUE THREAD

**Issue by bpollack** [factor/factor#2382]
Doing a vanilla x64 build of Factor on Windows, running `refresh-all` immediately on first startup triggers a reload that erroneously tries to update `alien.factor`, `syntax.factor`, `arrays.factor`, and `kernel.factor`, none of which have been updated (it's a fresh build), and then promptly locks Factor and crashes hard.

**Comment by bpollack** [comment]
The crash happens with `0xc0000005`, which would indicate that Factor is trying to jump into the data page, incidentally. This could be anything from a null pointer read to generating bad code for the JIT; I don't have a decent debugger on this box, but this repros consistently, so I should be able to drill in a bit more later.

**Comment by mrjbq7** [comment]
So, I can reproduce this with a "fresh bootstrap" (e.g., build.cmd).

But, I tried doing a self-bootstrap where I made my own boot images and then bootstrapped and then I didn't have this issue.

Perhaps the way we're building windows images on my macOS doesn't store the right checksums, so they show up as different?  Line endings?  Hmm, investigating.

**Comment by bpollack** [comment]
I can look more carefully, and am happy to even try to fix this myself; I just didn't want to forget the bug existed. I strongly suspect Git automatically twiddling line endings is playing a role somewhere here, but like you, I'd need to look more carefully.

**Comment by mrjbq7** [comment]
I would think that too, but we do ``crc32 checksum-lines`` which should ignore line endings...

So the bug version is the windows-x86.64 image made from ``make-images`` on my Mac.

The working version is a windows-x86.64 image made on Windows.

That's typically never been a problem, however I am developing on my new M1 MacBook Pro, but using Rosetta.

**Comment by bpollack** [comment]
That's plausible. I've seen some complaints that Photoshop behaves in unexpected ways on an M1 (e.g., resizing was doing either double or half what was asked, I forget which). It's entirely plausible we're hitting related issues.

If you're just doing a vanilla bootstrap on a Mac, I can try with my Intel MacBook and see if I get the same result or a different one if you'd like.

**Comment by mrjbq7** [comment]
This problem should be resolved now.
