### ISSUE TITLE
sets: intersection, refine: small duplication

### ISSUE THREAD

**Issue by jonenst** [factor/factor#2385]
$  git grep -B 1 '\[ intersect ] map-reduce ]'
```
basis/regexp/disambiguate/disambiguate.factor-: intersection ( seq -- elts/f )
basis/regexp/disambiguate/disambiguate.factor:    [ f ] [ [ ] [ intersect ] map-reduce ] if-empty ;
--
core/sets/sets.factor-: intersection ( sets -- set/f )
core/sets/sets.factor:    [ f ] [ [ ] [ intersect ] map-reduce ] if-empty ;
--
core/sets/sets.factor-: refine ( sets -- set/f )
core/sets/sets.factor:    [ f ] [ [ ] [ intersect ] map-reduce ] if-empty ;
```
refine was moved from compiler.cfg.stacks.global to sets in 2016, but intersection was there from 2013.
Intersection in basis/regexp/disambiguate predates them all (2009)

I think this also shows that we are missing docs for the sets vocab, because https://docs.factorcode.org/content/article-set-operations.html makes it feel like it's listing all operations on sets but some are missing (like intersection, combine) , the only way to find them is to look at the words in the vocab (this https://docs.factorcode.org/content/vocab-sets.html )

regarding the naming, combine/refine go well together, but intersection is used more in mathematics. In english, we have intersect (2sets) and intersection (n sets) but this naming doesn't work for union (whats the equivalent of "intersect" / "intersection" for "union") ?

**Comment by mrjbq7** [comment]
Maybe ``intersect-all`` and ``union-all``?

Or ``intersection-of`` and ``union-of``?

**Comment by mrjbq7** [comment]
For now, I'll remove the duplicate words, but I'd love to solve the naming suggestion!

**Comment by jonenst** [comment]
well we have `: adjoin ( elt set -- )` and `adjoin-all ( seq set -- )` so to use these names and be coherent we should have `: union-all ( seq set -- )`  ? So I would say we need another name for combine/refine

**Comment by mrjbq7** [comment]
Except current Union is already Union-all in your example. I’m not sure it’s such a bad name....

**Comment by bpollack** [comment]
`union` meaning `union-all-the-things` seems correct to me; if you wanted to follow the concept of `intersect`/`intersection`, I'd suggest `unify`, but I feel like these are all dancing around an antipattern; what we really should have (conceptually) are `foo2` and `foo-all`. And that in turn dovetails around the discussion on the list about `bi`/`bi*`/`tri`/etc. v. `cleave`/`spread` and friends: these strongly indicate we're dancing around some abstraction and missing it, IMVHO.

**Comment by mrjbq7** [comment]
... varargs and kwargs ...

😄

**Comment by bpollack** [comment]
I generically do not want to know what varargs in a concatenative language actually look like, but I have to admit your emoji has pushed that into religious areas for me. 😛

**Comment by mrjbq7** [comment]
I'm removing ``intersection`` and leaving ``refine``, even though I dislike the name, to be consistent for the moment with ``assoc-refine``... and because ``combine/refine`` seem to go together until we rename them!!!

**Comment by mrjbq7** [comment]
We also need a word for ``: diff-all ( sets -- set ) ... ``

**Comment by bpollack** [comment]
Did you actually do this, @mrjbq7 ? I was thinking of beefing up the docs today for `sets` per the above discussion so at least we have things documented, but if we're removing words, that's potentially waste of time.

**Comment by mrjbq7** [comment]
I removed the duplication.

Perhaps we should keep an ``ALIAS: intersection refine`` for backwards compatibility.

I'm in favor of improving the docs.

I think also, the ``union-all`` and ``intersect-all`` are my favorite current names.

**Comment by bpollack** [comment]
I agree on the names. You want me to take a look at doing the rename then?

**Comment by mrjbq7** [comment]
Sure!

And any documentation improvements is good.

We should make Assoc-combine and assoc-refine consistent with whatever name
we have.  Or not. But at least consider it.

**Comment by bpollack** [comment]
I'll do them as separate PRs so we can look at them separately (and definitely do them as PRs instead of just pushing to `main` so we can eject if the result looks off)
