### ISSUE TITLE
private docs ?

### ISSUE THREAD

**Issue by jonenst** [factor/factor#2393]
So math/combinatorics-docs.factor had documentation for words that were in math.combinatorics.private . It was  at the end of the file. But since https://github.com/factor/factor/commit/37bddfba54f2b5d6bf4470cf099f2edf6e5abb03 we've been appending to the file so the new docs are in math.combinatorics.private, which is a mistake.

So should we add some checks ? Find another system to document private words because this one is error prone? Document that this is the recommended way to document private words and just fix math.combinatorics-docs.factor ?

Note:
Here's where we document private words in a `<PRIVATE PRIVATE>` subsection of *docs.factor:
./basis/math/combinatorics/combinatorics-docs.factor
./basis/compiler/cfg/dataflow-analysis/dataflow-analysis-docs.factor
./basis/compiler/cfg/gc-checks/gc-checks-docs.factor

Other vocabs use PRIVATE but to define words to reuse markup code.

**Comment by mrjbq7** [comment]
The way it’s done there seems wrong. You can just USE: math.combinatorics.private and define help for those words. Let’s remove the IN: declaration.

**Comment by mrjbq7** [comment]
Fixed in 63e9a2704159212b16d25ff34efd56c5b91fd4cc and 8ac8c53d96b0e9bffad6829e48ca011a7624a442
