### ISSUE TITLE
"^" clash between math.functions and regexp.classes

### ISSUE THREAD

**Issue by Bubbler-4** [factor/factor#2394]
Probably a very minor issue, but I don't really like the fact that, whenever I enter `^` in a fresh session, I'm asked which one to use between `math.functions` and `regexp.classes`. I guess the particular name clash is worse than any others I might have encountered (I'm pretty sure there were other clashes but I can't remember) because:

* Every time I need it, it's `math.functions` one and not `regexp.classes` one, and I need it quite frequently
* Both are in `basis` root, and everything I tried to circumvent this issue failed (auto-use, `USE:` in `.factor-rc`, creating a new image)

I have two questions about this:

* Can I set up Factor so that it always grabs `math.functions` one, even in a fresh session?
* Or, can we rename the one in `regexp.classes` without having to fix many dependencies?

**Comment by mrjbq7** [comment]
Fixed in e69210d6d6233c9db54ab3a85bfefc84642be853.

**Comment by mrjbq7** [comment]
Thanks for the report!
