### ISSUE TITLE
Investigate Travis error?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2396]
https://travis-ci.org/github/factor/factor/jobs/749874242

```
...
Loading resource:basis/help/markup/markup.factor
Loading resource:basis/definitions/icons/icons.factor
Loading resource:basis/help/topics/topics.factor
Loading resource:basis/help/stylesheet/stylesheet.factor
Loading resource:basis/fonts/fonts.factor
Loading resource:basis/ui/theme/theme.factor
Loading resource:basis/colors/hex/hex.factor
Loading resource:basis/formatting/formatting.factor
Loading resource:basis/calendar/english/english.factor
assertion "return_address < compiled->size()" failed: file "vm/slot_visitor.hpp", line 257
./build.sh: line 682:  3831 Abort trap: 6           ./$FACTOR_BINARY -i=$BOOT_IMAGE
```

**Comment by bpollack** [comment]
Before I look into this, Travis is closing imminently. Do we want to look at moving somewhere else for CI?

**Comment by mrjbq7** [comment]
I'm not sure how much debugging we can do on Travis.  It's just a heisenbug that I hadn't seen before.

Also, they claim to migrate to ``travis-ci.com`` but maybe that requires new subscriptions instead of free.

Probably getting our build bots working by fixing the last couple small errors so releases get made again is a worthwhile effort.  The 32-bit one I caused with a predicate-def performance improvement.  The macOS one has a strange issue with ``tools.profiler.sampling``.

**Comment by mrjbq7** [comment]
It was on a gcc/x86-64 macOS configuration.

**Comment by bpollack** [comment]
Do we actually care about 32-bit support in 2020, being quite serious? Maybe we should let that go at this point?

**Comment by mrjbq7** [comment]
Maybe we should... that's kind of what the homebrew guys said when I tried to contribute legit and simple PostgreSQL patches to support 32-bit builds to their Formula... sigh.

**Comment by mrjbq7** [comment]
I kind of like the idea of someday Factor working on an embedded chip, but we're probably 100mb too big for that use case.

**Comment by bpollack** [comment]
Eh, that part's complicated. The embedded space right now is a bit split between 64-bit and 8- or 16-bit, with some also-ran weird 36-bits-and-the-like coming along as well. As far as I can tell, traditional 32-bit embedded CPUs are dead (with the arguable exception of ColdFire...which we never supported, anyway. Long live Mops for that domain, I guess?) So I'd love to look at this someday, but a classic Forth is probably better for now on the low-end, and we'll have our 64 bits on the high-end.

On Travis: best I can make out [from this press release](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), we'll lose macOS support, and (looking under "Building on a public repositories [sic] only") likely not fit into their new freemiumesque model, either. The atrociously named but quite capable Azure DevOps might be a suitable replacement, as might Sourcehut. Or we could see if we actually blow past their tiers before worrying about this.

**Comment by mrjbq7** [comment]
Sourcehut seems cool!

**Comment by bpollack** [comment]
I can take a stab at Sourcehut if you'd like. They notably only support FOSS-esque operating systems (so incl. the BSDs, but not Windows or macOS), but that might cover quite a bit. Unfortunately, all macOS build options I'm aware of are payware, although we could probably do spot builds with AWS' new offering if we needed to.

**Comment by mrjbq7** [comment]
If its useful, I'm open to paying for Travis.

Maybe we can get all our build machines on Travis if we do that...

**Comment by bpollack** [comment]
That's an option, I guess. Their pricing based on that article seems a bit steep, though: $15 buys you eight hours, which is a whole, like, ten PRs at our current test suite times. 🙃

**Comment by mrjbq7** [comment]
That is steep.

Really puts a value on faster compile times!

**Comment by jonenst** [comment]
As an alternative, I've been using Github Actions and it works really well
and supports Windows + macos + linux.

Le mar. 15 déc. 2020 à 22:43, Benjamin Pollack <notifications@github.com> a
écrit :

**Comment by bpollack** [comment]
I forgot about GitHub Actions. It's notably a thin veneer over Azure DevOps, but that's not a ding whatsoever; it's cheap, integrates well, and is coming from a battle-hardened part of Microsoft's cloud team. So yeah, that might be worth a serious look.

**Comment by erg** [comment]
I made a github actions for testing bootstrap and core. I'm not sure this issue is actionable, closing for now.

https://github.com/factor/factor/blob/master/.github/workflows/build-test-core.yml
