### ISSUE TITLE
Add 2group-map (and the like)

### ISSUE THREAD

**Issue by Bubbler-4** [factor/factor#2398]
`clump` has `2clump-map`, `3clump-map`, `nclump-map`, but `group` does not have such convenience words. The manual implementation `2 group [ first2 ... ] map` has appeared multiple times to me, usually while parsing a text file which is meant to contain some paired data. `assoc>map` lets me remove the `first2`, but the data isn't really a key-value pair.

That said, it is yet to be decided what to do when the seq length is not divisible by n. Maybe it can error, maybe it can silently ignore redundant items.

**Comment by mrjbq7** [comment]
Hi @Bubbler-4 !

Check out 76c9c9f2ac06222894daed9be11426b2b66ce0db.

Added ``ngroup-map`` and ``ngroup-map-as`` and some utility words ``pad-group`` and ``short-group``.

This should reduce your boilerplate code.

I decided ``ngroup-map`` can shorten the sequence to ignore the last elements if not divisible.  If you want to include them you can ``pad-group`` first with an element to extend the sequence in that case.

Feedback welcome!

**Comment by mrjbq7** [comment]
(We have a bunch of useful words in ``grouping.extras`` that we should probably promote to ``grouping``. This is kind of historically a place where we've allowed new features and ideas to simmer before being promoted to the core vocabularies.)

**Comment by mrjbq7** [comment]
Note: ``n-group`` is a different concept and probably needs a name that's a bit farther from ``ngroup-map`` to avoid user confusion.

**Comment by mrjbq7** [comment]
(Thoughts on just calling it ``group-map``?)

**Comment by mrjbq7** [comment]
(Or even ``map-groups``).

**Comment by mrjbq7** [comment]
Okay, I noticed ``clump-map`` could be made faster and generalized.

And both ``clump-map`` and ``group-map`` could be improved to allow calling non-inlined sequences... for example:

```factor
: foo ( seq -- seq' ) [ 2array ] 2 clump-map ;
```

Previously that (with ``nclump-map``) produced a warning that ``seq`` wasn't inlined... now it works.

**Comment by mrjbq7** [comment]
And now I made ``group-map`` a lot faster.
