### ISSUE TITLE
More name clashes ([a,b] family, in?)

### ISSUE THREAD

**Issue by Bubbler-4** [factor/factor#2402]
`[a,b]`, `[a,b)`, `(a,b]`, `(a,b)`

* Problem: These words appear in both `math.ranges` and `math.intervals` (both in basis) but only the former has been ever useful to me.
* Solution: Rename the words in `math.intervals` by prepending `interval-`?

`in?`

* Problem: This word appears in `sets` (core) and `interval-sets` (basis). I guess you get the point.
* Solution: Rename the `interval-sets` one to, say, `interval-in?`. But isn't it possible to make it a generic method implementation?

**Comment by mrjbq7** [comment]
We have a proposal being considered to rename the ranges to [a..b] forms. 

The in-interval? would be a better name for sure.

**Comment by mrjbq7** [comment]
https://github.com/factor/factor/blob/master/core/math/ranges/ranges.factor#L47

**Comment by Bubbler-4** [comment]
Cool, that would definitely work.

**Comment by mrjbq7** [comment]
Renamed ``interval-sets:in?`` to ``interval-sets:interval-in?`` to prevent common name conflict.

We still have aliases for math.ranges, but the future fix would be to remove those when code is updated, or to force update.  If we had the new lexer/parser then this could be a fixup that is auto-applied.

**Comment by mrjbq7** [comment]
This has been fixed.

If there are other clashing names we can address them individually.
