### ISSUE TITLE
Forgot to write "fry"?

### ISSUE THREAD

**Issue by kusumotonorio** [factor/factor#2424]
[`core/sets/sets.factor`](https://github.com/factor/factor/blob/master/core/sets/sets.factor) has been changed to use fryed quot at [this time](https://github.com/kusumotonorio/factor/commit/955938d09d21464125061d3751e721f4b9822ce8#diff-926c53feb78e6ea4c93803b6251ee7ac4cfeb1c25327238b74ecefd481c5331d), but it doesn't seem to have been declared to use `fry`.
When I rebuilt the image file today, it stopped here.

**Comment by erg** [comment]
I merged the ``USE: fry`` patch but I think it's not needed because ``'[`` and ``_`` are in ``syntax`` now. You might have to do ``IN: syntax`` and paste the ``SYNTAX: '[ ...`` definitions if your boot image is behind, or bootstrap the ``main`` branch and work from there.

**Comment by kusumotonorio** [comment]
Thank you. I now understand the situation that caused the problem.

**Comment by hiljusti** [comment]
Oh wait, so if I understand right - are fry quotations planned to be part of the standard language syntax in a future version?

**Comment by mrjbq7** [comment]
They are currently part of the standard syntax (promoted recently) in current git master.

**Comment by hiljusti** [comment]
Whoa, that's awesome!

**Comment by mrjbq7** [comment]
And locals as well. 

While it is true that Factor has very extensible syntax, and very modular, we are also trying to strike a balance with out of the box utility and think it’s about time to recognize the usefulness of fry and locals

**Comment by hiljusti** [comment]
That's awesome too, I find myself using locals (and also namespaces) in a majority of the things I write.

Is there somewhere that the language roadmap in general is already documented?

**Comment by mrjbq7** [comment]
There are a couple GitHub issues tracking 0.99 and 1.0 milestones, but also it’s just as much “what people want to build or contribute” and “what people vote and plan for”...
