### ISSUE TITLE
Fresh bootstrap on new Mac, can't open Factor.app the first time

### ISSUE THREAD

**Issue by erg** [factor/factor#2454]
```
Loading resource:basis/help/cookbook/cookbook.factor
Loading resource:basis/help/tutorial/tutorial.factor
Core bootstrap completed in 6 minutes and 30 seconds.
Bootstrap completed in 6 minutes and 30 seconds.
Bootstrapping is complete.
Now, you can run Factor:
/Users/erg/factor/./factor -i=factor.image
Loading vocab:bootstrap/finish-bootstrap.factor
Loading resource:basis/command-line/startup/startup.factor
Copying factor.image to factor.image.fresh...
erg@Dougs-MacBook-Pro factor % open Factor.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3665, _LSFunction=_LSOpenStuffCallLocal}
```

**Comment by erg** [comment]
https://stackoverflow.com/questions/2182040/the-application-cannot-be-opened-because-its-executable-is-missing

We could register the application with ``lsregister``:

``
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f MyApp.app
``
 
Or fix the ``CFBundleExecutable`` key in the plist maybe:
https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleexecutable?language=objc

**Comment by mrjbq7** [comment]
Closing, let's see if it happens again.

**Comment by erg** [comment]
This issue happened on a fresh install of macOS. It's not random, it's some permissions thing. We could make a fresh macOS vm and test, and then close if it passes?

**Comment by erg** [comment]
Ok let's close anyway XD
