### ISSUE TITLE
Vocabulary extra/python crashes upon loading

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2469]
Windows 7, x86_64, Factor 0.99 x86.64 (2101, heads/master-6ba333ed65, May 15 2021 18:13:14)

`"python" require`

crashes Factor.

Error message on stdout/stderr : `ImportError: No module named site`

**Comment by nomennescio** [comment]
Update: issue seem to be with loading `extra/python/ffi/ffi.factor`.

**Comment by mrjbq7** [comment]
This should be fixed a long time ago by 7a729b7637a33fa216c4664e7054c459e75b9a01.
