### ISSUE TITLE
Loading images and deploy-tool

### ISSUE THREAD

**Issue by George66** [factor/factor#2475]
"C:\\1.jpg" load-image make-texture
perfectly works in the listener, but throws  "unknown-image-extension" in
the executable file (obtained with the help of deploy-tool).
Simplest possible loading
https://pastebin.com/VzSZAxVy
 get
"bad-stack-effect
word load
got ( -- )
expected ( -- x ) "
Slightly more complex loading 
https://pastebin.com/ggtF5DZu
after deploy-tool get
"unknown-image-extension"
https://www.imagevenue.com/ME13HP4U
Win10 x64
George

**Comment by George66** [comment]
Tried with Linux Mint. All the same.

**Comment by alex-ilin** [comment]
I don't understand why in your examples you are using single backslash and double forward slash.
Should be the other way around.

Wrong: "C:\1.jpg", "C://1.jpg"
Right: "C:\\1.jpg", "C:/1.jpg"

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by George66** [comment]
All the same, try yourself.

**Comment by alex-ilin** [comment]
For me deployment doesn't always work, and it's a bit mysterious every time (one has to clear some caches somewhere, which I have to look up every time how to do, etc.), so I don't ever use it.
Also, load-image tends to hang forever on some images, but not on others, and even C-Break doesn't help.
So, to test two unreliable things in combination and see what doesn't work? No, thanks.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alex-ilin** [comment]
Last time I did some deployment (November 2019), I was using 32-bit Factor on Win10 and it loaded png- and tiff-files only.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mrjbq7** [comment]
I'm not aware of deploy related issues with image, however looking at your code, the issue is more simple: ``MAIN:`` words cannot have a stack effect, so are required to be ``( -- )``.

**Comment by mrjbq7** [comment]
I recommend trying it using factor first before deploy:

```
# As a vocabulary
$ ./factor -run=loading

# As a script
$ ./factor loading.factor
```

**Comment by George66** [comment]
> 
> 
> I'm not aware of deploy related issues with image, however looking at your code, the issue is more simple: `MAIN:` words cannot have a stack effect, so are required to be `( -- )`.

Thank you.

**Comment by George66** [comment]
Yes, I can do it myself. For Windows
https://pastebin.com/gTdQdVg4
For Linux use images.loader.gtk instead of  images.loader.gdiplus
There is  GENERIC: stream>image* in loader.factor vocab. Without definitions:) Factor is a language for persistent people.

**Comment by George66** [comment]
Sorry, in images.loader vocab. Without definitions.

**Comment by mrjbq7** [comment]
The definitions are in sub-vocabs, implemented for Linux, Windows, and Mac;

https://github.com/factor/factor/tree/master/basis/images/loader

**Comment by mrjbq7** [comment]
This particular issue seems addressed, the comment about better searchability for code implementations is something we should look into.
