### ISSUE TITLE
Swap argument order of `times` for easier use

### ISSUE THREAD

**Issue by umnikos** [factor/factor#2477]
It is common to use `times` with a literal number to repeat an action a fixed number of times:

    10 [ "Hello, world!" print ] times

Except the `10` and the `times` are separated by a long quotation, and it gets even worse with non-trivial examples. Besides, `10 times` looks way better and reads practically like English:

    [ "Hello, world!" print ] 10 times

**Comment by kusumotonorio** [comment]
I used to wonder why the word order of the `times` parameter was like this, too.

Factor's combinator words tend to put the quotation marks at the top of the stack, and I understand that the same rules apply.

**Comment by nomennescio** [comment]
I think the order is correct; usually code ("quotation") is fixed, and the number of repeats varies, hence should be an argument coming from the environment, something like

`: print-hello-worlds ( n -- ) [ "Hello, world!" print ] times ;`

**Comment by umnikos** [comment]
What I am expecting to actually happen is for a new word to be created that is just `swap times ; inline`. The problem is that I can't think of a good name for this new word. Any suggestions?

**Comment by nomennescio** [comment]
> What I am expecting to actually happen is for a new word to be created that is just `swap times ; inline`. The problem is that I can't think of a good name for this new word. Any suggestions?

You can create your own words, but I think you need to rethink your strategy; there really IS a good reason for the current order of arguments.

**Comment by erg** [comment]
```
factor64 git:(master) ✗ rg 'swap times'
extra/html/parser/parser.factor
66:    [ '[ _ advance drop ] 3 swap times ] bi ;

extra/imap/imap-tests.factor
110:            10 swap times
130:            10 swap times
```

With only three uses, I think we don't need a word. And I also don't know what I'd call it. Closing for now.

**Comment by nomennescio** [comment]
> ```
> factor64 git:(master) ✗ rg 'swap times'
> extra/html/parser/parser.factor
> 66:    [ '[ _ advance drop ] 3 swap times ] bi ;
> 
> extra/imap/imap-tests.factor
> 110:            10 swap times
> 130:            10 swap times
> ```
> 
> With only three uses, I think we don't need a word. And I also don't know what I'd call it. Closing for now.

Learned a new tool today! Instead of `find ... -exec grep`, can use `rg`, nice!
