### ISSUE TITLE
Opportunity : schedule release 0.99 for 2021-07-31, exactly 3 years after release 0.98

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2478]
After 3 years without an official release, we now have the opportunity to celebrate progress by releasing 0.99 at the same date, 3 years later.

Just pick any suitable stable snapshot, tag it '0.99', and update factorcode.org accordingly.

Of the very few external parties using release 0.98, [Codewars](https://www.codewars.com/) has the potential to increase the userbase of Factor. If you make a 0.99 release, I will do my part by asking Codewars to upgrade to 0.99, just as I did introduce 0.98 to them.

**Comment by mrjbq7** [comment]
Not a bad idea, the ARM64 port and the new parser are unlikely to be finished in the short term.

**Comment by erg** [comment]
We would like to release .99 soon, so this ticket has served its purpose. Closing!
