### ISSUE TITLE
Update raylib.dll api to 4.0 (was raylib guilock symbol missing)

### ISSUE THREAD

**Issue by jjonethal** [factor/factor#2479]
In Dll raylib.dll from https://downloads.factorcode.org/dlls/ and https://downloads.factorcode.org/dlls/64
Symbol GuiLock is missing - seems like raylib and gui are seperated now ?
![grafik](https://user-images.githubusercontent.com/6735757/126075153-710acc9a-c18a-4cba-a8e1-09b24873c81d.png)

**Comment by mrjbq7** [comment]
You can install yourself, obviously, but looks like @erg we need to install new RayLib DLL's maybe their 3.7.0 release?

https://github.com/raysan5/raylib/releases

**Comment by erg** [comment]
Updated to raylib 4.0 dlls. The Raylib binding itself might need some updating....

**Comment by mrjbq7** [comment]
@erg you need raygui.dll

**Comment by mrjbq7** [comment]
Nevermind i'm wrong.  I think raygui is packaged in raylib.dll

**Comment by mrjbq7** [comment]
This is fixed, closing.
