### ISSUE TITLE
Pango text rendering is garbled

### ISSUE THREAD

**Issue by gifti258** [factor/factor#2485]
A few months ago, text in the listener (and other windows) suddenly started to be mostly invisible or cut off for me.

![Bildschirmfoto_2021-09-05_03-06-20](https://user-images.githubusercontent.com/80504430/132111658-af388964-cc3a-4af5-bc9d-8431bc28aa86.png)

**Comment by mrjbq7** [comment]
Are you still seeing this problem?

I can't reproduce on any of my linux boxes.

**Comment by gifti258** [comment]
Yup, still broken. I use Arch32 on a 32bit machine, maybe that's why? Have you tried it with that distribution?

**Comment by gifti258** [comment]
I installed Debian today, because Arch fell apart some more. Here it works flawlessly. So I think it's definitely an issue with Arch32 packaging.

**Comment by erg** [comment]
Can we close this as an arch bug?

**Comment by mrjbq7** [comment]
Is Debian also 32-bit and working?

Or maybe it’s a bug with our 32-bit pango?

**Comment by gifti258** [comment]
It's on the same 32bit machine, so this Debian install is necessarily 32bit, also.

**Comment by erg** [comment]
If you want to report this issue to the Arch Linux 32 pango llibrary, go for it.

On our end, it doesn't look like there's anything to do? Closing for now.
