### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by gautamcgoel** [factor/factor#2494]
Hello all, I tried looking at the Factor tutorial at factorcode.org, but the website seems to be down. Is that intentional?

**Comment by erg** [comment]
Sorry about this. I think the ``fork`` command uses too much ram. There is a ticket to switch it to use ``posix_spawn`` which will help once completed.

Thanks for the heads up, I updated and rebooted the machine and hopefully it will work until I get some time to fix things.

**Comment by hiljusti** [comment]
https://github.com/factor/factor/issues/1862 Issue in question
