### ISSUE TITLE
Importing a source file

### ISSUE THREAD

**Issue by JohnGebbie** [factor/factor#2496]
In ~/projects/factorproject I a make file greetings.factor:
```
USING: ;
IN: greetings

: greet "hi" print ;
```
How do I use it in another source file or in the listener?

I try:
`factor-vm -run=listener <<< 'USE: greetings'`
I get:
```
Factor FACTOR_VERSION x86.64 (1889, FACTOR_GIT_LABEL-, Oct  6 2018 09:16:31)
[GCC 8.2.0] on linux
IN: scratchpad 1: USE: greetings
                 ^
Vocabulary does not exist
name "greetings"

Type :help for debugging help.
IN: scratchpad
```

**Comment by erg** [comment]
There's a palindrome tutorial which goes over a basic program which should answer your question. https://docs.factorcode.org/content/article-first-program.html

In your case, try putting this in ``factor/work/greetings/greetings.factor``

```factor
IN: greetings

: greet ( -- ) "hi" print ;
```

Then launch Factor ``./factor`` or launch the ui and do ``USE: greetings`` and it should load the ``greet`` word which you can then call.

Alternately, you can add another root in the ``.factor-roots`` file.

We have a gitter for questions like this that are not bug reports: https://gitter.im/factorcode/Lobby

**Comment by mrjbq7** [comment]
You can run a file like a script, if it has a MAIN: or top level code:

./factor /path/to/greetings.factor

But if you want to import it, then it (currently) needs to be in module structure:

/path/to/greetings/greetings.factor

And then /path/to would need to be a factor root. We don’t (currently) add the current directory to the vocabulary search path. 

https://docs.factorcode.org/content/article-add-vocab-roots.html
