### ISSUE TITLE
Out-of-date referral to irclogs.factorcode.org

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2497]
I just analyzed the log files at irclogs.factorcode.org, which is being referred to in the [README](https://github.com/factor/factor/blob/master/README.md) as the place to discuss all things Factor, and it showed people only logging in and logging out since about 2020, without any meaningful conversation happening. As a matter of fact, 20% of all logged traffic (that is, since 2016) is people just logging in and logging out. Shouldn't the  [README](https://github.com/factor/factor/blob/master/README.md) be adapted to mention it is there only for historical purposes?

**Comment by mrjbq7** [comment]
It didn't help that Freenode had a ton of drama and people seem to like Discord and Slack over IRC these days...

**Comment by mrjbq7** [comment]
Updated the README with a few of the other communities.

I don't really enjoy having Gitter, Slack, Discord, IRC, mailing list, etc.  It's too fractured... sigh.

**Comment by nomennescio** [comment]
Thanks! It also slightly worries me that the Factor community seems to more dwindling, in stead of growing. I try my best promoting it over at Codewars, and people are curious to learn about it, but the learning curve is very steep for many, and it's difficult to get new Factor programming challenges approved, as very little people are able to review and approve. It is however a promising population that is willing to experiment with new languages.

**Comment by nomennescio** [comment]
@mrjbq7 Maybe I'm doing something wrong, but I cannot find a Factor channel on Discord by using the search function.

**Comment by mrjbq7** [comment]
https://discord.gg/WcUEZ52J

**Comment by nomennescio** [comment]
@mrjbq7 It seems the pointer to the list archive is broken, because (apparently someone messed up)[https://lars.ingebrigtsen.no/2020/01/06/whatever-happened-to-news-gmane-org/] the mailinglist server...

**Comment by mrjbq7** [comment]
Wait, so all the links need to switch from news.gmane.org to news.gmane.io?

**Comment by nomennescio** [comment]
It seems [sourceforge](https://sourceforge.net/p/factor/mailman/factor-talk/) has the archives too, and it is listed as the server to (un)subscribe, so maybe that's a better choice?
