### ISSUE TITLE
TEST: appears twice in suggestion list?

### ISSUE THREAD

**Issue by erg** [factor/factor#2511]
<img width="348" alt="Screen Shot 2021-12-21 at 3 23 10 PM" src="https://user-images.githubusercontent.com/27430/146999466-b3121347-5744-498f-b6d8-bd7cb25a47fc.png">

Looks like the exact same location, too. (not visible in pic)

**Comment by mrjbq7** [comment]
something to do with the qualified-name lookup in ``words-matching``...

**Comment by mrjbq7** [comment]
since "TEST:" occurs twice and seems to be "prefixed"... but maybe it shouldn't since case doesn't match.

**Comment by erg** [comment]
<img width="552" alt="Screen Shot 2021-12-27 at 6 15 17 PM" src="https://user-images.githubusercontent.com/27430/147515064-4fb944d2-bfd4-4a9f-bcf4-1a68ee2a7c7a.png">

**Comment by mrjbq7** [comment]
Yep, i've almost got a fix for this...

**Comment by mrjbq7** [comment]
Fixed in ea4d6790b9519d96b897bdb800f33410815588e4.
