### ISSUE TITLE
Choosing editor restart immediately lets you choose again

### ISSUE THREAD

**Issue by erg** [factor/factor#2513]
Each place it says `continue-restart` it lets me choose again. Maybe I'm not supposed to call ``editor-class off`` because it works otherwise.

I think it happens when you select an editor you already loaded and selecting the restart doesn't reload the vocabulary which doesn't reset the ``editor-class`` variable.

<img width="469" alt="Screen Shot 2021-12-21 at 7 53 05 PM" src="https://user-images.githubusercontent.com/27430/147021655-d193ac77-29bd-48c2-828a-6321113ed0b4.png">

**Comment by mrjbq7** [comment]
Fixed in e0d07a32256e6928bd81a1b0961ef5a2fabd1c16.

Don't use ``editor-class off``, instead do ``f editor-class set-global``...

**Comment by mrjbq7** [comment]
We can improve how editors work for 0.100.
