### ISSUE TITLE
ulid: same-msec? check

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2519]
it looks like ``same-msec?`` checks for the same microsecond, not the same millisecond...

should it be changed?

https://github.com/factor/factor/blob/57cce5e2181ff39c1d603732c35f586ee84ca5b0/extra/ulid/ulid.factor#L31

**Comment by alex-ilin** [comment]
Yes, it should be changed millisecond.
I was not used to how small nanoseconds are when I wrote that code.
https://github.com/ulid/spec
