### ISSUE TITLE
Restarts error with wrong word name

### ISSUE THREAD

**Issue by erg** [factor/factor#2532]
In the last image, the error is wrong. Re-definitions should have the same name, these two do not because of the restarts.

If the using list is ``USING: ui.text.private ;`` then refresh-all works correctly.

```
! delete all using list
IN: ui.text.core-text
```

f2 refresh-all
<img width="611" alt="Screen Shot 2021-12-30 at 12 26 00 PM" src="https://user-images.githubusercontent.com/27430/147778596-f4969e8b-85cb-46de-9e44-a8a69db185ea.png">
<img width="601" alt="Screen Shot 2021-12-30 at 12 26 11 PM" src="https://user-images.githubusercontent.com/27430/147778608-f11028c4-8e63-4b72-b586-c7d6ca11c735.png">
<img width="606" alt="Screen Shot 2021-12-30 at 12 26 21 PM" src="https://user-images.githubusercontent.com/27430/147778615-f04ee3d3-dbe1-4a6d-b087-e5d4fd26994a.png">

**Comment by mrjbq7** [comment]
I can't reproduce the errors showing ``string>image``,  but i get the re-definition error of ``string-dim`` when you "Defer" instead of "Use ui.text.private" in the first restart...

**Comment by erg** [comment]
Possibly fixed by 7b7b90d9e7a639baf1cf3e12151ccd576fece66b. Closing for now, reopen if you can trigger it. (I can't!)
