### ISSUE TITLE
Editing command doesn't work (needs restarts on ambiguous word names)

### ISSUE THREAD

**Issue by erg** [factor/factor#2533]
```
USE: alien.c-types ! enter so we are using it
float[tab] ! select the one from alien.c-types
ctrl-e ! nothing happens
ctrl-h ! no help as expected
```

<img width="526" alt="Screen Shot 2021-12-30 at 1 11 27 PM" src="https://user-images.githubusercontent.com/27430/147781413-aaae9f9d-458c-459a-bd46-81c50ad5e886.png">

<img width="930" alt="Screen Shot 2021-12-30 at 1 23 09 PM" src="https://user-images.githubusercontent.com/27430/147782161-19b58861-aa36-4672-8965-3ab752eda95c.png">

**Comment by mrjbq7** [comment]
I broke it! 

Fixed in 8308cb629844e5fb7b97731f76ae6d6473113330.
