### ISSUE TITLE
sigset_t definition that works and doesn't crash with posix_spawn interface

### ISSUE THREAD

**Issue by catb0t** [factor/factor#2535]
I've tried to research this issue and after many days of debugging I give up but am surely overlooking something obvious.

## What doesn't work?

Any definition for `sigset_t` that I can think of. in POSIX, `sigset_t` should be either an integer or a C object, but shouldn't itself be a pointer type until it needs to be a parameter by reference (not just as an out parameter, but as input).

My platform: glibc 2.32 on Ubuntu Linux x86-64

Note that the failures happen in `posix_spawn_*` functions, never in `sigemptyset` o r `sigfillset`. Usually in `posix_spawn_setsigmask` and `setsigdefault`, less commonly in `getsigmask`/`getsigdefault`.

First, we'll need these declarations:
```factor
USING: alien.c-types alien.syntax alien.data kernel libc math ;
IN: sigset-debug
FUNCTION: int sigemptyset ( sigset_t* set )
FUNCTION: int sigfillset ( sigset_t* set )
FUNCTION: int posix_spawnattr_init ( posix_spawnattr_t* attr )
FUNCTION: int posix_spawnattr_getsigdefault ( posix_spawnattr_t* attr, sigset_t* sigdefault )
FUNCTION: int posix_spawnattr_setsigdefault ( posix_spawnattr_t* attr, sigset_t* sigdefault )

: <posix-spawnattr> ( -- attr )
    f posix_spawnattr_t <ref> [
        posix_spawnattr_init
    ] keep [ [ throw-errno ] unless-zero ] dip ;

: get-sigdefault ( attr: posix_spawnattr_t out-param: sigset_t -- sigdefault )
    [ posix_spawnattr_getsigdefault ] keep nip ;

: set-sigdefault ( attr: posix_spawnattr_t sigdefault: sigset_t -- )
    posix_spawnattr_setsigdefault drop ;
```

#### All of the following are broken in one way or another.

**Definition**: plain unsigned long - Current definition in Factor main branch.
```factor
TYPEDEF: ulong sigset_t

<posix-spawnattr> dup
0 sigset_t <ref> dup sigfillset drop

set-sigdefault      ! works until GC

0 sigset_t <ref> dup sigemptyset drop

get-sigdefault .

gc

--> B{ 16 32 0 0 0 0 0 0 } *crash*
```
`critical_error: Invalid header in base_size: 7f06e0fea470`

**Broken**: Works great until a GC happens. Usually works the first time, and then calling `posix_spawnattr_setsigdefault` again with a different new `sigset_t` object will crash the VM and/or give `~pprint error: byte array~` in the Listener, which will crash if you inspect it (see error in spoiler).

*If it works after GC*, and you try to later use the `posix_spawnattr_t` object to which a `ulong sigset_t` like this was applied as mask or default, Factor will crash then anyway.

POSIX allows `sigset_t` to be an integer type, but this may be incompatible with the libc implementation of `posix_spawn_*` functions, which may expect it to be 128 bytes wide depending on how libc was compiled (see **Why** section).

<details> <summary><code>integer-length-expected</code> Error in print-error!</summary>

```factor
Error in print-error!
Error in thread 70 (UI update, [ self ui-thread set-global update-ui-loop ]):

integer-length-expected
Error in print-error!

(U) Quotation: [ set-namestack init-catchstack self quot>> call => stop ]
(O) Word: update-ui-loop
(O) Word: rethrow
(O) Method: M\ object error-in-thread
(U) Quotation: [
        [ error-in-thread. nl print-error nl :c flush ] with-global
        => stop
    ]
(U) Quotation: [ swap >n call => ndrop ]
    Word: with-variables
(U) Quotation: [ error-in-thread. nl print-error => nl :c flush ]
(O) Word: print-error
(O) Word: describe
(O) Word: (describe)
(O) Word: simple-table.
(O) Word: pprint-cell
(O) Word: pprint-short
(O) Word: pprint
(O) Word: pprint*/predicate-engine
(O) Word: method?
(O) Word: word-prop
(O) Method: M\ word props>>
(U) Quotation: [ leaf-signal-handler => ]
    Word: leaf-signal-handler
(U) Quotation: [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]
```
</details>
<br>

**Definition**: ulong pointer typedef and `malloc`

```factor
TYPEDEF: ulong* sigset_t

<posix-spawnattr> dup
128 malloc dup sigfillset drop

set-sigdefault       ! works until GC

128 malloc dup sigemptyset drop

get-sigdefault .
gc
```
`critical_error: Invalid header in slot_count: 7f147942c690`

**Broken**: Works until GC.

Works in C but probably UB for aliasing reasons. As shown in the **Why** section, this works the same as the struct with a pointer/array member because it's always treated as opaque.

**Definition**: `struct` with ulong pointer member and `malloc`
```factor
STRUCT: sigset_t { val ulong* } ;

<posix-spawnattr>
128 malloc dup sigfillset drop sigset_t <struct-boa>

set-sigdefault  ! immediately crashes the UI; crashes on GC
```

`fatal_error: Memory protection fault during gc: 0x18`

**Broken**: UI immediately cascading errors, VM will crash on GC in the console listener. Maybe I need to cast the `malloc` pointer to `ulong*`?. Also works in C.

**Definition**: struct with `unsigned long [16]` member

```factor
USING: literals layouts ;
<< CONSTANT: SIGSET_NUM_WORDS $[ 1024 8 1 cells * / ] >>
STRUCT: sigset_t { val ulong[SIGSET_NUM_WORDS] } ;

<posix-spawnattr>
sigset_t <struct> dup sigfillset drop

posix_spawnattr_setsigdefault

sigset_t <struct> dup sigfillset drop
posix_spawnattr_getsigdefault .
gc
```
`critical_error: Invalid header in base_size: 7f06e0fea470`

**Broken**: Works until GC.

This definition mirrors how glibc and musl libc actually declare `sigset_t`.

## Why I think those should work and/or don't work

In glibc and musl libc, `sigset_t` is declared like this:

[glibc/sysdeps/unix/sysv/linux/bits/types/__sigset_t.h](https://code.woboq.org/userspace/glibc/sysdeps/unix/sysv/linux/bits/types/__sigset_t.h.html#__sigset_t):

```c
#define SIGSET_NUM_WORDS (1024 / (8 * sizeof (unsigned long int)))

typedef struct {
    unsigned long int __val[SIGSET_NUM_WORDS];
} sigset_t;
```

On x64 `SIGSET_NUM_WORDS` is 16; `sizeof (sigset_t) == 128` = 1 bit per possible signal.

I would write this in Factor as:
```factor
USING: literals layouts math classes.struct ;
<< CONSTANT: SIGSET_NUM_WORDS $[ 1024 8 1 cells * / ] >>
STRUCT: sigset_t { val ulong[SIGSET_NUM_WORDS] } ;
```
The Factor definition should not be a reference type from the FFI's view, only being made into a pointer when a callee parameter is a pointer type.

`sigfillset` and `sigemptyset` work with this declaration in C and Factor.

Factor and C results are the same here:
```factor
IN: scratchpad  sigset_t <struct> [ sigemptyset ] keep .
                sigset_t <struct> [ sigfillset  ] keep .

S{ sigset_t
    { val ulong-array{ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 } }
}
S{ sigset_t
    { val ulong-array{ 18446744067267100671 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 } }
}
```

That only the 1st 8 bytes are changed seems to imply that even though `sizeof (sigset_t) == 128` when I compile a program, my glibc was compiled with `sizeof (sigset_t) == 8` (or something else is going on).

This is a good reason why the current definition of `sigset_t` in Factor is `TYPEDEF: ulong sigset_t`.

Scalar `sigset_t` is POSIX-compliant but the issue arises when invoking functions like `posix_spawnattr_setsigdefault`, if they are compiled with `sizeof (sigset_t) == 128`.

[glibc/posix/spawnattr_setdefault.c](https://code.woboq.org/userspace/glibc/posix/spawnattr_setdefault.c.html#posix_spawnattr_setsigdefault):
```c
int posix_spawnattr_setsigdefault (posix_spawnattr_t *attr, const sigset_t *sigdefault) {
  memcpy (&attr->__sd, sigdefault, sizeof (sigset_t));
  return 0;
}
```

If glibc thinks `sigset_t` is 8 bytes then it should just read less than the input buffer, so the crashes are beyond me.

**Comment by erg** [comment]
On my M1 Macbook it's 4 bytes and on my linux machine it's 128 bytes!

```c
erg@Dougs-MacBook-Air.local  factor64 git:(master) ✗ cat sigset.c 
#include <signal.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
  printf("sizeof sigset_t %lu\n", sizeof(sigset_t));
  return 0;
}

erg@Dougs-MacBook-Air.local  factor64 git:(master) ✗ clang sigset.c && ./a.out     
sizeof sigset_t 4

On Linux:
sizeof sigset_t: 128
```

In Factor there are two definitions:

```factor
! IN: unix.process
TYPEDEF: uint sigset_t ! only on macos

! IN: unix.types
TYPEDEF: ulong sigset_t ! wrong
```

We need to remove the ulong definition and use 4 bytes on mac and 128 bytes on linux.

**Comment by erg** [comment]
```
(base) ➜  include cat x86_64-linux-gnu/bits/types/__sigset_t.h
#ifndef ____sigset_t_defined
#define ____sigset_t_defined

#define _SIGSET_NWORDS (1024 / (8 * sizeof (unsigned long int)))
typedef struct
{
  unsigned long int __val[_SIGSET_NWORDS];
} __sigset_t;

#endif
```

**Comment by catb0t** [comment]
Thanks! I knew macosx would be its own can of worms but I wasn't sure if this was the type of FFI abuse for which I deserve segfaults :')

**Comment by erg** [comment]
@catb0t I think I got it working. The problem is the void* types -- if we have to pass one in, we have to know the size first. The only way opaque types can work is if C creates the structs and passes them to us, and then we pass them around.

I pushed the code to unix.process.

**Comment by catb0t** [comment]
Ok, I previously had explicit STRUCT: defs for spawnattr and file_actions and I thought they were unstable so I switched back to `void*`s. I will pull this and try it though.

**Comment by erg** [comment]
According to this http://newosxbook.com/src.jl?tree=xnu&file=/libsyscall/wrappers/spawn/posix_spawn.c it looks like macOS allocates its own memory for you (whereas linux does not).

So the macOS version is opaque pointers, and you have to call things in two ways.

I think this would work:

```factor
GENERIC: <posix-spawnattr> ( -- attr )

M: linux <posix-spawnattr>
    posix_spawnattr_t <struct> [ posix_spawnattr_init check-posix ] keep ;

M: macosx <posix-spawnattr>
    f posix_spawnattr_t <ref> [ posix_spawnattr_init check-posix ] keep ;

: get-sigdefault ( attr: posix_spawnattr_t out-param: sigset_t -- sigdefault )
    [ posix_spawnattr_getsigdefault check-posix ] keep ;

: set-sigdefault ( attr: posix_spawnattr_t sigdefault: sigset_t -- )
    posix_spawnattr_setsigdefault check-posix ;
```

**Comment by catb0t** [comment]
erg you're a genius. i would need a brain the size of earth to have figured that out.

**Comment by erg** [comment]
Glad to help you get unstuck!
