### ISSUE TITLE
On Windows, closing f1/f3 ui windows with alt-f4 closes all of Factor

### ISSUE THREAD

**Issue by erg** [factor/factor#2538]
It should just close the window and not all of the windows.

**Comment by mrjbq7** [comment]
```
35:    { T{ key-down f { C+ } "F4" } close-window }
36:    { T{ key-down f { A+ } "F4" } com-exit }
```

**Comment by mrjbq7** [comment]
"Alt + F4 differs slightly from Ctrl + F4, which closes the current tab or window of the program you're currently using. For example, if you were on a web browser and had multiple tabs open, Alt + F4 would close the browser entirely while Ctrl + F4 would only close the open tab you were viewing."

https://www.businessinsider.com/alt-f4

**Comment by mrjbq7** [comment]
Is this a bug?

**Comment by mrjbq7** [comment]
I see, Alt-F4 should close the window and if there are no windows open, then maybe exit the application?

And Ctrl-F4 should... do the same by default?

**Comment by mrjbq7** [comment]
Well, it didn't do anything before d3a35c26ce41d2b861c489cd6454826c48495214.

Fix it if you want!

**Comment by erg** [comment]
I have never used ctrl-f4, neat.

alt-f4 closes the whole window, but not necessarily the application. If you have two large chrome windows open it will close all the tabs and the one window, but not both. ctrl-f4 and ctrl-w both close tabs and then the window if it's the last tab.

**Comment by mrjbq7** [comment]
I think I mis-read something which made me think they worked the way I did it.

Perhaps we should make them both call ``close-window``?

**Comment by erg** [comment]
If we have proper tabs then ctrl-f4 should close them one-by-one.
