### ISSUE TITLE
Not all Unicode Code Points supported in names are correctly displayed in the Factor Browser

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2555]
Factor compiles, but the help pages do not show the correct name for the following word:
https://docs.factorcode.org/content/word-__65533__C%2Cunits.si.html

**Comment by mrjbq7** [comment]
Looks like the file was saved with the wrong encoding... fixed by re-saving as utf-8.

9ba553c8fffc940be48ba510317ee7d3dfec0d44
