### ISSUE TITLE
Vocabulary extra/python crashes upon loading (again) #2469

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2561]
Issue #2469 was closed, but reoccurs in 

Factor 0.99 x86.64 (2120, heads/master-62879bed37, Jan 12 2022 12:45:17)
[Microsoft Visual C++ 190023506] on windows

**Comment by nomennescio** [comment]
Found by running load-all

**Comment by mrjbq7** [comment]
That's surprising.  When you get a moment to try with the latest version, it's been updated to Python 3 and works with and without it for me.

Do you have python and it's failing to load properly?  Or do you not have python and it's crashing trying to do something with the python dll?

**Comment by nomennescio** [comment]
I will check this John

**Comment by nomennescio** [comment]
Factor 0.99 x86.64 (2133, heads/master-0e0aa69839, Jan 22 2022 01:13:14)
[Microsoft Visual C++ 190023506] on windows

In listeners (see factor/extra/python/ffi/ffi.factor)
```{ "python2.7" "python2.6" "python27" "python26" } find-library-from-list``` yields
"XXXXX\\lib\\dll\\64/python27.dll", with the beginning of the path to the dll.

From cmd.exe:
```
C:\>where python
INFO: Could not find files for the given pattern(s).

C:\>where python27.dll
XXXXX\lib\dll\64\python27.dll
```

**Comment by mrjbq7** [comment]
okay, so on your compute you have python, and it's crashing in ``PyInitialize`` maybe?

when you update it will be only Python 3+ since Python 2 is EOL.

**Comment by nomennescio** [comment]
```"python.ffi" require``` does not throw errors, neither do
```"python" test
"python.ffi" test```

**Comment by mrjbq7** [comment]
In case this is preventing you from working, you can add ``not loaded`` to the ``extra/python/tags.txt`` file which will prevent it from being included in a ``load-all``...

**Comment by nomennescio** [comment]
Thanks for the tip

**Comment by nomennescio** [comment]
The python2 dll is legacy, and is needed for a different configuration. I'm not sure what is causing the crash, but quite honestly, I'm trying to focus on getting my crosscompile to work.

**Comment by nomennescio** [comment]
If you require some input, let me know, and I can do some tests.

**Comment by nomennescio** [comment]
Now that I'm checking, I see I created a library with DLLs that Factor requires. In this case Factor not only requires the DLL, but a full installation. Maybe it's safer in this case to check for the Python executable in the path, than to assume the existence of the dll is sufficient?

**Comment by nomennescio** [comment]
I think this touches upon previous discussions about Factor vocabularies having dependencies on external executables/libraries, which are not explicitly managed.

**Comment by mrjbq7** [comment]
I think this particular bug with python is fixed, closing.
