### ISSUE TITLE
win32 won't bootstrap on 9f40760959b4cdb69d384f2f542368d274652b17

### ISSUE THREAD

**Issue by erg** [factor/factor#2563]
There's some kind of random error that popped up on this patch. It works on the patches after, and the patch in question is just a file rename and not the cause.

9f40760959b4cdb69d384f2f542368d274652b17

25251da8445cb2841ab31c8ba23af74c36541934 too

**Comment by nomennescio** [comment]
commit 1b9590d28f71ae0ffe6ee26e5275db2fae59f084 too when compiling with Cygwin : 

(U) [ [ dup open-dll ] dip => <library> ]
    make-library
(U) [ GetLastError => n>win32-error-string ]
    M\ windows dlerror
(U) [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]
T{ callsite-not-compiled f alien-invoke }
You have triggered a bug in Factor. Please report.
critical_error: The die word was called by the library.: 0
Starting low level debugger...

@erg or is this a different issue?

**Comment by mrjbq7** [comment]
Closing, let's see if it happens again.
