### ISSUE TITLE
error doesn't always show in listener ui

### ISSUE THREAD

**Issue by erg** [factor/factor#2575]
Copy/paste the html for factorcode.org into the string and run this. There is an error (you can tell because the error gets dismissed by pressing enter and you can see that `:s` reports the error) but the error message box is missing.

```factor
[[
... entire html of factocode.org ...
]] "abc" throw
```

Actual (I hit enter, the error should be showing):
<img width="768" alt="Screen Shot 2022-02-05 at 1 23 38 PM" src="https://user-images.githubusercontent.com/27430/152655934-8f988015-a882-4ddc-878a-1da4c9261ca4.png">

Expected:

<img width="479" alt="Screen Shot 2022-02-05 at 1 25 20 PM" src="https://user-images.githubusercontent.com/27430/152655987-afcf8e09-aad9-420f-80ce-a233ee089305.png">

**Comment by mrjbq7** [comment]
Fixed by 9ef14daed303bc236472d4969a9455b91e054718
