### ISSUE TITLE
Optimizing size of factor.image?

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2577]
The current factor.image is about 10x bigger than the factor executable, at about 130MB (for 'core' only I think). Loading more roots and saving the image grows that size considerably. A simple gzip on such an image gives a 6x size reduction, showing the potential for size improvement. An inspection reveals many repeating 0x00, 0x7f, and 0xEA bytes in an uncompressed image.

Is it an idea to support an additional image format which is more optimized for size?
Ideally the image format would be detectable in a header (I didn't check this out yet), but alternatively different filename postfixes can be used to discern, to support multiple formats (at least during a transition period). Even supporting just loading .gz or .zip images could work.

**Comment by nomennescio** [comment]
I noticed that all work is done by primitive `(save-image)`

**Comment by mrjbq7** [comment]
You can use the tools.image.analyzer vocabulary to see what’s in the image.
It’s a lot of generated code, definitions, documentation.

It would be nice to have a smaller footprint.  Ideas are welcome. We
currently mmap into it and then jump into the specified assembly at
locations.

**Comment by nomennescio** [comment]
I'm looking at image.cpp, and do indeed see the dumping/loading of raw memory.
Given that many people have SSDs, compressing data tend to nowadays give a slight performance hit, so startup times might be slighty affected by using a compressed image. Using a compression lib in the vm is extremely straightforward and would just be an optional pre- and postprocessing step.

**Comment by nomennescio** [comment]
Factor already has binding to three native compression libraries:
```
compression.zstd.ffi
compression.zlib.ffi
compression.snappy.ffi
```
But the corresponsing dynamic libraries are not distributed.
Picking one of these and include them in the standard Factor distribution might be a good candidate for a compression lib to handle compressed factor images. I will check these out.

**Comment by mrjbq7** [comment]
I’m not sure compression but itself is a net positive. I’d rather see if we can reduce the image footprint in fundamental ways. 

These images are stored on local file systems, rarely copied over the network, and already slow to mmap when they are large?

**Comment by mrjbq7** [comment]
For example, word properties could be reduced to a bitmap, better string interning might be possible, we should see where the bloat really comes from. 

A load-all image is like 400MB. 

Intuitively, that seems high. But I haven’t spent much time in awhile looking detailed at the image contents.

**Comment by nomennescio** [comment]
That would of course be a better approach, but also requiring more in-depth knowledge, and requiring more implementation effort. Even if that would be done, still compression with a lib might then give additional benefits. So both may be valuable! It seems `zlib` is more or less a defacto standard used by e.g. the Linux Kernel and Git. I will do some experiments with that.

**Comment by nomennescio** [comment]
An added benefits of improving in-memory representation of Factor objects, is a reduction in memory usage, as well as a reduced stress on the memory subsystem, potentially giving performance benefits.

**Comment by nomennescio** [comment]
Compression is timed running on VirtualBox (!)
```
127528760 Feb  6 15:40 factor.image      : uncompressed
 22959661 Feb  6 15:40 factor.image.gz : gzip standard compression, 0m3.623s
 21491681 Feb  6 15:40 factor.image.zst   : standard -3 compression, 0m0.677s, better compression than gzip 
 19229774 Feb  6 15:40 factor.image.zst   : -10 compression, 0m3.454s
 18441119 Feb  6 15:40 factor.image.zst   : -15 compression, 0m16.950s
 16595641 Feb  6 15:40 factor.image.zst   : max -19 compression, 1m27.106s
```

**Comment by mrjbq7** [comment]
Is that time to compress?

Our startup time to open, mmap the image, and jump into the c-to-factor startup quotation is pretty short, I'm curious what adding uncompress a 100+mb image then mmap into the result step would add.

And also, I'm still unsure of "why" we want to do this?

**Comment by mrjbq7** [comment]
How much of the image is unicode stuff, how much is word properties, how much is documentation, what objects have the most overhead, etc.

**Comment by nomennescio** [comment]
Yes, those are compression times. I will check decompression, but it's much faster than compression.
As for why, it's just saving disk space if you use compression. Maybe not a lofty goal, but it also helps in the size of the Factor distributable. If you use more in-depth knowledge to shrink image size, that could lead to runtime benefits. I currently have to little knowledge to give that a quick try.

**Comment by nomennescio** [comment]
Will check a `load-all` factor.image. First need to create one.

**Comment by nomennescio** [comment]
> You can use the tools.image.analyzer vocabulary to see what’s in the image. It’s a lot of generated code, definitions, documentation. It would be nice to have a smaller footprint. Ideas are welcome. We currently mmap into it and then jump into the specified assembly at locations.

Wow! I just had a look at the tools.image.analyzer. That's impressive!

**Comment by nomennescio** [comment]
https://github.com/facebook/zstd
BSD License

**Comment by nomennescio** [comment]
I've noticed that the Factor image fall roughly into 2 incompatible groups : 32- and 64-bit images. As core parameters need to be the same for both variants, in 64 bit images (cell size 8 bytes), 50% of such cells are unused. When scanning through a 64 bit image file, I noticed that many pointers (?) have more or less constant upper 4 bytes value. Introducing a simple variable length encoding might therefore already yield significant size reduction. Also a simple dictionary approach for 64 bit values can help with often repeated values. Using a true compressed image can of course easily beat that.

**Comment by erg** [comment]
Should we load the one with the most recent timestamp if theres `.image` and `.image.zst` both?

**Comment by mrjbq7** [comment]
https://github.com/phiresky/sqlite-zstd

**Comment by mrjbq7** [comment]
If we had compressed images, would it take 20 seconds to save?

I'm thinking it might be good to put Factor on a diet by going through some of the obvious stuff in the image analyzer, string interning, etc.

**Comment by nomennescio** [comment]
> If we had compressed images, would it take 20 seconds to save?
> 
> I'm thinking it might be good to put Factor on a diet by going through some of the obvious stuff in the image analyzer, string interning, etc.

The 20 s above is to save on a VirtualBox Linux, on real HW that's going to be much faster.

**Comment by nomennescio** [comment]
Latest update support decompression at a cost of about 50ms during startup, which is neglectable, with a compression of about 7 times smaller as the original image.

See https://github.com/factor/factor/commit/b1cf1b85e08196d656931082b7ef6acbd67b39d7

**Comment by nomennescio** [comment]
Updated compression performance:
```
-rwxrwxr-x+ 1 130388264 factor.image

-rwxrwxr-x+ 1  24125674 factor.image1
-rwxrwxr-x+ 1  23101234 factor.image2
-rwxrwxr-x+ 1  21915406 factor.image3
-rwxrwxr-x+ 1  21819495 factor.image4
-rwxrwxr-x+ 1  20687120 factor.image5
-rwxrwxr-x+ 1  20051415 factor.image6
-rwxrwxr-x+ 1  19813513 factor.image7
-rwxrwxr-x+ 1  19827020 factor.image8
-rwxrwxr-x+ 1  19478579 factor.image9
-rwxrwxr-x+ 1  19266352 factor.image10
-rwxrwxr-x+ 1  19126494 factor.image11
-rwxrwxr-x+ 1  19121309 factor.image12
-rwxrwxr-x+ 1  19141156 factor.image13
-rwxrwxr-x+ 1  19010295 factor.image14
-rwxrwxr-x+ 1  18829608 factor.image15
-rwxrwxr-x+ 1  17938889 factor.image16
-rwxrwxr-x+ 1  17481058 factor.image17
-rwxrwxr-x+ 1  17246991 factor.image18
-rwxrwxr-x+ 1  16968008 factor.image19
-rwxrwxr-x+ 1  16613149 factor.image20
-rwxrwxr-x+ 1  16507944 factor.image21
-rwxrwxr-x+ 1  16470187 factor.image22
```
(number after the name indicates compression level)

**Comment by nomennescio** [comment]
Load times with these images (Windows), use:
```
./factor -i=<image-file> -e=""
```
uncompressed:
```
real    0m0.266s
user    0m0.000s
```
compressed:
```
$ for f in f*image? f*image??; do echo $f;time ./factor -i=$f -e="";done
factor.image1

real    0m0.324s
user    0m0.000s
sys     0m0.015s
factor.image2

real    0m0.312s
user    0m0.000s
sys     0m0.016s
factor.image3

real    0m0.323s
user    0m0.000s
sys     0m0.030s
factor.image4

real    0m0.325s
user    0m0.000s
sys     0m0.015s
factor.image5

real    0m0.325s
user    0m0.000s
sys     0m0.015s
factor.image6

real    0m0.310s
user    0m0.000s
sys     0m0.031s
factor.image7

real    0m0.316s
user    0m0.000s
sys     0m0.015s
factor.image8

real    0m0.310s
user    0m0.000s
sys     0m0.016s
factor.image9

real    0m0.307s
user    0m0.000s
sys     0m0.015s
factor.image10

real    0m0.325s
user    0m0.000s
sys     0m0.015s
factor.image11

real    0m0.298s
user    0m0.015s
sys     0m0.000s
factor.image12

real    0m0.295s
user    0m0.000s
sys     0m0.015s
factor.image13

real    0m0.305s
user    0m0.000s
sys     0m0.030s
factor.image14

real    0m0.296s
user    0m0.000s
sys     0m0.031s
factor.image15

real    0m0.293s
user    0m0.000s
sys     0m0.015s
factor.image16

real    0m0.322s
user    0m0.000s
sys     0m0.016s
factor.image17

real    0m0.310s
user    0m0.000s
sys     0m0.015s
factor.image18

real    0m0.297s
user    0m0.015s
sys     0m0.015s
factor.image19

real    0m0.295s
user    0m0.000s
sys     0m0.015s
factor.image20

real    0m0.339s
user    0m0.000s
sys     0m0.015s
factor.image21

real    0m0.311s
user    0m0.000s
sys     0m0.000s
factor.image22

real    0m0.325s
user    0m0.000s
sys     0m0.015s
```

**Comment by nomennescio** [comment]
Compression time (Windows):
```
Compression Level  1 Compression time: 1.3806134 seconds
Compression Level  2 Compression time: 1.0658926 seconds
Compression Level  3 Compression time: 1.124638 seconds
Compression Level  4 Compression time: 1.1554422 seconds
Compression Level  5 Compression time: 1.7049032 seconds
Compression Level  6 Compression time: 2.1719375 seconds
Compression Level  7 Compression time: 2.3395833 seconds
Compression Level  8 Compression time: 2.802639 seconds
Compression Level  9 Compression time: 2.9200353 seconds
Compression Level 10 Compression time: 3.6229222 seconds
Compression Level 11 Compression time: 5.1016556 seconds
Compression Level 12 Compression time: 7.0103689 seconds
Compression Level 13 Compression time: 6.8351505 seconds
Compression Level 14 Compression time: 8.7019937 seconds
Compression Level 15 Compression time: 11.3290319 seconds
Compression Level 16 Compression time: 24.7936639 seconds
Compression Level 17 Compression time: 28.8313107 seconds
Compression Level 18 Compression time: 44.2611328 seconds
Compression Level 19 Compression time: 59.8817612 seconds
Compression Level 20 Compression time: 62.1815037 seconds
Compression Level 21 Compression time: 67.427667 seconds
Compression Level 22 Compression time: 74.3363846 seconds
```
