### ISSUE TITLE
Canonicalize math.parser with >dec

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2598]
math.parser has pairs
```
>bin bin>
>digit digit>
>hex hex>
>oct oct>
```
but is missing the pair
```
>dec dec>
```
instead we have the much more cumbersome
```
number>string dec>
```

Please introduce `ALIAS: >dec number>string`

**Comment by mrjbq7** [comment]
Fixed in 1945b8f54cd62c7d6dd811586ee21bf43d6794a6.
