### ISSUE TITLE
Show help message when invalid arguments are given

### ISSUE THREAD

**Issue by razetime** [factor/factor#2610]
Some first-time users type `factor --help` on their first usage of factor, so showing a message such as `Invalid arguments. type 'factor -help' for help topics.` would be useful.

**Comment by mrjbq7** [comment]
For 0.99, we already support ``./factor --help``, see this commit 67bc5a92891d51824ef6b4a896ff49ca107ae774.

**Comment by mrjbq7** [comment]
Perhaps we should support more standard —args also.
