### ISSUE TITLE
DOC: alien calling conventions are marked as being only for 32-bit x86 platforms.

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2616]
All `alien` calling conventions are marked as "this symbol only has meaning on 32-bit x86 platforms" in the documentation. I've seen however use of these on 64 bit platforms, so this is wrong.

Smaller issue; `alien` has `mingw` calling convention, which has no documentation, and is missing from lists which mention all calling conventions.

**Comment by mrjbq7** [comment]
I guess it needs updating since we've moved onto 64-bit platforms!

Want to update the docs, or should I?

**Comment by mrjbq7** [comment]
I'm not sure mingw support is actually implemented, but I made the documentation fixes in 6b9dd453879eeaf33540f2f539458c7951fe794a.
