### ISSUE TITLE
Pull request only run tests on MacOS and Linux, not Windows?

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2627]
I noticed that when creating pull request, the tests run are only run on MacOS and Linux, not on Windows. That will prevent detection of any errors in Windows specific code.

**Comment by mrjbq7** [comment]
GitHub windows test runners were flaky for some reason, we should try and reactivate them. 

But!

We run tests on all platforms using our own CI infrastructure.

**Comment by nomennescio** [comment]
Are the results of these tests public? I guess when you're handling Windows specific pull requests you'll check them?

**Comment by mrjbq7** [comment]
Runs on all commits, uploads nightly builds on success of tests.

https://builds.factorcode.org/dashboard

Occasionally some platforms are offline due to various reasons.

**Comment by mrjbq7** [comment]
The other difference is the GitHub action runs only a subset of all the tests, due to time limits of free GitHub test runners. 

Our other builders run extensive tests (load-all test-all).

**Comment by mrjbq7** [comment]
Looks like we are testing on windows now!
