### ISSUE TITLE
On Windows support HOME environment variable

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2630]
On Windows HOMEPATH and HOMEDRIVE might be set automatically, and HOME can be used to override.
Also HOME is used by several ported commandline utilities to find configuration files.
If the user has set it, he clearly prefers it over the other options.

See https://github.com/factor/factor/pull/2626

**Comment by mrjbq7** [comment]
I don't think ``HOME`` is a standard environment variable on Windows?

**Comment by mrjbq7** [comment]
Or is this to allow using Factor somehow in WSL?

**Comment by melted** [comment]
You can run a unixy shell natively on Windows, Git comes with bash for example, other examples are MSYS2 and Cygwin.

**Comment by mrjbq7** [comment]
So, is the desire that in a unix shell on Windows, we use the ``$HOME`` because it is "more correct" than ``$HOMEDRIVE/$HOMEPATH``?

**Comment by nomennescio** [comment]
It indeed is "more correct" than `$HOMEDRIVE/$HOMEPATH` in case the user has installed e.g. Cygwin, MSys, or similar shells, that by default use `HOME`. If the user has not set it, this patch will then just try the regular ones, which I think is the correct way to handle this.

**Comment by mrjbq7** [comment]
Sounds good!

Let's see if it causes any issues.
