### ISSUE TITLE
Disassembly for `TYPED:` only shows partial disassembly

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2640]
Consider this code:
```
TYPED: 1= ( n: fixnum -- 1/0 ) 1 = [ 1 ] [ 0 ] if ;
```

in the listener call:
```
\ 1= disassemble
000001f95f15dfd0: 89052a30d4fe    mov [rip-0x12bcfd6], eax
000001f95f15dfd6: 4883ec28        sub rsp, 0x28
000001f95f15dfda: e801ecdcfe      call 0x1f95df2cbe0 ([ \ integer>fixnum-strict ~array~ 0 ~array~ inline-cache-miss ])
000001f95f15dfdf: 89051b30d4fe    mov [rip-0x12bcfe5], eax
000001f95f15dfe5: 4883c428        add rsp, 0x28
000001f95f15dfe9: 488d1d05000000  lea rbx, [rip+0x5]
000001f95f15dff0: e97b86feff      jmp 0x1f95f146670 (( typed 1= ))
000001f95f15dff5: 0000            add [rax], al
000001f95f15dff7: 0000            add [rax], al
000001f95f15dff9: 0000            add [rax], al
000001f95f15dffb: 0000            add [rax], al
000001f95f15dffd: 0000            add [rax], al
000001f95f15dfff: 00              invalid
```

which only shows part of the definition, the whole `(( typed 1= ))` is missing.

Compare that with
```
: 1= ( n: fixnum -- 1/0 ) 1 = [ 1 ] [ 0 ] if ;
\ 1= disassemble
```
which does show the full code

**Comment by mrjbq7** [comment]
It’s not missing, it’s an inner compiler word that is jumped to. You can
look at that word’s efficient definition by disassembling it.

**Comment by mrjbq7** [comment]
See for example:

[ { fixnum } declare 1= ] disassemble

**Comment by nomennescio** [comment]
Well, it's missing from the disassembly listing, but if we ignore that for a moment, how do I look at it?
If I use
```
[ { fixnum } declare 1= ] disassemble
```
I only get
```
000001f95f15bfa0: 89055a50d4fe    mov [rip-0x12bafa6], eax
000001f95f15bfa6: 89055450d4fe    mov [rip-0x12bafac], eax
000001f95f15bfac: 488d1d05000000  lea rbx, [rip+0x5]
000001f95f15bfb3: e9d8410000      jmp 0x1f95f160190 (1=)
000001f95f15bfb8: 0000            add [rax], al
000001f95f15bfba: 0000            add [rax], al
000001f95f15bfbc: 0000            add [rax], al
000001f95f15bfbe: 0000            add [rax], al 
```

**Comment by nomennescio** [comment]
(And b.t.w., I know we're relying on an external disassembler, but is it possible to not have it show a trail of "unused" code?)

**Comment by nomennescio** [comment]
Is it maybe an option to keep disassembling when code fragments end with a `jmp`?

**Comment by mrjbq7** [comment]
Stepping back, the code disassembles "correctly" as is, because it contains type checking and then a call to an inner typed word.

It should be more easy maybe to disassemble the inner typed word. Perhaps we can change the disassembly output to provide clickable links to the words that are called so you can push those easily and then call ``disassemble`` on them.

**Comment by nomennescio** [comment]
Sounds like an improvement!

**Comment by mrjbq7** [comment]
Hi @nomennescio i made it so that calls are clickable in 1e595fcad03687c72338eaa7c02d70b0ab0cfb15.
