### ISSUE TITLE
Proposal: aliases for terse bitwise operators

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2641]
Maybe it's just me, but I find myself resorting to bit operators quite often, and am longing for a more terse representation, such as in C. However, some symbols are already in use, and it's better to avoid nameclashes.

I therefore propose the following terse bit operators, each start with `.` (pronounce: "bit"), followed by the familiar C operator

```
ALIAS: .& bitand
ALIAS: .| bitor
ALIAS: .^ bitxor
ALIAS: .~ bitnot
```

And the following abbrev for left shift is strangely missing too:
```
: 2* ( n -- 2n ) 1 shift ; inline
```

Unfortunately, shift operators `<<` and `>>` are in use by `syntax`, which is always present, therefore
```
ALIAS: .<< shift
: .>> ( x n -- x/2^n ) neg shift ; inline
```

If you like this, I can prepare a pull request.

**Comment by twopir** [comment]
we'd appreciate all of these, especially since we can never remember the directionality of `shift`

**Comment by razetime** [comment]
since `.` is already under use by many formatting words, qould it make sense to have the words have a `b` postfix? (akin to `/i` and similarly named words)

giving us `&b`, `|b` and so on.

**Comment by nomennescio** [comment]
> since `.` is already under use by many formatting words, qould it make sense to have the words have a `b` postfix? (akin to `/i` and similarly named words)
> 
> giving us `&b`, `|b` and so on.

There is no ambiguity; `.` as postfix means "print", `.` as prefix is only used by `cuda.ptx`, and no ambiguity would result to have it as bit operators, hence "bit"-or, "bit"-and etc.

**Comment by erg** [comment]
In general we don't just add `ALIAS:` because `ALIAS:` is a half-baked feature and having multiple names for things increases complexity and decreases readability.

As for the name, `.` means print in Factor, so `.|` looks like some kind of print/pipe shell thing to my eyes. I like the suggestion on discord for `b|` and `b<<` etc over `.`

Really this is the kind of thing you should put in `.factor-boot-rc` or `.factor-rc` or some kind of `USE: golf` vocab.

**Comment by nomennescio** [comment]
> In general we don't just add `ALIAS:` because `ALIAS:` is a half-baked feature and having multiple names for things increases complexity and decreases readability.

Just curious, why is `ALIAS:` a half-baked feature in your opinion?

In my opinion it's a great thing and should be present in more languages. Abbreviations play an important role even in natural languages. As for readability; the bitwise operators are not only part of the C language, but almost all languages that borrow C's operator syntax, which are actually quite a few. Why introduce a confusing convention with `b` prefixes, that visually "get in the way", whereas `.` is very minimalistic?

**Comment by mrjbq7** [comment]
Aliases is great for backwards compatibility of word renames.

Maintaining a list of “better but not better enough to replace the
original” aliases seems off.

**Comment by razetime** [comment]
terse bitwise word aliases have been added to `syntax.terse` in 8c9bb02.
