### ISSUE TITLE
Bottom status bar should show word's vocabulary root too

### ISSUE THREAD

**Issue by erg** [factor/factor#2645]
<img width="300" alt="Screen Shot 2022-08-08 at 08 28 39" src="https://user-images.githubusercontent.com/27430/183429311-ab36af5c-b09e-450a-8f1f-6c580ddcaa26.png">

I forget if this is in basis/ or extra/, would be nice to see.

**Comment by catb0t** [comment]
do you think this should affect all invocations of `M\ word summary`, or just for the bottom bar?

**Comment by mrjbq7** [comment]
I don't really want to see the vocab root personally

**Comment by catb0t** [comment]
a .factor-rc setting for it? :')

**Comment by erg** [comment]
Closing with a revisit tag.
