### ISSUE TITLE
cmd-t throws out of bounds error

### ISSUE THREAD

**Issue by erg** [factor/factor#2654]
What's this feature supposed to do?
<img width="610" alt="Screen Shot 2022-08-13 at 10 47 02" src="https://user-images.githubusercontent.com/27430/184501263-0efe7a41-277e-40f9-87b8-b90939e55627.png">

Then typing afterwards also errors:
<img width="503" alt="Screen Shot 2022-08-13 at 10 47 17" src="https://user-images.githubusercontent.com/27430/184501268-02ffb2bd-6da3-4c81-b968-32391373c1e0.png">

**Comment by mrjbq7** [comment]
It might only work in the browser?

**Comment by erg** [comment]
```
world get
world-buttons <model> "Active Buttons"
    <active-buttons-popup>
    [ hand-loc get-global point>rect B show-glass ]
    [ request-focus ] bi
```
