### ISSUE TITLE
sum throws for empty ranges

### ISSUE THREAD

**Issue by Kacarott** [factor/factor#2655]
Currently, if a `range` object is defined with "invalid" arguments, such as `start > end, step > 0`, then calling `sum` on the range will result in an error `Sequence index out of bounds`. This is because such ranges have a length of `0`, and yet the `sum` method for range relies on `first` and `last`, which both fail for empty sequences.

Example:
```
! works correctly when first converting the range to an array
1 0 1 <range> >array sum ! 0

! throws when taking the sum directly
1 0 1 <range> sum ! Error: Sequence index out of bounds
```

The `sum` method for `range` objects should first check for empty ranges, and return `0` if that is the case.

**Comment by erg** [comment]
Thanks for the report. Fixed!
