### ISSUE TITLE
Incorrect result for strftime

### ISSUE THREAD

**Issue by jmiven** [factor/factor#2672]
The `%W` and `%U` attributes for `strftime` incorrectly compute their result:

```factor
{ "34" } [ 2022 8 27 <date> "%U" strftime ] unit-test
{ "34" } [ 2022 8 27 <date> "%W" strftime ] unit-test
```
Both tests should pass, but they currently fail.

Although `%W` and `%U` should use respectively Monday and Sunday as first day of the week (according to the docs), it seems that they both start the new week on Saturday:
```factor
! 2022-08-26 is a Friday
{ "34" } [ 2022 8 26 <date> "%U" strftime ] unit-test    ! OK
{ "34" } [ 2022 8 26 <date> "%W" strftime ] unit-test    ! OK
```

I haven't had a chance to look at the code at the moment, but I believe that the recommendations in #2131 would be useful.

This was first reported by @luftluft on Gitter, thanks!

**Comment by mrjbq7** [comment]
Fixed maybe by 1198695223596ff2306a3204a097c00fad1f1cdc.
