### ISSUE TITLE
interval-contains? does not fully handle `full-interval` and `empty-interval`

### ISSUE THREAD

**Issue by erg** [factor/factor#2708]
```factor
! should not throw an error
full-interval 1 2 (a,b] interval-contains?
empty-interval 1 2 (a,b] interval-contains?
```

**Comment by erg** [comment]
Possibly handle this by wrapping with `interval-division-op` or the like which checks boundary/special conditions.

This is `full-interval` but maybe should just go from `[0..inf]`: `10 20 [a,b] 0 0 [a,b] interval/i`

Also: `10 20 [a,b] -0 0 [a,b] interval/i -> full-interval` ?

**Comment by mrjbq7** [comment]
NOT A BUG

interval-contains? takes ``( real interval -- ? )``
