### ISSUE TITLE
misc/vim: stack effect highlighting issue

### ISSUE THREAD

**Issue by razetime** [factor/factor#2715]
From the `sequences` vocabulary:

![image](https://user-images.githubusercontent.com/11015319/206501759-5f12b2be-afa4-4945-97e1-7a4c73a4cf8a.png)

Copypastable code for reproduction:
```
: if-empty ( ..a seq quot1: ( ..a -- ..b ) quot2: ( ..a seq -- ..b ) -- ..b )
    [ dup empty? ] [ [ drop ] prepose ] [ ] tri* if ; inline
```

**Comment by mrjbq7** [comment]
what is the issue? I'm not noticing it

**Comment by razetime** [comment]
the `.b ) -- ..b )` portion seems to be parsed improperly.

**Comment by mrjbq7** [comment]
It's not parsed improperly, it's highlighted as exceeding the line length.

in ``ftplugin/factor.vim``:

```
" Try to limit lines to 64 characters.
setlocal textwidth=64
augroup factorTextWidth
    au!
    au BufEnter <buffer> 2match Error /\%>64v.\+/
    au BufLeave <buffer> 2match none
augroup END
```

**Comment by mrjbq7** [comment]
It's more obvious on my color scheme:

<img width="607" alt="Screenshot 2022-12-08 at 8 27 45 AM" src="https://user-images.githubusercontent.com/24195/206506730-25548376-3544-44af-a0db-db2ed5952571.png">

**Comment by razetime** [comment]
oh, i see. deleting this issue.

**Comment by mrjbq7** [comment]
One could argue that 64 characters is too small a number...

I'd prefer it to not be bigger than 80.

**Comment by razetime** [comment]
I can argue that there should be a global varable for setting the width of a line.

**Comment by mrjbq7** [comment]
Good idea :-)
