### ISSUE TITLE
EBNF Variables not being captured inside { } groups

### ISSUE THREAD

**Issue by Kacarott** [factor/factor#2718]
When using curly bracket syntax for grouping in EBNF expressions, named variables are not properly bound. An example is best to clarify this:

The following snippet uses parenthesis for a group, and *works correctly*:
```
"aa" EBNF[=[ rule = ( "a"+:var ) => [[ var ]] ]=]
! V{ "a" "a" }
```
The same code, but using curly brackets for the group, fails:
```
"aa" EBNF[=[ rule = { "a"+:var } => [[ var ]] ]=]
! Error: No word named “var” found in current vocabulary search path
```

**Comment by mrjbq7** [comment]
Fixed in 6fc95b7080f8e91b4fade30937d206aae6a58f32.

The way ``ebnf-whitespace`` works could be better, but that's a larger change.
