### ISSUE TITLE
raylib: GetRayCollisionModel and friends were removed

### ISSUE THREAD

**Issue by erg** [factor/factor#2741]
https://github.com/raysan5/raylib/blob/master/CHANGELOG#L115

https://github.com/raysan5/raylib/commit/ec8fabceeb20939e9330b4fd84e69bba3506a78b#diff-e89702ba8db97f3defa1eca07222c395c4781ef8fa43802238c3095462876e8cL560

Factor throws an error when running ``"raylib.demo.mesh-picking" run`` with the latest raylib.

Can compile with:
``USE: build-from-source.windows build-raylib-dll``

**Comment by mrjbq7** [comment]
Fixed.
