### ISSUE TITLE
How to print to stderr in a script?

### ISSUE THREAD

**Issue by Bubbler-4** [factor/factor#2750]
I tried some things like

```
error-stream get [ "abc" print ] with-output-stream*
"abc" error-stream get stream-print
```

but `factor a.factor` prints nothing on stderr. Tested on commit ca90f9f10dd2e50e6ab0e42675b9148560b0a94c.

Motivation: The fact that the message

```
Restarts were invoked adding vocabularies to the search path.
To avoid doing this in the future, add the following forms
at the top of the source file:
```

prints to stdout instead of stderr bugged me. I found the relevant portion of the code at https://github.com/factor/factor/blob/391be9810289dc714b2d6d9042ddc889926f1b93/basis/vocabs/prettyprint/prettyprint.factor#L91-L100 but couldn't figure out how to fix it.

**Comment by razetime** [comment]
does adding `error-stream get stream-flush` at the end solve the problem?

**Comment by Bubbler-4** [comment]
That... works. Duh. Surely I saw the related issue but didn't imagine it's the cause here.
