### ISSUE TITLE
`readline-listener` gives "rl_completion_entry_function" Symbol not found

### ISSUE THREAD

**Issue by r-re** [factor/factor#2753]
Just (2023-01-25) cloned factor and tried to run `./factor -run=readline-listener` which results in

```
Symbol not found
name    "rl_completion_entry_function"
message "readline"

(U) [ c-to-factor => ]
    c-to-factor
(U) [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
(O) command-line-startup
(O) readline-listener
(O) set-rl_completion_entry_function
(O) address-of
(O) no-such-symbol
(O) M\ object throw
(U) [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]
```

I'm running Fedora 36 and readline-library is installed. 
` sudo dnf list readline` gives

```
[sudo] password for XXXXXX: 
Last metadata expiration check: 2:32:27 ago on Wed 25 Jan 2023 05:30:47 PM CET.
Installed Packages
readline.i686                                     8.2-2.fc36                                    @updates
readline.x86_64                                   8.2-2.fc36                                    @updates

```
Is there any addditional information i could provide?

Thanks a lot!

**Comment by mrjbq7** [comment]
Do you have readline-dev installed?On Jan 25, 2023, at 11:10 AM, r-re ***@***.***> wrote:﻿
Just (2023-01-25) cloned factor and tried to run ./factor -run=readline-listener which results in
Symbol not found
name    "rl_completion_entry_function"
message "readline"

(U) [ c-to-factor => ]
    c-to-factor
(U) [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
(O) command-line-startup
(O) readline-listener
(O) set-rl_completion_entry_function
(O) address-of
(O) no-such-symbol
(O) M\ object throw
(U) [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]

I'm running Fedora 36 and readline-library is installed.
 sudo dnf list readline gives
[sudo] password for XXXXXX: 
Last metadata expiration check: 2:32:27 ago on Wed 25 Jan 2023 05:30:47 PM CET.
Installed Packages
readline.i686                                     8.2-2.fc36                                    @updates
readline.x86_64                                   8.2-2.fc36                                    @updates


Is there any addditional information i could provide?
Thanks a lot!

**Comment by mrjbq7** [comment]
Specifically, we look for ``libreadline.so`` available in the LD_LIBRARY_PATH somewhere.

**Comment by r-re** [comment]
> Do you have readline-dev installed?

I didn't and installing it fixed the issue. Thanks for the quick reply.

**Comment by mrjbq7** [comment]
Great! It would be nice in a future Factor to not require the ``-dev`` versions of libraries installed...
