### ISSUE TITLE
Browse in new window

### ISSUE THREAD

**Issue by razetime** [factor/factor#2758]
I always have a problem where I follow references across a tree of article, having to search the original article again since I can't find it in my history. I'd like to have a feature where i can open any link in a separate browser window, so it's easier to follow articles with many references.

**Comment by mrjbq7** [comment]
Fixed in https://github.com/factor/factor/commit/855db86de15ea76cdf5e34f1b60518d85fe96372.

Could play with the name of it... it's currently "Browse New".
