### ISSUE TITLE
"Open URL" on `vocab:` links does not resolve the URL

### ISSUE THREAD

**Issue by razetime** [factor/factor#2760]
In the UI listener:
![image](https://user-images.githubusercontent.com/11015319/216749484-bb22cf52-8fa2-4964-be1e-96955df75c99.png)
```
word-link definition-icon
```
I am trying to get the file path of the image, but when it opens in the browser, it does not convert the URL to its full expansion. It tried to open `"vocab:definitions/icons/class-predicate-word.png"` in firefox.

**Comment by mrjbq7** [comment]
Changed so that these are not URL-like... and "Open URL" isn't an option
