### ISSUE TITLE
hang on tab-complete on macos and linux and windows

### ISSUE THREAD

**Issue by erg** [factor/factor#2766]
edit, repro:

```
USE: codebase-analyzer

phi[tab] ... wait til it all loads... [tab][hang]
```
google charts loads instantly on my linux, need one that takes longer. start the tab complete while it's loading, press [tab] after done with the stale menu up

--------------------

tab-complete something and hit tab again at the wrong time and it can lock

beachballing:
![signal-2023-03-03-221427_002](https://user-images.githubusercontent.com/27430/222876419-0af0189b-3cd4-4278-a22a-74c9ebbfebd9.png)

**Comment by mrjbq7** [comment]
How do I reproduce? Never seen this

**Comment by erg** [comment]
Saw this on the .99 release download. Both these screenshots are hard-locked beachballing

I think what you have to do is `USE: google.charts` and then auto-complete something that is in that vocab like `qr>` to `<qr-code>` and tab-select or hit enter just as the last vocabulary is finishing loading.

![signal-2023-08-24-112611_002](https://github.com/factor/factor/assets/27430/31955802-f869-4eda-8532-bda28bd4916a)
![signal-2023-08-24-112826_002](https://github.com/factor/factor/assets/27430/f2e7db25-4df4-499e-9e94-fd0cee5ee39c)

**Comment by mrjbq7** [comment]
Fixed.
