### ISSUE TITLE
right-clicking a large string takes a long time to pop up the menu

### ISSUE THREAD

**Issue by erg** [factor/factor#2769]
```
10,000,000 CHAR: a <string>
```

right click that and notice that it takes awhile when it could just pop right up immediately

<img width="489" alt="Screenshot 2023-03-07 at 6 44 53 PM" src="https://user-images.githubusercontent.com/27430/223589737-7e80aa79-3ab2-4a48-8d0c-f30e9ed52907.png">

**Comment by mrjbq7** [comment]
Fixed in a510b1d3968e6954d746d0fb78c26e8ef0ae092a
