### ISSUE TITLE
crontab parser vocab doesn't seem to support fractions

### ISSUE THREAD

**Issue by erg** [factor/factor#2781]
``https://crontab.guru/#2/29_*_*_*_*``

```factor
"2/27 * * * *" parse-cronentry
T{ cronentry
    { minutes { 2 } }
    { hours T{ range { length 24 } { step 1 } } }
    { days T{ range { from 1 } { length 31 } { step 1 } } }
    { months T{ range { from 1 } { length 12 } { step 1 } } }
    { days-of-week T{ range { length 7 } { step 1 } } }
}
```

I expect this:
```factor
T{ cronentry
    { minutes { 2 29 56 } }
    { hours T{ range { length 24 } { step 1 } } }
    { days T{ range { from 1 } { length 31 } { step 1 } } }
    { months T{ range { from 1 } { length 12 } { step 1 } } }
    { days-of-week T{ range { length 7 } { step 1 } } }
}
```

Also this one:
``https://crontab.guru/#0_2/6_*_*_*``

Should be at hours ``{ 2 8 14 20 }``
``"0 2/6 * * *" parse-cronentry 50 next-times``

And this:
``https://crontab.guru/#2/4_2/6_3/3_1/2_2/3``
``2/4 2/6 3/3 1/2 2/3``
“At every 4th minute from 2 through 59 past every 6th hour from 2 through 23 on every 3rd day-of-month from 3 through 31 and on every 3rd day-of-week from Tuesday through Sunday in every 2nd month from January through December.”

**Comment by mrjbq7** [comment]
Fixed in d362b569abfc751757fb7b6e04e1691251f63b36
