### ISSUE TITLE
Both `deploy` and `deploy-tool` fail to build application using `ui` vocab

### ISSUE THREAD

**Issue by Capital-EX** [factor/factor#2784]
Attempting to run the factor deploy tool off the master branch results in the following error if a vocab uses the UI framework.

https://paste.factorcode.org/paste?id=4557

Not to sure what's going wrong here?

**Comment by mrjbq7** [comment]
Have you tried delete-staging-images first?On Apr 25, 2023, at 9:36 PM, Capital-EX ***@***.***> wrote:﻿
Attempting to run the factor deploy tool off the master branch results in the following error if a vocab uses the UI framework.
https://paste.factorcode.org/paste?id=4557
Not to sure what's going wrong here?

**Comment by Capital-EX** [comment]
Yeah, I forget to run that. Would it be worth adding `./factor -e="USE: tools.deploy.backend delete-staging-images"` to `build.sh`? I feel like this trips someone up like twice a month...

**Comment by mrjbq7** [comment]
We need to version them. Maybe there is a quick fix we can do with git refOn Apr 25, 2023, at 9:47 PM, Capital-EX ***@***.***> wrote:﻿
Yeah, I forget to run that. Would it be worth adding ./factor -e="USE: tools.deploy.backend delete-staging-images" to build.sh? I feel like this trips someone up like twice a month...

**Comment by mrjbq7** [comment]
I think I fixed this issue in 76d3b8b6be40c46b68e0d2f3ee32595b1e405a11
