### ISSUE TITLE
Weird EOL choices in the repo

### ISSUE THREAD

**Issue by alex-ilin** [factor/factor#2793]
Checking out the contents of the commit ed9674089916064635c67afc31e32aacbf14be6b in `factor-windows-x86-64-2023-06-11-10-26.zip`, I see that the following files have been converted from using LF for EOL to CRLF, which makes no sense to me:
- .dir-locals.el,
- .gitattributes,
- shell.nix.

For *.md files I guess it's fine either way, although I would prefer not having such conversions in Git history, as they make confusing full-file conflicts on merge, not to mention completely avoidable ones. I'm guessing someone needs to watch out for their text editor and/or enable whitespace diff display in their Git client. Maybe we should add some more entries to the `.gitattributes` file.

**Comment by mrjbq7** [comment]
Added some in b535d547fe1e5ec456f7b2a671c7501ab64ea7d3
