### ISSUE TITLE
linux/windows openssl error on google charts api

### ISSUE THREAD

**Issue by erg** [factor/factor#2806]
```factor
USE: google.charts
"omg" <qr-code> chart.
```

**Windows error:**
error:0A000126:SSL routines::unexpected eof while reading

`ssl_read` returns 0 and `SSL_get_error` returns 1 which is `SSL_ERROR_SSL` which means there's a "real error" even though it seems we got the image already.

**Linux error:**
error:0A000197:SSL routines::shutdown while in init

it's failing in `shutdown`

macos works.

repro:
``"https://chart.googleapis.com/chart?cht=qr&chs=320x240&chd=116&chd=58&chl=omg" http-get``

**Comment by erg** [comment]
```factor
: (shutdown) ( ssl-handle -- )
    dup dup handle>> SSL_shutdown check-ssl-error
    [ dupd wait-for-fd (shutdown) ] [ drop ] if* ;
```

`check-ssl-error` is wrong here. we need to do a `SSL_read` in this case

https://www.openssl.org/docs/man3.1/man3/SSL_shutdown.html

**Comment by erg** [comment]
.98 has the same bug (after s/SSL_get_peer_certificate/SSL_get1_peer_certificate/g)

```
IN: scratchpad "https://chart.googleapis.com/chart?cht=qr&chs=320x240&chd=116&chd=58&chl=omg" http-get
error:0A000197:SSL routines::shutdown while in init
```

**Comment by erg** [comment]
SSL_OP_IGNORE_UNEXPECTED_EOF might help since if you don't call SSL_shutdown you get 

``error:0A000126:SSL routines::unexpected eof while reading``

https://github.com/openssl/openssl/issues/20365 is also basically our issue

**Comment by mrjbq7** [comment]
We have to call ERR_clear_error before SSL_read or SSL_write?https://stackoverflow.com/questions/18179128/how-to-manage-the-error-queue-in-openssl-ssl-get-error-and-err-get-errorOn Aug 11, 2023, at 10:08 PM, Doug Coleman ***@***.***> wrote:﻿
SSL_OP_IGNORE_UNEXPECTED_EOF might help since if you don't call SSL_shutdown you get
error:0A000126:SSL routines::unexpected eof while reading
openssl/openssl#20365 is also basically our issue

**Comment by mrjbq7** [comment]
See also:https://github.com/uNetworking/uSockets/issues/43On Aug 11, 2023, at 10:08 PM, Doug Coleman ***@***.***> wrote:﻿
SSL_OP_IGNORE_UNEXPECTED_EOF might help since if you don't call SSL_shutdown you get
error:0A000126:SSL routines::unexpected eof while reading
openssl/openssl#20365 is also basically our issue

**Comment by erg** [comment]
An SSL truncation attack is a type of attack where an adversary prematurely terminates an SSL/TLS connection. The main goal of the attacker is to make the client believe that the connection has ended normally, even if the server intended to send more data. The attacker will typically interrupt the connection by forging a TCP FIN packet or a TLS close_notify alert. If the client isn't correctly verifying the end of the SSL/TLS session, it might consider the data transmission complete and process the partial information.
Mitigation:

    Properly Handle close_notify Alert: The formal way to close a TLS connection is for one side to send the close_notify alert. Both sides of a connection should expect to receive a close_notify alert before the connection truly ends. Applications should be cautious if the connection drops without receiving this alert and should consider any received data as potentially incomplete or tampered.

    Strong SSL/TLS Configuration: Ensure that the server and clients use strong ciphers and the latest version of TLS (as of my last update, TLS 1.3). Avoid deprecated versions of SSL/TLS, like SSLv2, SSLv3, and early versions of TLS.

    End-to-end Authentication: Make sure both the client and server are properly authenticating each other, typically through certificates. Using mutual TLS (mTLS) where both server and client present certificates can be an effective strategy.

    Application-layer Confirmation: Applications can include an integrity check at the application layer, such as a hash or checksum of the transmitted data, or a final confirmation message that verifies the completeness of a transmitted dataset.

    Monitor and Alert: Use intrusion detection and intrusion prevention systems (IDS/IPS) to monitor for anomalies in the network traffic. Forged FIN packets and other malicious activities can sometimes be detected and stopped by these systems.

    Regularly Update Libraries and Software: Ensure that SSL/TLS libraries (like OpenSSL) and the applications using them are regularly updated. Vulnerabilities and bugs are frequently discovered, and software updates will often contain crucial patches.

    Educate Developers and Administrators: Ensure that developers and system administrators are aware of the risks of SSL truncation attacks and are knowledgeable about implementing correct error-handling and connection-closing routines.

    SSL_OP_IGNORE_UNEXPECTED_EOF Option: In contexts where OpenSSL is used, ensure that the SSL_OP_IGNORE_UNEXPECTED_EOF option isn't set, as it makes the library tolerate truncated connections.

By ensuring secure configurations, proper SSL/TLS termination checks, and by monitoring network traffic, you can effectively mitigate the risk of SSL truncation attacks.

**Comment by erg** [comment]
python talking about eof and uni/bi/hard shutdowns

https://bugs.python.org/issue27815
