### ISSUE TITLE
Add vocabulary with renamed 0.98 words for backwards compatibility

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2820]
Now with the 0.99 release pending, I propose to add an optional vocabulary to support backwards compatibility with 0.98 names. Some codebases still need to support both 0.98 and 0.99 releases, and might benefit from a shared vocabulary with aliases of 0.98 names.

This also serves as a nice overview of all name changes.

**Comment by alex-ilin** [comment]
For me the `fixups` vocab is enough, it helps me update the code as necessary.

**Comment by mrjbq7** [comment]
Probably not worth the effort...
