### ISSUE TITLE
Provide merge boot image

### ISSUE THREAD

**Issue by gifti258** [factor/factor#2822]
Pull requests currently fail because the checks can't retrieve a boot image for the merge branch (?). We should either provide that again (?) or change the merge branch name (??).

**Comment by mrjbq7** [comment]
For now, I symlinked them to ``master`` boot images, so will fail maybe if a PR changes core words but otherwise should work.

**Comment by mrjbq7** [comment]
https://downloads.factorcode.org/images/merge/

**Comment by gifti258** [comment]
I tried rerunning checks on a PR, the windows one wants to download a boot image from /HEAD/.

**Comment by mrjbq7** [comment]
ok, i symlinked ``images/HEAD/`` for now, we can figure out why its different later
