### ISSUE TITLE
changed code signature in macOS 0.99?

### ISSUE THREAD

**Issue by suschizu** [factor/factor#2831]
I've received the information that the code signature has changed in the latest update - can you please confirm it @mrjbq7?

EXPECTED 'Douglas Coleman (47GYDV57R6)' but FOUND 'John Benediktsson (4Q7HZ57BMF)'

thanks!

**Comment by mrjbq7** [comment]
Hi, yes the old certificate was maintained by @erg and expired, and the new one is my @mrjbq7 and maintained.

**Comment by mrjbq7** [comment]
Thank you for checking.

**Comment by erg** [comment]
Confirming!

**Comment by suschizu** [comment]
@mrjbq7 - I'm doing the maintenance for an app called MacUpdater - it shows new releases for macOS apps that are installed on your mac and we daily run self-made security checks before we publish the new information - a changed code signature could indicate that it's not an official release from the developer - so better to ask before showing something fraudulent :) checking the code signature is just : 
`codesign -dv --verbose=4 /Path/To/Application.app`
