### ISSUE TITLE
[Feature] Anonymous Predicates

### ISSUE THREAD

**Issue by Capital-EX** [factor/factor#2849]
Factor already features anonymous intersections and unions. Additionally, these can be used as part of generic definitions:

```factor
GENERIC: foobar ( x -- x )

M: union{ a b } foobar ... ;
M: intersection{ a b } foobar ... ;
```

I've recently demonstrated using `PREDICATE:` to remove the need for potentially nested if statements. This example is using the fibonacci function:

```factor
PREDICATE: '0 < integer 0 = ;
PREDICATE: '1 < integer 1 = ;

GENERIC: fib ( n -- fib )

M:      '0 fib drop 0 ;
M:      '1 fib drop 1 ;

M: integer fib [ 1 - fib  ] [ 2 - fib ] bi + ;
```

So my idea is implementing anonymous predicates which would allow for a sort of pattern matching on methods:

```factor
GENERIC: fib ( n -- fib )

M: predicate{ integer [ 0 = ] } fib drop 0 ;
M: predicate{ integer [ 1 = ] } fib drop 1 ;

M: integer fib [ 1 - fib ] [ 2 - fib ] bi + ;
```

**Comment by mrjbq7** [comment]
This was already merged.
