### ISSUE TITLE
Rename `supremum` and `infimum`

### ISSUE THREAD

**Issue by Kacarott** [factor/factor#2860]
`supremum` and `infimum` could be named to the more natural `max` and `min`, while the existing `max` and `min` could be named `2max` and `2min`. Potentially similar words such as `3min` and a generalised `n-min` could also be added.

**Comment by razetime** [comment]
maybe maximum and minimum could be aliases for supremum and infimum, or the other way around (a la Haskell). It seems unwise to make decisions around golf.

**Comment by Kacarott** [comment]
I am not sure the `golf` tag was added, as the reasons for this are not for golf. The reasons are:
1) `supremum` and `infimum` are slightly inaccurate, as both terms actually refer to a broader concept
2) they are very unintuitive. Myself, and most of the people I have introduced factor to have had to actually ask someone "Does factor not have a `min/max` word for sequences?" before being pointed to them.
3) `min` and `max` I think are also slightly unintuitive in that compare only two values, *especially* in the apparent absence of a word that operates on sequences. I think that `2min`/`2max` are much more explicit

`minimum` and `maximum` would be much better than the current names, but it still prefer my idea as there is less ambiguity. Admittedly my idea is much more of a breaking change, so `minimum` and `maximum` might be a good compromise.

**Comment by gifti258** [comment]
I do not love the names `2min` and `2max`. To me they imply that they work on two sequences. Having `minimum`/`maximum` while keeping `min`/`max` could work.

**Comment by erg** [comment]
`max` and `maximum` is growing on me, if for no other reason than `maximum` looks longer so it can operate on long sequences while `max` is short and operates on two objects.

Want to do this?

**Comment by Capital-EX** [comment]
If we are trying to find a more "common usage" wording `biggest` and `smallest` also exist

**Comment by tgunr** [comment]
also, larger-of, smaller-of

**Comment by Kacarott** [comment]
I like `minimum` and `maximum` the best still, they feel the most intuitive to me.

**Comment by nomennescio** [comment]
I'm not a big fan of renaming a full codebase, but having `maximum` and `minimum` as aliases seems fine to me.
If we introduce a true `supremum` and `infimum` in the future, we then separate into different definitions instead of aliases.

**Comment by mrjbq7** [comment]
I like ``min`` and ``min-of``.
