### ISSUE TITLE
Parsing JSON value "-0"

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2904]
This should work:

```factor
{ -0.0 } [ "-0" json> ] unit-test
```

Should match Javascript ``JSON.parse("-0")``

Noticed this Zig issue https://github.com/ziglang/zig/pull/17729

**Comment by razetime** [comment]
i just added a special case for `-0` in the PR. Is that an alright way to handle it?

**Comment by mrjbq7** [comment]
I think that’s a perfectly fine way to do it, since we probably don’t want to change our math.parser for this case. Thank you!On Oct 28, 2023, at 3:25 AM, Raghu R ***@***.***> wrote:﻿
i just added a special case for -0 in the PR. Is that an alright way to handle it?

**Comment by razetime** [comment]
complete in [e79f02d](https://github.com/factor/factor/commit/e79f02d161fd939774e4ae5f681393b291f10535).
