### ISSUE TITLE
Adding Code_of_Conduct to repo

### ISSUE THREAD

**Issue by mohitd404** [factor/factor#2907]
Why Code-Of-Conduct:- We propose adding a comprehensive Code of Conduct to our repository to ensure 
a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a 
wider range of perspectives.

**Issue type**

- [✅] Docs

@mrjbq7 If you were planning this issue kindly assign it to me! I would love to work on it ! Thank you !

**Comment by erg** [comment]
Please see the discussion on https://github.com/factor/factor/pull/2908

**Comment by mohitd404** [comment]
@erg I was not making this contribution for any hacktoberfest, as I'm already done with it 4 weeks ago !! I was casually looking repos and found that this one doesn't had COC !! I hardly makes such contributions ! I'm sorry that you found this Invalid !! appreciate for your review !!
