### ISSUE TITLE
[macOS] `factor` 0.99 build issues

### ISSUE THREAD

**Issue by barracuda156** [factor/factor#2928]
```
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor'
:info:build make: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor'
:debug:build Executing proc-post-org.macports.build-build-0
:debug:build system: cd /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor && ./factor -i=./boot.unix-arm.64.image
:info:build fatal_error: Cannot (un)protect low guard page: 0x1051a0000
:info:build sh: line 1: 95661 Abort trap: 6           ./factor -i=./boot.unix-arm.64.image
:info:build Command failed: cd /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor && ./factor -i=./boot.unix-arm.64.image
:info:build Exit code: 134
```
[factor_fail_arm64.log](https://github.com/factor/factor/files/13769062/factor_fail_arm64.log)

**Comment by mrjbq7** [comment]
We don’t support arm 64 native yet. You can build with Rosetta. On Dec 25, 2023, at 10:04 PM, Sergey Fedorov ***@***.***> wrote:﻿
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor'
:info:build make: Leaving directory `/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor'
:debug:build Executing proc-post-org.macports.build-build-0
:debug:build system: cd /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor && ./factor -i=./boot.unix-arm.64.image
:info:build fatal_error: Cannot (un)protect low guard page: 0x1051a0000
:info:build sh: line 1: 95661 Abort trap: 6           ./factor -i=./boot.unix-arm.64.image
:info:build Command failed: cd /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_lang_factor/factor/work/factor && ./factor -i=./boot.unix-arm.64.image
:info:build Exit code: 134

factor_fail_arm64.log

**Comment by barracuda156** [comment]
@mrjbq7 How is the target supposed to work?
https://github.com/factor/factor/blob/bea64da2eb5378ffb7e6df79164cfaeaf041f788/GNUmakefile#L207-L208
It fails with `boot.unix-x86.64.image` likewise.

**Comment by mrjbq7** [comment]
That target is only for development of the (currently not working) ARM64 support.  You can bootstrap using Rosetta:$ arch -x86_64 ./build.sh updateOn Dec 25, 2023, at 11:08 PM, Sergey Fedorov ***@***.***> wrote:﻿
@mrjbq7 How is the target supposed to work?
https://github.com/factor/factor/blob/bea64da2eb5378ffb7e6df79164cfaeaf041f788/GNUmakefile#L207-L208
It fails with boot.unix-x86.64.image likewise.

**Comment by barracuda156** [comment]
@mrjbq7 It seems to fail on x86 either: https://github.com/factor/factor/issues/2929

**Comment by mrjbq7** [comment]
Are you working on the macports update?

Let me look at the errors in that log file.

**Comment by barracuda156** [comment]
@mrjbq7 Yes, since it is both outdated and broken currently: https://ports.macports.org/port/factor/details

I would also like to restore PowerPC, but that is another issue, and to begin with we need x86 to work anyway.

**Comment by mrjbq7** [comment]
Works fine for me:

```
$ cd tmp
$ wget https://downloads.factorcode.org/releases/0.99/factor-src-0.99.zip
$ unzip factor-src-0.99.zip
$ cd factor
$ arch -x86_64 make
$ ./factor -i=boot.unix-x86.64.image # or arch -x86_64 ./build.sh bootstrap
```

How do I see what the factor formula is doing on macports?

The error in the macports build is a failure in ``M\ macosx default-cache-directory``, specifically calling NSSearchPathForDirectoriesInDomains (https://developer.apple.com/documentation/foundation/1414224-nssearchpathfordirectoriesindoma), and we are assuming the directory that it returns for caching already exists.

Is there a way to make sure a user cache directory exists on the macports github builder?

We could fix this for 0.100, but for 0.99, maybe the formula needs to create that directory.  It is typically ``$HOME/Library/Caches/org.factorcode.Factor``...

**Comment by mrjbq7** [comment]
As an aside, is there a reason you don't use the binary distribution in macports? is there a preference to building from source?

And we haven't supported ppc for awhile now, unfortunately, we don't have hardware to dev on at the moment.

**Comment by mrjbq7** [comment]
I'm leaving in a couple hours for a few days trip, and won't be able to help until end of the week, sorry.

**Comment by barracuda156** [comment]
@mrjbq7 Sure, we can wait until then, thank you very much for responding.

> As an aside, is there a reason you don't use the binary distribution in macports? is there a preference to building from source?

Yes, it is a general policy to build everything from source, as long as that is feasible. Obviously, we still need bootstrap binaries.

> And we haven't supported ppc for awhile now, unfortunately, we don't have hardware to dev on at the moment.

I can handle testing, but I may need a bit of assistance with the new assembler usage (may work in fact, but may be specific to ELF in some spots) – not in `cpu-ppc`, but in basis/bootstrap and alike, where it is Factor code already, but relating to assembler.

One specific problem I got is that there is no dispatch_signal_handler for PowerPC, since it was not used on 0.93 (last one to have support for ppc), and `cpu-ppc` uses assembler, unlike other archs, it is unclear how to even add this.

P. S. I will consolidate all issues here or should I make a separate one for PowerPC?

**Comment by barracuda156** [comment]
P. S. 0.93 appears perfectly functional on macOS PowerPC; a glitch I might have mentioned earlier was caused by external issues (conflict between system and Macports X11 headers/libs).

**Comment by mrjbq7** [comment]
I hope to someday support PowerPC again, but i have no test hardware.  Closing for now.
