### ISSUE TITLE
peg.ebnf: stack effect errors in semantic actions not cleared

### ISSUE THREAD

**Issue by olus2000** [factor/factor#2931]
When a vocab is loaded that has an `EBNF:` definition that includes a semantic action with effect different than `( ast -- ? )` an error in listener is raised, but it is not cleared when the vocab is fixed and reloaded.

## How to reproduce
In the UI listener load a vocabulary containing this source code:
```factor
USING: kernel multiline peg peg.ebnf ;
IN: bug-report
EBNF: test [=[
test = . ?[ CHAR: a ]?
]=]
```
Then change the vocabulary to contain this source code instead and reload:
```factor
USING: kernel multiline peg peg.ebnf ;
IN: bug-report
EBNF: test [=[
test = . ?[ CHAR: a = ]?
]=]
```

## Expected behavior
Loading the first sample should report an error that can be inspected by pressing F3. The list of errors should contain a stack effect error for a quotation given to `when`.

Loading the second sample should clear the error list.

## Actual behavior
Loading the firs sample works as expected.

Loading the second sample does not clear the error list.

## Additional notes
Reloading source with the same error does not add new errors to the list, but reloading it with a different incorrect stack effect does add new errors to the list.

**Comment by mrjbq7** [comment]
Fixed in 306a8883ea77fe3c7325db218d99728f9cb4d000.
