### ISSUE TITLE
Add `system` to standard word search list such that calling `exit`/`(exit)` does not first issue an error

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2937]
Exiting the (UI) listener is a basic operation. Add `system` to the standard word search order, so the user can exit without getting annoying error messages.

**Comment by mrjbq7** [comment]
Ctrl-D or closing window isn’t a solution?On Jan 25, 2024, at 9:23 AM, nomennescio ***@***.***> wrote:﻿
Exiting the (UI) listener is a basic operation. Add system to the standard word search order, so the user can exit without getting annoying error messages.

**Comment by mrjbq7** [comment]
Does the user think ``exit`` would close the whole Factor process, or just the UI Listener window that its being typed into?

**Comment by nomennescio** [comment]
> Does the user think `exit` would close the whole Factor process, or just the UI Listener window that its being typed into?

I don't know of course, but having used quite some interpreters, typing a keyword to close everything is pretty standard.

**Comment by nomennescio** [comment]
Searching through the vocabs, the only other vocab that defines `exit` is `cuda.ptx`, where it is a tuple.

Looking at the command-line listener, `return` is required to "exit" it (https://docs.factorcode.org/content/article-listener.html), which is a bit uncommon, but then again, it's not a common way to run Factor, so that is less of a concern.

Maybe the more elegant solution is to introduce an alias in the UI Listener for `com-exit`; it won't affect existing code, doesn't introduce all `system` words in the global vocab search space, and is limited to the UI Listener only, and only clashes if the user explicitly loads `system` in scratchpad and defines words with that.

I'll make a pull request out of that, and then you can comment on that, and if you agree accept it, or reject it. Then I'll close this issue.

**Comment by nomennescio** [comment]
Hmm, just adding the alias to `ui,tools.factor` still does not make it immediately available to the standard search path. OK, I'll think of something else.

**Comment by mrjbq7** [comment]
What’s wrong with Ctrl-D for EOF?Works in command line and UI listeners?On May 9, 2024, at 1:02 AM, nomennescio ***@***.***> wrote:﻿
Searching through the vocabs, the only other vocab that defines exit is cuda.ptx, where it is a tuple.
Looking at the command-line listener, return is required to "exit" it (https://docs.factorcode.org/content/article-listener.html), which is a bit uncommon, but then again, it's not a common way to run Factor, so that is less of a concern.
Maybe the more elegant solution is to introduce an alias in the UI Listener for com-exit; it won't affect existing code, doesn't introduce all system words in the global vocab search space, and is limited to the UI Listener only, and only clashes if the user explicitly loads system in scratchpad and defines words with that.
I'll make a pull request out of that, and then you can comment on that, and if you agree accept it, or reject it. Then I'll close this issue.

**Comment by nomennescio** [comment]
> What’s wrong with Ctrl-D for EOF?Works in command line and UI listeners?

As noted `CTRL-D` does *not* work on Windows to exit Factor (see above)
And I want a command to help people who expect a command to exit Factor, not a key-combo

**Comment by mrjbq7** [comment]
But they likely don't expect it to *exit* Factor, they likely expect it to exit one of the listener windows,  no?

**Comment by mrjbq7** [comment]
How do you type an EOF on windows?

**Comment by nomennescio** [comment]
> How do you type an EOF on windows?

`CTRL-Z` if you're on `cmd.com`, but that's never used to close a console.

**Comment by nomennescio** [comment]
> But they likely don't expect it to _exit_ Factor, they likely expect it to exit one of the listener windows, no?

As I said, I find that hard to predict; typically people start an interpreter from the commandline (`factor.exe`) with a keyboard, then also expect to exit using a keyboard command. People who start it by double-clicking on icon with the mouse, expect it to close with the mouse. Both scenarios happen. People using universally an EOF char to close things is not very common outside Unix.

**Comment by nomennescio** [comment]
With the solution for #3004 , `CTRL-Q` closes the Factor Windows *and* properly handles calls to be handled at window closure (`ungraft*`). Given that `exit` bypasses all Windows handlers, for the UI I don't consider `exit` the preferred way to exit the UI anymore. 

Therefore the word to properly end the listener is `com-exit`

Maybe we can have an easier to remember `ALIAS:` for that?

**Comment by nomennescio** [comment]
I propose `quit` for that, it's used only in a few other vocabs to quit a special application, so that will hardly lead to troublesome clashes.

**Comment by nomennescio** [comment]
a50f45c92da

**Comment by mrjbq7** [comment]
I don’t like this word, but I’m not going to immediately revert it. You have at least two keyboard shortcuts and can close the window. I don’t think this alias is a good idea. Let’s let it bake for a bit before I decide.  On May 29, 2024, at 5:47 AM, nomennescio ***@***.***> wrote:﻿
a50f45c

**Comment by mrjbq7** [comment]
You can also add this to your install using factor-rc or factor-boot-rcOn May 29, 2024, at 5:47 AM, nomennescio ***@***.***> wrote:﻿
a50f45c

**Comment by mrjbq7** [comment]
I’d be more interested in making Ctrl-D work across all platforms On May 29, 2024, at 5:47 AM, nomennescio ***@***.***> wrote:﻿
a50f45c

**Comment by mrjbq7** [comment]
Reverting, ``ui.tools`` isn't even in the default search path.

if you need this you can make an alias in your factor-rc / factor-boot-rc.

**Comment by mrjbq7** [comment]
Ctrl-D works on windows
