### ISSUE TITLE
Implement Dragonbox algorithm

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2940]
It would be cool to get the Dragonbox algorithm (https://github.com/jk-jeon/dragonbox) implemented in pure Factor for float formatting, instead of relying on the fmtlib (https://github.com/fmtlib/fmt).

**Comment by mrjbq7** [comment]
Perhaps look at simplified version of Dragonbox here: https://github.com/abolz/Drachennest

**Comment by jonenst** [comment]
#2083 #1555 previous alternative work

**Comment by mrjbq7** [comment]
Hi @jonenst that's great, I think #1555 is resolved now with use of fmtlib but ideally we would do more in pure factor at some point!

**Comment by mrjbq7** [comment]
Wow, @gifti258 contributed in #2943 amazing!

It's much faster too!

Factor 0.99:

```factor
IN: scratchpad gc [ parse-float-benchmark ] time
Running time: 3.181906583 seconds
```

Factor 0.100 git:

```factor
IN: scratchpad gc [ parse-float-benchmark ] time
Running time: 0.378132792 seconds
```
