### ISSUE TITLE
`help` output is unreadable in 256color mode

### ISSUE THREAD

**Issue by ToxicFrog** [factor/factor#2951]
Compare the output of `help` and `[ help ] with-256color`, or just look at the screenshot below:

![image](https://github.com/factor/factor/assets/90456/7e1a29b8-036b-477b-bf78-640b84f4d601)

I suspect that it has a bunch of styles baked in that assume the dark-on-light colour scheme baked into the GUI REPL, with tragic results in the tty. `.` and other prettyprinters have similar issues, but not as pronounced.

**Comment by mrjbq7** [comment]
try ``dark-mode``

**Comment by ToxicFrog** [comment]
Much more readable, thank you.

**Comment by mrjbq7** [comment]
Even though that "fixes" your bug, there's pending work to maybe use colors automatically based on $TERM detection, and maybe always use dark-mode since terminals typically are that way by default... anyway, glad you have a fix!
