### ISSUE TITLE
How could I implement some simple multi-threading?

### ISSUE THREAD

**Issue by amherag** [factor/factor#2964]
Right now I'm using Factor's cooperative multitasking. It would be great to put my other CPU cores to use, though. What are my options?

My first thought is to run multiple instances of Factor, but I want to try to avoid doing this, as my project uses 3-4 Gb RAM, as I need to allocate some big machine learning models.

How hard would it be to implement multi-threading? Maybe a bare-bones vocabulary, tailored down for my project.

**Comment by spacefrogg** [comment]
Preemptive multi-threading basically needs support from the Factor VM. The hard part is memory management, esp. garbage collection. You are out of luck, on this front, I'd say. You could still put multitasking to good use. If you are curious, zero-copy IPC is possible and quite performant when using Unix domain sockets well. You would want look into sending file descriptors to other processes via sockets. So, if I were you, I would look into this. It should be very possible to make a nice little IPC vocab based on sockets.

**Comment by amherag** [comment]
Zero-copy IPC sounds like an excellent approach. Thank you, @spacefrogg
