### ISSUE TITLE
command-line.parser matches options too eagerly 

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#3000]
The command-line parser matches options too eagerly.
```
  T{ option { name "--force" } ... }
  T{ option { name "-c" } ... }
```
gives a runtime error:
```
ERROR: The option ``c'' matches more than one (c, force)
```
I had the same experience with an option named `-l` which was matched with `--help`.

I would expect a lower limit of a couple of characters for a match to occur.

**Comment by mrjbq7** [comment]
I changed it right now to try and exact match first before trying a fuzzy one.

There are a lot of things to improve on what's there, perhaps add to #2994.
