### ISSUE TITLE
Listener startup fails ungracefully if $DISPLAY is set but empty

### ISSUE THREAD

**Issue by ToxicFrog** [factor/factor#3003]
The intended behaviour of `command-line-startup` appears to be:
- if the user specified something to run, run it;
- otherwise, if an X terminal (or your local equivalent) is available, start the graphical listener;
- otherwise, start the tty listener.

However, its assessment of "an X terminal is available" appears to be optimistic. In particular, if `$DISPLAY` is set to the empty string (which is functionally equivalent to having it unset), it tries to use it anyways, and you need to unset it completely to get the tty listener:
```
$ DISPLAY= ./factor
Unable to initialize GTK
[stack trace elided]

$ (unset DISPLAY; ./factor)
Factor 0.100 x86.64 (2268, heads/master-8a94e1048b, May 24 2024 13:48:23)
[GCC 11.4.0] on linux
IN: scratchpad
```

This is technically in accord with the documentation, which says "if DISPLAY is set" rather than "if DISPLAY is set to a nonempty value", but it's surprising given that most programs treat unset envars, and envars set to `""`, as completely equivalent.

It also crashes if libgtk2 or libgtkglext are unavailable, but that is less surprising, even if falling back to the tty listener there would be a nice-to-have.

**Comment by mrjbq7** [comment]
Fixed in 14f7d918536bb62bb1cfb1087b585340b600b5f0.
