### ISSUE TITLE
Call window close at `com-exit`

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#3004]
When `CTRL-Q` or similar is pressed in the UI, `com-exit` is called, which currently has:
```
: com-exit ( -- ) 0 exit ;
```

However, this fails to close Window, which would prevent some code to dispose of resources to be triggered.

@mrjbq7  suggested:
```
: com-exit ( -- ) worlds get values [ [ close-window ] ignore-errors ] each 0 exit ; 
```

**Comment by nomennescio** [comment]
It seems `ungraft*` is still not being called on `ui.tools.listener` even with https://github.com/factor/factor/commit/378fb18f164dd2cf16d8982baada0acc54beee36 and https://github.com/factor/factor/commit/7aa0e505c283ea6c6d8144cea7ac3c2eefd4ec33

**Comment by mrjbq7** [comment]
Interesting, it appears ``M\ object close-window`` calls ``ungraft`` but the UI backends don't...

**Comment by mrjbq7** [comment]
So perhaps we should change it to have an inner backend ``close-window*`` and an outer ``close-window`` that calls ``ungraft`` before ``close-window*``...

**Comment by nomennescio** [comment]
It's nearly impossible for me to track this down, because using the Walker will cause a segmentation fault at certain points.
How do you debug this?

**Comment by mrjbq7** [comment]
Paper debugging by logic

or [ . ] with-global style stdout print debugging

You can’t currently debug the UI with the UI

**Comment by nomennescio** [comment]
Ye olde printf debugging

**Comment by nomennescio** [comment]
Paper debugging is how I usually do it, however in this case the whole UI stack is relatively new to me, so will take significant time to work through. Have to pass on that for now.

**Comment by mrjbq7** [comment]
It would be cool to have it drop into the command line debugger but I *think* there are some issues due to using the main thread to pump the UI, but would make a nice contribution. On May 27, 2024, at 10:37 AM, nomennescio ***@***.***> wrote:﻿
Ye olde printf debugging

**Comment by mrjbq7** [comment]
You know, I think it's sort of "working".

``ungraft`` is being called, but it defers the ``ungraft*`` until later (``ungraft-later``), and we don't wait for that later before calling exit.

**Comment by nomennescio** [comment]
I couldn't check what the ungraft did, but then we would need to wait for it run.

**Comment by mrjbq7** [comment]
I mean we could also enqueue a close-later, but alternatively, we could add an ``ungraft-now``...

**Comment by nomennescio** [comment]
I think it all has to do with the whole native handling of windows, where you need to post messages and do stuff async, that we need to do things `-later`, isn't it? But then again, the whole Factor windowing stuff is new to me.

**Comment by mrjbq7** [comment]
the ``-later`` is largely to allow for "change a bunch of UI stuff" in one iteration of the UI thread message loop, then apply all the changes, then loop again.  There are cases where do-it-now is useful.

**Comment by nomennescio** [comment]
so why not just:
```
: ungraft-now ( gadget -- )
    dup [ ungraft-now ] each-child ungraft* ;
```
plus flushing the graft/ungraft queues?

**Comment by mrjbq7** [comment]
Perhaps want to do the current way but also flush queues so you don’t
ungraft twice.

**Comment by mrjbq7** [comment]
This calls ``ungraft*`` properly when ``com-end`` is called, but it doesn't seem to work with ``Cmd-Q`` on mac maybe?

4311024e6e96245a1a3c3ff3d2882010a850f17e

**Comment by nomennescio** [comment]
It does now work on Windows with `CTRL-Q`, thanks!

**Comment by nomennescio** [comment]
Windows close button works now too!

**Comment by nomennescio** [comment]
And `ALT-F4` too!

It seems the whole feature is now working as expected!

**Comment by mrjbq7** [comment]
Ctrl-D works on windows

**Comment by nomennescio** [comment]
Not really, it keeps the windows open.

I noticed your revert. Pity you don't want an alias for the user to type. Seemed like a good solution to me.

**Comment by nomennescio** [comment]
a50f45c92da

and

831568aaf88e7b9

**Comment by mrjbq7** [comment]
Ctrl-D works consistently on all platforms.

OS-specific commands (Cmd-Q / Alt-F4) work also.

Users can make their own words if they want that.

**Comment by nomennescio** [comment]
This was about having a command to type.
