### ISSUE TITLE
`simple-table.` doesn't understand SGRs, with unfortunate results in some error messages

### ISSUE THREAD

**Issue by ToxicFrog** [factor/factor#3010]
Here's the default listener:
![image](https://github.com/factor/factor/assets/90456/4c6eff2c-4bdc-4b3b-863e-53b2509c7a77)

It's a bit boring, let's spice it up with `with-256color` and a custom prompt:
![image](https://github.com/factor/factor/assets/90456/824e09a3-2d2d-4ce8-92a4-20639fe1f9f7)

What happened to the table headers? Well, it turns out that `simple-table.` doesn't understand that SGR codes aren't printable, so you get stuff like this:
![image](https://github.com/factor/factor/assets/90456/def664f9-b24c-46c2-8704-fc55fa6e2e53)

`""\x1B[1ma\x1B[0m"` is nine characters long, so it makes that table column nine cells wide, not realizing that it will actually *display* as a single-character-wide bold `a`.

Based on discord discussion, this is a problem with formatted output in general, not just `simple-table.` -- it gets rendered to a string early enough that by the time it hits words like `simple-table.`, it can no longer differentiate the actual content from the formatting codes.

A quick and dirty, but not at all portable, approach would be to change the prettyprinter to use a `display-length` word or similar that ignores control codes. I think an actual solution probably involves keeping the content and the presentation separate for longer so that when calculating table column sizes (or what have you) it can meaningfully ask for the content length without getting tangled up in the formatting codes needed to implement the presentation style.

**Comment by mrjbq7** [comment]
I guess, *fixed* with 83e7354daaeb35a55cc1f27110bc592b2d4b68ba

**Comment by mrjbq7** [comment]
It's fixed for implicit table streams, but ``simple-table.`` will still be wrong I guess...

**Comment by mrjbq7** [comment]
Definitely fixed for ``simple-table.``...
