### ISSUE TITLE
Add `quit` to `system`, add `system` to default search path, to let user have readily available command to quit Factor  

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#3030]
See also #2937.

John's comment about that:
"add quit as an alias for 0 exit in system, and then close-all-windows as a shutdown hook, and then add system as a normal used vocab"

**Comment by nomennescio** [comment]
@mrjbq7 , question about this implementation scheme; currently `0 exit` hard exits without calling `close-all-windows`, would calling `close-all-windows` at shutdown be safe to deal with a Factor that's not responsive in UI code or has a bug in e.g. user code?

**Comment by nomennescio** [comment]
@mrjbq7 I noticed you already (partially) implemented this. Doesn't ce2bc44ca60 also not require a call to `notify-queued`?

**Comment by mrjbq7** [comment]
probably yes, and then maybe change com-exit to be an alias to quit

**Comment by mrjbq7** [comment]
quit/exit is not safe to factor bugs and can hang

I think that’s okay, as you always have task manager / pkill to be the backup plan and usually there aren’t bugs. 

Do you think different?

**Comment by mrjbq7** [comment]
Maybe this fixes if bfb58c54485145ad5444736fcec55fba0f03f8fa

**Comment by mrjbq7** [comment]
Except for the ``USE: system`` which is a restart which is fine for now, I don't know if os/cpu/vm-* stuff makes sense to be in the normal using, have to think about it.

**Comment by nomennescio** [comment]
> Except for the `USE: system` which is a restart which is fine for now, I don't know if os/cpu/vm-* stuff makes sense to be in the normal using, have to think about it.
> 
> What do you think?

It works fine at my end; but would like to have either `system` in the standard search path, or in another vocab that's loaded at startup such that `quit` always works.

**Comment by mrjbq7** [comment]
Fixed in 938d99be04682e7cb53023de5b9bf6fe0f30afc0.
