### ISSUE TITLE
Add `latest` symlink to nightly builds

### ISSUE THREAD

**Issue by ToxicFrog** [factor/factor#3039]
At the moment, if you want to download the latest nightly, you need to fetch the directory listing from downloads.factorcode.org, then figure out what the latest is and download that -- there's no unchanging link that always points to the most recent nightly build. It would be convenient to have one.

**Comment by mrjbq7** [comment]
That would be nice. 

I mostly use the links on the nightly build pages but a symlink would be useful. 

https://builds.factorcode.org/package?os=linux&cpu=x86.64

Most people who track the nightly builds do so more directly by tracking the source tree from what I’ve heard.

**Comment by ToxicFrog** [comment]
I've got a source tree, but it's convenient to be able to pull the nightly and get a pre-built binary on any machine rather than waiting for it to build.

**Comment by mrjbq7** [comment]
I added latest symlinks.

```sh
# downloads.factorcode.org
$ find . | grep latest
./windows-x86-64/factor-windows-x86-64-latest.zip
./linux-x86-32/factor-linux-x86-32-latest.tar.gz
./linux-x86-64/factor-linux-x86-64-latest.tar.gz
./macosx-x86-64/factor-macosx-x86-64-latest.dmg
./windows-x86-32/factor-windows-x86-32-latest.zip
./macosx-x86-32/factor-macosx-x86-32-latest.dmg
```

And modified mason to symlink after upload (b305ac871d300b7401b9de3e675e79c72d1d845f).
