### ISSUE TITLE
1check documentation typo

### ISSUE THREAD

**Issue by swsch** [factor/factor#3069]
1check online help has two "True case:" lines in the Examples section.

**Comment by mrjbq7** [comment]
Fixed in 33d46b0baf33e29a26fb60486baf6401dd077bbe

**Comment by mrjbq7** [comment]
Thanks!

**Comment by mrjbq7** [comment]
It will take some time for the docs website to be uploaded after the next successful nightly build.

**Comment by swsch** [comment]
There was a bit of head-scratching involved when I finally found the source location and the typo was already fixed :-)
