### ISSUE TITLE
mouseover doesn't show up on dark theme

### ISSUE THREAD

**Issue by erg** [factor/factor#3076]
- Use dark mode
- ``"demos" run``
- notice no mouseover is visible

compare to light theme

**Comment by inivekin** [comment]
Maybe it would make sense for the button background to match the border of the button on hover.
i.e. change `toolbar-background` [here](https://github.com/factor/factor/blob/master/basis/ui/gadgets/buttons/buttons.factor#L129) to be `field-border-color` as given to the border [here](https://github.com/factor/factor/blob/master/basis/ui/gadgets/buttons/buttons.factor#L149)

**Comment by mrjbq7** [comment]
Fixed now
