### ISSUE TITLE
range definition

### ISSUE THREAD

**Issue by carbonmetrics** [factor/factor#3101]
From the browser: 
Factor handbook >> Guided tour of Factor >> Defining our first word:

"If your write `[1..b]` in the listener, Factor will prompt you with a choice"
Factor would suggest the `ranges` vocabulary. 

However, it doesn't (`Data stack underflow`), with the only option given "`Abort`". 

How do I get a range on the stack?

**Comment by carbonmetrics** [comment]
from the error message it was not clear that you first have to put a number on the stack, after which [1..b] works.

**Comment by mrjbq7** [comment]
Good point, the original language about being "prompted with a choice" was resolved by making ranges and intervals use different syntax.  I updated that and added a comment about seeing a ``Data stack underflow`` error:

4a71effa9e84be71c85f37032454499b54fd0091

**Comment by mrjbq7** [comment]
It seems like you are learning Factor, so I appreciate knowing anything that doesn't go smoothly for you.
