### ISSUE TITLE
help.html should output more compact HTML

### ISSUE THREAD

**Issue by slavapestov** [factor/factor#317]
Right now, it emits HTML elements with the style attribute set to various CSS expressions. These style attributes are very long and repetitive. Instead, we should pre-define styles and use the class attribute with them.

The problem is that the formatted stream protocol was not designed to make this easy. Instead of taking an assoc with style attributes, stream-format should take a style name. Then we can have a separate define-stream-style generic or similar, which defines a named style. html.streams would collect these and emit a style tag. Then spans and divs would refer to these previously-defined styles. This will reduce the size of the generated HTML text.

**Comment by mrjbq7** [comment]
(Kinda) fixed this issue in 74d8e433125288fde69fa0fc818ab2db58a3d766.  The ``help.html`` vocabulary cleans up the HTML, storing unique styles as classes and then updating the HTML stylesheet with them when outputting.
