### ISSUE TITLE
docs.factorcode.org "UI error list" doesn't show the TIFF icons

### ISSUE THREAD

**Issue by otoburb** [factor/factor#326]
http://docs.factorcode.org/content/article-ef5b5a4a27798a6f5fc616cf0f222ebfbd92e7f4.html

The icons aren't showing up when accessing this page via web-browser. Tried with two versions of Chrome, IE8 and Firefox7.

**Comment by mrjbq7** [comment]
Should be fixed by 2e2f1d673a7ee98b4e6e5829d3ba077339c36c7e and da8a378b38b786042552a1ac92b3b66841106e39.

Waiting for the next docs upload.
