### ISSUE TITLE
Connecting to closed ports gives "Broken pipe" instead of a "Connection refused" error

### ISSUE THREAD

**Issue by erg** [factor/factor#34]
``T{ inet f "127.0.0.1" 5000 } binary [ ] with-client``

wait-connect calls write, which writes 0 bytes to a socket with no reader, causing a broken pipe.

If you read 0 bytes instead, it seems to cause other issues.

Linux and Mac give different errors in the builder emails.

**Comment by erg** [comment]
Still broken on mac, fine on linux.

**Comment by bjourne** [comment]
Looks like read and write with 0 bytes are used to check if the socket is ready after connect. I think instead `getsockopt` should be used to do that test. See http://stackoverflow.com/questions/17769964/linux-sockets-non-blocking-connect and http://mff.devnull.cz/pvu/src/tcp/non-blocking-connect.c

**Comment by mrjbq7** [comment]
That seems like a pretty easy change to make.

**Comment by mrjbq7** [comment]
Fixed in 3fdbbe0fea01ef0f63abf95debc9c393b6d91304.

**Comment by mrjbq7** [comment]
Thanks @bjourne !

**Comment by bjourne** [comment]
You are welcome. :) I also think that the recursion isn't needed. Like `getsockopt` should never return EAGAIN or EINTR, only 0 or a real error. At least the examples I've seen doesn't loop the getsockopt call.

**Comment by mrjbq7** [comment]
Good idea, fixed in ebfa9402d41437de12b34093205a25fbbddb5d15.
