### ISSUE TITLE
Natively store sample callstacks and callstack>array output in reverse order

### ISSUE THREAD

**Issue by jckarter** [factor/factor#452]
The new callstack walking code visits callstacks in reverse order, and it applies `std::reverse` in the case of sample callstacks and `callstack>array` to retain the previous bottom-to-top presentation. We should update code so it expects to see callstacks in top-to-bottom order so this reversing isn't necessary.

**Comment by bjourne** [comment]
The last two commits tries to fix this bug. I didn't realize the changes would require new boot images too. I'm sorry about that.

**Comment by mrjbq7** [comment]
No problem! Also had a question where reverse third turns into first. I think that's okay but wanted to confirm.

**Comment by bjourne** [comment]
Looks like it works now.
