### ISSUE TITLE
max-reduce

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#522]
It might be useful (since this is used 20 times or so) to create `max-reduce`:

``` factor
: max-reduce ( ... seq quot: ( ... x -- ... y ) -- ... result )
    [ max ] map-reduce ; inline
```

Maybe also:

``` factor
: min-reduce [ min ] map-reduce ;
: sum-reduce [ + ] map-reduce ;
: append-reduce [ append ] map-reduce ;
```

Not sure if these are good names though...

**Comment by razetime** [comment]
`sum-reduce` is `map-sum`, `append-reduce` is `map-concat` in sequences.extras, min and max-reduce are not in any general vocabs, can be map-supremum and infimum.
