### ISSUE TITLE
Mysterious paths created with numbers appended

### ISSUE THREAD

**Issue by erg** [factor/factor#571]
I put a `[ .s ] with-global` in `get` and noticed paths like "/home/erg/core/math/4179" in the console. Why?

**Comment by mrjbq7** [comment]
Can you reproduce this?  I can't seem to.

**Comment by mrjbq7** [comment]
Likely a feature of how your $EDITOR works.

https://stackoverflow.com/questions/41842835/what-happens-when-i-save-a-file-using-vim
