### ISSUE TITLE
2array could use <array>

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#617]
In ``2array`` and ``2sequence``, we could use the ``<array>`` constructor to set the first element as the ``elt``, rather than ``0``, saving one ``set-nth``.

Alternatively, it might be useful to have an ``<uninitialized-array>`` when we don't care to set the ``elt`` like in this case (mapping to ``allot_uninitialized_array`` in the C code?``)

**Comment by bjourne** [comment]
Because the array only has two elements it uses inline allocation so it works out automatically.

**Comment by bjourne** [comment]
Don't think this is a bug. `2array` and friends are already very efficient.
