### ISSUE TITLE
factorcode.org quickstart one-liners

### ISSUE THREAD

**Issue by erg** [factor/factor#625]
Mac/Linux:

`git clone https://github.com/factor/factor.git && cd factor && ./build.sh update`

Windows:

`git clone https://github.com/factor/factor.git && cd factor && build.cmd latest`

**Comment by AlexIljin** [comment]
@erg: The links above should be updated to https://github.com/factor/factor.git

**Comment by mrjbq7** [comment]
Good idea, I edited them to reflect the current urls.
