### ISSUE TITLE
vocabs have docs links without docs files

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#628]
See `wake-on-lan`, for example:

http://docs.factorcode.org/content/vocab-wake-on-lan.html

**Comment by AlexIljin** [comment]
I assumed that was so that you could start your editor and write the docs. A feature?
It would be nice to have a clickable link to `scaffold-docs` + `edit` instead, though.

**Comment by mrjbq7** [comment]
You can always ``"foo" edit-docs`` or ``"foo" dup scaffold-docs edit-docs``.  Mostly I think it's weird for the HTML help documentation to link to a non-existing file.  We could remove that link in ``help.html`` by detecting vocabularies that don't have any docs defined.

**Comment by AlexIljin** [comment]
Ah, OK. I didn't realize you were talking about the HTML help. I assumed we are in the Factor's Browser.

**Comment by mrjbq7** [comment]
Fixed in 409b07e8722cd58b28dd40e13ddf3cbe86d95985.
