### ISSUE TITLE
gc-events: negative space reclaimed?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#659]
What does negative space reclaimed mean?

```
Event type:      Copying from nursery
Total time:      377 µs
Space reclaimed: 1,662 KB

Event type:      Copying from nursery
Total time:      31 µs
Space reclaimed: -151 KB

Event type:      Copying from aging
Total time:      6,383 µs
Space reclaimed: 736 KB
```

**Comment by bjourne** [comment]
It's the aborted gc cycle. The gc tries to copy from nursery to aging, but if space runs out in aging it aborts the gc cycle and begins collecting aging instead. But it's probably a bug because those aborted cycles shouldn't be reported in the list.

**Comment by erg** [comment]
Nice fix! Github apparently wants to give me credit for closing this for some reason. 👻
