### ISSUE TITLE
Deployed vocabularies can't have resources on linux

### ISSUE THREAD

**Issue by jonenst** [factor/factor#678]
The executable name inside the deployed vocab is the vocabulary name. If the vocabulary or one of its child has a `resource.txt` file, then the name of the executable and the directory where the resource is copied are the same, which makes `make-directories` fail.

Don't know if it's best to just change the executable name to be different than the vocabulary name (perhaps suffix `.exe` or something like in window), or to allow to have a binary with the same name as the vocabulary, and move the resources away.

Note that a workaround is make the vocab with the resources not a child of the deployed vocab: ie instead of A and A.theme, use A and A-theme.

**Comment by mrjbq7** [comment]
Fixed using ``.out`` extension and the strategy suggested by @jonenst.

Thanks!
