### ISSUE TITLE
Concatenative wiki is stale and hard to maintain

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#706]
We should organize, freshen, and/or move its content somewhere.

I'm mostly interested in having good wiki documentation for Factor -- other stuff isn't that interesting to me.

**Comment by AlexIljin** [comment]
I wanted to contribute some changes to the Wiki, but it doesn't seem to work. Are we moving to the GitHub Wiki or not?

**Comment by mrjbq7** [comment]
This isn't really an actionable issue, closing...
