### ISSUE TITLE
new icons with gtk

### ISSUE THREAD

**Issue by jonenst** [factor/factor#760]
@mrjbq7 added new (awesome) icons in 708313fb00ab0f684b96e7ea5c5d3d9269c03e79, but we can't see them with gtk because icons were renamed from Factor_TxT.png to icon_TxT.png, and the name is hardcoded in basis/ui/backend/gtk/gtk.factor

Can we rename the pngs to Factor_TxT.png ?

Also, gtk was using the 48x48 icon which has been removed. 48x48 is the recommended size for applications icons, can we have it back ?

**Comment by bjourne** [comment]
I pushed a commit to use the better icons (2c8b2d9bf528bf31991513c6862311a2fb87a209) and it seem to work in gtk. I don't know if there is any drawback to it though...

**Comment by jonenst** [comment]
The problem I had was in 2012 when ubuntu 12.04 and its version of unity which was displaying a very big (blurry) icon when pressing alt+tab. There are reports from 2012 2013 about this (see http://askubuntu.com/questions/245875/how-do-i-get-high-resolution-icons-in-unity-for-my-application-without-a-deskto ).
On ubuntu 14.04, the icon during alt tab is smaller, but I think it's also of better quality, so maybe they changed something.

**Comment by bjourne** [comment]
Alright then. Let's consider the problem solved unless it shows up again!

**Comment by jonenst** [comment]
I tried the following patch, giving a list of icons to gtk instead of only the 128x128 one. It works, but unity and gnome shell end up using the 128x128 everywhere I saw the icon (I modified the icons by hand and drew the size directly on them to identify which was used). Also, I didn't find a way to use the @2x icons.
```diff
diff --git a/basis/ui/backend/gtk/gtk.factor b/basis/ui/backend/gtk/gtk.factor
index a10ad51..8cc00c9 100644
--- a/basis/ui/backend/gtk/gtk.factor
+++ b/basis/ui/backend/gtk/gtk.factor
@@ -218,18 +218,22 @@ CONSTANT: action-key-codes
 
 ! This word gets replaced when deploying. See 'Vocabulary icons'
 ! in the docs and tools.deploy.shaker.gtk-icon
-: get-icon-data ( -- byte-array/f )
+: get-icon-data ( size -- byte-array/f )
     [
-        "resource:misc/icons/Factor_48x48.png" binary file-contents
-    ] [ drop f ] recover ;
+        dup "resource:misc/icons/Factor_%dx%d.png" sprintf binary file-contents
+    ] [ 2drop f ] recover ;
 
 : load-icon ( -- )
-    get-icon-data [
-        [
-            data>GInputStream &g_object_unref
-            GInputStream>GdkPixbuf gtk_window_set_default_icon
-        ] with-destructors
-    ] when* ;
+    f
+    { 16 32 48 128 256 } [
+        get-icon-data [
+            [
+                data>GInputStream &g_object_unref
+                GInputStream>GdkPixbuf
+                g_list_prepend
+            ] with-destructors
+        ] when*
+    ] each [ gtk_window_set_default_icon_list ] when* ;
 
 :: connect-user-input-signals ( win -- )
     win "motion-notify-event" [ on-motion yield ]
```

**Comment by bjourne** [comment]
What does gnome shell do now? I can't try it myself because both gnome-shell and unity hates my graphics card... In kde, the full resolution icon is shown in the alt+tab switcher but scaled down when shown in the task bar and top left edge of the window frame. I think other desktops should do that too, but I don't know.

**Comment by jonenst** [comment]
Both gnome shell and unity used the 128x128 icon (scaled or not scaled depending on where the icon was displayed) . If i removed the 128x128 icon from the list, the 256x256 icon was used. If i added à bigger icon, à gdk warning was displayed saying it was to big so 256 is the max size.
