### ISSUE TITLE
Inverse sin function slightly off?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#777]
``` factor
IN: scratchpad 1.5 .h
1.8p0

IN: scratchpad 1.5 cos acos .h
1.8p0

IN: scratchpad 1.5 sin asin .h
1.8000000000001p0

IN: scratchpad 1.5 tan atan .h
1.8p0

IN: scratchpad 1.5 sec asec .h
1.8p0

IN: scratchpad 1.5 cot acot .h
1.8p0
```

**Comment by erg** [comment]
``1.5 sin asin .h`` looks like it calls ``fsin`` and then ``fasin``, both in libc.

**Comment by razetime** [comment]
Since it is impractical to implement our own trig functions from scratch, and the consistency issue is from libc, I am closing this.

**Comment by razetime** [comment]
A reference: https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html
