### ISSUE TITLE
canvas class switching to final

### ISSUE THREAD

**Issue by dondy** [factor/factor#836]
When you run the Dragon Curve (http://paste.factorcode.org/paste?id=2858) drawing thingy, everything works fine.

But if you run fuel-update-usings (in Emacs, using fuel attached to a listener ofc) the usings-update stops with a error message somewhat like: "TUPLE: dragon-canvas < canvas" can't inherit from final class.

If you then try to reload/run the Dragon Curve drawing thingy it fails with the same error.

**Comment by bjourne** [comment]
Looks to be working now. :)
