### ISSUE TITLE
f 0 <inet4> send doesn't work the same on Windows

### ISSUE THREAD

**Issue by erg** [factor/factor#85]
The following code works on Linux/Mac but throws an exception in (send) on Windows:

"The format of the specified network name is invalid."

"127.0.0.1" 0 `<inet4>`  works on Windows.

    : send/recv ( packet server client -- )
        [ over over addr>> ] [ send ] bi* receive drop assert= ;

    : udp-echo ( -- )
        [
            10000 iota [ 4 >be ] map
            f 0 <inet4> <datagram>
            f 0 <inet4> <datagram>
            [ send/recv ] 2curry each
        ] with-destructors ;

**Comment by mrjbq7** [comment]
What does Mac/Linux do with send on 0.0.0.0?  Assume localhost?

Maybe we can make the windows io layer convert ``0.0.0.0`` to localhost for **sends only**.

**Comment by mrjbq7** [comment]
What does send on 0.0.0.0 mean?

**Comment by erg** [comment]
The sockaddr struct on Windows is an opaque ``C-TYPE:``. If we check that it's a 0.0.0.0 and use the SOCKADDR_ANY as the ``sa_data`` slot, that might fix everything.

**Comment by bjourne** [comment]
Do we really event want to allow `f 0 <inet>` to work? The problem is that it resolves to 0.0.0.0 and if you bind a server to that address on Linux (and Mac I presume), it listens on public interfaces so it becomes reachable from the internet. Not good if you are running a testing server. I think it would be better if you were required to write `"127.0.0.1" 0 <inet4>` for the local interface or `"0.0.0.0" 0 <inet4>` for all interfaces, including the public ones.

**Comment by erg** [comment]
``f 0 <inet4>`` is the same as ``"0.0.0.0" 0 <inet4>``

``f 0 <inet6>`` is the same as ``"::" 0 <inet6>``

``f 0 <inet>`` is the same as ``"0.0.0.0" 0 <inet4>`` and ``"::" 0 <inet6>`` both.

There's no other way to do ``f 0 <inet>`` because ``0.0.0.0`` is an ipv4 and ``::`` is ipv6. We could introduce a replacement for ``f`` like ``INADDR-ANY 0 <inet>``...

It comes down to if people know the implications of using ``0.0.0.0`` and ``::`` or not, which we could document.

**Comment by mrjbq7** [comment]
I could be in favor of disallowing ``f`` and forcing a host to be specified.

To quote from the Zen of Python: explicit is better than implicit.

**Comment by bjourne** [comment]
Yes, that is what I was getting at. ;) It's not an onerous task to write `"localhost" 0 <inet>` instead.

**Comment by erg** [comment]
Oh yeah, forgot about "localhost". ``f`` doesn't scream out "localhost" to me...
