### ISSUE TITLE
NO_UI=1 does not keep UI from being included if it is available, on Linux

### ISSUE THREAD

**Issue by Ziphilt** [factor/factor#982]
The NO_UI flag (for compiling factor) appears to be to allow factor to ignore a lack of graphics libraries. However, if they still are available, factor includes them anyway. I would like to be able to compile factor entirely without a graphical UI, regardless of whether my system has the libraries installed.

[Build log](https://gist.github.com/Ziphilt/8642654)

**Comment by bjourne** [comment]
Ima go ahead and close this. Factor doesn't dynlink to any ui libs anymore so you can run it fine without any gui.
