### ISSUE TITLE
Mixing of wchar_t and char on Windows

### ISSUE THREAD

**Issue by bjourne** [factor/factor#992]
This line renders an error when the image isn't found:

```
std::cout << "Cannot open image file: " << p->image_path << std::endl;
```

But it looks like this on Windows:

```
Cannot open image file: 0000000000BDAA44
```

Obviously that's wrong and a filename should be shown instead of the hexadecimal code. It happens because `image_path` is declared as a `vm_char*` and a `vm_char` on Windows is a `wchar_t` which is not compatible with `std::cout` that only accepts char-strings.

To solve that problem you could either:
- Encode all wchar_t\* to utf8 char\* before printing them:

```
std::cout << "Cannot open image file: " << AS_UTF8(p->image_path) << std::endl;
```

(memory deallocation omitted) AS_UTF8 would be a macro defined on Windows and a no-op on other platforms.
- Change `vm_char` so that it is a `char` on all platforms. That's probably much better in the long run (because wchar_t is a nuisance), but would require encoding between utf8 char\* and utf16 wchar_t\* when passing data to and from Windows api functions.

Any ideas?

**Comment by erg** [comment]
Test:
```
C:\factor64>factor -i=asdf
Cannot open image file: 0000006FF3C3869C
strerror:2: No such file or directory
```
